php/doc-en

- reference/hash/functions/hash-hmac-file.xml
This was missed in 20dcfbb0dd7150cbe5dfd7903a3001229295c549.
> hash_hmac_file: Sync example with hash_hmac

- language-snippets.ent
- reference/xml/functions/xml-set-character-data-handler.xml
- reference/xml/functions/xml-set-default-handler.xml
- reference/xml/functions/xml-set-element-handler.xml
- reference/xml/functions/xml-set-end-namespace-decl-handler.xml
- reference/xml/functions/xml-set-external-entity-ref-handler.xml
- reference/xml/functions/xml-set-notation-decl-handler.xml
- reference/xml/functions/xml-set-object.xml
- reference/xml/functions/xml-set-processing-instruction-handler.xml
- reference/xml/functions/xml-set-start-namespace-decl-handler.xml
- reference/xml/functions/xml-set-unparsed-entity-decl-handler.xml
This also removes the last remaining usage of the ``&note.func-callback;`` language snippet.
> Overhaul XML handler docs

- language/types.xml
- language/types/declarations.xml
- language/types/type-system.xml
- language/types/value.xml
Use 'atomic type' instead of simple or base types
Replace 'literal' types by 'value' types
Mention that class, interface, and trait constants can have a type declaration as of PHP 8.3
> Update type system documentation

- appendices/aliases.xml
- reference/mbstring/functions/mb-str-pad.xml
- reference/mbstring/versions.xml
I've mostly just copied from `str_pad`, so any pointers are welcome.
closes: #2701
> Copy and modify mb_str_pad from str_pad

- reference/strings/functions/str-decrement.xml
- reference/strings/functions/str-increment.xml
- reference/strings/versions.xml
> Document str_increment() and str_decrement()

- reference/reflection/reflectionproperty/setvalue.xml
Document the consequence of [`11703`](https://github.com/php/php-src/pull/11703) for `ReflectionProperty::setValue`
> Document ReflectionProperty::setValue PHP 8.3 deprecation

- reference/info/constants.xml
- reference/info/functions/assert-options.xml
- reference/info/functions/assert.xml
- reference/info/ini.xml
- reference/info/versions.xml
Yanked the table markup for the constants just for assert and shoved it in a ``<section>`` tag.
This requires it moving it to the end to comply with the DTD.
> PHP 8.3: legacy assertion have been deprecated

- reference/url/functions/get-headers.xml
Function get_headers() called with wrong signature in example of usage with context. Add missing $associative argument.
> Fix example of get_headers() usage with context

- reference/array/functions/range.xml
~~TODO Better examples~~ I can't come up with them, and they can always be added later.
> range: Update for PHP 8.3

- reference/random/random/randomizer/getfloat.xml
Some first words explaining the problems of selecting a random float within a given interval and how `getFloat()` does it correctly. I plan to expand the explanation a little more in a second iteration, but wanted to put up for review what I already have to make sure that it is any good and not completely incomprehensible before spending more time on it. It was hard enough to write these words :grin:
> Randomizer::getFloat(): Add documentation

- reference/info/functions/assert.xml
They are no longer supported as of PHP 8 and only serve to cause confusion for a feature that is already complex enough by itself.
In fact the examples will silently misbehave in PHP 8, because a non-empty string is truthy and no warning is emitted.
> assert: Drop examples for legacy string-based assertions

- reference/info/functions/assert.xml
Specifically `assert()` will always return `true` if assertions are disabled. Ideally the return value would never be used anyway …
> assert: Fix return value explanation

- reference/info/functions/assert.xml
- Drop the assert.exception=0 case, because that is deprecated.
- Showcase the output for enabled assertions first.
- Add example with a custom message
> assert: Rewrite examples

- reference/mysql/functions/mysql-fetch-assoc.xml
- reference/mysql/functions/mysql-fetch-object.xml
- reference/mysql/functions/mysql-fetch-row.xml
- reference/mysql/functions/mysql-get-client-info.xml
- reference/mysql/functions/mysql-get-host-info.xml
- reference/mysql/functions/mysql-get-server-info.xml
- reference/mysql/functions/mysql-stat.xml
This is to make the documentation more comformant to the Docbook standard
> Drop usage of phd:args XML attribute usage

- language/functions.xml
Proper variadics were introduced in PHP 5.6, legacy variadics are explicitly noted as “not recommended”. Remove the examples from this part of the documentation, which effectively is starter documentation.
Folks that see the legacy variadics being used in legacy code can simply refer to the reference manual for the respective functions to understand how they work.
In fact the documentation caused some confusion as per #2875.
> function.arguments: Remove explanation of legacy variadics

- reference/info/functions/assert.xml
`assert()` behaves like a regular function for all intents and purposes. It can even be used as a string callable. The only special thing about is that the `$description`'s default parameter is dynamic.
> assert: Remove note about it being a language construct

- reference/info/functions/assert.xml
The reference itself says that this is not recommended and `assert_options()` itself is deprecated in PHP 8.3. Remove the reference to slim down the docs.
> assert: Remove “not recommended” reference to `assert_options()`

- reference/exif/functions/exif-imagetype.xml
- reference/image/functions/image-type-to-mime-type.xml
This constant is introduced with PHP 8.1 and is not documented yet.
For reference: php/doc-de#163
> Add `IMAGETYPE_AVIF` constant to documentation

- reference/intl/spoofchecker/setrestrictionlevel.xml
- reference/intl/versions.xml
Part of #2163
Stumbled upon this (amongst other things) while implementing [Symfony’s `NoSuspiciousCharacters` constraint](https://symfony.com/doc/current/reference/constraints/NoSuspiciousCharacters.html).
> Document `Spoofchecker::setRestrictionLevel`

- language/oop5/magic.xml
A method that expects a `string` type argument will not allow a `stringable` object to be passed. This behaviour surprised me today and recently someone else here https://github.com/php/php-src/issues/12097
I tend to think that PHP should have an exception here, but I also understand the arguments against it. So, since the behaviour is what it is, I would like to propose making it clearer in the docs.
> Stringable can't be passed to argument expecting string, when strict types enabled

- reference/igbinary/functions/igbinary-serialize.xml
The current description renders oddly and somewhat looks like a typo, I rephrased it to make it less of a stumbler.
> Improve clarity of igbinary_serialize() documentation

- reference/strings/functions/str-pad.xml
`mb_str_pad` is a new function added in PHP 8.3, so I added a link in `str_pad` page.
> add link to multibyte version of str_pad

- appendices/migration83/other-changes.xml
refs: https://github.com/php/php-src/commit/d4183c2c91ccbbf2d561e7839503ca6dfd471916
> Followed PHP-8.3 changes about IntlDateFormatter::construct exception

- reference/ldap/examples.xml
As I've noted below the documentation, `empty('0')` is true in PHP, but `$cookie` is an opaque string and can legitimately be `'0'` (e.g. python-ldapserver returns this for the first response to every query).
I think `strlen` should work in all the same places, and also for `'0'`.
> Correct LDAP paging example

- reference/intl/numberformatter-constants.xml
refs: https://www.php.net/manual/en/migration83.deprecated.php#migration83.deprecated.intl
> [PHP 8.3] The NumberFormatter::TYPE_CURRENCY constant has been deprecated.

- appendices/migration83/deprecated.xml
- reference/phar/Phar/setStub.xml
based on [Other Changes](https://www.php.net/manual/en/migration83.deprecated.php#migration83.deprecated.phar) and [Phar object stub](https://github.com/php/php-src/blob/PHP-8.3/ext/phar/phar_object.stub.php#L201-L205).
> [PHP 8.3] Calling Phar::setStub() with a resource and a $length is now deprecated.

- reference/opcache/ini.xml
refs: https://www.php.net/manual/en/migration83.incompatible.php#migration83.incompatible.opcache
> [PHP 8.3] Removed opcache.consistency_checks INI directive

- reference/reflection/reflectionproperty/setvalue.xml
I noticed this while updating code for 8.3.
Whilst the deprecation ins referenced as a Note, it was not reflected in the parameter descriptions.
Whilst `$object` is _optional_ before 8.3, it has supported a `null` value to have the same meaning for a long time (probably always). I felt it better to not suggest the alternative as it will lead to future compatability issues.
> [PHP 8.3]: The ReflectionProperty::setValue $object is now required.

- reference/posix/constants.xml
> [PHP 8.3] posix constants addition.

- reference/dom/domcharacterdata/appenddata.xml
Corresponds to `Changed DOMCharacterData::appendData() tentative return type to true.` of https://github.com/php/doc-en/issues/2796.
> Changelog for return type of DOMCharacterData::appendData

- reference/errorfunc/functions/debug-backtrace.xml
Fix the documentation introduced by #1630
Demonstration: https://3v4l.org/9kCpQ
```
debug_backtrace()
args:   true
object: true
debug_backtrace(0)
$options = 0
args:   true
object: false
debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT)
$options = 1
args:   true
object: true
debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS)
$options = 2
args:   false
object: false
debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT|DEBUG_BACKTRACE_IGNORE_ARGS)
$options = 3
args:   false
object: true
```
> Fix `debug_backtrace` argument description

- reference/mongodb/bson/binary.xml
https://jira.mongodb.org/browse/PHPC-2267
Split this off from https://github.com/php/doc-en/pull/2938 since it relates to an unmerged PR: https://github.com/mongodb/mongo-php-driver/pull/1488
> Add MongoDB\BSON\Binary::TYPE_SENSITIVE constant

- reference/uodbc/functions/odbc-autocommit.xml
- refs
* [php-src stubs](https://github.com/php/php-src/blob/PHP-8.3/ext/odbc/odbc.stub.php#L427-L428)
* [other changes](https://www.php.net/manual/en/migration83.other-changes.php#migration83.other-changes.functions.odbc)
* [odbc_autocommit source code](https://github.com/php/php-src/blob/PHP-8.3/ext/odbc/php_odbc.c#L2551-L2587)
> [PHP 8.3] odbc_autocommit $enable parameter is now nullable.

- reference/json/functions/json-validate.xml
- reference/json/versions.xml
Based on [RFC](https://wiki.php.net/rfc/json_validate) and [json_validate source code](https://github.com/php/php-src/blob/ea299d44a155e0ef39c24a4d79b0e51accf8d9d0/ext/json/json.c#L313-L353).
> [PHP 8.3] Added json_validate function description.

- reference/reflection/reflectionclass/getstaticproperties.xml
refs: [php-src](https://github.com/php/php-src/blob/PHP-8.3/ext/reflection/php_reflection.stub.php#L408-L409) and [other changes](https://www.php.net/manual/en/migration83.other-changes.php#migration83.other-changes.functions.reflection)
> [PHP 8.3] Return type of ReflectionClass::getStaticProperties() is no longer nullable.

- language/types/type-juggling.xml
Remove "a" before a plural subject.
> Correct sentence grammar

- reference/intl/intlgregoriancalendar/createfromdate.xml
- reference/intl/intlgregoriancalendar/createfromdatetime.xml
- reference/intl/versions.xml
Stubs: https://github.com/php/php-src/blob/PHP-8.3/ext/intl/calendar/calendar.stub.php#L491-L493
> [PHP 8.3] New IntlGregorianCalendar methods

- reference/datetime/datetime/construct.xml
- reference/datetime/datetimeimmutable/construct.xml
a 'Е'(&amp;#1045;) of `Exception` was a multibyte character. fixed typo to 'E'(&amp;#69;).
> Fix typo of Section 'Errors/Exceptions' in DateTime construct

- appendices/migration83/new-functions.xml
refs: https://github.com/php/php-src/pull/12735 and https://github.com/php/doc-en/pull/2953
> Removed pgsql pipeline related functions from migration83

- reference/spl/recursivearrayiterator.xml
This change makes a couple of minor grammar fixes to the RecursiveArrayIterator docs, which I found on reading through the respective documentation, recently.
> Minor grammar correction to RecursiveArrayIterator docs

- language/types/float.xml
The update makes numbers like `_123.456` and `123._456` incorrect.
> Update floating point number syntax in float.xml

- appendices/migration83/other-changes.xml
refs: https://github.com/php/php-src/blob/PHP-8.3/ext/dom/php_dom.stub.php
> deleted DOMDocument::loadXMLFile() reference from migration83

- reference/zip/ziparchive/extractto.xml
- reference/zip/ziparchive/getexternalattributesindex.xml
After discussion about https://github.com/php/php-src/issues/12730
it was chosen to not restore original permissions.
Add a note in doc about this
as we have an example about how to do it
> ZipArchive:extractTo do not restore perm

- language-snippets.ent
- reference/dom/domcharacterdata/after.xml
- reference/dom/domcharacterdata/before.xml
- reference/dom/domcharacterdata/replacewith.xml
- reference/dom/domchildnode/after.xml
- reference/dom/domchildnode/before.xml
- reference/dom/domchildnode/replacewith.xml
- reference/dom/domdocument/append.xml
- reference/dom/domdocument/createattributens.xml
- reference/dom/domdocument/prepend.xml
- reference/dom/domdocument/replacechildren.xml
- reference/dom/domdocumentfragment/append.xml
- reference/dom/domdocumentfragment/prepend.xml
- reference/dom/domdocumentfragment/replacechildren.xml
- reference/dom/domelement/after.xml
- reference/dom/domelement/append.xml
- reference/dom/domelement/before.xml
- reference/dom/domelement/prepend.xml
- reference/dom/domelement/replacechildren.xml
- reference/dom/domelement/replacewith.xml
- reference/dom/domparentnode/append.xml
- reference/dom/domparentnode/prepend.xml
- reference/dom/domparentnode/replacechildren.xml
Basically these are BC-breaking bugfixes
> Document DOM BC breaks in 8.3

- reference/var/functions/unset.xml
If I `unset($this->property)`, and `__get()` is declared, then `$this->__get()` is called when accessing `$this->property`
If I `unset($this->property`, and `__set()` is declared, then `$this->__set()` is called when setting `$this->property`
Tested in php 8.2
This functionality was not clearly documented, and I did not expect this behavior, so I added a note describing this.
I also updated the existing note with slightly different language, because I think it reads better.
I think I did the `<link>` bits correctly, but idk.
> Add note about __get() & __set() being called on unset object properties

- reference/gmp/gmp.xml
- reference/intl/spoofchecker.xml
- reference/zip/ziparchive.xml
Created by ``./build/gen_stub.php --replace-classsynopses ./ ./../docs-php/en/`` with some omissions due to false positives in DateTime.
> PHP 8.3 gen_stub.php --replace-classsynopses

- reference/mysqli/mysqli_stmt/error-list.xml
Included 'Error:' message in the screen output
The screen output is missing the 'Error:' message
introduced by the echo command in the example.
Closes #3017
> include 'Error:' message in the screen output

- language/oop5/traits.xml
As of PHP 8.0.0, the signature of abstract methods defined in traits is checked against the implementing class method.
This changeLog in the migration guide is not updated in the traits documentation.
https://3v4l.org/3l0fF
> Fixed the signature compatibility rule of concrete method of trait.

- reference/mysqli/mysqli/options.xml
As documented [here](https://www.php.net/manual/en/mysqli.quickstart.prepared-statements.php#example-4303), this option does nothing when prepared statements are used. I believe it is handy to have this mentioned right next to the option.
> MYSQLI_OPT_INT_AND_FLOAT_NATIVE has no effect on prepared statements

- reference/pdo/pdo/getattribute.xml
This is currently undocumented behaviour, example [here](https://github.com/php/php-src/issues/12969)
> PDO::getAttribute may throw PDOException

- reference/outcontrol/constants.xml
Added additional section headers above each set of constants to clarify what they are and how to access them, clarified which functions the buffer control flags have an effect on, and added a section for the missing handler status constants. 
These last three constants include PHP_OUTPUT_HANDLER_PROCESSED which is returned by ob_get_status() but it is, IMO by mistake, not exposed to userland (PR submitted php/php-src/pull/13019).
The other two, PHP_OUTPUT_HANDLER_STARTED and PHP_OUTPUT_HANDLER_DISABLED, are mentioned as needing documentation in #2747 .
> Update output control constants

- language/oop5/basic.xml
A comma is neither necessary nor conventional in a "neither/nor" construction and is confusing because it is in, though doesn't complete, the dependent clause.
> Remove unnecessary and, thus, confusing comma

- reference/dom/domnode/getlineno.xml
- reference/outcontrol/functions/ob-get-status.xml
Closes #3021 and https://bugs.php.net/bug.php?id=62019.
> Update outdated ob_get_status docs

- reference/outcontrol/functions/ob-list-handlers.xml
Added more details on when "default output handler" and "Closure::__invoke" is returned, and what is returned when passing functions or classes/objects and their methods. Added examples for each of these as well.
If bugs.php.net is still maintained, this closes https://bugs.php.net/bug.php?id=65826 .
> Update ob_list_handlers documentation

- reference/com/constants.xml
Add three missing COM constants that were listed in #2747.
References for these changes:
- [LOCALE_NEUTRAL](https://learn.microsoft.com/en-us/windows/win32/intl/locale-neutral)
- [LOCALE_SYSTEM_DEFAULT](https://learn.microsoft.com/en-us/windows/win32/intl/locale-system-default)
- DISP_E_PARAMNOTFOUND [1](https://learn.microsoft.com/en-us/windows/win32/com/com-error-codes-2) and [2](https://learn.microsoft.com/en-us/windows/win32/api/oaidl/nf-oaidl-idispatch-invoke)
The values of the constants were verified on PHP 8.2 running on Windows 10.
> Add missing COM constants

- language-snippets.ent
- language/predefined/attributes.xml
- language/predefined/attributes/override.xml
- language/predefined/attributes/override/construct.xml
- language/predefined/versions.xml
So... I don't remember what the reason was to move the ``AllowDynamicProperties`` Class methods definition out of the subfolder like I did it this time.
But I can't see any issues with it.
> Add Override Attribute stub

- reference/com/constants.xml
Removed all the values and references to PHP 7.0 from the table as advised [here](https://github.com/php/doc-en/pull/3043#discussion_r1438376597) and [here](https://github.com/php/doc-en/pull/3043#discussion_r1438376784).
> Remove COM constant values

- reference/outcontrol/constants.xml
- reference/outcontrol/functions/ob-get-level.xml
- reference/outcontrol/functions/ob-get-status.xml
- reference/outcontrol/functions/ob-list-handlers.xml
Added `<link>`s to `ob_get_status()` to reference other functions/constants as appropriate and added appropriate `xml:id`s to these functions/constants so these can be linked to.
Also added the same note on the difference in `ob_get_level()` and `ob_get_status()` nesting levels as the one in `ob_get_status()`.
> Add more function/constant links to ob_get_status

- reference/pdo/book.xml
- reference/pdo/constants.xml
- reference/pdo/pdorow.xml
- reference/pdo/pdostatement/fetch.xml
- reference/pdo/versions.xml
Add the PDORow class to the docs (#2162) and reference it from the appropriate parts of the PDO docs.
As this class has no methods and all but one the properties of this class are dynamic, I added the description of the class and it's dynamic properties to the introduction section (I've got the idea from stdClass's docs). Let me know whether this format is acceptable.
> Add PDORow class to docs

- reference/dom/book.xml
- reference/dom/domnamespacenode.xml
- reference/dom/versions.xml
Add the missing DOMNameSpaceNode class to the docs (ref #2162) and reference it from the DOM book.
> Add DOMNameSpaceNode class to docs

- language/namespaces.xml
Removed ZEND_THREAD_SAFE and ZEND_DEBUG_BUILD from the section about defining namespaced special, built-in constants resulting in a fatal error as this is no longer the case for these two.
This code (https://3v4l.org/iMP1P)
```php
<?php
namespace bar;
const ZEND_DEBUG_BUILD = true;
const ZEND_THREAD_SAFE = true;
var_dump(\ZEND_DEBUG_BUILD);
var_dump(\ZEND_THREAD_SAFE);
var_dump(ZEND_DEBUG_BUILD);
var_dump(ZEND_THREAD_SAFE);
```
no longer results in a fatal error but in this output
```
bool(false)
bool(false)
bool(true)
bool(true)
```
> Update namespace FAQ on overriding special constants

- reference/image/configure.xml
- reference/image/setup.xml
This makes it slightly easier to find and recognise as an option.
Also add avif and webp to the list with supported types for reference. Note that this might require additional details (e.g. link to library) if that is preferred.
> Add avif to gd installation instructions

- reference/com/book.xml
- reference/com/com-safearray-proxy.xml
- reference/com/versions.xml
Add com_safearray_proxy to docs (#2162). 
This internal class doesn't have any methods or properties and doesn't extend or implement any other class or interface hence the almost empty documentation.
The description of the class is based on the [comments](https://github.com/php/php-src/blob/0b7cd1423add534fc27030f57934cc8bb6d4c6a1/ext/com_dotnet/com_saproxy.c#L17-L22)  in the implementation.
> Add com_safearray_proxy to docs

- reference/mbstring/functions/mb-ereg-replace-callback.xml
Either the $string parameter needs to be changed to $subject, or the parameter name in the function description needs to be corrected
> Incorrect param name in mb_ereg_replace_callback() docs

- reference/ibm_db2/ini.xml
A bunch of previously undocumented stuff, including things that are ugly and probably should be deprecated.
Note some of these are platform-specific; I have tried to word based on this ("on IBM i" vs. "when connecting to IBM i"), but I've considered adding a column, if that would make sense.
> Update INI documentation for ibm_db2

- language/predefined/closedgeneratorexception.xml
- language/predefined/exceptions.xml
- language/predefined/versions.xml
Add the missing ClosedGeneratorException class to the docs (#2162). Also listed it under the predefined exceptions in the language reference as this seemed for it the appropriate place to be.
> Add ClosedGeneratorException to docs

- appendices/reserved.constants.core.xml
Added the missing constants (https://github.com/php/doc-en/issues/2747) ZEND_THREAD_SAFE and ZEND_DEBUG_BUILD, and descriptions of their PHP integer aliases (PHP_ZTS and PHP_DEBUG).
> Add missing ZEND constants and descriptions of their PHP aliases

- reference/outcontrol/functions/ob-clean.xml
- reference/outcontrol/functions/ob-end-clean.xml
- reference/outcontrol/functions/ob-end-flush.xml
- reference/outcontrol/functions/ob-flush.xml
- reference/outcontrol/functions/ob-get-clean.xml
- reference/outcontrol/functions/ob-get-flush.xml
Update all six `ob_ clean/flush` functions' documentation with the following:
- describe what each function does in detail
- differentiate between contents of the output buffer and values returned by the output handler
- list flags passed to output handlers
- list flags affecting or, if unexpected, not affecting each function
- use consistent terminology for output buffer, it's contents and it's handler, and 'turn off' instead of 'destroy' an output buffer
- add a section on notices issued
Closes the following:
https://bugs.php.net/bug.php?id=64977
https://bugs.php.net/bug.php?id=69404
https://bugs.php.net/bug.php?id=71486
https://bugs.php.net/bug.php?id=74399
https://bugs.php.net/bug.php?id=76563
> Update all ob_  clean/flush functions

- language/oop5/paamayim-nekudotayim.xml
My phrasing is ugly, and needs to be corrected by someone else, but I tried my best to make this definition more complete and less ambiguous. To me, the current phrasing suggests that any overridden property could be accessed, while, as I suppose, it's the late static binding is meant.
> Ambiguous phrasing on the Scope Resolution Operator page

- reference/intl/intlchar/istitle.xml
- reference/intl/intlchar/totitle.xml
The current examples are incorrect and are identical to the examples of islower.xml and toupper.xml respectively.
The istitle() function determines wether the character is a titlecase code point ("Lt" general category of Unicode). Titlecase characters are digraphs (in one character) formed by a combination of two glyphs, one uppercase and the other lowercase.
Similarly, totitle() converts a character to titlecase, if available.
The examples included in these commits were retrieved from the Unicode specification, also presented in https://www.compart.com/en/unicode/category/Lt
> IntlChar::istitle and IntlChar::totitle examples corrections

- language/enumerations.xml
On the one hand, we are writing a closing tag ?> in examples, probably, such an agreement is in effect so that the user can copy the example code and paste it into a document that may contain, say, HTML markup, and immediately look at the result of this code. At the same time, there are functions in the documentation whose signatures contain three dots, which, when trying to execute the example, will result in a syntax error: Parse error: syntax error, unexpected token "..." Wouldn't it be a good practice to abandon the three dots in the definition of functions in the examples?
> Make code examples on enumeration documentation executable

- reference/json/functions/json-validate.xml
If flags parameter is different than the constant JSON_INVALID_UTF8_IGNORE, a ValueError exception is thrown.
> ValueError on flags diferent to JSON_INVALID_UTF8_IGNORE

- reference/mbstring/functions/mb-convert-encoding.xml
- reference/mbstring/functions/mb-detect-encoding.xml
Add changelog entry to both functions about these functions no longer returning `Base64`, `QPrint`, `UUencode`, `HTML entities`, `7 bit` or`8 bit`. 
This should complete the appropriate part of the [PHP 8.2 documentation tracker](https://github.com/php/doc-en/issues/1803).
References can be found [here](https://github.com/php/php-src/commit/f07c1935839bf87e9d5a26a82a0ed8747c4f178f) and [here](https://github.com/php/php-src/commit/a2bc57e0e531367f40fc50aa935bffac60cd61e8).
> Add PHP 8.2 changelog entry to mb_convert_encoding() and mb_detect_encoding()

- reference/outcontrol/functions/flush.xml
Removed sections of web server specific description (there is plenty of these in the comments of that page), add a sentence on how functionality differs on the CLI and in a web server, added a section on flush possibly interfering with output handlers and moved the notes user level handlers and web server/browser buffering into separate `<note>` tags.
Closes https://bugs.php.net/bug.php?id=65115.
> Update flush() documentation

- language/types/array.xml
Can you accept this change? This is necessary in order for the array values translated into another language to be converted to uppercase
> Update array.xml: make strtoupper an mb_strtoupper

- language/operators/arithmetic.xml
- language/operators/array.xml
- language/operators/assignment.xml
- language/operators/bitwise.xml
- language/operators/comparison.xml
- language/operators/errorcontrol.xml
- language/operators/execution.xml
- language/operators/increment.xml
- language/operators/logical.xml
- language/operators/precedence.xml
- language/operators/string.xml
- language/operators/type.xml
Now the list of operators looks very noisy. Take a look:
It's hard for the eye to catch on to the desired section. The list only shows Operators, Operators, Operators…
Make the list of operators (on the [Operators](https://www.php.net/manual/en/language.operators.php) page and in the [menu](https://www.php.net/manual/en/language.operators.precedence.php), which is located at the top right) pure, but keep the full titles on the pages.
Now it takes 5 times faster to select the desired section; the eye instantly catches on to the desired operator name.
P. S. I'm not 100 % sure that I chose the right way to add a short title for the sections via the `titleabbrev` tag, maybe someone will tell me how to do it better. I'm ready.
> Make the Operators list pure

- reference/network/functions/header.xml
- reference/network/functions/setcookie.xml
As per [discussion in the StackOverflow chat](https://chat.stackoverflow.com/transcript/message/56990396#56990396), I added a note to the `setcookie()` doc to say that one can use `header()` to create cookies with arbitrary params. I then added an example to the `header()` doc.
I also propose a minor language fix-up.
> Document approach to set cookie params not known to setcookie()

- reference/outcontrol/functions/ob-implicit-flush.xml
Closes #3115 
Clarifies that empty strings or sending headers do not trigger implicit flushing.
> Clarify output in ob_implicit_flush()

- reference/intl/dateformatter/get-error-code.xml
- reference/intl/dateformatter/get-error-message.xml
reference/intl/dateformatter/get-error-code.xml
reference/intl/dateformatter/get-error-message.xml
* Examples in get-error-code.xml and get-error-message.xml use the function IntlDateFormatter::format() with less parameters than expected, both in OO and procedural. Corrections made by this commit intend to generate the expected error code and message given in the example. Tested with PHP 8.3.1.
* Rephrased purpose of function in get-error-code.xml, there was redundant information.
* Correction to identation.
* Removed trailing ws.
> Correction to IntlDateFormatter examples

- reference/intl/grapheme/grapheme-stristr.xml
grapheme_stristr function name is incorrect in parameter section
was: grapheme_strstr
to be: grapheme_stristr
> grapheme_stristr function name is incorrect in parameter section

- reference/outcontrol/book.xml
- reference/outcontrol/flushing-system-buffers.xml
- reference/outcontrol/output-buffering.xml
- reference/outcontrol/user-level-output-buffers.xml
The aim of this PR is to document most details of output control / output buffering. 
It adds three new pages to the `outcontrol` book: 
- output buffering in general
- flushing system buffers (`flush()` and implicit flushing)
- user-level output buffering
I've checked all related user comments in the manual, and bugs, PR's and issues on `bugs.php.net`, `php-src` and `doc-en`. Additionally, I've tested everything before I've added it to these pages (on the CLI and a web server) so everything on them at least `"works on my machine"`.
If accepted, these pages or sections of it could be linked to from other output control pages.
Closes https://bugs.php.net/bug.php?id=60984
Closes https://bugs.php.net/bug.php?id=65115
Related bug report that is already resolved and can be closed …
> Document details of output buffering / output control

- reference/array/functions/array-key-exists.xml
As of 8.0.0 [array_key_exists](https://github.com/php/php-src/blob/master/ext/standard/array.c#L6652) the `$key` parameter takes mixed arguments now (string, int, bool, null, and resource). So updated the docs to reflect that.
Added screenshot for proof
> Update array key exists key parameter for PHP 8.0.0

- reference/info/constants.xml
Adds descriptions to each `INI` mode constant, copied from their `PHP_INI` aliases.
These are also on the [missing constants list](https://github.com/php/doc-en/issues/2747) which I'm guessing is because these are in a `table` instead of a `variablelist`.
> Add description to INI mode constants

- reference/outcontrol/functions/ob-start.xml
- reference/outcontrol/user-level-output-buffers.xml
Updated `ob_start()` by removing inaccuracies and unnecessary details focused on buffering (instead of on the function) and linked to the appropriate sections of the new `user-level-output-buffers.xml` file.
> Update ob_start() docs

- install/ini.xml
- reference/info/constants.xml
Replace the duplicate of the `INI` mode table with a link to its copy on a constant list page. This is a continuation of #3140 and the final piece in the `PHP_INI_` mode constant cleanup.
As a side note, `INI_USER`, `INI_PERDIR`, `INI_SYSTEM` and `INI_ALL` can be marked as complete on the [missing constants list](https://github.com/php/doc-en/issues/2747).
> Link duplicate INI constant table

- reference/filesystem/constants.xml
- reference/filesystem/functions/glob.xml
Adds the missing GLOB_ERR constant, adds descriptions to each GLOB constant and `XInclude`s them on the `glob()` function's page.
> Cleanup of GLOB constants

- install/cloud/digitalocean.xml
- install/cloud/index.xml
As php.net and manual are hosted for years on DigitalOcean, it would be good to mention it in this section.
> Add DigitalOcean section in Cloud Hosting installation section

- reference/pdo_mysql/constants.xml
note that `PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT` is [only available with mysqlnd](https://github.com/php/php-src/blob/87edeed3b9fcb9d066d8e18b10fb0ed8cb976873/ext/pdo_mysql/pdo_mysql.c#L143-L145).
Recently we ran into a problem that this constant requires a `defined` check, as its not always defined.
> PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT is mysqlnd only

- reference/array/functions/array-pad.xml
It ain't much, but it's one less TODO item for the 8.3 docs :tada:
> Update array_pad docs for 8.3

- reference/array/functions/array-search.xml
The second parameter of the [array_keys()](https://www.php.net/manual/en/function.array-keys.php) function is `filter_value`, but not `search_value`
> Update array-search.xml: wrong the parameter name

- reference/pgsql/functions/pg-convert.xml
- reference/pgsql/functions/pg-fetch-object.xml
- reference/pgsql/functions/pg-fetch-result.xml
- reference/pgsql/functions/pg-field-is-null.xml
- reference/pgsql/functions/pg-field-prtlen.xml
- reference/pgsql/functions/pg-insert.xml
For [`pg_fetch_result()`](https://github.com/php/php-src/blob/PHP-8.3/ext/pgsql/pgsql.stub.php#L605), [`pg_field_prtlen()`](https://github.com/php/php-src/blob/PHP-8.3/ext/pgsql/pgsql.stub.php#L652), and [`pg_field_is_null()`](https://github.com/php/php-src/blob/PHP-8.3/ext/pgsql/pgsql.stub.php#L661) updated signature, based on stubs.
> [PHP 8.3] Update PGSQL

- appendices/reserved.constants.core.xml
- error_constant_ids.sh
- reference/errorfunc/constants.xml
The script (which can be applied to all translations) will do the following:
- remove IDs from error constants on the core constants page
- standardize constant IDs on the error handling constant page
> Fix error constant IDs

- reference/memcache/constants.xml
Update memcache constant IDs to standard global constant ID format. 
Move IDs to <row> tags as those on <constant> tags are not rendered.
> Update memcache constant IDs

- radius_constant_id.sh
- reference/radius/constants.xml
Update Radius constant ID to the "standard" global constant ID format.
Add bash script this update was made with so that it can be applied to translations as well.
> Update Radius constant ID

- reference/ssh2/constants.xml
- ssh2_constant_id.sh
There was a typo in the ID.
Bash script can be used to apply update to all translations.
> Update SSH2 constant ID

- gender_constant_ids.sh
- reference/gender/gender.xml
Update gender constant IDs to the "standard" class constant ID format.
Add bash script this update was made with so that it can be applied to translations as well.
> Update gender constant IDs

- reference/snmp/snmp.xml
- reference/sqlite3/sqlite3.xml
- reference/zookeeper/zookeeper.xml
- reference/zookeeper/zookeeper/addauth.xml
- reference/zookeeper/zookeeper/create.xml
- reference/zookeeper/zookeeper/getacl.xml
- reference/zookeeper/zookeeper/getclientid.xml
- reference/zookeeper/zookeeper/getstate.xml
- reference/zookeeper/zookeeper/isrecoverable.xml
- reference/zookeeper/zookeeper/setacl.xml
- reference/zookeeper/zookeeper/setdebuglevel.xml
- sqlite_zookeeper_snmp_constant_ids.sh
Update SQLite, Zookeeper and SNMP constant IDs to the "standard" class constant ID format.
Add bash script this update was made with so that it can be applied to translations as well.
> Update SQLite, Zookeeper and SNMP constant IDs

- appendices/tokens.xml
Remove link to __TRAIT__ as Phd now automatically links to constants.
This update was made with the following bash script:
```bash 
\grep -lrE --include='*.xml' '<link linkend="constant\.trait">__TRAIT__<\/link>' | xargs -d '\n' sed -i 's/<link linkend="constant\.trait">__TRAIT__<\/link>/<constant>__TRAIT__<\/constant>/g'
```
> Remove link to __TRAIT__

- appendices/reserved.constants.core.xml
- reference/misc/constants.xml
Remove duplicate ID from core constants and update ID in `misc` constants.
This update was made with the following bash script:
```bash
\grep -lrE --include='*.xml' '<varlistentry xml:id="constant\.compiler-halt-offset">' | xargs -d '\n' sed -i 's/<varlistentry xml:id="constant\.compiler-halt-offset">/<varlistentry>/g'
\grep -lrE --include='*.xml' '"constant\.--compiler-halt-offset--"' | xargs -d '\n' sed -i 's/"constant\.--compiler-halt-offset--"/"constant\.compiler-halt-offset"/g'
```
> Update COMPILER_HALT_OFFSET ID

- ffi_constant_id.sh
- reference/ffi/ffi.xml
Update FFI constant ID to the "standard" class constant ID format.
Add bash script this update was made with so that it can be applied to translations as well.
> Update FFI constant ID

- appendices/reserved.constants.core.xml
Add the following CLI constants to the core constant list:
- PHP_CLI_PROCESS_TITLE
- STDERR
- STDIN
- STDOUT
> Add CLI constants to core constant list

- reference/mysqli/constants.xml
Fix mysqli constant IDs so these can be linked to.
This update was done with using following bash script:
```bash
#!/bin/bash
\grep -lrE --include="*.xml" '"constantmysqli-' | xargs -d '\n' sed -i 's/"constantmysqli-/"constant.mysqli-/g'
\grep -lrE --include="*.xml" '"constant.mysqli-type-fload"' | xargs -d '\n' sed -i 's/"constant.mysqli-type-fload"/"constant.mysqli-type-float"/g'
```
> Fix mysqli constant IDs

- appendices/migration72/constants.xml
- reference/simplexml/simplexmlelement/construct.xml
- reference/zip/ziparchive/close.xml
- reference/zip/ziparchive/getarchiveflag.xml
- reference/zip/ziparchive/open.xml
- reference/zip/ziparchive/setarchiveflag.xml
This makes it easier to programmatically/manually cross-reference the contents of `<constant>` tags with constant IDs.
_Edit:_
Links are not needed for constants anymore as these are now rendered by Phd.
> Remove links from within constant tags

- reference/ibm_db2/ini.xml
These are not constants but IBM DB2 options that are not exposed to PHP userland in any way. 
These changes were made with the following bash script:
```bash
#!/bin/bash
sed -i -E 's/<constant>(\*HEX)<\/constant>/<literal>\1<\/literal>/g' reference/ibm_db2/ini.xml
sed -i -E 's/<constant>(SQL_ATTR_CONN_SORT_SEQUENCE)<\/constant>/<literal>\1<\/literal>/g' reference/ibm_db2/ini.xml
```
> Replace constant with literal tags for IBM DB2 options

- reference/reflection/reflectionproperty/construct.xml
In strict mode: 
> Fatal error: Uncaught TypeError: var_export(): Argument #2 ($return) must be of type bool, int given
> construct.xml: fiexed the example's syntax and amend the function arg

- reference/sodium/functions/sodium-crypto-pwhash.xml
Code requires the length to be exactly, not at least, this amount of bytes.
> Fix GH-3160: sodium_crypto_pwhash misleading $salt length requirement

- reference/pcre/pattern.modifiers.xml
The parentheses must be included into the literals sequence, as described in https://www.php.net/manual/en/regexp.reference.internal-options.php
```
<?php
declare(strict_types = 1);
preg_match_all(
pattern: '~
?U".*" # It is wrong without parenthesis
~x',
subject: '"Bob" and "Alice"',
matches: $matches,
);
print_r($matches);
```
And correct with:
```
<?php
declare(strict_types = 1);
preg_match_all(
pattern: '~
(?U)".*" # Find each word in quotes
~x',
subject: '"Bob" and "Alice"',
matches: $matches,
);
print_r($matches);
```
> pattern.modifiers.xml: include parenthesis within literals sequence

- reference/spl/emptyiterator/valid.xml
- reference/spl/filteriterator/valid.xml
- reference/spl/iteratoriterator/valid.xml
This commit updates the documentation for the `valid` method of the following iterators:
- `EmptyIterator` - add a note that this will always return false
- `FilterIterator` - add a note that the value will be false until the pointer is advanced to the first valid element
- `IteratorIterator` - clarify that the method checks if the element is valid.
These now match the source.
I have checked other iterators and these seem to be correctly documented.
It's worth noting that the `ArrayIterator::valid` method behaves differently - it checks if the next element is valid (confirmed in source).
The `DirectoryIterator::valid` method may also be incorrectly documented but I am not 100% sure of this. The documentation states that the method checks if it is a valid _file_, but I believe that the …
> Clarify usage of Iterator::valid methods

- reference/xlswriter/xlsx-kernel/set-row.xml
Apparently, the `Vtiful\Kernel\Excel::set Row` method sets the format of a row, not a column
> Fix typo in xlswriter/xlsx-kernel/set-row.xml

- appendices/migration80/incompatible.xml
[count](https://www.php.net/manual/en/function.count) provides information about its BC, but [migration documentation](https://www.php.net/manual/en/migration80.incompatible.php) does not.
> fix: document BC on count function in PHP 8.0

- language/functions.xml
On page https://www.php.net/manual/en/functions.arguments.php, examples 4 and 7 have both code and output, but examples 5 and 6 only have the code. This PR does a tiny bit of code change (to add line breaks in example 6)  but otherwise is about adding the output of examples 5 and 6.
> Update functions.arguments to include output of code samples

- reference/dom/domnode/getrootnode.xml
- reference/errorfunc/functions/trigger-error.xml
- reference/intl/intlcalendar/setdatetime.xml
- reference/intl/intlgregoriancalendar/createfromdate.xml
- reference/intl/intlgregoriancalendar/createfromdatetime.xml
- reference/json/functions/json-validate.xml
- reference/ldap/functions/ldap-connect-wallet.xml
- reference/network/functions/long2ip.xml
- reference/outcontrol/functions/ob-start.xml
- reference/simplexml/functions/simplexml-import-dom.xml
- reference/spl/splfixedarray/jsonserialize.xml
- reference/stream/functions/stream-context-set-options.xml
- reference/stream/functions/stream-context-set-params.xml
- reference/zip/ziparchive/getarchiveflag.xml
I intended to fix some of the methodsynopses which didn't need a changelog.
> Sync some methodsynopses with stubs

- reference/fpm/status.xml
reference/fpm/status.xml: if reach the maximun number of processes, max_children_reached is greater than or equal to 1
> Modify the description of the max_children_reached

- reference/datetime/dateperiod.xml
- reference/datetime/formats.xml
Part of https://github.com/php/doc-en/issues/3326, an `<example>` tag requires a `<title>`.
I couldn't come up with titles for the 3 examples, so I converted them to `<informalexample>` which don't have that requirement. @derickr if you have suggestions for titles to use instead, let me know.
> Fix minor markup conformance issue in DateTime extension

- features/commandline.xml
To make it compliant with the DocBook schema.
Mark the introduction as not chunked so that the rendering of the manual doesn't just have a ToC: https://www.php.net/manual/en/features.commandline.php
> CLI docs: Remove PHP 5 era changelog and rework markup

- reference/openssl/configure.xml
The optional DIR argument in --with-openssl configure option was removed in PHP 7.4.0.
> Document removal of --with-openssl[=DIR] argument

- reference/zip/configure.xml
This is part of #3326, a `<section>` tag needs to be immediately be followed by a `<title>` tag to conform to the DocBook schema.
At the same time, we take the opportunity to rewrite the documentation in such a way that it is easier to remove PHP 7 related docs when the time comes to remove them.
> Rewrite installation docs for Zip extension

- reference/pdo_cubrid/reference.xml
Rewrite this table as a series of sections that describes each feature.
And do some slight markup fixes at the same time.
However, these docs are in a sad state and not up to our standard which is somewhat usual with PECL extension docs
> Make PDO CUBRID DocBook 5.2 conformant

- install/unix/index.xml
This updates the development tools versions required to configure and build PHP across various versions:
* autoconf:
* PHP 7.3 and later: 2.68+
* PHP 7.2: 2.64+
* From PHP 5.4 to 7.1: 2.59+
* re2c:
* From PHP 8.3 and later 1.0.3+
* From PHP 5.2 to 8.2: 0.13.4+
* PHP 5.1 required 0.9.11+ (not noting in the docs due to obsoletion)
* bison:
* From PHP 7.4 and later: 3.0.0+
* From PHP 7.0 to 7.3: 2.4+ (including Bison 3.x)
* From PHP 5.5 to 5.6: 2.4 to 2.7
* PHP 5.4: 1.28, 1.35, 1.75, 2.0 to 2.6.4
PHP versions are sorted in reverse order from newest to oldest PHP.
This is also a sync with https://github.com/php/web-php/pull/983 because these are listed on two places. In this docs and in here https://www.php.net/git.php
Maybe we could simplify the https://php.net/git.php and link this …
> Update minimum versions of development tools

- reference/parle/pattern.matching.xml
This is to make it compliant with DocBook 5.2
Based on http://www.benhanson.net/lexertl.html
> Clean-up Parle pattern matching markup

- reference/yaml/functions/yaml-parse-file.xml
It seems like a copy-paste from `yaml_parse`.
> Fix incorrect reference to non-existent parameter in yaml_parse_file

- reference/session/functions/session-cache-limiter.xml
IE5-specific fields of `Cache-Control` header were removed in PHP 7.0.
https://github.com/php/php-src/commit/413d23f6f0d5e56bda3c01d3951590c05ed4d7fc
> Remove outdated header fields of `session_cache_limiter`

- reference/xmlreader/xmlreader/open.xml
- reference/xmlreader/xmlreader/xml.xml
Since these aren't deprecated or anything, I think we should document what exists now.
> Document overloads of XMLReader::open and ::XML

- reference/oci8/dtrace.xml
- reference/oci8/fan.xml
- reference/oci8/taf.xml
- reference/oci8/testing.xml
This is part of https://github.com/php/doc-en/issues/3326, a `<section>` tag needs to be immediately be followed by a <title> tag to conform to the DocBook schema.
There are still more OCI8 fixes required, so splitting this into its own PR.
> Fix markup issues in OCI8 extension docs

- reference/mysqlnd/stats.xml
- Remove personalization
- Improve document structure
- DocBook 5.2 conformance
This is probably easier by comparing to the actual live page: https://www.php.net/manual/en/mysqlnd.stats.php
The only things that really ought to be looked at, are my `TODO` comments.
> Rewrite MySQLnd statistic page

- reference/intl/locale-constants.xml
- reference/intl/numberformatter-constants.xml
Basically add required title tags.
Part of #3326
> Make Intl constant pages DocBook 5.2 conformant

- install/ini.xml
- reference/info/constants.xml
Convert info constant `<table>`s (and a table that XIncluded one of these `<table>`s) to `<variablelist>`s.
Conversion was done with [this script](https://gist.github.com/haszi/5b6815c63b0512cfa73e375562235de4) that can also be used for converting the same tables in all translations.
> Convert info constant tables to variablelists

- reference/mysqlnd/stats.xml
- Use of leading double dashes in mysqld option instead of U+2013 char
- Correction of 'implicit' to 'explicit' in example title
> Fixes to mysqlnd statistics text

- reference/dom/constants.xml
- reference/libxml/constants.xml
Add missing libxml related constants to ext/DOM and ext/libxml.
The references for these constants are:
- [XML_LOCAL_NAMESPACE](https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/include/libxml/tree.h?ref_type=heads)
- [XML_GLOBAL_NAMESPACE](https://github.com/GNOME/libxml2/commit/a4964b75003d138d4643ab03e3e116a8453f8308#diff-4d724327c74c8e7b349eb38258524a6228cc3e06b5d10f783557a8f38bcf737b) - Please note that this has been removed from libxml in October 2000 and should probably be dropped from PHP as well
- [LIBXML_LOADED_VERSION](https://github.com/GNOME/libxml2/blob/4fefba4cf63acbb17c9f9cee90b8a3b5213a2b8c/parser.c#L184-L189) - [the line in the arginfo file](https://github.com/php/php-src/blob/09d0e38ecffcae767505452a8ee853e4ed4ec6d3/ext/libxml/libxml_arginfo.h#L61) and [the internal …
> Add missing libxml related constants

- reference/pcre/pattern.modifiers.xml
as documented on https://php.watch/versions/8.2/preg-n-no-capture-modifier
> Note that no-capture modifier (/n) support for preg_* was added in PHP 8.2

- reference/dom/constants.xml
The libxml2 versions used by PHP don't have this anymore.
> Remove global namespace entry

- reference/intl/constants.xml
References:
- [INTL_ICU_DATA_VERSION](https://github.com/unicode-org/icu/blob/main/icu4c/source/common/unicode/uvernum.h#L151-L154)
- [ULOC_ACTUAL_LOCALE and ULOC_VALID_LOCALE](https://github.com/unicode-org/icu/blob/main/icu4c/source/common/unicode/uloc.h#L339-L346)
> Add some missing intl constants

- reference/uodbc/constants.xml
References for [SQL_FETCH_FIRST and SQL_FETCH_NEXT](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlfetchscroll-function?view=sql-server-ver16#positioning-the-cursor) and the [SQL_W*CHAR types](https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/unicode-data?view=sql-server-ver16).
> Add missing UODBC constants

- reference/strings/constants.xml
Copy constants from `nl_langinfo()` to constants page.
The `ABDAY`, `DAY`, `ABMON` and `MON` constants need to be listed individually (as opposed to the current `(1-7)` and `(1-12)`) format) so they can be automatically linked to which will be done in a follow up PR.
I used the following script for this update which can also be used to update all translations having the necessary files in one go:
https://gist.github.com/haszi/be927f351ab7efe23f46a11cc92c2000
If used, please note that the script should only be ran once as it will just blindly add the new constant tables to the constants page.
> Copy constants from nl_langinfo() to constants page

- reference/pcntl/constants.xml
Descriptions are from [this man page](https://www.man7.org/linux/man-pages/man3/errno.3.html) with the exception of the `ECAPMODE` constant which is from [some](https://man.freebsd.org/cgi/man.cgi?query=open&sektion=2&n=1) [BSD](https://man.freebsd.org/cgi/man.cgi?query=rename) [pages](https://man.freebsd.org/cgi/man.cgi?memfd_create).
> Add missing PCNTL error constants

- reference/intl/constants.xml
Add missing `U_` error constants to `intl` constant list. All of these are listed on the missing constant list (#2747).
_Edit:_
I used the following script which can also be used to update all translations:
https://gist.github.com/haszi/66f36bc412323e0365b8614aeabaa816
Please note that the scripts unconditionally adds the constants to the constants page, ie. without checking whether these are already present so running it more than once is not advised.
> Add U_ error constants to intl constant list

- reference/mongodb/bson/document.xml
- reference/mongodb/bson/document/offsetexists.xml
- reference/mongodb/bson/document/offsetget.xml
- reference/mongodb/bson/document/offsetset.xml
- reference/mongodb/bson/document/offsetunset.xml
- reference/mongodb/bson/packedarray.xml
- reference/mongodb/bson/packedarray/get.xml
- reference/mongodb/bson/packedarray/offsetexists.xml
- reference/mongodb/bson/packedarray/offsetget.xml
- reference/mongodb/bson/packedarray/offsetset.xml
- reference/mongodb/bson/packedarray/offsetunset.xml
- reference/mongodb/versions.xml
https://jira.mongodb.org/browse/PHPORM-182
Feature introduced in [ext-mongodb v1.17.0](https://github.com/mongodb/mongo-php-driver/releases/tag/1.17.0) by https://github.com/mongodb/mongo-php-driver/commit/2a3a9d8ce50ce4aa5ce125a2e23cdc5d43e1f625
The method files were copied from `ArrayAccess` files:
- removed examples
- `offsetGet` throws an exception instead of producing a warning
- add "see other" links to `ArrayAccess` methods and `get`/`has`
- `offsetSet` and `offsetUnset` always throw an exception, the return type is more `never` than `void`
> Add `ArrayAccess` methods for ext-mongodb BSON classes

- reference/datetime/functions/date-sun-info.xml
This function no longer returns false since PHP 8.
Also, "success" for this function means calling the function with three arguments of the correct type.
- https://github.com/php/php-src/blob/php-7.0.0/ext/date/php_date.c#L4725-L4737
- https://github.com/php/php-src/blob/php-7.4.0/ext/date/php_date.c#L5077-L5094
Therefore, only `array` was consistently written in the return value of the prototype.
> Fix return type of date_sun_info()

- reference/apcu/ini.xml
Additionally, use `<literal>` when mentioning values.
> apcu: fix types in default configuration options

- reference/apcu/ini.xml
`apc.slam_defense` was disabled by default a few years ago, in https://github.com/krakjoe/apcu/commit/c510a5ff4035647f61d24dd723e9f8e02ac9cf9b
Also, the implementation has changed significantly, and now the setting is a boolean.
This tries to update the documentation based on [the current implementation](https://github.com/krakjoe/apcu/blob/1ba5a2dade72d44ded54ebcb56b5392e2960c436/apc_cache.c#L1195).
I am happy to rebase this if https://github.com/php/doc-en/pull/3425 gets merged before.
> apcu: fix and update apc.slam_defense documentation

- language/context/ftp.xml
- language/context/http.xml
- language/context/parameters.xml
- language/context/phar.xml
- language/context/socket.xml
- language/context/ssl.xml
- language/context/zip.xml
- language/wrappers/compression.xml
- language/wrappers/php.xml
- language/wrappers/rar.xml
- language/wrappers/ssh2.xml
@Girgias Splitting this off #3422 as [requested](https://github.com/php/doc-en/pull/3422#issuecomment-2137142889).
> [skip-revcheck] Fix whitespace in stream wrapper and context options files

- README.md
I added a shortcut from this repo to the doc, it's handy when you just want to get back to the doc.
I took the same link that the on the PHP repo: https://github.com/php/php-src/blob/89c4e4c4cbf14268b71d5a340d50f8e465de2a09/README.md?plain=1#L23
> README: add link to manual

- reference/opcache/ini.xml
- Use correct type for default configuration options
- Use `<literal>` and `<code>` tags consistently
- Mark all windows-only options in the Changelog column, for consistency
- Slightly improve wording in opcache.file_cache_fallback
- Use `&null;` consistently.
> opcache: misc fixes

- language/context/ftp.xml
- language/context/http.xml
- language/context/parameters.xml
- language/context/phar.xml
- language/context/socket.xml
- language/context/ssl.xml
- language/context/zip.xml
- language/context/zlib.xml
- language/wrappers/audio.xml
- language/wrappers/compression.xml
- language/wrappers/data.xml
- language/wrappers/expect.xml
- language/wrappers/file.xml
- language/wrappers/ftp.xml
- language/wrappers/glob.xml
- language/wrappers/http.xml
- language/wrappers/phar.xml
- language/wrappers/php.xml
- language/wrappers/rar.xml
- language/wrappers/ssh2.xml
Add a role attribute with an appropriate value to all stream wrappers and context options. PhD is patched also to index these as non-functions/methods and with that these entries are removed from the function method listing.
*Edit:*
The PhD side of this fix is [this one](https://github.com/php/phd/pull/133).
> Remove stream wrappers and context options from function method listing

- reference/mongodb/architecture.xml
Lines: 422-456.
In particular:
```
class ContainerClass implements MongoDB\BSON\Serializable {
public $things = AnotherClass4 implements MongoDB\BSON\Serializable {
private $elements = [ 0 => 'foo', 2 => 'bar' ];
function bsonSerialize(): array {
return $this->elements;
}
}
function bsonSerialize(): array {
return [ 'things' => $this->things ];
}
} // => { "things" : { "0" : "foo", "2" : "bar" } }
```
Wrong `$things` definition and two `bsonSerialize()` method instead one. And `$elements` doesn't seem to be supposed to be in this example.
Etc.
I suggest replacing the code of the examples like this.
Or replace `AnotherClass4 — AnotherClass6` class names to `ContainerClass1 — ContainerClass3`
> mongodb/architecture.xml: The code of the examples seems invalid

- reference/array/setup.xml
- reference/classobj/setup.xml
- reference/dir/setup.xml
- reference/errorfunc/setup.xml
- reference/exec/setup.xml
- reference/filesystem/setup.xml
- reference/funchand/setup.xml
- reference/hash/setup.xml
- reference/info/setup.xml
- reference/json/setup.xml
- reference/mail/setup.xml
- reference/math/setup.xml
- reference/misc/setup.xml
- reference/network/setup.xml
- reference/outcontrol/setup.xml
- reference/random/setup.xml
- reference/reflection/setup.xml
- reference/spl/setup.xml
- reference/stream/setup.xml
- reference/url/setup.xml
- reference/var/setup.xml
This PR removes the installation pages for every extension that doesn't need to be installed (ie. is part of PHP's core extensions).
> Remove empty installation pages

- reference/network/functions/setcookie.xml
In strict types mode: `Fatal error: Uncaught TypeError: setcookie(): Argument #6 ($secure) must be of type bool, int given`
> setcookie.xml: amend the argument type to bool

- reference/curl/constants_curl_getinfo.xml
#3289 and this PR adds all missing CURLINFO constants listed on the [missing internal global constants](https://github.com/php/doc-en/issues/2747) list.
> Add missing CURLINFO constants

- reference/curl/constants.xml
- reference/curl/constants_curlproto.xml
Make a dedicated `<variablelist>` for `CURLPROTO_*` constants and copy all of them into this new `<variablelist>`.
> Move CURLPROTO constants to dedicated variablelist

- reference/curl/constants.xml
- reference/curl/constants_curl_share_setopt.xml
Add `curl_share_setopt()` constants (`CURLSHOPT_*` and `CURL_LOCK_DATA_*` constants) to their own dedicated constant list on the cURL constant page.
Note: `CURLSHOPT_NONE` is deliberately missing a description as the comment in the cURL source code simply says `don't use` (i.e. it probably should not be exposed by PHP).
> Add curl_share_setopt() constants to constants page

- reference/curl/constants.xml
- reference/curl/constants_curl_multi.xml
Move cURL multi handle status constants to their own variablelist. 
Add missing constant.
Add descriptions.
> Move cURL multi handle status constants to their own variablelist

- contributors.xml
This PR adds two contributors from the [frontpage](https://www.php.net/manual/en/) of the docs to the [contributors list](https://www.php.net/manual/en/preface.php#contributors).
> Add authors and editors from front page to list

- reference/hash/functions/hash-algos.xml
- reference/hash/functions/hash-file.xml
- reference/hash/functions/hash-hmac-file.xml
- reference/hash/functions/hash-hmac.xml
- reference/hash/functions/hash-init.xml
- reference/hash/functions/hash-update-file.xml
- reference/hash/functions/hash-update-stream.xml
- reference/hash/functions/hash.xml
- reference/strings/functions/md5-file.xml
- reference/strings/functions/md5.xml
- reference/strings/functions/sha1-file.xml
- reference/strings/functions/sha1.xml
Specifically remove the `md5*()` and `sha1*()` references, but also shorten the lists in general: All hash functions are somewhat related, that does not mean that each should reference each other.
see https://wiki.php.net/rfc/deprecations_php_8_4#deprecate_md5_sha1_md5_file_and_sha1_file
see php/doc-en#2822
> Clean up “See Also” for `hash*()`

- reference/tokenizer/constants.xml
The description has been copied from `token-get-all()`/`tokenize()`.
> Add TOKEN_PARSE constant

- reference/filesystem/functions/fgets.xml
In the test with multiline file, all lines of the file are outputed as one line. Let's add end-of-line symbol to the example ;-)
> fgets.xml: place each file line on new line by PHP_EOL

- appendices/transports.xml
The link text talks about the `Sockets Extension`, and the actual link leads to the list of functions of the `Socket class` (of Sockets Extension).
If I haven't got confused myself yet, and I understand correctly that the Sockets extension contains a Socket class that defines a list of socket functions, then I think it would be useful to correct the link text and add the extension name after it
> transports.xml: amend the link text

- language/predefined/stringable.xml
Stringable is introduced in PHP 8.0, so constructor promotion can be assumed.
> Simplify Stringable example with PHP 8 syntax

- language/predefined/weakmap/offsetget.xml
see https://3v4l.org/QjCMI
see RFC https://wiki.php.net/rfc/weak_maps
> Reading a non-existent key results in an Error exception.
refs https://github.com/phpstan/phpstan/issues/10655
> WeakMap::offsetGet() does not return null

- reference/sockets/functions/socket-getpeername.xml
Or at least no longer than that, as example: `Queries the remote side of the given socket for a host/port or a file system path`
> socket-getpeername.xml: remove excessive length of refpurpose

- reference/curl/constants.xml
- reference/curl/constants_curl_multi_setopt.xml
…and add descriptions. Descriptions were copied from the page of `curl_multi_setopt()`.
> Move curl_multi_setopt() constants to a dedicated variablelist

- reference/mysqli/constants.xml
Add missing mysqli constants.
Rename mistyped `MYSQLI_TRANS_START_CONSISTENT_SNAPSHOT` constant to `MYSQLI_TRANS_START_WITH_CONSISTENT_SNAPSHOT`.
> Add missing mysqli constants

- reference/tidy/tidy/errorbuffer.xml
This is a nullable string: https://github.com/php/php-src/blob/e9254494ffde88af0160a30cee53c3dfce226edf/ext/tidy/tidy.stub.php#L866
> Correct the type of $tidy->errorBuffer

- language/predefined/errorexception.xml
Incidentally this also fixes a deprecation in PHP 8.4 (nullable parameter).
> Do not throw for deprecations in ErrorException example

- reference/misc/functions/uniqid.xml
The identifier generated is time-based either in its entirety (with default options) or with some random data (with `more_entropy` enabled) so avoid describing it as unique without immediate caveats.
It's not much more than a fancy timestamp when called without any parameters, so let's not make "unique" such a central part of its description.
> Use "unique" less in describing `uniqid()`

- reference/mongodb/tutorial/apm.xml
The method `$event->getCommandName()` is more explicit in determining the name of the command used.
Fix [PHPC-2327](https://jira.mongodb.org/browse/PHPC-2327)
> Use MongoDB's `CommandStartedEvent::getCommandName()` in APM tutorial

- reference/mongodb/bson/utcdatetime/todatetimeimmutable.xml
- reference/mongodb/versions.xml
The method  `toDateTimeImmutable` is identical to `toDateTime`, except it returns an instance of `DateTimeImmutable`.
Related to https://github.com/mongodb/mongo-php-driver/pull/1611 (not released yet, it will be in extension mongodb 1.20.0).
> Add method `MongoDB\BSON\UTCDateTime::toDateTimeImmutable`

- chapters/tutorial.xml
`features/xforms.xml` will be removed once it's no longer referenced from doc-base.
> Remove reference to features.xforms (part of php/doc-en#3579)

- reference/sockets/constants.xml
Can we add a few words about these constants? The [socket_getpeername()](https://www.php.net/manual/en/function.socket-getpeername.php) function page mentions these constants, but there is not a word about them in the documentation
> constants.xml: add constant description

- reference/outcontrol/constants.xml
Add a sentence from which PHP version PHP_OUTPUT_HANDLER_PROCESSED is available.
Closes GH-3384
> Fix GH-3384

- reference/json/functions/json-decode.xml
- reference/json/functions/json-encode.xml
I think `json_last_error_msg()` is more helpful then the older `json_last_error()` variant, therefore adding it to the see-also list
> json: added json_last_error_msg to see-also

- appendices/extensions.xml
- reference/hrtime/book.xml
Updates: https://www.php.net/manual/en/extensions.membership.php
Please correct me if I'm wrong, but AFAIK, HRTime is a PECL extension and not a bundled extension.
Refs:
https://www.php.net/manual/en/hrtime.installation.php
> Extensions/Membership: fix placement HRTime

- features/http-auth.xml
It was declared obsolete as a standard in 2011. Some of the supporting code is still technically part of the SAPI layer, but there's no reason to document it here.
> Remove documentation/example of HTTP Digest Authorization

- reference/mcrypt/functions/mcrypt-module-open.xml
- reference/pdo_sqlite/PDO/sqliteCreateFunction.xml
- reference/radius/constants.xml
- reference/radius/functions/radius-put-attr.xml
- reference/sqlite3/sqlite3/createfunction.xml
`hash()` has existed since 5.1.2, should be fine to update these old examples now.
> Update examples using md5(...) to use hash('md5', ...)

- appendices/extensions.xml
- reference/gnupg/book.xml
- reference/pdo_dblib/reference.xml
- reference/pdo_firebird/reference.xml
- reference/pdo_oci/reference.xml
- reference/svn/book.xml
- reference/xmlrpc/book.xml
Note that I just grepped for the state comments, and removed those which do no longer apply. Almost certainly there are extensions which would need to be tagged, but maybe this PR is a good start to tackle https://github.com/php/doc-en/issues/3643.
> Remove extension state tags which do no longer apply

- language-snippets.ent
- reference/dom/domdocument/loadhtml.xml
- reference/dom/domdocument/loadhtmlfile.xml
Consolidates the duplicated note between `DOMDocument::loadHTML` and `DOMDocument::loadHTMLFile` and adds information about how `libxml` HTML5 parsing isn't stable across versions and the new DOM\HTMLDocument functions should be used. (Not documented yet, so they aren't linked, but will wire up automatically when it is.)
> Warn about libxml's unstable HTML parsing (fixes #2219)

- reference/session/functions/session-create-id.xml
Maximum length of prefix is 256 characters.
Reference:
https://github.com/php/php-src/blob/master/ext/session/session.c#L379
https://github.com/php/php-src/blob/master/ext/session/session.c#L75
> Maximum length of prefix in session_create_id

- reference/cmark/setup.xml
- reference/imagick/setup.xml
- reference/pthreads/setup.xml
- reference/uopz/setup.xml
Besides that new builds are no longer placed on that server, users better go to the PECL page, where they can get more information anyway.
See also #3632.
> Don't link to the direct downloads, but rather to the PECL page

- reference/mysql_xdevapi/examples.xml
The extension name is mysql_xdevapi
> Typo in mysql_xdevapi examples

- bookinfo.xml
I think this was mentioned in the discussion around #3468, the `<copyright>` block is redundant with the information in the `<legalnotice>` which is the first thing in the ToC, so we can just remove it. Will just leave a lonely `pubdate` before the ToC, but we could look at styling that better via CSS on the website, at least. Or maybe just turn it into a `<date>` within `manual.xml.in` so it ends up after the ToC along with a language snippet that actually identifies it as the date the manual was generated.
> Remove the top-level <copyright>, redundant with the <legalnotice>

- reference/ldap/constants.xml
I did not write any descriptions for the peer certificate checking and CRL evaluation strategy constants as I could not find any references discussing these in detail.
Peer certificate checking strategies:
`LDAP_OPT_X_TLS_ALLOW`
`LDAP_OPT_X_TLS_DEMAND`
`LDAP_OPT_X_TLS_HARD`
`LDAP_OPT_X_TLS_NEVER`
`LDAP_OPT_X_TLS_TRY`
CRL evaluation strategies:
`LDAP_OPT_X_TLS_CRL_ALL`
`LDAP_OPT_X_TLS_CRL_NONE`
`LDAP_OPT_X_TLS_CRL_PEER`
> Add LDAP constants

- install/ini.xml
- reference/info/constants.xml
Replace XInclude'd variablelist with a duplicate which does not have any IDs for the constants. Add IDs to the variablelist on the constant page.
> Add links to INI_* constants

- language/predefined/versions.xml
I grepped `__PHP_Incomplete_Class` in the source code of PHP musesum.
- Not found
* https://museum.php.net/php3/php-3.0.18.tar.gz
*  https://museum.php.net/php4/php-4.0.0.tar.gz
- Found
* https://museum.php.net/php4/php-4.0.1.tar.gz
refs: #3451
> Added __PHP_Incomplete_Class version info

- language-defs.ent
- reference/cmark/commonmark.cql.xml
- reference/cmark/commonmark.node.bulletlist.xml
- reference/cmark/commonmark.node.code.xml
- reference/cmark/commonmark.node.codeblock.xml
- reference/cmark/commonmark.node.heading.xml
- reference/cmark/commonmark.node.htmlblock.xml
- reference/cmark/commonmark.node.htmlinline.xml
- reference/cmark/commonmark.node.image.xml
- reference/cmark/commonmark.node.link.xml
- reference/cmark/commonmark.node.orderedlist.xml
- reference/cmark/commonmark.node.text.xml
- reference/cmark/commonmark.parser.xml
This make the word "Constructor" automatically translated in `<classsynopsisinfo>`, as is already done in most other `<classsynopsisinfo>` texts.
> New `&Construtor;` entity to avoid translatable text in parts of XML source

- reference/eio/functions/eio-seek.xml
The  signature of the `eio_seek` function does not have the `length` parameter, `whence` instead, and function does not read bytes. There is no need to specify the `length` parameter ;)
> eio-seek.xml: amend `whence` parameter and shorten the `refpurpose`

- reference/ds/ds.set.xml
- reference/ds/ds/set/map.xml
- reference/ds/versions.xml
The method `Ds\Set::map()` was first tagged in version `v1.2.7` of the extension, although it's not mentioned in the Changelog.
* https://github.com/php-ds/ext-ds/commit/ae9ce662360e9f93b4b6c7abb78b938672be1abc
What I did:
* Copied documentation from `ds/vector/map.xml` and basically just changed `vector` -> `set`
* Tested the examples
I verified the documentation and it looks OK, apart from ALL examples which look like this:
I guess it's just my environment.
> Add documentation for Ds\Set::map()

- reference/com/functions/variant-fix.xml
- reference/com/functions/variant-int.xml
There is a difference between variant_fix() and variant_int() in MSDN docs.
See [VarInt function](https://learn.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varint) and  [VarFix function](https://learn.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-varfix).
The note was removed from variant_fix() and the logic was fixed in variant_int().
> COM variant_fix() and variant_int(): differences are now clear in MSDN

- reference/cubrid/cubridmysql/cubrid-data-seek.xml
The "row number" in the sentence is not a direct reference to the function parameter row_number.
> cubrid-data-seek.xml: remove parameter tag

- reference/datetime/datetimeinterface/format.xml
We must either add the names of the format methods of both classes — `DateTime::format` and `DateTimeImmutable::format` and names of the both class names — `DateTime` and `DateTimeImmutable`, or replace the name of the method of the `DateTime::format` class with the name of the interface method — `DateTimeInterface::format`, and the name of the `DateTime` class with the name of the interface common to these classes — `DateTimeInterface`.
Otherwise, the description of the `u` parameter behaves as if it does not concern the `DateTimeImmutable::format()` method (although it is assumed that every PHP programmer knows about this; but in reality not everyone knows).
Alternative:
```
Microseconds. Note that
<function>date</function> will always generate
<literal>000000</literal> since it takes …
```
> format.xml: add both class method names or replcate to interface name

- .docker/Dockerfile
- .gitignore
- Makefile
- README.md
- docker-compose.yml
This allows us to build different formats more easily, and use `phd` and `doc-base` from parallel checkouts, which is much easier for issues that span the repositories.
> Use Makefile instead of docker-compose.yml

- reference/win32service/constants.xml
Add the `WIN32_` prefix for all constants.
> Fix typo on Win32Service constants name

- reference/gmp/book.xml
- reference/mysqlnd/config.xml
Neither PHP 5.6, nor Visual C 9 are relevant for the manual.  And the fact that GMP is available on Windows (as of PHP 5.1.0) is also irrelevant.
> Drop some irrelevant info

- reference/array/functions/array-map.xml
Why not add a few words about what a 'zip operation' is? Yes, the `array_map` page contains a sample code, but it does not contain a formal explanation, as far as all other doc pages. I suppose this information will be useful :-)
> array-map.xml: add an explanation of the 'zip operation' term

- language/enumerations.xml
> Enumerations, or "Enums", allow a developer to define a custom type that is limited to one
`or "Enums"` is parenthetical. It should have a trailing comma before the main sentence kicks back in.
> Add missing comma

- reference/memcache/memcache/delete.xml
It never should have been a parameter, basically, and was never a timeout. Just a wonky edge of the underlying interface.
Was originally noticed as part of #3672, split out to be reviewed/merged on its own.
> Clarify second param of Memcache::delete and how it was changed

- language-snippets.ent
Fixed a possible omission in "language-snippets.ent" file, where "trader.arg.slowk.ma.type" entity is duplicated but "trader.arg.fastk.ma.type" is missing.
> Possible omission fix (language-snippets.ent)

- reference/session/ini.xml
Related patch: https://github.com/php/php-src/pull/15284
Adds information about invalid values of session.gc_divisor and session.gc_probability.
> Update invalid values of session gc ini settings.

- appendices/migration72/incompatible.xml
- chapters/tutorial.xml
- language/operators/bitwise.xml
- language/operators/comparison.xml
- language/types/array.xml
- language/types/integer.xml
- reference/array/functions/array-merge.xml
- reference/datetime/datetimeinterface/gettimestamp.xml
- reference/ffi/examples.xml
- reference/mongodb/mongodb/driver/command.xml
- reference/rar/examples.xml
- reference/reflection/reflectionenum/getbackingtype.xml
- reference/session/sessionhandlerinterface.xml
- reference/stream/functions/stream-notification-callback.xml
This PR standardises the spacing of casting in PHP via `(bool) $value` style casts.
We currently have an inconsistent usage. I feel that we should standardise on a single space, which is commonly used in the community and also helps separate the "cast" from the "value".
> Standardise casting spacing

- reference/dom/domnamednodemap.xml
- reference/dom/domnamednodemap/getnameditem.xml
- reference/dom/domnodelist.xml
- reference/dom/domnodelist/item.xml
As discussed in https://github.com/php/doc-en/issues/3691 there's a read-only array access functionality to `DOMNamedNodeMap` and `DOMNodeList` which isn't documented
This is my first phpdoc PR so please review. The phd build looked fine other than `<programlisting>` tags rendering without whitespace (But that includes the ones I didn't touch so I presume it's a phd issue)
> Document DOMNamedNodeMap/DOMNodeList array access syntax

- reference/mongodb/mongodb/driver/cursor/getid.xml
- reference/mongodb/mongodb/driver/cursorid.xml
- reference/mongodb/mongodb/driver/cursorinterface/getid.xml
- reference/mongodb/versions.xml
https://jira.mongodb.org/browse/PHPC-2412
> Deprecate CursorId, document Cursor::getId() returning Int64

- reference/sockets/functions/socket-bind.xml
Remove notes related to Windows 9x/Me which is not supported by the PHP versions currently documented in the manual.
> socket-bind.xml: Remove notes related to Windows 9x/Me

- chapters/intro.xml
This is computer output.
From what I can see, we usually wrap computer output in `computeroutput` tags without quotes.
See `a is greater than b` on: https://www.php.net/manual/en/control-structures.else.php
I would say the docs site should probably style this tag in monospace font any highlight somehow.
> Use output tags

- reference/openssl/configure.xml
Cf. <https://github.com/php/php-src/issues/9890>.
Requires https://github.com/php/doc-base/pull/77. Note that this should not be merged yet, since legacy.dll is not yet shipped with the official Windows binaries.
> Document OpenSSL legacy.dll provider on Windows

- reference/strings/functions/strncmp.xml
> strncmp: Correct minor typo in example

- chapters/intro.xml
- preface.xml
As this text is prose and not computer output, I would argue that `literal` should not be used and, if anything, we should use `emphasis` for visual reasons.
We are also inconsistently quoting the initialism expansion, i.e., _PHP: Hypertext Preprocessor_. Removing the quotes makes sense to me because we will present the term in italics.
I've also added the missing closing comma for the _Preface_ parenthetical.
Discussion point: I don't love the _What is PHP?_ parenthetical. It feels clunky. I would propose that we duplicate the _Preface_ parenthetical.
> PHP ~~(recursive acronym for PHP: Hypertext Preprocessor)~~, which stands for PHP: Hypertext Preprocessor,   is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded …
> Improve _PHP: Hypertext Preprocessor_ presentation

- reference/pcntl/functions/pcntl-strerror.xml
The doc uses `error_number` as the first parameter to the `pcntl_strerror` function. However, `php-src` name for this parameter is `error_code`[^1], and it has always been[^2] `error_code`
[^1]: https://github.com/php/php-src/blob/php-8.4.0beta5/ext/pcntl/pcntl.stub.php#L1075
[^2]: https://github.com/php/php-src/blob/PHP-8.0/ext/pcntl/pcntl.stub.php#L75
> reference/pcntl: Fix `pcntl_strerror($error_code)` parameter name

- reference/pcntl/functions/pcntl-waitid.xml
The doc uses `siginfo` as the third parameter name to the `pcntl_waitid` function. However, `php-src` name for this parameter is `info`[^1].
[^1]: https://github.com/php/php-src/blob/php-8.4.0beta5/ext/pcntl/pcntl.stub.php#L1010
> reference/pcntl: Fix `pcntl_waitid(,,$info)` parameter name

- reference/readline/book.xml
- reference/readline/configure.xml
- reference/readline/constants.xml
- reference/readline/setup.xml
The libedit library is a non-GPL replacement for the GNU Readline library.
> Remove GNU Readline in favor of libedit

- language-snippets.ent
- reference/filesystem/functions/fgetcsv.xml
- reference/filesystem/functions/fputcsv.xml
- reference/spl/splfileobject/fgetcsv.xml
- reference/spl/splfileobject/fputcsv.xml
- reference/spl/splfileobject/setcsvcontrol.xml
- reference/strings/functions/str-getcsv.xml
The escape parameter is kind of a mess and the default is changing, so this adds a warning about it with an explicit recommendation to set it to the empty string instead of relying on the default that is in the process of being changed/deprecated.
> Add explicit warning about CSV function's escape parameter

- preface.xml
Kind of a proof of concept for using titleabbrev+title for more sections so the front page of the manual isn't quite so sparse.
> Add titleabbrev+title to preface and reformat info box

- install/macos/index.xml
- install/macos/packages.xml
- install/unix/debian.xml
- install/unix/dnf.xml
- install/unix/index.xml
- install/unix/openbsd.xml
- install/unix/source.xml
- language-snippets.ent
Trying to put more emphasis/information on how to install from packages (either from distributions or third parties) and for Unix, in particular, move the stuff about compiling from source down a level so new users don't get knocked in the face with it.
> Move/rewrite some of the macOS and Unix install instructions

- reference/exif/setup.xml
The required dependency on mbstring extension in exif was removed via php/php-src@755c2cd0d85b65f35abb2d54204fa7d38b820268 which made the mbstring extension optional dependency.
Also the exif extension uses the `ZEND_MOD_OPTIONAL` to define the dependency on mbstring extension so it already loads the extensions in this case properly (meaning: there's no need to mention that mbstring must be loaded before the exif in php.ini).
Update for the PHP build system:
https://github.com/php/php-src/pull/16062
> Sync exif dependency on mbstring extension as optional

- reference/zip/constants.xml
Introduced in libzip 1.11
Available in zip extension version 1.22.4 (and php 8.4)
> add Zip::ER_TRUNCATED_ZIP

- reference/mongodb/bson/utcdatetime/construct.xml
Related tickets:
* https://jira.mongodb.org/browse/PHPC-2443
* https://jira.mongodb.org/browse/PHPC-2458
Related PRs:
* https://github.com/mongodb/mongo-php-driver/pull/1643
* https://github.com/mongodb/mongo-php-driver/pull/1695
> UTCDateTime supports Int64, deprecates string and float

- reference/mongodb/mongodb/driver/monitoring/sdamsubscriber/serverchanged.xml
- reference/mongodb/mongodb/driver/monitoring/sdamsubscriber/serverclosed.xml
- reference/mongodb/mongodb/driver/monitoring/sdamsubscriber/serveropening.xml
- reference/mongodb/mongodb/driver/monitoring/sdamsubscriber/topologychanged.xml
- reference/mongodb/mongodb/driver/monitoring/sdamsubscriber/topologyclosed.xml
- reference/mongodb/mongodb/driver/monitoring/sdamsubscriber/topologyopening.xml
- reference/mongodb/mongodb/driver/monitoring/serverchangedevent.xml
- reference/mongodb/mongodb/driver/monitoring/serverclosedevent.xml
- reference/mongodb/mongodb/driver/monitoring/serverheartbeatfailedevent.xml
- reference/mongodb/mongodb/driver/monitoring/serverheartbeatstartedevent.xml
- reference/mongodb/mongodb/driver/monitoring/serverheartbeatsucceededevent.xml
- reference/mongodb/mongodb/driver/monitoring/serveropeningevent.xml
- reference/mongodb/mongodb/driver/monitoring/topologychangedevent.xml
- reference/mongodb/mongodb/driver/monitoring/topologyclosedevent.xml
- reference/mongodb/mongodb/driver/monitoring/topologyopeningevent.xml
https://jira.mongodb.org/browse/PHPC-2449
> Improve docs for when SDAM Monitoring events are dispatched

- reference/openssl/functions/openssl-pbkdf2.xml
The current recommendation are out of date so this PR updates them.
> Update recommendations for openssl_pbkdf2

- reference/openssl/functions/openssl-pkey-derive.xml
We should probably deprecate that `key_length` in 8.5...
> Add caution about openssl_pkey_derive key_length parameter

- reference/openssl/functions/openssl-dh-compute-key.xml
Currently there is no warning that it requires using the same DH parameters.
> Add caution about using the same DH params in openssl_dh_compute_key

- reference/openssl/functions/openssl-decrypt.xml
- reference/openssl/functions/openssl-encrypt.xml
Extend info for passphrase behaviour and note that it doesn't use KDF.
> Clarify passphrase for openssl_encrypt and openssl_decrypt

- reference/openssl/functions/openssl-open.xml
- reference/openssl/functions/openssl-seal.xml
The current docs for `openssl_seal` and `openssl_open` are outdated and incorrect in many places. This fixes the issues and makes them up to date with more info.
> Update and fix docs for openssl_open and openssl_seal

- reference/imagick/imagick/getresourcelimit.xml
Unit of Imagick::getResourceLimit returns value is following, not megabytes.
- bytes
- disk
- map
- memory
- pixel
- area
- count
- file
- thread
- throttle
- seconds
- time
ImageMagick 6.9.11-60 Q16 aarch64
```xml
<policy domain="resource" name="area" value="1MP"/>
<policy domain="resource" name="disk" value="2GiB"/>
<policy domain="resource" name="file" value="3"/>
<policy domain="resource" name="map" value="4MiB"/>
<policy domain="resource" name="memory" value="5MiB"/>
<policy domain="resource" name="thread" value="1"/> 
<policy domain="resource" name="time" value="7"/> 
<policy domain="resource" name="throttle" value="8"/> 
```
```php
echo "Area: " . Imagick::getResourceLimit(Imagick::RESOURCETYPE_AREA) . PHP_EOL;
echo "Disk: " . Imagick::getResourceLimit(Imagick::RESOURCETYPE_DISK) . …
```
> Fix return value description of Imagick::getResourceLimit

- reference/curl/constants_curl_setopt.xml
Add the 52 missing `CURLOPT_*` constants and their descriptions to the cURL predefined constant list. 
Reference used: https://curl.se/libcurl/c/symbols-in-versions.html
> Add missing CURLOPT constants

- reference/filesystem/functions/glob.xml
libxml2 doesn't support XIInclude 1.1 so the `set-xml-id` attribute will not work. This attribute was added by me and I've just noticed it still being there as it showed up as an error during the builds of one of the language repos.
> Remove XIInclude 1.1 attribute from element

- reference/mongodb/versions.xml
Noticed both of the following pages were displaying "(No version information available, might only be in Git)":
* https://www.php.net/manual/en/mongodb-bson-document.tophp.php
* https://www.php.net/manual/en/mongodb-bson-iterator.construct.php
> Add missing version info for Document::toPHP and Iterator ctor

- language-snippets.ent
- reference/mongodb/mongodb/driver/clientencryption.xml
- reference/mongodb/mongodb/driver/clientencryption/encrypt.xml
- reference/mongodb/mongodb/driver/clientencryption/encryptexpression.xml
The "sparsity" and "trimFactor" range options are optional. Also add missing changelog entry from introducing "rangeOpts" in 1.16.0.
https://jira.mongodb.org/browse/PHPC-2403
https://jira.mongodb.org/browse/PHPC-2462
> Range indexes are no longer experimental

- reference/array/functions/array-replace.xml
Based on discussion at PR #1470
> Simplify array_replace description and add nested array example

- features/commandline.xml
refs: https://www.php.net/manual/en/migration83.new-features.php#migration83.new-features.cli
> [PHP 8.3] It is now possible to lint multiple files.

- appendices/tokens.xml
- language/types/string.xml
This covers the PHP 8.2.0 deprecation of interpolation It also renames simple to basic and complex to advanced as those don't make a judgement on complexity.
> Rewrite and flesh out string interpolation docs

- language/types/string.xml
There is no index 4 in the `$arr` variable, which has an index 3, maybe it was meant $arr[3][2]:
```
Array
(
[0] => 1
[1] => 2
[2] => 3
[3] => Array
(
[0] => 41
[1] => 42
[2] => 43
)
[key] => Indexed value
[const-key] => Key with minus sign
[foo] => Array
(
[0] => foo1
[1] => foo2
[2] => foo3
)
)
```
> Update string.xml Fix the code example

- language/variables.xml
Updated information about restrictions on initialization of static variables to comply with PHP 8.3
> Updated paragraph on initialization of static variables

- reference/url/functions/parse-url.xml
This information is apparently not widely known, so we put it in a more prominent place.
---
In my opinion, the notes section should not contain any notes, cautions, and warnings at all. These should be put where they make most sense; the notes section should only contain "normal" text.
> Move the parse_url() caution up to description section

- appendices/migration80.xml
- appendices/migration80/new-classes.xml
- appendices/migration81/new-classes.xml
While these are already documented in the incompatible changes section regarding the resource to object conversions, they should also be listed explicitly as new classes.
---
Note that I used to verbose `<itemizedlist>` markup for consistency, although a `<simplelist>` seems more appropriate.
> Add missing new classes to migration guides

- language/variables.xml
At least we remove the grossest style guideline violations.  This still partly reads like a tutorial, though.  And the page is long.
> Depersonalize variables.xml

- reference/pcre/pattern.modifiers.xml
> The 'S' modifier has no effect, patterns are studied automatically. No real impact.
> https://wiki.php.net/rfc/pcre2-migration#backward_incompatible_changes
> PCRE S modifier has no effect since PHP 7.3.0

- reference/gmagick/gmagick/compositeimage.xml
According to the standards (and to the source code), the parameter name should be in lowercase.
> Gmagick compositeimage.xml: set parameter name to lowercase

- features/gc.xml
This is not completely true:
https://www.php.net/manual/en/language.oop5.references.php
> gc.xml objects are passed by references by default

- reference/session/functions/session-create-id.xml
- reference/session/functions/session-id.xml
Can we specify a range in the pcre-style, without introductory constructions in the sentence?
> session-create-id.xml: preg_* functions style for range

- reference/pdo/pdostatement/fetchall.xml
Currently, case 3 makes no sense (PDO::FETCH_COLUMN|PDO::FETCH_UNIQUE would result in error) and case 4 is misleading (describing rather vanilla PDO::FETCH_GROUP's behavior). I added vanilla PDO::FETCH_UNIQUE and PDO::FETCH_GROUP cases and fixed PDO::FETCH_GROUP|PDO::FETCH_COLUMN.
Also, how does one remove a comment? 
- [88699](https://www.php.net/manual/en/pdostatement.fetchall.php#88699) is bogus, they need PDO::FETCH_UNIQUE but using PDO::FETCH_GROUP
- [122299](https://www.php.net/manual/en/pdostatement.fetchall.php#122299) same as above
- [115175](https://www.php.net/manual/en/pdostatement.fetchall.php#115175) is bogus, PDO::FETCH_UNIQUE|PDO::FETCH_GROUP makes no sense and effectively just PDO::FETCH_UNIQUE
> Update use cases for the mode parameter in PDOStatement::fetchAll()

- reference/session/functions/session-name.xml
There is no directive `session.transid` in PHP. It's probably about the `session.use_trans_sid` directive instead `session.transid`, if I got the context right
> session-name.xml: use the correct directive name and add the link to

- appendices/tokens.xml
Original "::" is repetitive and difficult to see.
Changed to "scope resolution" for clarity.
> Change the T_PAAMAYIM_NEKUDOTAYIM link text in tokens doc

- reference/spl/arrayobject.xml
See <https://github.com/php/php-src/pull/15775#issuecomment-2334813587>. While a formal deprecation process is pending, it seems prudent to not advertise this class any longer.
> Discourage the use of ArrayObject

- reference/outcontrol/constants.xml
- reference/outcontrol/user-level-output-buffers.xml
Documents the changes made in https://github.com/php/php-src/pull/13087 and https://github.com/php/php-src/pull/15183. Also related to https://github.com/php/php-src/issues/16133.
> Update descriptions of disabled output handler

- install/windows/recommended.xml
The php.ini file has not `extensions_dir` directive. Apparently the directive `extension_dir` was meant
> recommended.xml Add tags

- reference/uodbc/functions/odbc-num-rows.xml
Replace `<literal>` with the more suitable `<emphasis>`.
> odbc-num-rows.xml: Replace literal with emphasis

- language/oop5/final.xml
- language/oop5/properties.xml
- language/oop5/visibility.xml
- reference/reflection/reflectionproperty/isprivate.xml
- reference/reflection/reflectionproperty/isprotected.xml
- reference/reflection/reflectionproperty/ispublic.xml
First stab at documenting asymmetric visibility and final properties.  (Technically final properties came in with hooks, but that's a much bigger task and it does impact aviz, so I included it here.)
> Asymmetric Visiblity and Final properties

- reference/tidy/tidy/getoptdoc.xml
- reference/tidy/tidy/parsefile.xml
- reference/tidy/tidynode/getnextsibling.xml
- reference/tidy/tidynode/getprevioussibling.xml
- reference/tidy/versions.xml
Drive by fix in second commit too
> Document tidyNode::getNextSibling() and tidyNode::getPreviousSibling()

- language-snippets.ent
- reference/gearman/gearmanclient/setclientcallback.xml
- reference/gearman/gearmanclient/setcompletecallback.xml
- reference/gearman/gearmanclient/setcreatedcallback.xml
- reference/gearman/gearmanclient/setdatacallback.xml
- reference/gearman/gearmanclient/setexceptioncallback.xml
- reference/gearman/gearmanclient/setfailcallback.xml
- reference/gearman/gearmanclient/setstatuscallback.xml
- reference/gearman/gearmanclient/setwarningcallback.xml
- reference/gearman/gearmanclient/setworkloadcallback.xml
This includes:
- specification of arguments and return type of each callback method (see #1370)
- a note that the `setXXXCallback` methods should be called before calling `addTaskXXX` (see #1369)
___
In the [PECL extension](https://github.com/php/pecl-networking-gearman) you can see, that all callback functions are called (equally) by this code snippet:
https://github.com/php/pecl-networking-gearman/blob/a52052cdd712a95091ce926be3bcdca41c730696/php_gearman_task.c#L32-L48
If you look closely, you might note, that `task->zdata` (which is called `$context` in PHP) will be provided if it has been set when `GearmanClient::addTaskXXX` was called. As I have tested, otherwise `null` is passed and no warning/error/exception is raised.
For some of the `GearmanClient::setXXXCallback` methods, there …
> Fix #1369 + #1370: adding GearmanClient::setXXXCallback documentation

- appendices/migration84.xml
- appendices/migration84/constants.xml
- appendices/migration84/deprecated.xml
- appendices/migration84/incompatible.xml
- appendices/migration84/new-classes.xml
- appendices/migration84/new-features.xml
- appendices/migration84/new-functions.xml
- appendices/migration84/other-changes.xml
- appendices/migration84/removed-extensions.xml
- appendices/migration84/windows-support.xml
> WIP: start writing migration guide

- reference/tidy/tidynode/getnextsibling.xml
- reference/tidy/tidynode/getparent.xml
- reference/tidy/tidynode/getprevioussibling.xml
I guess we now know why these weren't linked properly.
> Fix "See also" section in tidyNode

- reference/win32service/setup.xml
The Win32Service version 1.1 improves the service's rights management. This PR updated the security consideration section to add the new feature from version 1.1.
Must be merged after https://github.com/php/doc-base/pull/164 
Replace #3551
> [Win32Service] Update the security consideration with the 1.1.0 feature

- faq/obtaining.xml
The GNU Readline library is GPL 3 licensed and incompatible with PHP license.
> Recommend obtaining libedit instead of GNU Readline

- features/http-auth.xml
Digest HTTP Authentication example has been removed, but the mention of the content of the deleted paragraph remains
> http-auth.xml: remove mention of digest

- reference/intl/intlchar/getbidipairedbracket.xml
Based on: https://github.com/php/php-src/issues/15092 and https://github.com/unicode-org/icu/blob/23d9628f88a2d0127c564ad98297061c36d3ce77/icu4j/main/core/src/main/java/com/ibm/icu/lang/UCharacter.java#L5008
> getbidipairedbracket.xml: add a note about the ICU compatible version

- reference/spl/arrayobject.xml
This is a follow-up to PR #3858, based on a comment by @arnaud-lb[1].
[1] <https://github.com/php/php-src/issues/16371#issuecomment-2410928030>
> Restrict discouragement of ArrayObject to wrapping objects

- reference/pdo/pdostatement/execute.xml
The incredibly wasteful way this example creates SQL placeholders has long annoyed me, so here's a fix.
> Reduce overhead of SQL placeholder creation

- reference/zip/ziparchive/getarchiveflag.xml
The "s" was outside of the parameter tag.
> getarchiveflag.xml: fix parameter name to flags

- appendices/migration70/incompatible/other.xml
This is no longer allowed ([3v4l.org](https://3v4l.org/MMuci)):
```php
while (true) {
break E_ERROR;
}
```
It seems like this is a continuation of the change introduced in PHP 5.4, and was overlooked in the documentation.
> The break and continue statements no longer accept variable arguments (e.g., break 1 + foo() * $bar;).
Source: https://php-legacy-docs.zend.com/manual/php5/en/migration54.incompatible
> Constant disallowed as break and continue argument as of PHP 7.0

- reference/oauth/oauth/enablesslchecks.xml
In reference/oauth/oauth/enablesslchecks.xml:
A non-false value in sslChecks member turns SSL checks on, not off.
> OAuth::enableSSLChecks non-false value turns checks on, not off.

- reference/dom/functions/dom-import-simplexml.xml
See <https://github.com/php/php-src/pull/16489>.
> Fix dom_import_simplexml() return type

- appendices/extensions.xml
- language-snippets.ent
- reference/mongodb/architecture.xml
- reference/mongodb/book.xml
- reference/mongodb/bson.xml
- reference/mongodb/configure.xml
- reference/mongodb/exceptions.xml
- reference/mongodb/ini.xml
- reference/mongodb/mongodb.xml
- reference/mongodb/monitoring.xml
- reference/mongodb/security.xml
- reference/mongodb/setup.xml
- reference/mongodb/tutorial.xml
- reference/mongodb/tutorial/apm.xml
- reference/mongodb/tutorial/library.xml
Convert all underlying elements as needed:
- `<books>` to `<part>`s or `<chapter>`s
- `<article>`s to `<section>`s
Move the Predefined Constants page from the Installing/Configuring section to its own
Change the following `xml:id`s:
- `book.mongodb` to `mongodb.mongodb`
- `set.mongodb` to `book.mongodb`
- `book.bson` to `mongodb.bson`
Please note that these changes only work when the accompanying `doc-base` changes are merged too (https://github.com/php/doc-base/pull/138).
*Note:*
Please note that because of the difference between `root chunks` and `container chunks` in `PhD` (ie. a `<book>` and a `<part>`), the four pages linked to from the main [MongoDB page](https://www.php.net/manual/en/set.mongodb) ([MongoDB](https://www.php.net/manual/en/book.mongodb.php), …
> Convert MongoDB documentation from a top element of set to book

- language/predefined/stringable.xml
Props to Gormack for the idea: https://www.php.net/manual/en/class.stringable.php#126627
The interface was introduced in PHP 8, and you know what else was introduced in that version? Promoted constructor properties. By reducing the boilerplate, the example becomes a lot more focused.
> Simplify example in `Stringable` docs.

- reference/curl/constants.xml
This PR adds the last few missing constants from https://github.com/php/doc-en/issues/2747. All constant descriptions and cURL version availability is based on the [cURL Symbols page](https://curl.se/libcurl/c/symbols-in-versions.html).
As the last commit sorts the constants which throws off the diff, this PR is definitely best reviewed commit by commit.
As a side note, I used [this script](https://gist.github.com/haszi/bca07054a7d4504d773d8d7fdfcffe2f) to sort the constants which may or may not be useful for doing the same in the translations.
> Add missing cURL constants

- reference/curl/functions/curl-multi-close.xml
This function is not actually a noop with PHP 8.x.
> curl: Fix `curl_multi_close()` description

- reference/strings/functions/strcspn.xml
Using human readable words for the `$characters` parameter creates confusion, as each character is used separately in the function.
I propose to simplify the example by using one character when focusing on the standard behavior or the offset/length parameters. And modifying the example to use multiple consecutive characters instead of a real word (with duplicate characters).
> Clarify `strcspn()` example

- reference/dom/domimplementation/createdocument.xml
Technically this can throw INVALID_STATE_ERR on allocation failure, just like other DOM node classes, but people shouldn't be handling that anyway as that happens when the system allocator is OOM...
> Document DOMImplementation::createDocument() change for PHP  8.4

- reference/sodium/constants.xml
- reference/sodium/functions/sodium-crypto-aead-aegis128l-decrypt.xml
- reference/sodium/functions/sodium-crypto-aead-aegis128l-encrypt.xml
- reference/sodium/functions/sodium-crypto-aead-aegis128l-keygen.xml
- reference/sodium/functions/sodium-crypto-aead-aegis256-decrypt.xml
- reference/sodium/functions/sodium-crypto-aead-aegis256-encrypt.xml
- reference/sodium/functions/sodium-crypto-aead-aegis256-keygen.xml
- reference/sodium/versions.xml
- https://github.com/php/doc-en/issues/3872
Constants:
- `SODIUM_CRYPTO_AEAD_AEGIS128L_KEYBYTES`
- `SODIUM_CRYPTO_AEAD_AEGIS128L_NSECBYTES`
- `SODIUM_CRYPTO_AEAD_AEGIS128L_NPUBBYTES`
- `SODIUM_CRYPTO_AEAD_AEGIS128L_ABYTES`
- `SODIUM_CRYPTO_AEAD_AEGIS256_KEYBYTES`
- `SODIUM_CRYPTO_AEAD_AEGIS256_NSECBYTES`
- `SODIUM_CRYPTO_AEAD_AEGIS256_NPUBBYTES`
- `SODIUM_CRYPTO_AEAD_AEGIS256_ABYTES`
Functions:
- `sodium_crypto_aead_aegis128l_decrypt()`
- `sodium_crypto_aead_aegis128l_encrypt()`
- `sodium_crypto_aead_aegis128l_keygen()`
- `sodium_crypto_aead_aegis256_decrypt()`
- `sodium_crypto_aead_aegis256_encrypt()`
- `sodium_crypto_aead_aegis256_keygen()`
> [PHP 8.4] Add new Sodium functions and constants

- reference/filter/constants.xml
Two were missing, and two are removed as of PHP 8.0.0.
> Update filter constants

- reference/mhash/constants.xml
We fix the uncommon markup, remove constants which are not available, and add constant which are available (including the PHP version they have been introduced). We do not, however, document the purpose of these legacy constants, which should be self-explaining anyway.
Closes GH-3902.
---
Might best be reviewed commit by commit.
> Update mhash constants page

- Makefile
As a `docker run` will only perform a single build, the container is useless afterwards. Ensure it is automatically removed after the build.
> Makefile: Automatically remove Docker containers

- reference/curl/constants_curl_setopt.xml
Updated descriptions of `CURLOPT_*` constants with the following:
- added some missing descriptions
- added type information on the associated accepted values
- added default values
- added cURL version information on availability, deprecation, removal 
- added applicable DocBook tags
- replaced lists of accepted value constants with their generalized version (eg.  `CURLALTSVC_*` instead of listing all `CURLALTSVC_` constants individually)
- standardized minor style details (e.g. use cURL instead of curl, libcurl, CURL; sentences to end in a period; remove double quotes from within `<literal>` tags, etc.)
Unfortunately since `CURLOPT` constants are the biggest subset of all cURL constants, the diff is pretty big.
> Update CURLOPT constant descriptions

- reference/com/functions/variant-cast.xml
- reference/com/functions/variant-get-type.xml
- reference/com/variant/construct.xml
- reference/curl/functions/curl-multi-add-handle.xml
- reference/curl/functions/curl-multi-remove-handle.xml
- reference/curl/functions/curl-setopt.xml
- reference/curl/functions/curl-version.xml
- reference/dom/domnode.xml
- reference/image/functions/getimagesize.xml
- reference/image/functions/image-type-to-extension.xml
- reference/image/functions/image-type-to-mime-type.xml
- reference/image/functions/imagepng.xml
- reference/soap/soapserver/setpersistence.xml
- reference/tidy/constants.xml
Replace the replaceable parts of constants using `_XXX` with `_*` and add a `<replaceable>` tag. 
Also replaced some `<literal>` with `<constant>` tags and removed two `<link>`s as I'm planning on adding a feature to `PhD` that would link these `_*` constants to the first matching constant defined in the index.
> Replace _XXX with _* in constants

- reference/curl/functions/curl-multi-remove-handle.xml
The function removes a normal handle from the cURL multi handle, rather than multi handle
> curl-multi-remove-handle.xml Correct the inaccuracy of the description

- language-snippets.ent
- reference/mysqli/mysqli/kill.xml
- reference/mysqli/mysqli/ping.xml
- reference/mysqli/mysqli/refresh.xml
In addition to the row in the changelog,
shouldn't we also add this entry?
Refs: 
1afd3581fea176162adacef6dd692dfc114410f3
4d68e15db0907404cad6c78ac274fd8f8c31fba3
3bbf9e31d58a54743c8509cbce76567efd4de5d1
> [PHP 8.4] Add deprecation warning to mysqli functions

- reference/mysqli/constants.xml
Deprecate `MYSQLI_REFRESH_* ` and `MYSQLI_STORE_RESULT_COPY_DATA`
> [PHP 8.4] Add deprecation warning to mysqli constants

- reference/curl/functions/curl-multi-select.xml
The term `activity` is too general, and does not explain exactly what the function is waiting for. Besides, at least for me, it's not obvious what exactly the function is blocking: the PHP script, the current connection, all of the cURL multi handle connections?..
I propose to consider a more detailed description of the function
> curl-multi-select.xml Describe in more detail

- reference/tidy/constants.xml
This adds the type of the constants at the same time.
> Use standard variablelist markup for Tidy constants

- appendices/migration84/constants.xml
- appendices/tokens.xml
Once the property hooks page is done, links should be added in tokens.xml
> [PHP 8.4] Add new constants and tokens from the tokenizer

- reference/curl/functions/curl-exec.xml
It seems to me an omission that in the description of the `curl_exec()` there is no mention of the transfer output to the browser (if https://www.php.net/manual/en/curl.constants.php#constant.curlopt-returntransfer option is not set)
> Update curl-exec.xml Mention the direct output

- reference/pgsql/functions/pg-fetch-result.xml
- reference/pgsql/functions/pg-free-result.xml
This is a very small change.
It's a fairly old code example, and it has unnecessary error handling, similar to what was pointed out in https://github.com/php/doc-en/pull/3972#discussion_r1822605837, so I removed it.
> refactor(ext/pgsql): Remove unnecessary error handling

- reference/intl/grapheme/grapheme-str-split.xml
- reference/intl/versions.xml
- reference/mbstring/functions/mb-str-split.xml
- reference/strings/functions/str-split.xml
Add grapheme_str_split function.
RFC:
- https://wiki.php.net/rfc/grapheme_str_split
ref: #3872
> [PHP 8.4] Add manual for grapheme_str_split function

- reference/pgsql/functions/pg-result-memory-size.xml
- reference/pgsql/versions.xml
> [PHP 8.4] Add manual for `pg_result_memory_size()`

- install/fpm/configuration.xml
Maybe we should explain the access log format in more detail?
> fpm/configuration.xml Clarify the option descriptions

- reference/math/constants.xml
This also adds a note to recommend using the new RoundingMode enum.
> Group math constants and use standard <variablelist> tag

- reference/pdo_pgsql/constants.xml
> [PHP 8.4] Add manual for `PDO::PGSQL_ATTR_RESULT_MEMORY_SIZE`

- language-snippets.ent
> Add `warn.deprecated.feature-8-4-0` to language-snippets.ent

- reference/array/functions/array-all.xml
- reference/array/functions/array-any.xml
- reference/array/functions/array-filter.xml
- reference/array/functions/array-find-key.xml
- reference/array/functions/array-find.xml
- reference/array/versions.xml
This pull request adds the documentation for the [array_find RFC](https://wiki.php.net/rfc/array_find) which introduced the methods `array_find`, `array_find_key`, `array_all` and `array_any`.
> Add documentation for `array_find` RFC

- reference/pdo_pgsql/constants.xml
fixes: https://github.com/php/doc-en/pull/3983#discussion_r1827141548
> fix(pdo_pgsql/constants): Correct use of `null` values

- language/oop5.xml
- language/oop5/changelog.xml
- language/oop5/lazy-objects.xml
- reference/reflection/reflectionclass.xml
- reference/reflection/reflectionclass/getlazyinitializer.xml
- reference/reflection/reflectionclass/initializelazyobject.xml
- reference/reflection/reflectionclass/isuninitializedlazyobject.xml
- reference/reflection/reflectionclass/marklazyobjectasinitialized.xml
- reference/reflection/reflectionclass/newlazyghost.xml
- reference/reflection/reflectionclass/newlazyproxy.xml
- reference/reflection/reflectionclass/resetaslazyghost.xml
- reference/reflection/reflectionclass/resetaslazyproxy.xml
- reference/reflection/reflectionproperty/islazy.xml
- reference/reflection/reflectionproperty/setrawvaluewithoutlazyinitialization.xml
- reference/reflection/reflectionproperty/skiplazyinitialization.xml
- reference/reflection/versions.xml
RFC: https://wiki.php.net/rfc/lazy-objects
> Document lazy objects

- reference/datetime/constants.xml
Improve grouping and add a warning for the whole group
> SUNFUNCS_* constants are deprecated as of PHP 8.4.0

- reference/strings/versions.xml
see https://github.com/php/doc-en/pull/4010#discussion_r1830046625
> Use full version for `utf8_(de|en)code` deprecation

- language/predefined/weakreference.xml
Maybe we should describe in more detail the features of weak references?
I am not sure about the correctness of the wording, but the scant information about WeakReference needs to be supplemented
> weakreference.xml Give more details about the WeakReferences

- language/functions.xml
`function bar(A $a = null, $b) {} // Deprecated (Deprecated what exactly? The positioning, implicity nullable type, other?) as of PHP 8.4.0; $a is required (Why? After all, the parameter has a default value) but nullable (Why?)`
My questions are in parentheses.
As a reader, I would like to get answers to these questions. (Especially if considering the example outside the context of the page.)
> functions.xml Make the comment clearer

- reference/curl/functions/curl-init.xml
I think that in the context of the curl_init() function, it is appropriate to replace the term "resource" with the term "session", since the resource is no longer relevant since PHP 8.0.0, and the session is relevant for both newer versions of PHP and before PHP 8.0.0
> curl-init.xml: replace 'resource' to 'session'

- reference/info/functions/phpversion.xml
Since the versioning constants names is `PHP_*_VERSION` rather than `PHP_VERSION_*`:
* PHP_MAJOR_VERSION
* PHP_MINOR_VERSION
* PHP_RELEASE_VERSION
> phpversion.xml: move replaceable part of constant name

- reference/curl/constants_curl_share_setopt.xml
Please note that `CURLSHOPT_NONE` is one of those constants that don't actually do anything but are the first element in a `c` enum in `cURL`. There are also a few `_LAST` and `_LASTONE` constants in `doc-en` that also don't do anything but are the last element of such enums.
> Add cURL version availability info to CURLSHOPT constants

- reference/libxml/constants.xml
- reference/libxml/functions/libxml-disable-entity-loader.xml
Based on stale PR GH-1409.
Closes GH-1409.
Closes GH-1408.
> Fix GH-1408: Deprecation of libxml_disable_entity_loader() should warn about constants which will override the new default behaviour

- reference/reflection/reflectionattribute.xml
- reference/reflection/reflectionclass/resetaslazyghost.xml
- reference/reflection/reflectionmethod/construct.xml
- reference/reflection/reflectionproperty.xml
- reference/reflection/reflectionproperty/islazy.xml
- reference/reflection/reflectionproperty/setrawvaluewithoutlazyinitialization.xml
> PHP 8.4: Document reflection changes

- appendices/migration84/new-features.xml
The headline of this change is "Readfile", but it should be "Readline".
> Added ability to change the `.php_history` path through   the `PHP_HISTFILE` environment variable.
The change is related to REPL (read-eval-print loop) mode, which requires readline extension.
> Update migration84/new-features.xml: readfile -> readline

- reference/math/functions/fdiv.xml
- reference/math/functions/fpow.xml
- reference/math/functions/pow.xml
- reference/math/versions.xml
~~Waiting on https://github.com/php/php-src/pull/16751~~
> PHP-8.4: Document fpow()

- reference/spl/arrayiterator/seek.xml
- reference/spl/seekableiterator/seek.xml
- reference/spl/splobjectstorage/seek.xml
- reference/spl/versions.xml
@nielsdos could you document this as, IIRC, you added this?
Related (#4047)
> PHP 8.4: Document SplObjectStorage::seek()

- install/fpm/configuration.xml
This mirrors the simplification that has already been done [here](https://github.com/php/php-src/commit/482784284a2e3869b500b25b41ff729143d61c79#diff-9b8e23037e5096da2b8c638e594d879bd09d61bb4acca3c80d4dc68469130ed0R117).
> Simplify pm.start_servers default

- reference/opcache/ini.xml
PR: https://github.com/php/php-src/pull/13676
> Update documentation of opcache.interned_strings_buffer

- reference/errorfunc/functions/trigger-error.xml
Turns out the return type is already correct.
I have no idea for a "good" example, I was going to go for something to use `E_USER_DEPRECATED` but realised the new `Deprecated` attribute is better suited for this.
Maybe @TimWolla has opinions on how to format it for a See Also section?
> PHP 8.4: trigger_error() updates

- reference/apache/functions/apache-request-headers.xml
- reference/apache/functions/apache-response-headers.xml
- reference/apache/functions/getallheaders.xml
The stubs for Apache functions `apache_request_headers`, `getallheaders` and `apache_response_headers` are as follows:
```php
<?php
// https://github.com/php/php-src/blob/PHP-8.3.12/sapi/apache2handler/php_functions.stub.php
// https://github.com/php/php-src/blob/PHP-8.3.12/sapi/cgi/cgi_main.stub.php
function apache_request_headers(): array {}
/** @alias apache_request_headers */
function getallheaders(): array {}
function apache_response_headers(): array {}
```
However, the return types in the docs wrongly include `false` as a return type for those functions.  
There even are some discrepancies within the same page between the **Description** content and the **Return Values** section.
This PR aims to fix these inconsistencies.
> Fix Apache functions return types to reflect the stubs

- reference/curl/constants.xml
- reference/curl/constants_curl_getinfo.xml
- reference/curl/constants_curl_setopt.xml
- reference/curl/functions/curl-getinfo.xml
- reference/curl/functions/curl-setopt.xml
- reference/curl/functions/curl-version.xml
- reference/curl/setup.xml
> [PHP 8.4] Curl new options and constants

- reference/posix/constants.xml
Seems like a typo?
Also, the `POSIX_PC_SYMLINK_MAX` from PHP 8.3 seems to be undocumented, and the `POSIX_SC_OPEN_MAX` which has existed since I don't know when is also not documented. Could you document those @devnexen?
> POSIX: Fix typo in constant

- appendices/reserved.constants.core.xml
Listing all `E_*` constants in the appendix appears to be reasonable, but having a dedicated `varlistentry` for each seems to be overkill.
---
> Group E_* constants in appendix

- reference/filesystem/functions/fgetcsv.xml
- reference/filesystem/functions/fputcsv.xml
- reference/spl/splfileobject/fgetcsv.xml
- reference/spl/splfileobject/fputcsv.xml
- reference/spl/splfileobject/getcsvcontrol.xml
- reference/spl/splfileobject/setcsvcontrol.xml
- reference/strings/functions/str-getcsv.xml
I *might* have pushed it a bit with the XIncludes and XPath queries.
> PHP 8.4: CSV related changes and deprecations

- appendices/reserved.constants.core.xml
Change PHP_DEBUG and PHP_ZTS to bool and add that these are aliases of their ZEND equivalents. Follow up of #3054.
> Change PHP_DEBUG and PHP_ZTS to bool

- reference/math/book.xml
- reference/math/roundingmode.xml
- reference/math/versions.xml
Related to #3419 and https://github.com/php/phd/pull/179
> PHP 8.4: Document RoundingMode

- reference/pcntl/book.xml
- reference/pcntl/qosclass.xml
Requires https://github.com/php/phd/pull/179 for rendering
> PCNTL: Include new enum into docs

- reference/random/book.xml
- reference/random/random.intervalboundary.xml
- reference/random/versions.xml
Part of: https://github.com/php/doc-en/issues/2796
Fixes:
- https://github.com/php/doc-en/issues/3074
Requires:
- https://github.com/php/doc-en/issues/3326
- PhD support to render it like an enum (https://github.com/php/phd/issues/89)
I kinda wish I could use a `<refentry>` tag instead, but we need to insert this into a `<book>` element which requires an intermediate tag anyway, so steal the suboptimal markup from classes.
@haszi do you think this makes sense, and is this not too complicated to add support to PhD for it?
> 8.3: Document Random\IntervalBoundary

- language/constants.xml
- language/oop5.xml
- language/oop5/abstract.xml
- language/oop5/interfaces.xml
- language/oop5/property-hooks.xml
- language/oop5/variance.xml
This is now ready for content review.  Should be mergeable.
> Hooks documentation

- reference/pgsql/constants.xml
- reference/pgsql/functions/pg-result-status.xml
- reference/pgsql/functions/pg-set-chunked-rows-size.xml
- reference/pgsql/versions.xml
Refs:
* php/php-src#14571
I'm not very good at English, so please feel free to point out or correct any unnatural parts in my phrasing.
> PHP 8.4: pgsql: Add `pg_set_chunked_rows_size`, `PGSQL_TUPLES_CHUNK`

- reference/dom/domnode.xml
Includes missing 8.3 and 8.4 changes.
Closes & replaces GH-2893.
> Update changelog for DOMNode

- reference/spl/splfileobject/setcsvcontrol.xml
Fix `tr` build. Also remove an error on `it`.
> [skip-revcheck] Fill xi:fallback to avoid 'variablelist incomplete' in some translations

- reference/bc/functions/bcpow.xml
Also, the explanation of the behavior when the second argument `exponent` has a fractional part was incorrect, so I fixed it.
> ext/bcmath - `bcpow`: Reflected the behavior change when division by 0 occurs.

- reference/bc/functions/bcdiv.xml
- reference/bc/functions/bcmod.xml
about `bcdiv` and `bcmod`.
Also, since `bcmod` was missing the explanation of the scale parameter, I added it in passing.
It seems like some of the error/exception items can be shared, but other functions are also involved, so I'll do it all together later.
> ext/bcmath - Fixed because the behavior change when dividing by 0 from PHP 8.0 was not reflected.

- reference/xmlreader/xmlreader.xml
Their definitions were already typed, so this just adds the changelog entry.
> PHP 8.4: Add changelog entry for typed constants in XMLReader

- reference/filter/constants.xml
- reference/filter/filters.xml
Remove the "Other filter" section
> Filter: Document FILTER_CALLBACK

- language/oop5/property-hooks.xml
The word `all` seems to deceive the reader a little :)
How about adding some specifics about which properties are allowed to declare hooks for?
> property-hooks.xml Replace 'all' with 'non-static', as not all + typos

- reference/bc/functions/bcceil.xml
- reference/bc/functions/bcdiv.xml
- reference/bc/functions/bcdivmod.xml
- reference/bc/functions/bcfloor.xml
- reference/bc/functions/bcmod.xml
- reference/bc/functions/bcround.xml
- reference/bc/versions.xml
RFC:
https://wiki.php.net/rfc/adding_bcround_bcfloor_bcceil_to_bcmath
https://wiki.php.net/rfc/add_bcdivmod_to_bcmath
I found an error in the existing documentation regarding `bcdiv` and `bcmod`.
But instead of this PR, I'll follow it up with another PR.
Regarding errors/exceptions, I will add everything except `bcdivmod` later.
> ext/bcmath - Added `bcceil`, `bcfloor`, `bcround` and `bcdivmod`

- language/oop5/interfaces.xml
In the footsteps of the issue: https://github.com/php/doc-en/issues/4151
> interfaces.xml Make the class property truly virtual

- language/oop5/interfaces.xml
I've also made the same correction in the original RFC, where this was copied from.
> Fix typo in example code.

- install/composer.xml
- language/oop5/autoload.xml
Long past time that we included information about Composer in the documentation. Related PR for `doc-base` incoming.
> Add information about Composer and example of using its autoloader

- language/functions.xml
If we agree that a) parameters are part of the function signature, i.e. an integral part of the function declaration, and b) arguments are information that comes to the function from the outside, then we must eliminate confusion in the text. To simplify it: the arguments are passed, and the parameters take values from the arguments and, after argument's expression are evaluated, set values for their parameters. If so, there seem to be inconsistent places in the text where parameters are passed and functions take parameters rather than arguments or something like that
> functions.xml Eliminate confusion in fn's parameters and arguments

- reference/pcre/pattern.syntax.xml
https://www.php.net/manual/en/regexp.introduction.php
When viewing the page from php.net, "described below" is awkward phrasing when there is no content below from which is described.
I haven't proposed changes in a while to the manual, which is why I'm making this a PR instead of pushing directly.
> On Regexp manual page, revise wording, "described below" -> "described in this section"

- language/oop5/abstract.xml
The only thing I'm not sure about is whether one empty line is required between the hooks that contain the implementation. With an empty string, readability seems to be better.
If we imagine that hooks are the same as methods, then, perhaps, it is better to leave one empty string between the "methods" :)
In this case, it might be better to add one empty line between hooks without implementation
> abstract.xml Fix the error in the last example and CS

- reference/iconv/functions/iconv-strlen.xml
"length in byte" should read "length in bytes."
> Fix typo in iconv-strlen.xml

- language/oop5/constants.xml
> [PHP 8.3] Add class constants dynamic fetch syntax

- language/variables.xml
Part of #2796
Already present, but I think this could be emphasized a bit rather than just having a code snippet that says it's correct without further explanation in example 9 of https://www.php.net/manual/en/language.variables.scope.php.
> [PHP 8.3] Emphasize arbitrary expressions in static initializer

- language/oop5/anonymous.xml
> [PHP 8.3] Add an example for readonly anonymous class

- language/oop5/properties.xml
> [PHP 8.3] Mention readonly props reset in `__clone()`

- language/errors/php7.xml
- language/predefined/exceptions.xml
- language/predefined/requestparsebodyexception.xml
- language/predefined/versions.xml
- reference/network/functions/request-parse-body.xml
- reference/network/versions.xml
@iluuu1994 I created a stub, if you could document this. :)
> Create stub for request_parse_body()

- language/types/array.xml
> [PHP 8.3] Assigning a negative index to an empty array

- language/oop5/constants.xml
> [PHP 8.3] Check variance of class constants

- reference/ffi/ffi/cdef.xml
FFI is pretty sparsely documented as it is, so just a changelog entry here seems appropriate.
> Document change in how C void returns are handled (closes #4202)

- reference/dom/domattr.xml
- reference/dom/domcdatasection.xml
- reference/dom/domcharacterdata.xml
- reference/dom/domcomment.xml
- reference/dom/domdocument.xml
- reference/dom/domdocumentfragment.xml
- reference/dom/domdocumenttype.xml
- reference/dom/domelement.xml
- reference/dom/domentity.xml
- reference/dom/domentityreference.xml
- reference/dom/domnamespacenode.xml
- reference/dom/domnamespacenode/sleep.xml
- reference/dom/domnamespacenode/wakeup.xml
- reference/dom/domnode.xml
- reference/dom/domnode/sleep.xml
- reference/dom/domnode/wakeup.xml
- reference/dom/domnotation.xml
- reference/dom/domprocessinginstruction.xml
- reference/dom/domtext.xml
- reference/dom/versions.xml
DOM class synopsis related changes.
> Synchronize manual with stubs for PHP 8.4 - part 5

- reference/datetime/dateinterval/createfromdatestring.xml
- reference/datetime/datetime/modify.xml
- reference/datetime/datetime/sub.xml
- reference/datetime/datetimeimmutable/modify.xml
- reference/mysqli/mysqli_driver/report-mode.xml
- reference/phar/Phar/copy.xml
- reference/phar/Phar/decompressFiles.xml
- reference/phar/Phar/delMetadata.xml
- reference/phar/Phar/delete.xml
- reference/phar/Phar/unlinkArchive.xml
- reference/phar/PharData/copy.xml
- reference/phar/PharData/decompressFiles.xml
- reference/phar/PharData/delMetadata.xml
- reference/phar/PharData/delete.xml
- reference/phar/PharFileInfo/compress.xml
- reference/phar/PharFileInfo/decompress.xml
- reference/phar/PharFileInfo/delMetadata.xml
Apparently, all the affected mysqli and Phar methods were always returning `true`.
> Synchronize manual with stubs for PHP 8.4 - part 2

- language-snippets.ent
- reference/bc/functions/bcadd.xml
- reference/bc/functions/bcceil.xml
- reference/bc/functions/bccomp.xml
- reference/bc/functions/bcdiv.xml
- reference/bc/functions/bcdivmod.xml
- reference/bc/functions/bcfloor.xml
- reference/bc/functions/bcmod.xml
- reference/bc/functions/bcmul.xml
- reference/bc/functions/bcpow.xml
- reference/bc/functions/bcpowmod.xml
- reference/bc/functions/bcround.xml
- reference/bc/functions/bcscale.xml
- reference/bc/functions/bcsqrt.xml
- reference/bc/functions/bcsub.xml
Fixed and added exception behavior.
Also added a `<literal>` tag.
> ext/bcmath: Correctly modified an existing document

- reference/sockets/constants.xml
> [PHP 8.4] socket update

- reference/var/functions/is-callable.xml
If by "callable object" means an object in whose class the magic method `__invoke` was implemented, maybe we should replace the word `callable` with the word `invokeable' and add a link to the magic method?
> is-callable.xml Add a link to the `__invoke` magic method

- install/pecl.xml
Hopefully this fixes the weird empty line in https://www.php.net/manual/en/install.pecl.pear.php
> Use CDATA tags for content of screen tags

- reference/reflection/book.xml
- reference/reflection/reflectionconstant.xml
- reference/reflection/reflectionconstant/construct.xml
- reference/reflection/reflectionconstant/getextension.xml
- reference/reflection/reflectionconstant/getextensionname.xml
- reference/reflection/reflectionconstant/getfilename.xml
- reference/reflection/reflectionconstant/getname.xml
- reference/reflection/reflectionconstant/getnamespacename.xml
- reference/reflection/reflectionconstant/getshortname.xml
- reference/reflection/reflectionconstant/getvalue.xml
- reference/reflection/reflectionconstant/isdeprecated.xml
- reference/reflection/reflectionconstant/tostring.xml
- reference/reflection/versions.xml
@iluuu1994 if you could fill in the docs
> W.I.P: PHP 8.4: Add ReflectionConstant stubs

- appendices/ini.core.xml
> [PHP 8.3] Parent dir with `open_basedir` and `ini_set` at runtime

- reference/calendar/functions/easter-date.xml
Explicitly specify "local midnight" to avoid confusion. Unix timestamps represent seconds since 1970-01-01 00:00:00 UTC, and without this clarification, users might assume the timestamp corresponds to UTC midnight. In fact, the timestamp (UTC) corresponds to 00:00:00 when converted to the local timezone.
> Clarify that it represents midnight in the local timezone, not UTC.

- reference/ffi/ffi/load.xml
> [PHP 8.3] `FFI::load` in preload scripts

- reference/datetime/dateperiod.xml
- reference/datetime/datetime.xml
- reference/datetime/datetimeimmutable.xml
- reference/datetime/datetimeinterface.xml
- reference/datetime/datetimezone.xml
> [PHP 8.4] Add `ext-date` constant types

- reference/intl/collator-constants.xml
- reference/intl/collator.xml
- reference/intl/dateformatter-constants.xml
- reference/intl/dateformatter.xml
- reference/intl/intlbreakiterator.xml
- reference/intl/intlcalendar.xml
- reference/intl/intlchar.xml
- reference/intl/intlpartsiterator.xml
- reference/intl/intltimezone.xml
- reference/intl/locale-constants.xml
- reference/intl/locale.xml
- reference/intl/normalizer-constants.xml
- reference/intl/normalizer.xml
- reference/intl/numberformatter-constants.xml
- reference/intl/numberformatter.xml
- reference/intl/spoofchecker.xml
- reference/intl/transliterator.xml
- reference/intl/uconverter.xml
> [PHP 8.4] Add `ext-intl` constant types

- reference/opcache/functions/opcache-get-status.xml
After #4231 and #4235, this closes #2796 🎉
> [PHP 8.3] Add `opcache_get_status()` example and changelog

- reference/password/functions/password-hash.xml
> [PHP 8.3] `ValueError`'s previous exception is now set in `password_hash()`

- reference/pdo/pdo.xml
Part of #3872. Class constants are already typed elsewhere for this extension.
> [PHP 8.4] Mention class constant types in `PDO` changelog

- reference/pdo_mysql/pdo/mysql/getwarningcount.xml
The property is not a link and mysqli links in PDO are irrelevant anyway.
> Remove see also from getWarningCount()

- reference/mbstring/functions/mb-decode-numericentity.xml
- reference/mbstring/functions/mb-encode-numericentity.xml
- reference/mbstring/functions/mb-http-input.xml
- reference/mbstring/functions/mb-http-output.xml
> [PHP 8.4] Update `ext-mbstring`

- reference/opcache/ini.xml
> [PHP 8.3] `opcache.preload_user` is not required when run as root

- reference/apcu/ini.xml
This updates the documentation for `apc.gc_ttl` to reflect its current behavior in APCu. The existing description appears outdated, maybe written for the older APC extension when it also handled opcode caching.
Current implementation is https://github.com/krakjoe/apcu/blob/635899cfe32496323d03e051e15be220f8b53d68/apc_cache.c#L191
> APCu: update apc.gc_ttl description

- reference/var/functions/unserialize.xml
> [PHP 8.4] `unserialize()` can throw a `ValueError` and `TypeError`

- reference/math/functions/round.xml
> [PHP 8.4] `round()` can throw a `ValueError`

- reference/simplexml/versions.xml
Prior to PHP 8, these were actually living in SimpleXMLIterator, but since then they live in SimpleXMLElement. The version file never changed the SimpleXMLIterator entries to SimpleXMLElement. We change the names here and because they are only available since PHP 8 on SimpleXMLElement also change the version data.
> Fix missing version information for SimpleXML iterator methods

- reference/misc/functions/pack.xml
Removed wrong caution From https://www.php.net/manual/en/function.pack.php
Fixes #4266
> Fix inaccurate caution note on pack()

- reference/pdo_mysql/constants.xml
- reference/pdo_mysql/pdo-mysql.xml
Found while reviewing doc-fr PRs
> The constant classes cannot be available before the introduction of the class

- reference/filesystem/functions/fputcsv.xml
This commit resolves a deprecation warning in PHP 8.4 regarding the $escape parameter of the fputcsv function. The warning indicates that the default value for $escape will change in future PHP versions, requiring it to be explicitly provided.
* Changes Made
Updated the fputcsv calls to include the $escape parameter explicitly with a backslash ('\\') as the value.
* Benefits
Ensures compatibility with PHP 8.4.
Prevents potential future errors caused by the deprecation of the default $escape parameter value.
This update makes the script more robust and ready for future PHP versions.
> Fix: Add explicit $escape parameter in fputcsv for PHP 8.4 compatibility

- reference/uodbc/functions/odbc-fetch-row.xml
> [PHP 8.4] `odbc_fetch_row()` can emit a `E_WARNING`

- language/oop5/lazy-objects.xml
When running "Example 3 Initializing Properties Eagerly" result in https://www.php.net/manual/en/language.oop5.lazy-objects.php, an error occurs :
```
Fatal error: Uncaught Error: Cannot access private property BlogPost::$id
```
Changing visibility to public on id property for class BlogPost, example 3 resolves this error. All properties for this class example are set to public for preserve visibility homogeneity.
> Change and fix property visibility in lazy-objects example 3

- reference/yaf/yaf_route_map/construct.xml
- reference/yaf/yaf_route_regex/construct.xml
- reference/yaf/yaf_route_rewrite/construct.xml
- reference/yaf/yaf_route_supervar/construct.xml
- reference/yaf/yaf_view_simple/construct.xml
Replace `function` tags from example titles where the class name is being referenced.
Fixes constructor method name `__construct`.
Fixes typo.
> Remove function tags from titles in Yaf examples

- language/predefined/countable/count.xml
Return type of Counter::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> count.xml Amend the code example and add return type

- reference/pdo_pgsql/pdo/pgsql/lobopen.xml
There was no errors section in `PDO::pgsqlLOBOpen` document.
https://github.com/php/doc-en/blob/b95d28e6ec86e4a71e012737d36ebdc1cf009180/reference/pdo_pgsql/PDO/pgsqlLOBOpen.xml
> `Pdo\Pgsql::lobOpen`: Remove errors section from skeleton

- language/oop5/property-hooks.xml
Per a conversation with @crell, added a note to detail behavior of hooks
when the set hook allows more types than the property, and is used with
constructor property promotion.
> Adds a note about hooks + constructor property promotion

- bookinfo.xml
The license is clear on its own, there's not really anyone who can give permission to do anything else.
Fixes #4130.
> Remove paragraph about contacting doc-license@ about licensing

- reference/openssl/constants.xml
- reference/openssl/functions/openssl-pkey-get-details.xml
- reference/openssl/functions/openssl-pkey-new.xml
This significantly extend docs for openssl_pkey_new and adds 8.4 changes for Curve25519 + Curve448
> Document pkey gen params and addition of Curve25519 + Curve448

- language/types/string.xml
The `\f` within double quotes actually represents a form feed, so `"outputs: C:\folder\{fantastic}.txt"` is incorrect. Representing a form feed in a comment can be a bit tricky, and since it is not the focus of the example, I have changed `folder` in the strings to `directory`.
> Fix incorrect description of output

- reference/pdo/drivers.xml
- reference/pdo_dblib/reference.xml
- reference/pdo_firebird/reference.xml
- reference/pdo_mysql/reference.xml
- reference/pdo_odbc/reference.xml
- reference/pdo_pgsql/reference.xml
- reference/pdo_sqlite/reference.xml
While creating a new tool for detecting problematic XML files (from libxml perspective), I got reports of two invalid XML files in wkhtmltox, that are really XML fragment files, and various files in PDO hierarchy.
The "error" was about "Extra content at the end of the document", caused by entities used outside elements. To avoid losing that test, this PR changes the position of these entities of <reference>`s at sibling positions of other <reference>`s, maintaining the structure of XML, and to better reflect how the manual is rendered at the end.
But... are these files intended to be positioned in sibling positions? It is rendered nowadays as:
It's is possible to have `<reference>`s inside `<reference>`s, so an alternative is to move these class documentation *inside* their defining PDO …
> Move some PDO file  entities at sibling positions, wkhtmltox fragment dir

- reference/reflection/reflectionproperty/isdynamic.xml
> Add `ReflectionProperty::isDynamic()`

- reference/openssl/functions/openssl-csr-new.xml
This clarifies `distinguished_names` and `extra_attributes` params as well.
> Document 8.4 changes in openssl_csr_new

- install/fpm/configuration.xml
This improves event.mechanism docs and fixes poll type (it was documented as pool).
The idea was to also document removal of `/dev/poll` but it was not documented and considering that it's just for unsupported Solaris platform and likely no one was using for ages, there is not much point to mention its removal in 8.4.
> Fix FPM event mechanism poll typo and improve it

- reference/pcre/pattern.modifiers.xml
This section compares cases where the `r` flag is not used and where it is used. While the `u` flag is also in effect, it seems likely that "u" is a mistake and should be "r".
> Fix typo in pattern.modifiers.xml

- appendices/ini.core.xml
- reference/mysqli/ini.xml
Prompted by feedback on PR to clean up formatting of php.ini in php/php-src#17282
> Clarify type of a few INI values

- reference/pdo_cubrid/reference.xml
- reference/pdo_dblib/reference.xml
- reference/pdo_firebird/reference.xml
- reference/pdo_ibm/reference.xml
- reference/pdo_informix/reference.xml
- reference/pdo_mysql/reference.xml
- reference/pdo_oci/reference.xml
- reference/pdo_odbc/reference.xml
- reference/pdo_pgsql/reference.xml
- reference/pdo_sqlite/reference.xml
- reference/pdo_sqlsrv/reference.xml
Rename PDO driver titleabrevs to something less crypt, as indicated on https://github.com/php/doc-en/pull/4330 .
The other line changes are trailing spaces, that does not shows on online diffs.
> Rename PDO driver titleabrevs

- reference/pdo/constants.xml
- reference/pdo/pdo/setattribute.xml
1. Standardizes definition in both `constants` and `setattribute` pages. I'm not sure this duplication is ideal, but that is how the PDO documentation is currently structured.
2. Update text to reflect that it's not the numeric values that get converted, it's all non-null values. (E.g. boolean values get converted too.). I imagine the behavior could theoretically be different depending on the PDO driver, and that the behavior may have been different in the past too, but that seems to be the case nowadays in all core drivers, and so I think it's useful to state it.
3. Specify the default. Again, this may be driver-specific (an extension may override it), but at least that seems to be the case in all existing supported drivers.
4. Mention `ATTR_ORACLE_NULLS`. As a developer, it can be …
> PDO: improve PDO::ATTR_STRINGIFY_FETCHES description

- reference/info/functions/ini-get.xml
- reference/info/functions/ini-parse-quantity.xml
- Use ini_parse_quantity instead of custom code for ini value parsing.
- Replace register_globals ini value with something more current, as register_globals was removed in, I think, PHP 5.4.
- Change the wording for the ini_parse_quantity example to not contain “similar to” as it's deterministic output.
Resolves php/doc-en#4185
> ini_get: Update example to use `ini_parse_quantity()`

- appendices/ini.list.xml
- reference/mail/ini.xml
Documentation does not match: https://github.com/php/doc-en/blob/3cdd39bb9505e6735d802da83a04870cfa8f2311/appendices/ini.list.xml
This param cannot be set through PHP_INI_PERDIR because of https://bugs.php.net/bug.php?id=71901
> Cannot set mail.force_extra_parameters as PHP_INI_PERDIR

- language/oop5/property-hooks.xml
Fixes #4336
Copy-pasta error on my part when cloning the RFC to the docs page.  This should resolve it.
> Fix hooks example

- reference/pdo/constants.xml
- reference/pdo/pdostatement/fetch.xml
I'm not sure if this behavior is intentional, but it's something I rely on.
> PDO(FETCH_CLASS): private and read-only properties are populated too

- language/types.xml
- language/types/declarations.xml
- language/types/singleton.xml
- language/types/type-system.xml
- language/types/unit.xml
Fixes #4077
https://en.wikipedia.org/wiki/Unit_type
> Use "singleton type" instead of "value type"

- .docker/Dockerfile
Java is used to run jing, to explain schema violations, [here](https://github.com/php/doc-base/blob/643f7dd80707bef61fa661ca6247d344fc46f4bc/configure.php#L1105).
> Install java in the docker image

- appendices/ini.list.xml
- appendices/migration82/other-changes.xml
- appendices/migration83/other-changes.xml
- reference/info/ini.xml
Document `zend.max_allowed_stack_size`, `zend.reserved_stack_size`, and `fiber.stack_size`.
This includes https://github.com/php/doc-en/pull/4385.
> Document zend.max_allowed_stack_size and related parameters

- reference/var/functions/unserialize.xml
Fix `unserialize()` manual: modify XML tags for union type to make each type name hyperlink.
https://www.php.net/manual/en/function.unserialize.php
`<type>array|bool</type>` is recognized as single type of `array|bool`, which is not defined. `<type class="union">` tag is appropriate for union types.
> unserialize(): fix XML tags for union type

- reference/var/functions/empty.xml
Relates to issue: https://github.com/php/doc-en/issues/4390
This PR addresses issues with the "empty()" documentation.
1- one of the "String Offsets" examples contains an invalid example with deprecated syntax
2- add examples for multidimensional arrays
> remove deprecated example, add multidimensional arrays examples

- reference/spl/arrayobject/construct.xml
Related with https://github.com/php/doc-en/pull/4416
> ArrayObject::__construct: clarify subtyping of `iteratorClass` parameter

- reference/pgsql/functions/pg-pconnect.xml
Also, added some literal tags, fixed minor white spacing issues and improved case and position of code comments
> pg-pconnect: fix typos

- reference/pcntl/functions/pcntl-waitpid.xml
[Issue php doc fr](https://github.com/php/doc-fr/pull/2031#issuecomment-2631090273)
This pull request includes a small change to the `reference/pcntl/functions/pcntl-waitpid.xml` file. The change updates the documentation to correctly reference the `pcntl_wait` function instead of the generic `wait` function.
* [`reference/pcntl/functions/pcntl-waitpid.xml`](diffhunk://#diff-dbd5da28d4f8fd870fca632443c4669cbb6be67f68313e8ad43b88bd866775e1L57-R57): Updated the documentation to specify that the behavior is the same as the `pcntl_wait` function.
> fix function wording pcntl

- reference/funchand/functions/register-tick-function.xml
The example for [register_tick_function()](https://www.php.net/manual/en/function.register-tick-function.php) is incomplete. It is missing the definitions for the callback function my_function and the class method my_method.
Additionally, due to the missing definitions, the "Sandbox Example" code provided on the PHP documentation page cannot be run directly, making it difficult for users to test or understand the functionality.
> Missing function and method definitions in Example #1 for register_tick_function()

- reference/image/functions/getimagesize.xml
See <https://github.com/php/php-src/issues/17707>.
> getimagesize() is agnostic of image metadata

- reference/mysqli/mysqli/construct.xml
In https://github.com/php/doc-en/commit/390278d79b453af8f2f0837596c4cd25882b951a, lines 126-129 were incorrectly removed - `__construct` will still return an object in all circumstances.
> Re-add mysqli::__construct return value description

- language/exceptions.xml
Adjusted the last example to prevent an 'undefined function' error and added output screens for the last two exception examples.
> Add output screens for last two exception examples

- reference/classobj/functions/is-a.xml
While browsing the docs, I tried to "run [the] code" examples of [`is_a`](https://www.php.net/manual/en/function.is-a.php).
The firs worked but the second failed with `Warning: Undefined variable $WF in php-wasm run script on line 2` due to missing setup code.
If the "run code" functionality should actually be usable, code examples must be self-containing.
> Copy setup code into second example to enable "run code"

- reference/sockets/functions/socket-write.xml
The note was not parseable for me, and the use of "buffer" for both the network buffers and the input data (in the same sentence) made it too confusing for me to interpret initially.
> Clarify socket_write()

- features/dtrace.xml
From PHP 7.0.14,  `USE_ZEND_DTRACE=1` must be set to target PHP processes to enable DTrace actually.
https://github.com/php/php-src/commit/0c78fe4bb55a9d39afc79cbcbadb9a273f2ec2ef
Though this requirement is not explained explicitly in the manual, so this PR adds the step.
I personally discovered this when I tried to trace USDT probe points using eBPF.
I hope this could help someone who want to use this feature.
> Add one necessary step to enable DTrace

- language/control-structures/foreach.xml
The goal of this rework is to, hopefully, bring the `foreach` docs up to current practices and widely used syntax
https://www.php.net/manual/en/control-structures.foreach.php
The main motivation for this was that the *first* example on the current page is the following: 
```
<?php
$arr = array(1, 2, 3, 4);
foreach ($arr as &$value) {
$value = $value * 2;
}
```
Given that this uses a reference and classic array syntax, I felt we can showcase `foreach` better.
The focused on the following aspects:
- Use short array syntax everywhere
- Easier to visually parse pseudocode example 
- Prefer names to abbreviations `[$a => $array, $k => $key, $v => $value]` for readability
- Implicitly prefer `array destructuring []` over `list()` by mentioning it first in the examples, as it's the more commonly …
> Modernize `foreach` docs

- reference/reflection/book.xml
- reference/reflection/propertyhooktype.xml
- reference/reflection/reflectionproperty/gethook.xml
- reference/reflection/reflectionproperty/gethooks.xml
- reference/reflection/reflectionproperty/getrawvalue.xml
- reference/reflection/reflectionproperty/getsettabletype.xml
- reference/reflection/reflectionproperty/hashook.xml
- reference/reflection/reflectionproperty/hashooks.xml
- reference/reflection/reflectionproperty/isabstract.xml
- reference/reflection/reflectionproperty/isfinal.xml
- reference/reflection/reflectionproperty/isprivateset.xml
- reference/reflection/reflectionproperty/isprotectedset.xml
- reference/reflection/reflectionproperty/ispublic.xml
- reference/reflection/reflectionproperty/isvirtual.xml
- reference/reflection/reflectionproperty/setrawvalue.xml
- reference/reflection/versions.xml
New PR, includes #4039, which generates the stubs.
Resolves #4039.
I'm not certain if the enum is in the right place, but I wasn't sure where else to put it.  Open to suggestions.
> Hooks reflection

- language/predefined/iteratoraggregate/getiterator.xml
the return type is not always a iterator, therefore use less wording which implies it would
triggered by https://github.com/phpstan/phpstan/issues/12619#issuecomment-2670970120
> More precise IteratorAggregate::getIterator() description

- appendices/resources.xml
Fix #4471
```html
<col width="1*"/>
<col style="width: 1.4*;"/>
```
Firefox renders the style. But it's an invalid property value in Chrome.
https://github.com/php/phd/blob/3c00a1a7539b660a5d792d4306d4c5a355676eea/phpdotnet/phd/Package/Generic/XHTML.php#L2054-L2063
> Adjust column width in resources.xml for improved layout

- reference/rpminfo/book.xml
- reference/rpminfo/constants.xml
- reference/rpminfo/functions/rpmaddtag.xml
- reference/rpminfo/functions/rpmdbinfo.xml
- reference/rpminfo/functions/rpmdbsearch.xml
- reference/rpminfo/functions/rpmdefine.xml
- reference/rpminfo/functions/rpmexpand.xml
- reference/rpminfo/functions/rpmexpandnumeric.xml
- reference/rpminfo/functions/rpmgetsymlink.xml
- reference/rpminfo/functions/rpminfo.xml
- reference/rpminfo/functions/rpmvercmp.xml
- reference/rpminfo/reference.xml
- reference/rpminfo/setup.xml
Use more appropriate DocBook tags, add constant tags which will handle automatic linking, use entities and literal tags, fix indentation, group related constants together.
> Modernize RPM docs

- reference/dom/domxpath/registerphpfunctionns.xml
- reference/dom/versions.xml
- reference/xsl/versions.xml
- reference/xsl/xsltprocessor/registerphpfunctionns.xml
Hopefully this PR is correct.
I was not able to build the docs locally.
```log
frederik@frederik-laptop:/srv/libraries/php-doc-en$ make
docker run --rm -v .:/var/www/en -w /var/www -u 1000:1000 php/doc-en
configure.php: $Id$
PHP version: 8.2.26
Checking for source directory... 
error: Source directory doesn't exist or can't be written to.
make: *** [Makefile:22: xhtml] Error 1
```
> add XSLTProcessor::registerPHPFunctionNS and DOMXPath::registerPhpFunctionNS

- reference/reflection/reflectionproperty/gethook.xml
- reference/reflection/reflectionproperty/gethooks.xml
- reference/reflection/reflectionproperty/getrawvalue.xml
- reference/reflection/reflectionproperty/getsettabletype.xml
- reference/reflection/reflectionproperty/hashook.xml
- reference/reflection/reflectionproperty/hashooks.xml
- reference/reflection/reflectionproperty/isfinal.xml
- reference/reflection/reflectionproperty/isvirtual.xml
- reference/reflection/reflectionproperty/setrawvalue.xml
I have added output for the examples added in #4110. I had to tweak the examples a bit for output readability
> Hooks reflection examples output

- .github/workflows/integrate.yaml
This pull request includes updates to the build environment and the PHP version used for building documentation in the GitHub Actions workflow.
Issue:  [https://github.com/actions/runner-images/issues/11101](https://github.com/actions/runner-images/issues/11101)
Improvements to the build environment:
* [`.github/workflows/integrate.yaml`](diffhunk://#diff-d684acc09c646fd347d0ee93598101fb403664cc70e38cb6f671355ab6de1854L18-R18): Updated the runner to use `ubuntu-22.04` instead of `ubuntu-20.04`.
Updates to PHP version:
* [`.github/workflows/integrate.yaml`](diffhunk://#diff-d684acc09c646fd347d0ee93598101fb403664cc70e38cb6f671355ab6de1854L51-R51): Changed the PHP version from `php8.0` to `php8.1` for the documentation build step.
> update workflow integrate yaml ubuntu

- reference/reflection/propertyhooktype.xml
Close #4485
I'm not sure there's any special significance to adding `\` before it. cc @Crell
> Fix missing PropertyHookType link

- reference/password/functions/password-hash.xml
- reference/password/functions/password-needs-rehash.xml
- reference/password/functions/password-verify.xml
This updates the `password_hash()` documentation for the updated default cost of bcrypt in PHP 8.4. It also performs some general cleanup.
> password_hash: Update for PHP 8.4

- reference/password/functions/password-verify.xml
This was already removed from `password_hash()` in abc0c909d5a642fbc9008c5ed1a4c3ead5ecb9a2. Given that `password_hash()` is built-in since PHP 5.5, we no longer need this in the manual.
> password_verify: Remove reference to userland implementation

- language/control-structures/foreach.xml
Ensure each /* Example: */ block is directly on top of the code it's describing, instead of sometimes hovering between code blocks.
I missed this inconsistency in https://github.com/php/doc-en/pull/4451
> Align whitespace for examples on foreach

- reference/curl/book.xml
- reference/curl/curlsharepersistenthandle.xml
- reference/curl/functions/curl-share-init-persistent.xml
- reference/curl/functions/curl-share-init.xml
- reference/curl/versions.xml
This PR adds documentation for `curl_share_init_persistent` and its respective `CurlSharePersistentHandle` class.
RFC: https://wiki.php.net/rfc/curl_share_persistence_improvement.
I wrote the documentation by running `build/gen_stub.php` and also copying bits from other `curl` documentation pages. Since this is my first time contributing to the PHP documentation, I expect I may have made some mistakes or missed some common patterns that are usually followed.
> `ext/curl`: add `curl_share_init_persistent`

- language-snippets.ent
- reference/mongodb/mongodb/driver/bulkwrite/update.xml
- reference/mongodb/mongodb/driver/clientencryption/createdatakey.xml
- reference/mongodb/mongodb/driver/clientencryption/rewrapmanydatakey.xml
- reference/mongodb/mongodb/driver/manager/executebulkwrite.xml
- reference/mongodb/mongodb/driver/manager/executecommand.xml
- reference/mongodb/mongodb/driver/manager/executequery.xml
- reference/mongodb/mongodb/driver/server/executebulkwrite.xml
- reference/mongodb/mongodb/driver/server/executecommand.xml
- reference/mongodb/mongodb/driver/server/executequery.xml
https://jira.mongodb.org/browse/PHPLIB-1375 (missed for 1.20)
https://jira.mongodb.org/browse/PHPC-2518
https://jira.mongodb.org/browse/PHPC-2489
> Documentation updates for ext-mongodb 1.21

- appendices/migration71/new-features.xml
Old example would actually have output:
Fatal error: Cannot redeclare testReturn()
We can also see that the output was not from real code execution because "elePHPant" should be string(9) not string(10).
> Fixed Nullable types example in migration71/new-features.xml

- reference/classobj/functions/method-exists.xml
Incorporate the top two comments as part of the documentation. It copies a similar note from `property_exists` around support for `__get`.
> method_exists: Add changelog and note regarding not supporting `__call`.

- reference/password/functions/password-hash.xml
see https://github.com/php/doc-en/pull/4455#discussion_r1963655830
> password_hash: Remove personalization

- reference/pcntl/examples.xml
- reference/pcntl/functions/pcntl-signal.xml
This merges several user notes into the current documentation.
> pcntl_signal: Switch to pcntl_async_signals and improve documentation

- reference/info/functions/assert.xml
The implication of only being used as a debugging tool is that it should never hit production code. This is contradicted by the line above ("but are optimised away to have zero cost in production") above and the paragraph following it which requires asserts to exist in running code to make sense.
As mentioned in a comment on the php.net page (https://www.php.net/manual/en/function.assert.php#129271), `assert` sees widespread usage in code in the wild. It definitely is used outside of debugging.
Instead of removing it, this changes the line to mention its relation to debugging which is relevant and otherwise absent from the article.
> Change line mentioning assert should only be used when debugging

- reference/reflection/propertyhooktype.xml
Other than `<reference xmlns="http://docbook.org/ns/docbook" xml:id="enum.propertyhooktype" role="enum">`, they are not required, but I modified it for consistency.
> ext/reflection: `PropertyHookType` - Fixed id for enum autolinking

- reference/var/functions/intval.xml
This is to emphasize intval truncates the value to 4, and there's another function for rounding
> intval: changed example from 4.2 to 4.7

- reference/reflection/reflectionparameter/getattributes.xml
- Fix calls to non-existent `getParameter` method of `ReflectionFunction`.
- Add missing `Red` attribute class definition implementing `Color`.
---
[Current page](https://www.php.net/manual/en/reflectionparameter.getattributes.php) in question.
Although I like the idea of being able to filter/get a specific function parameter by name, as far as I can tell, there is no such method on [`ReflectionFunctionAbstract`](https://www.php.net/manual/en/class.reflectionfunctionabstract.php) or its subclasses.
Also, the entire point of the [third example](https://www.php.net/manual/en/reflectionparameter.getattributes.php#example-5485) presumably was to illustrate that sub-type relationships are honored by passing the `IS_INSTANCEOF` flag to `getAttributes`. Therefore including the `Red` class in …
> Fix buggy code examples for `ReflectionParameter::getAttributes`

- reference/mongodb/mongodb/driver/bulkwrite.xml
- reference/mongodb/mongodb/driver/bulkwrite/construct.xml
- reference/mongodb/mongodb/driver/manager/executebulkwrite.xml
- reference/mongodb/mongodb/driver/query/construct.xml
- reference/mongodb/mongodb/driver/writeconcernerror/getcode.xml
- reference/mongodb/mongodb/driver/writeconcernerror/getinfo.xml
- reference/mongodb/mongodb/driver/writeconcernerror/getmessage.xml
- reference/mongodb/mongodb/driver/writeresult/getwriteconcernerror.xml
- reference/mongodb/mongodb/driver/writeresult/isacknowledged.xml
This was missed in 51ea49d0a56569458483a36478f6e5571a59bdc8
https://jira.mongodb.org/browse/PHPC-2489
> Update examples to pass WriteConcern and ReadPreference as options

- reference/mongodb/mongodb/driver/writeresult/getmodifiedcount.xml
Support for MongoDB 2.6 was dropped in ext-mongodb 1.5.0
https://jira.mongodb.org/browse/PHPC-1662
> Remove note about MongoDB 2.6 in getModifiedCount()

- contributors.xml
I just couldn't believe that @haszi removed people with the biggest contributions in fde7fc4. Only two of them were added in 169faf3.
> Add back authors previously featured on the frontpage

- reference/sqlsrv/constants.xml
No such constant at https://github.com/microsoft/msphpsql/blob/master/source/sqlsrv/init.cpp or in runtime.
> sqlsrv: Delete invalid constant

- language/oop5/constants.xml
PHP 8.3 introduced types to class constants, but the documentation doesn't seem to mention this yet. This PR updates the doc to mention it & provide an example.
> Add information about type declarations to Class Constants

- reference/random/random.intervalboundary.xml
This was correct in my initial suggestions (https://github.com/php/doc-en/pull/3419#discussion_r1617712920), but incorrect in my later suggestions (https://github.com/php/doc-en/pull/3419#discussion_r1845547942) 😔 
---------------
see #3419
> random: Fix right-open / left-open confusion for Random\IntervalBoundary

- reference/errorfunc/functions/get-error-handler.xml
- reference/errorfunc/functions/get-exception-handler.xml
- reference/errorfunc/functions/restore-exception-handler.xml
- reference/errorfunc/functions/set-error-handler.xml
- reference/errorfunc/functions/set-exception-handler.xml
- reference/errorfunc/versions.xml
RFC: https://wiki.php.net/rfc/get-error-exception-handler
> Document get_error_handler(), get_exception_handler()

- language/exceptions.xml
PHP 8.4 deprecates inferred nullable parameters. Many people copy this code directly into their codebase so it's good to make sure it won't break anything soon.
> Use explicit nullable type in language/exceptions.xml

- reference/datetime/datetimeinterface/serialize.xml
- reference/datetime/datetimeinterface/unserialize.xml
- reference/datetime/versions.xml
Add
- DateTime::__serialize()
- DateTime::__unserialize()
- DateTimeInterface::__serialize()
- DateTimeInterface::__unserialize()
- DateTimeImmutable::__serialize()
- DateTimeImmutable::__unserialize()
Adding these methods helps #2163.
> Add DateTime related serialize/unserialize methods

- reference/mysqlnd/stats.xml
There is no `buffered_from_server` statistic.
> Fix name of `rows_buffered_from_client_ps` MySQLnd statistic

- reference/intl/dateformatter/localtime.xml
Date/time format adjusted to match the specified one in the first line.
Last parameter is a reference.
> IntlDateFormatter::localtime: Fix example

- language/predefined/variables/phperrormsg.xml
See php/php-src@920b4b249f71e6cbfd795f81c6a08126a33c659e
Use `&warn.deprecated.feature-7-2-0.removed-8-0-0;` instead of `&warn.deprecated.feature-7-2-0;`
> $php_errormsg was removed in PHP 8.0

- reference/strings/functions/parse-str.xml
Most of the text still acted as though "create a bunch of local variables" was the normal behaviour, even though it's been discouraged for years, and isn't even supported in PHP 8.
There were also a few incorrect or questionable uses of markup.
> Modernise parse_str description

- reference/random/functions/rand.xml
Since PHP 7.1 `getrandmax` is an alias of `mt_getrandmax`, which returns 2**31 - 1
> random: clarify that `getrandmax` was small only before PHP 7.1

- reference/mongodb/bson/persistable/bsonserialize.xml
- reference/mongodb/bson/serializable/bsonserialize.xml
- reference/mongodb/bson/unserializable/bsonunserialize.xml
- reference/mongodb/mongodb/driver/exception/bulkwriteexception.xml
This adds changelog entries and methods that were missed when initially adding the 2.0 documentation.
> MongoDB: Fix docs errors for 2.0 version

- reference/hash/functions/hash-file.xml
`hash_file()` return type is `string|false`, but this does not appears in the returned values doc block.
> Add missing `false` return type in `hash_file` documentation

- appendices/tokens.xml
- language/control-structures/include.xml
- language/predefined/variables/server.xml
- reference/errorfunc/functions/debug-backtrace.xml
- reference/misc/functions/define.xml
Not sure what happened here, but found quite a few incorrect links for the magic constants page.
Fixed now.
> Fix links to magic constants page

- reference/bc/bcmath/number/round.xml
https://www.php.net/manual/en/bcmath-number.round.php
The current doc:
```php
<?php
$number = new BcMath\Number('123.45');
var_dump(
$number->round(3),
// ...
);
?>
```
```
object(BcMath\Number)#2 (2) {
["value"]=>
string(6) "123.45"
["scale"]=>
int(2)
}
...
```
the actual current behavior:
```
> new BcMath\Number('123.45')->round(3);
= BcMath\Number {#4083
+value: "123.450",
+scale: 3,
}
> new BcMath\Number('123.45')->round(10);
= BcMath\Number {#4094
+value: "123.4500000000",
+scale: 10,
}
```
since [bcround](https://www.php.net/manual/en/function.bcround.php) behaves this way too, I assume it's a documentation issue
> Incorrect result in BcMath\Number::round() example

- language/oop5/decon.xml
When we run example #5, we get:
```
Fatal error: Uncaught TypeError: Cannot assign SimpleXMLElement to property Product::$id of type ?int in script:28
Stack trace:
#0 script(36): Product::fromXml('<animal><id>100...')
#1 {main}
thrown in script on line 28
```
> Fix error in deconstructor example 5

- reference/filter/functions/filter-has-var.xml
This PR fixes a minor grammatical issue in the description of the `filter_has_var` function. Adding "a" and "the" makes the sentence grammatically complete and easier to understand.
> filter_has_var: Fix grammar

- language/control-structures/match.xml
Above in this text it states:
> match expression arms may contain multiple expressions separated by a comma. That is a logical OR, and is a short-hand for multiple match arms with the same right-hand side.
So in the code example below we prefer to use the comma instead of a logical OR.
> Prefer comma over || for match conditions

- reference/hash/functions/hash-equals.xml
As stated in the document, the user provided string is supposed to be the second parameter. Whereas before this pull request, the user provided string is the first parameter.
> Reverse hash_equals parameters

- reference/misc/functions/pack.xml
a and Z had the same definition, but Z is the NUL-terminated variation.
> Update the definition of the Z pack format code

- language/context/http.xml
- reference/filesystem/functions/file-get-contents.xml
- reference/libxml/functions/libxml-set-streams-context.xml
- reference/stream/functions/stream-context-create.xml
- reference/stream/functions/stream-context-get-default.xml
- reference/stream/functions/stream-context-set-default.xml
- reference/xmlrpc/functions/xmlrpc-encode-request.xml
compare Section 4.1 of RFC-2616 etc.
generic-message = start-line
*(message-header CRLF)
CRLF
[ message-body ]
RFC-2616: https://www.rfc-editor.org/rfc/rfc2616#section-4.1
ok: /reference/stream/functions/stream-context-set-default.xml etc.
> fix(reference/stream): HTTP Headers are U+0D U+0A (CRLF) separated

- language/exceptions.xml
This is already documented as [a user note][The note], but the note does not explain what happens if both exceptions already have a previous exception.
Here is what I believe is the related piece of code:
```c
/* Chain potential exception from wrapping finally block */
if (Z_OBJ_P(fast_call)) {
if (ex) {
if (zend_is_unwind_exit(ex) || zend_is_graceful_exit(ex)) {
/* discard the previously thrown exception */
OBJ_RELEASE(Z_OBJ_P(fast_call));
} else {
zend_exception_set_previous(ex, Z_OBJ_P(fast_call));
}
} else {
ex = EG(exception) = Z_OBJ_P(fast_call);
}
}
```
[The note]: https://www.php.net/manual/en/language.exceptions.php#129177
> Document exception chaining

- reference/pcntl/book.xml
- reference/pcntl/pcntl.qosclass.xml
> Fix Pcntl\QosClass enum symbol names

- reference/mongodb/mongodb/driver/manager/construct.xml
Fix the `$driverOptions` parameter table this page to prevent unreadable nested array: https://www.php.net/manual/en/mongodb-driver-manager.construct.php#mongodb-driver-manager.construct-driveroptions
This page is not modified: https://www.php.net/manual/en/mongodb-driver-manager.createclientencryption.php
Question: I would like to optimize the column width to give more space to the description.
https://jira.mongodb.org/browse/PHPC-2573
> Extract `autoEncryption` driver options in `MongoDB\Driver\Manager::__construct()`

- reference/apcu/functions/apcu-entry.xml
> Rename parameter 'generator' to 'callback' in apcu_entry documentation

- reference/array/functions/extract.xml
> Remove wddx_deserialize from extract example

- language/types/array.xml
- reference/array/functions/list.xml
Update notes about the handling of missing keys and non-arrays during array destructuring to match the behavior seen on 3v4l.org, which doesn't issue a warning or notice in some cases where the documentation claims it does. Also update list() docs to provide the same information.
list():
* missing key: https://3v4l.org/bYBt6
* destructuring an integer: https://3v4l.org/7lNhK
* a boolean: https://3v4l.org/p5LDd
* a string: https://3v4l.org/KHSAH
* null: https://3v4l.org/lk1iu
array notation:
* missing key: https://3v4l.org/KCiTC
* destructuring an integer: https://3v4l.org/louVG
* a boolean: https://3v4l.org/SWL5L
* a string: https://3v4l.org/aK90L
* null: https://3v4l.org/Y8cOY
Fixes #3640.
> Fix type juggling notes for list() and array destructuring

- install/fpm/configuration.xml
> Add documentation for listen.setfib and access.suppress_path parameters

- language-snippets.ent
Apparently it hasn't been added yet, so here it is.
This should unblock #4892, #4893, and the many other deprecations to document for 8.5.
> Add entity for PHP 8.5 deprecations.

- reference/xml/functions/xml-parser-free.xml
- reference/xml/versions.xml
Not sure if anything else is really needed here.
> Mark xml_parser_free as deprecated.

- language/operators/functional.xml
> Typographic fixes for the new pipe docs
