language/oop5/final.xml
language/oop5/inheritance.xml

Note changes in how private methods inherit.

---

language/oop5/magic.xml
language/predefined/interfaces.xml
language/predefined/stringable.xml

I think that covers it, but please make sure I didn't miss a step...

Stringable

---

language/types/boolean.xml

There is no integer -0 (minus zero)

Fix list of falsy values

---

reference/mysqli/summary.xml

Remove mysqli::get_client_stats

---

reference/eio/functions/eio-init.xml

Added a note about removal of the eio_init function

---

reference/filter/constants.xml
reference/filter/filters.xml

The documentation was not updated with this change yet.

Add FILTER_SANITIZE_ADD_SLASHES

---

reference/mysqli/mysqli_stmt/store-result.xml

I have rewritten the description and provided a better title. I also simplified the example by removing all redundant stuff.

Updating mysqli: mysqli_stmt_store_result

---

reference/mysqli/mysqli_stmt/num-rows.xml

Improved the page to cause less confusion. I am unsure about the page title. I left it almost unchanged but maybe it should be changed too?

Updating mysqli: mysqli_stmt_num_rows

---

appendices/migration74/new-features.xml
language/constants.xml
reference/iconv/functions/iconv-mime-decode-headers.xml
reference/ldap/constants.xml
reference/math/functions/round.xml
reference/mbstring/functions/mb-detect-encoding.xml
reference/mongo/configure.xml
reference/mongodb/configure.xml
reference/sqlite3/sqlite3/setauthorizer.xml
reference/win32service/functions/win32-query-service-status.xml
reference/yaf/yaf_loader/registernamespace.xml

Inspired by #538 I grepped the repo for repeated words.

Remove repeated words

---

appendices/reserved.constants.core.xml
appendices/reserved.xml
appendices/transports.xml
faq/using.xml
features/commandline.xml
features/http-auth.xml
reference/curl/constants.xml
reference/curl/functions/curl-setopt.xml
reference/curl/ini.xml
reference/dom/domdocument/loadhtml.xml
reference/dom/domdocument/loadhtmlfile.xml
reference/dom/domdocument/schemavalidate.xml
reference/dom/domdocument/schemavalidatesource.xml
reference/dom/domdocument/xinclude.xml
reference/fileinfo/constants.xml
reference/filesystem/constants.xml
reference/gmp/book.xml
reference/intl/ini.xml
reference/outcontrol/constants.xml
reference/pcre/functions/preg-last-error.xml
reference/pdo/constants.xml
reference/pdo_firebird/constants.xml
reference/pdo_odbc/ini.xml
reference/readline/ini.xml
reference/session/functions/session-set-save-handler.xml
reference/simplexml/functions/simplexml-load-file.xml
reference/spl/functions/class-implements.xml
reference/spl/functions/class-parents.xml
reference/stream/constants.xml
reference/zip/constants.xml

Removed references to PHP 5, PHP 7.0

---

reference/pcre/functions/preg-match-all.xml
reference/pcre/functions/preg-match.xml
reference/pcre/functions/preg-replace.xml
reference/pcre/pattern.posix.xml
reference/pcre/pattern.syntax.xml
reference/pdo/book.xml
reference/pdo/configure.xml
reference/pdo/pdo/prepare.xml
reference/pdo_dblib/reference.xml
reference/pdo_mysql/configure.xml
reference/pdo_odbc/configure.xml
reference/pdo_sqlsrv/configure.xml

Removed references to PHP 5, 7.0

---

reference/mysqli/mysqli/affected-rows.xml

Similar to https://github.com/php/doc-en/pull/553

Updating mysqli: mysqli_affected_rows

---

reference/mysqli/mysqli_stmt/affected-rows.xml

Fixed incorrect information and synchronized the page with https://dev.mysql.com/doc/c-api/8.0/en/mysql-affected-rows.html

Updating mysqli: mysqli_stmt_affected_rows

---

reference/openssl/functions/openssl-pkcs7-read.xml

The input shall be a string data.

Improve the document of openssl-pkcs7-read

---

reference/exif/functions/exif-read-data.xml

Remove Windows XP note

---

reference/tokyo_tyrant/tokyotyrant/connect.xml
reference/tokyo_tyrant/tokyotyrant/connecturi.xml
reference/tokyo_tyrant/tokyotyrant/construct.xml
reference/tokyo_tyrant/tokyotyrant/copy.xml
reference/tokyo_tyrant/tokyotyrant/getiterator.xml
reference/tokyo_tyrant/tokyotyrant/out.xml
reference/tokyo_tyrant/tokyotyrant/put.xml
reference/tokyo_tyrant/tokyotyrant/putcat.xml
reference/tokyo_tyrant/tokyotyrant/putkeep.xml
reference/tokyo_tyrant/tokyotyrant/putnr.xml
reference/tokyo_tyrant/tokyotyrant/putshl.xml
reference/tokyo_tyrant/tokyotyrant/restore.xml
reference/tokyo_tyrant/tokyotyrant/setmaster.xml
reference/tokyo_tyrant/tokyotyrant/size.xml
reference/tokyo_tyrant/tokyotyrant/sync.xml
reference/tokyo_tyrant/tokyotyrant/tune.xml
reference/tokyo_tyrant/tokyotyrant/vanish.xml
reference/tokyo_tyrant/tokyotyrantquery/addcond.xml
reference/tokyo_tyrant/tokyotyrantquery/construct.xml
reference/tokyo_tyrant/tokyotyrantquery/count.xml
reference/tokyo_tyrant/tokyotyrantquery/key.xml
reference/tokyo_tyrant/tokyotyrantquery/metasearch.xml
reference/tokyo_tyrant/tokyotyrantquery/next.xml
reference/tokyo_tyrant/tokyotyrantquery/out.xml
reference/tokyo_tyrant/tokyotyrantquery/search.xml
reference/tokyo_tyrant/tokyotyrantquery/setlimit.xml
reference/tokyo_tyrant/tokyotyranttable/putnr.xml

Add reference to `TokyoTyrantException ` class

TokyoTyrantException reference

---

language/oop5/traits.xml

There are examples for Static Methods and Static Variables, so it is better to add Static Properties example also

Added Static Properties example for Traits

---

reference/mysqli/mysqli/close.xml

This page was missing its own example. I have also replaced the old shared note, with a better description. The link was not particularly useful.

Updating mysqli: mysqli_close

---

reference/filesystem/functions/fpassthru.xml

Related bug [81067](https://bugs.php.net/bug.php?id=81067).

fpassthru error description (bug 81067)

---

reference/datetime/dateinterval/construct.xml

DateInterval: weeks and days can be combined since 8.0.0

---

language/attributes.xml
reference/reflection/book.xml
reference/reflection/reflectionattribute.xml
reference/reflection/reflectionattribute/construct.xml
reference/reflection/reflectionattribute/getarguments.xml
reference/reflection/reflectionattribute/getname.xml
reference/reflection/reflectionattribute/gettarget.xml
reference/reflection/reflectionattribute/isrepeated.xml
reference/reflection/reflectionattribute/newinstance.xml
reference/reflection/reflectionclass/getattributes.xml
reference/reflection/reflectionclassconstant/getattributes.xml
reference/reflection/reflectionfunctionabstract/getattributes.xml
reference/reflection/reflectionparameter/getattributes.xml
reference/reflection/reflectionproperty/getattributes.xml
reference/reflection/versions.xml

Documented `ReflectionAttribute` based on RFC and implementation.
- https://wiki.php.net/rfc/attributes_v2
- https://github.com/php/php-src/blob/php-8.0.0/ext/reflection/php_reflection.stub.php
- https://github.com/php/php-src/blob/php-8.0.0/ext/reflection/php_reflection.c

Added ReflectionAttribute related Documentation.

---

reference/filesystem/functions/fopen.xml

make it consistent with x+, c+

shorten fopen w+ description

---

reference/strings/functions/localeconv.xml
reference/strings/functions/money-format.xml
reference/strings/functions/substr.xml
reference/svn/functions/svn-add.xml
reference/svn/functions/svn-auth-set-parameter.xml
reference/svn/functions/svn-cat.xml
reference/svn/functions/svn-checkout.xml
reference/svn/functions/svn-cleanup.xml
reference/svn/functions/svn-client-version.xml
reference/svn/functions/svn-commit.xml
reference/svn/functions/svn-diff.xml
reference/svn/functions/svn-import.xml
reference/svn/functions/svn-log.xml
reference/svn/functions/svn-ls.xml
reference/svn/functions/svn-status.xml
reference/svn/functions/svn-update.xml
reference/tidy/tidy/getrelease.xml
reference/tidy/tidynode/getparent.xml
reference/tidy/tidynode/haschildren.xml
reference/tidy/tidynode/hassiblings.xml
reference/tidy/tidynode/isasp.xml
reference/tidy/tidynode/iscomment.xml
reference/tidy/tidynode/ishtml.xml
reference/tidy/tidynode/isjste.xml
reference/tidy/tidynode/isphp.xml
reference/tidy/tidynode/istext.xml

Fixed section order issues, added parameters sections for:
- tidy
- svn
- strings
ref #658

Fix section order issues

---

reference/intl/functions/intl-get-error-code.xml
reference/intl/functions/intl-get-error-message.xml
reference/intl/intlchar/isxdigit.xml
reference/ldap/functions/ldap-mod-del-ext.xml
reference/ldap/functions/ldap-sort.xml
reference/libxml/functions/libxml-clear-errors.xml
reference/libxml/functions/libxml-get-errors.xml
reference/libxml/functions/libxml-get-last-error.xml

Fixed section order issues in #658 
- libxml
- ldap
- intl

Fix section order issues in some extensions

---

reference/array/functions/arsort.xml
reference/array/functions/asort.xml
reference/array/functions/krsort.xml
reference/array/functions/ksort.xml
reference/array/functions/rsort.xml
reference/array/functions/sort.xml

we have several sort functions, but it's not clear if they sort in ascending or descending order. I updated them accordingly.
ps. Do you prefer a more layman definition for them? e.g. `from lowest to highest` instead of `ascending order`.

Clarify the order of sort functions in their description

---

reference/sodium/functions/sodium-bin2hex.xml

Fix sodium_bin2hex description

---

reference/datetime/functions/localtime.xml
reference/datetime/functions/time.xml
reference/mcrypt/functions/mdecrypt-generic.xml

I'm not sure about the `localtime()` function changes 🤔

Fix issues in mcrypt and datetime directories

---

install/macos/bundled.xml
install/macos/index.xml

Apple [removed](https://developer.apple.com/forums/thread/681907) build-in PHP in macOS Monterey

Update installation guide for macOS Monterey

---

reference/memcached/memcached/setoption.xml

Not sure about moving the note to `parameters` 🤔

Fix issues in memcached directory

---

reference/phar/Phar/createDefaultStub.xml
reference/phar/PharFileInfo/compress.xml

`Phar::createDefaultStub` methodsynopsis  based on [stubs](https://github.com/php/php-src/blob/PHP-8.0.0/ext/phar/phar_object.stub.php#L154).

Fix issues in phar directory

---

appendices/resources.xml
language-snippets.ent
reference/gmp/book.xml
reference/gmp/functions/gmp-sign.xml
reference/gmp/functions/gmp-testbit.xml
reference/gmp/setup.xml

Remove obsolete resource information and fix `pg_metadata`

Remove obsolete resource information

---

reference/strings/functions/ucwords.xml

My apologies for my trigger happy merging in https://github.com/php/doc-en/pull/726.
This PR includes revisions as specified by @salathe.

Additional revisions to ucwords

---

reference/array/functions/array-walk-recursive.xml
reference/array/functions/array-walk.xml

After  #614 and #615 I realized, that the documentations uses different parameter names than the actual implementation for many functions. This is a huge problem with the [named arguments][1] from PHP8.
I have hacked together a script, that parses the parses the xml files of the documentation and compares the parameter names to the actual ones using reflection. This script is available in [this gist][2].
The following name differences were detected by the script for function under `reference/array`. As this table is **automatically generated**, some entries may be **wrong** or **missing** and all entries must be manually reviewed.
Function                                |Expected parameter name                 |Actual parameter name …

Fix parameter names for array functions

---

reference/phar/Phar/webPhar.xml

Capitalized a word at the beginning of a sentence on https://www.php.net/manual/en/phar.webphar

Capitalize word on webPhar page

---

reference/phar/Phar/webPhar.xml

Add missing period on webPhar page

---

reference/phar/Phar/webPhar.xml

Not sure if this is better. I pulled a basic description from the method summary for the synopsis and muted some of the emotion in the method summary.
Changes are related to #766 and #767.

Revise wording for synopsis and summary

---

language-snippets.ent
reference/mysqli/mysqli/multi-query.xml
reference/mysqli/mysqli/query.xml
reference/mysqli/mysqli/real-query.xml

Moved to snippet as it appears at least 3 times

Fix mysqli SQL injection warning

---

reference/pthreads/cond/broadcast.xml
reference/pthreads/cond/destroy.xml
reference/pthreads/cond/signal.xml
reference/pthreads/cond/wait.xml
reference/pthreads/mutex/destroy.xml
reference/pthreads/mutex/lock.xml
reference/pthreads/mutex/trylock.xml
reference/pthreads/mutex/unlock.xml
reference/pthreads/pool/resize.xml
reference/pthreads/pool/shutdown.xml
reference/pthreads/thread/isjoined.xml
reference/pthreads/thread/isstarted.xml
reference/pthreads/thread/join.xml
reference/pthreads/thread/kill.xml
reference/pthreads/thread/start.xml
reference/pthreads/threaded/extend.xml
reference/pthreads/threaded/merge.xml
reference/pthreads/threaded/notify.xml
reference/pthreads/threaded/notifyone.xml
reference/pthreads/threaded/unlock.xml
reference/pthreads/threaded/wait.xml
reference/pthreads/worker/isshutdown.xml
reference/pthreads/worker/isworking.xml
reference/pthreads/worker/shutdown.xml

Not sure about "indication of state" replacements 🤔

Fix pthreads return values

---

reference/dom/functions/dom-import-simplexml.xml

Changed the incorrect false for null.

---

reference/pdo/pdo/query.xml

When reading the page I noticed that the first sentence says it only executes the SQL, so I decided to add "prepares and " but then I noticed more inaccuracies.

Fix inaccurate information in pdo query

---

reference/pdo/pdo/query.xml

I'm not sure how it would be best to document this parameter. See both commits. I'd appreciate tips on how to make it clearer.

Add missing parameter to pdo query

---

reference/exec/functions/shell-exec.xml

Reviews from https://github.com/php/doc-en/pull/821
cc @cmb69 @salathe

Improve shell_exec text

---

reference/array/functions/array-map.xml

Also added some types to the examples along the way, because types.

Fold in comments to array_map()

---

reference/classobj/examples.xml

It's still a dumb example, but I didn't write it. Not sure many people even know about this page.

New examples for classes

---

reference/uopz/versions.xml

Cf. <https://github.com/krakjoe/uopz/issues/152#issuecomment-891582155>.
---
This version is not yet released, so this PR has to wait.

Update versions.xml for UOPZ 7.1.0

---

reference/mysqli/mysqli_stmt/bind-result.xml

I have split up the note, added a helpful tip, and modernized the code example.

Updating mysqli: bind_result

---

.github/workflows/integrate.yaml

This is mostly meant for PhD CI, but may be useful for other purposes
as well.

CI: upload .manual.xml

---

reference/pdo/pdostatement/fetchall.xml

Fix fetchAll synopsis

---

language-snippets.ent

Fix &style.oop;

---

language-snippets.ent

Just makes the language feel a little more natural

slight improvement to the language

---

reference/mysqli/mysqli/set-charset.xml

I am not sure if the first note on this page is still relevant.

Updating mysqli: set_charset

---

language/oop5/magic.xml

It is proposal to explain more concrete the type of the fail after re-importing objects from var_export.
That it is not only would not be re-imported - but also causes fatal error

Proposal - more concrete explanation of the fail for __set_state

---

reference/apcu/functions/apcu-key-info.xml

As per https://github.com/krakjoe/apcu/blob/b68953ccbc1a5234c2caf8ed5800afd222270948/php_apc.stub.php#L12

Fix apcu_key_info return value

---

reference/pdo/pdo/setattribute.xml

Fix type in PDO::setAttribute

---

reference/filesystem/functions/parse-ini-file.xml

(looks like a copy-paste from previous example)

Remove irrelevant paragraph

---

reference/filesystem/functions/parse-ini-file.xml

See merged PR https://github.com/php/php-src/pull/7420 (https://github.com/php/php-src/commit/d3a6054d4441a6d431e6ca7aa63de62cee5585c2)

Add a separate example section for escaping of characters

---

reference/dom/domelement/setattribute.xml

DomElement::setAttribute does not always return a new DomAttr instance

---

language/predefined/iteratoraggregate.xml

IteratorAggregate is an inteface, not a class.
Not tested. I don't know how to build it etc.

Fixed synopsis of IteratorAggregate

---

language-snippets.ent
reference/curl/functions/curl-close.xml
reference/curl/functions/curl-multi-close.xml
reference/curl/functions/curl-share-close.xml
reference/image/functions/imagedestroy.xml
reference/openssl/functions/openssl-pkey-free.xml
reference/openssl/functions/openssl-x509-free.xml
reference/shmop/functions/shmop-close.xml
reference/xml/functions/xml-parser-free.xml

Based on https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.core.other

Add note about NOP code

---

reference/mysqli/mysqli_result/data-seek.xml

I have provided a better example. The secondary example should replace the [user note](https://www.php.net/manual/en/mysqli-result.data-seek.php#85629).

Updating mysqli: data_seek

---

reference/image/functions/imagecreatefromtga.xml
reference/image/versions.xml

Add `imagecreatefromtga` description

---

reference/classobj/functions/get-mangled-object-vars.xml
reference/classobj/versions.xml

Add `get_mangled_object_vars` description

---

reference/filesystem/functions/fputcsv.xml
reference/spl/splfileobject/fputcsv.xml

Based on stubs:
- [fputcsv](https://github.com/php/php-src/blob/PHP-8.1/ext/standard/basic_functions.stub.php#L1158)
- [SplFileObject::fputcsv](https://github.com/php/php-src/blob/PHP-8.1/ext/spl/spl_directory.stub.php#L213)

[PHP 8.1] Update `fputcsv` and `SplFileObject::fputcsv` description

---

reference/stream/functions/stream-context-set-option.xml

Corrected spelling

---

language-snippets.ent
reference/fileinfo/functions/finfo-buffer.xml
reference/fileinfo/functions/finfo-close.xml
reference/fileinfo/functions/finfo-file.xml
reference/fileinfo/functions/finfo-open.xml
reference/fileinfo/functions/finfo-set-flags.xml
reference/fileinfo/setup.xml

[PHP 8.1] Use an `finfo` instance instead of a resource

---

reference/mysqli/mysqli_stmt/execute.xml

I'd be glad we can merge this before #987

Small fixes in pdo execute

---

reference/mysqli/mysqli_stmt/execute.xml

Related [RFC](https://wiki.php.net/rfc/mysqli_bind_in_execute)

[PHP 8.1] Update `mysqli_stmt::execute` description

---

reference/url/functions/get-headers.xml

Change int to bool

---

reference/mysqli/mysqli_result/fetch-array.xml
reference/mysqli/mysqli_result/fetch-assoc.xml
reference/mysqli/mysqli_result/fetch-object.xml
reference/mysqli/mysqli_result/fetch-row.xml

I fixed the merge conflicts between the two PRs #39 and #207 as best I could. @colshrapnel did not enable changes from maintainers, so I had to open a new PR instead of appending to the existing one.
Closes #39

Clarification of return values descriptions for mysqi fetch functions

---

reference/sockets/constants.xml
reference/sockets/functions/socket-get-option.xml

Add `SO_DONTTRUNC`, `SO_WANTMORE`, and `TCP_DEFER_ACCEPT` description.

[PHP 8.1] Add new Sockets constants

---

reference/filesystem/functions/dirname.xml

🤞🏻 I hope I got the syntax correct ;-)

dirname(): add warning about risk of infinite loop

---

language/enumerations.xml

Correct the wrong keyword in the sample code

---

reference/mysqli/mysqli/debug.xml

As per https://www.php.net/manual/en/mysqli.debug.php#122219

Add options parameters from comment

---

reference/intl/dateformatter/create.xml

See https://github.com/php/php-src/pull/7640

Fix IntlDateFormatter constructor documentation

---

language-snippets.ent
reference/mysqli/mysqli_result/num-rows.xml
reference/mysqli/mysqli_stmt/num-rows.xml

Note taken from reference/mysqli/mysqli_result/num-rows.xml

Add note when return value is string

---

reference/sockets/addressinfo.xml
reference/sockets/socket.xml

Generate ext/sockets class synopses from stubs

---

reference/pcre/functions/preg-match-all.xml

Fix preg_match_all return values

---

language/predefined/backedenum.xml
language/predefined/backedenum/from.xml
language/predefined/backedenum/tryfrom.xml

Closes #1135
https://github.com/php/doc-en/issues/1135#issuecomment-977262147

BackedEnum is also an interface.

---

language/predefined/generator.xml

Generator is final

---

language/predefined/closure.xml
language/predefined/weakreference.xml
reference/dom/domexception.xml
reference/hash/hashcontext.xml
reference/reflection/reflectiongenerator.xml

Add missing final modifier

---

reference/stream/functions/stream-bucket-make-writeable.xml

Here's an initial documentation of the object returned by `stream_bucket_make_writable`. Let me know in the comment if more informations is needed or if I missed something. Since it's my first contribution to the documentation.

Adding initial documentation to stream bucket make writable

---

reference/pdo_pgsql/constants.xml
reference/pdo_pgsql/reference.xml

The attribute was added in 2014 but never documented.

Document PDO::PGSQL_ATTR_DISABLE_PREPARES attribute

---

language-snippets.ent
reference/array/functions/current.xml
reference/array/functions/end.xml
reference/array/functions/key.xml
reference/array/functions/next.xml
reference/array/functions/prev.xml
reference/array/functions/reset.xml

- `current()`
- `end()`
- `key()`
- `next()`
- `prev()`
- `reset()`
Relates #1034

[PHP 8.1] Changelog entry for standard functions

---

appendices/comparisons.xml

@cmb69 1a89eb1e2de815801d6ab2a29f30b5cc3bf4bf12

Fix loose type comparison table

---

reference/curl/setup.xml

PHP 7.3 increased the min version of curl

Update the min version of curl required by PHP

---

reference/ffi/ffi.cdata.xml
reference/ffi/ffi.ctype.xml
reference/ffi/ffi.exception.xml
reference/ffi/ffi.parserexception.xml
reference/ffi/ffi.xml

This is the last one for today

Generate ext/ffi class synopses from stubs

---

reference/spl/emptyiterator.xml
reference/spl/filesystemiterator.xml
reference/spl/filteriterator.xml
reference/spl/globiterator.xml
reference/spl/infiniteiterator.xml
reference/spl/iteratoriterator.xml
reference/spl/norewinditerator.xml
reference/spl/outeriterator.xml

Generate ext/spl class synopses from stubs - part 5

---

language/predefined/generator.xml
language/predefined/iterator.xml
language/predefined/iteratoraggregate.xml
language/predefined/parseerror.xml
language/predefined/serializable.xml
language/predefined/stringable.xml
language/predefined/throwable.xml
language/predefined/traversable.xml
language/predefined/typeerror.xml
language/predefined/unhandledmatcherror.xml
language/predefined/unitenum.xml
language/predefined/valueerror.xml
language/predefined/weakmap.xml
language/predefined/weakreference.xml

Mostly formatting changes again

Generate Zend class synopses from stubs - part 2

---

reference/datetime/dateinterval.xml
reference/datetime/dateperiod.xml
reference/datetime/datetime.xml
reference/datetime/datetimeimmutable.xml
reference/datetime/datetimeinterface.xml
reference/datetime/datetimezone.xml

Mostly formatting changes besides one Traversable -> IteratorAggregate one

Generate ext/date class synopses from stubs

---

reference/phar/Phar/buildFromDirectory.xml
reference/phar/Phar/buildFromIterator.xml
reference/phar/Phar/copy.xml
reference/phar/Phar/offsetGet.xml
reference/phar/Phar/offsetUnset.xml
reference/phar/PharData/buildFromDirectory.xml
reference/phar/PharData/buildFromIterator.xml
reference/phar/PharData/copy.xml
reference/phar/PharData/offsetUnset.xml

Regenerate ext/phar method synopses based on stubs

---

reference/intl/intlgregoriancalendar/getgregorianchange.xml
reference/intl/intlgregoriancalendar/isleapyear.xml
reference/intl/intlgregoriancalendar/setgregorianchange.xml
reference/intl/intliterator/key.xml
reference/intl/intlrulebasedbreakiterator.xml
reference/intl/intlrulebasedbreakiterator/construct.xml
reference/intl/intlrulebasedbreakiterator/getbinaryrules.xml
reference/intl/intlrulebasedbreakiterator/getrules.xml
reference/intl/intlrulebasedbreakiterator/getrulestatusvec.xml

This is my last PR for ext/intl 🎉

Generate ext/intl methodsynopses based on stubs (IntlGregorianCalendar, IntlIterator, IntlRuleBasedBreakIterator)

---

reference/intl/intlcodepointbreakiterator.xml
reference/intl/intlgregoriancalendar.xml
reference/intl/intlpartsiterator.xml
reference/intl/intlrulebasedbreakiterator.xml
reference/intl/resourcebundle.xml
reference/intl/spoofchecker.xml
reference/intl/uconverter.xml

Only formatting changes (+ fallbacks)

Generate ext/intl class synopses from stubs - part 3

---

reference/strings/functions/get-html-translation-table.xml
reference/strings/functions/html-entity-decode.xml
reference/strings/functions/htmlentities.xml
reference/strings/functions/htmlspecialchars-decode.xml
reference/strings/functions/htmlspecialchars.xml
reference/strings/functions/ltrim.xml
reference/strings/functions/rtrim.xml
reference/strings/functions/trim.xml

These are probably somewhat controversial changes

Update some string function parameter default values

---

reference/gmp/functions/gmp-export.xml
reference/gmp/functions/gmp-import.xml

Adjust ext/gmp default values

---

reference/dom/domdocumentfragment.xml
reference/dom/domdocumentfragment/construct.xml

Although this is not the most useful page to have

Add initial documentation for DOMDocumentFragment::__construct()

---

language/oop5/properties.xml
language/oop5/visibility.xml

The first paragraph is becoming a bit complexe, so maybe it would be better to rewrite it?

Properties do not need to be declared with a visibility modifier

---

reference/mysqli/mysqli_sql_exception.xml
reference/mysqli/mysqli_sql_exception/getsqlstate.xml
reference/mysqli/versions.xml

I have to admit that the descriptions are not too informative.

Document mysqli_sql_exception::getSqlState()

---

reference/dom/domchildnode.xml
reference/dom/domchildnode/after.xml
reference/dom/domchildnode/before.xml
reference/dom/domchildnode/replaceWith.xml
reference/dom/domparentnode.xml
reference/dom/domparentnode/append.xml
reference/dom/domparentnode/prepend.xml

Regenerated these pages via gen_stub.php

Fix DOMParentNode and DOMChildNode class and method synopses

---

reference/gnupg/functions/gnupg-init.xml

This adds documentation for options parameter added to php-gnupg 1.5.0

Document options for gnupg_init

---

install/unix/litespeed.xml

Updated old dead links to new links.

Update dead links for LiteSpeed

---

reference/eio/functions/eio-readlink.xml

See https://github.com/rosmanov/pecl-eio/blob/5291fa10d0ebd8c3454475957c32748920167cf2/php8/php_eio.stub.php#L101

Fix parameter type for eio_readlink

---

install/fpm/index.xml
install/fpm/install.xml
language-snippets.ent
reference/fpm/book.xml

Updated FPM installation info with addition of AppArmor configure options and clarify some outdated bits. Also the coding style has been improved.

Update FPM installation and intro

---

appendices/migration81/incompatible.xml
language-snippets.ent
language/functions.xml

* Document change in behaviour of misplaced optional parameters in 8.1
* Expand and update documentation of default/optional parameters

Optional parameter changes in 8.1, and description improvements

---

reference/event/event/add.xml
reference/event/event/addsignal.xml
reference/event/event/addtimer.xml
reference/event/event/del.xml
reference/event/event/delsignal.xml
reference/event/event/deltimer.xml

This also fixes the alias detection for the section order script

Fix method aliases in Event class

---

reference/pcntl/constants.xml
reference/pcntl/functions/pcntl-unshare.xml
reference/pcntl/versions.xml

Add `pcntl_unshare` description

---

reference/imagick/imagick/getimagealphachannel.xml

Mentioned in doc-de/issues/67 by Daijobou (thanks).
Changelog entry?

Fix return type (int → bool)

---

language/oop5/decon.xml

Related [RFC](https://wiki.php.net/rfc/new_in_initializers).

[PHP 8.1] New in initializers

---

language/functions.xml

[PHP 8.1] Use named arguments after unpacking

---

.github/workflows/integrate.yaml

This prevents from introducing incorrect section orders.
Hopefully I amended the GH Action file correctly

Run section-order QA script on CI

---

language/operators.xml

All of these based off of comments, some of which I've deleted and some not (for reference, will delete after this is merged).

Comparison operator updates from comments

---

language/oop5/autoload.xml

Mostly the exceptions, which are bad mojo with `spl_autoload_register()`.

Clean up autoload page

---

reference/funchand/functions/register-shutdown-function.xml

I have purged a bunch of comments.  This is what's worth keeping.

register_shutdown_function() updates based on comments

---

reference/array/functions/usort.xml

I have already removed 2/3 of the page's comments. :smile:

Usort updates based on comments

---

reference/array/functions/array-combine.xml

Update `array_combine` return values section

---

reference/sodium/constants.xml

Relates [Migration Guide](https://www.php.net/manual/en/migration81.constants.php#migration81.constants.sodium)

[PHP 8.1] Add new global Sodium constants

---

reference/pdo/pdostatement/getcolumnmeta.xml

Sorry for the additional PR so soon; someone asked me what was meant by "drivers in the manual" - this just cross-links to the drivers page.

Link to the drivers, since it's not obvious what it's meant

---

language/oop5/inheritance.xml

But perhaps there is a more appropriate page 🤔

[PHP 8.1] Return Type Compatibility with Internal Classes

---

reference/datetime/formats.xml

Remove personalisation, use entity for ``false``, use spaces for indentation.

Nits to datetime/formats.xml

---

reference/reflection/reflectionfunctionabstract/gettentativereturntype.xml
reference/reflection/reflectionfunctionabstract/hastentativereturntype.xml
reference/reflection/versions.xml

Add 
- `ReflectionFunctionAbstract::getTentativeReturnType()`
- `ReflectionFunctionAbstract::hasTentativeReturnType()`
Closes #1614

[PHP 8.1] Add get/hasTentativeReturnType functions

---

reference/funchand/functions/func-num-args.xml

more concise example code

---

reference/intl/dateformatter/create.xml

See https://github.com/php/php-src/blob/master/ext/intl/dateformat/dateformat.stub.php

Fix signature for datefmt_create

---

language/expressions.xml

I changed some `<literal>` tags, `<varname>` tags, and quotes to `<code>` tags in cases where inline code was written. Full disclosure and apologies: I  created this PR on GitHub without running it.

Changed some tags and single quotes to <code>

---

reference/ldap/functions/ldap-exop.xml

I don't know if these ever get re-generated.

Use updated parameter names for ldap_exop

---

reference/pcre/functions/preg-replace.xml

The only things worth adding from the now-purged comments.

preg_replace additional notes

---

reference/json/functions/json-encode.xml

Several (now dead) comments mentioned this in some way, so let's mention it for them.

Clarify object and array handling in json_encode

---

reference/strings/functions/str-split.xml

The only useful issues raised by the now mostly deleted comments.

Clarify error handling and other behvaior of str_split

---

reference/filesystem/functions/mkdir.xml

The useful bits of the comments that have now bitten the dust.

Add caveats to mkdir based on comments

---

reference/datetime/datetimeimmutable/construct.xml

there is no DateTimeImmutableZone, its just DateTimeZone

wrong class in example code

---

reference/funchand/functions/call-user-func-array.xml

Indicates change in keys handling

Add call-user-func-array Changelog

---

reference/misc/functions/sleep.xml

add note about usleep vs sleep usage mirroring the top comment to help myself from yesterday

sleep() additional notes

---

language/namespaces.xml

... for completeness.
Page link: https://www.php.net/manual/en/language.namespaces.importing.php

Namespaces/importing: update the list of structures which can be imported

---

reference/datetime/functions/time.xml

the example was related to `date` method and then I tried to fix it

Update document for time method

---

reference/array/functions/in-array.xml

More than 3/4 of the comments on in_array are/were (I deleted them) variations on "beware weak mode, it does weird things."
So let's kill them all and add a note that says the same thing so people stop posting it over and over again.

Add note about how bad weak mode is for in_array.

---

reference/classobj/functions/get-class-methods.xml

Relates php/doc-ru#418
https://3v4l.org/CJBaS

Fix example output

---

language/oop5/magic.xml

I find that the documentation of magic methods is poor of practicals examples. In this PR I try do improve the documentation of `__invoke` method. Hope that will be accepted.

magic methods: improve __invoke documentation

---

reference/mysqli/functions/mysqli-execute.xml
reference/solr/solrdocument/reset.xml
reference/solr/solrinputdocument/reset.xml
reference/solr/solrparams/add.xml
reference/solr/solrparams/get.xml
reference/solr/solrparams/set.xml
reference/xdiff/functions/xdiff-file-diff-binary.xml
reference/xdiff/functions/xdiff-file-patch-binary.xml
reference/xdiff/functions/xdiff-string-diff-binary.xml
reference/xdiff/functions/xdiff-string-patch-binary.xml

So that https://github.com/php/php-src/pull/9491 can find all the aliases.

Use even more &alias; entities

---

reference/openssl/functions/openssl-cipher-key-length.xml
reference/openssl/versions.xml

Ref https://github.com/php/php-src/pull/9368

[PHP 8.2] Add `openssl_cipher_key_length` description

---

reference/curl/functions/curl-upkeep.xml
reference/curl/versions.xml

Ref: https://curl.se/libcurl/c/curl_easy_upkeep.html

[PHP 8.2] Add `curl_upkeep` description

---

reference/pcre/configure.xml

Cf. <https://github.com/php/php-src/commit/32cceb75bf5e42bebbf4d12bab4369924f1d6885>.

Update Upgrade history of the bundled PCRE library

---

reference/datetime/formats.xml

But actually neither seems to work currently? https://3v4l.org/9fKt3/rfc#vgit.master :confused:

Fix one 5+ digit year example (sign is required)

---

reference/ldap/functions/ldap-get-option.xml

LDAP_OPT_DIAGNOSTIC_MESSAGE is a string

Fix error on ldap_get_option page

---

reference/datetime/dateperiod/construct.xml

Hello, just a little typo issue i found today !
Thanks for your work !

Typo in DatePeriod construct

---

appendices/reserved.xml
language/predefined/interfaces.xml
language/predefined/stdclass.xml
language/predefined/versions.xml

Document stdClass

---

appendices/migration82/other-changes.xml
reference/mbstring/ini.xml

Document mbstring.regex_retry_limit and mbstring.regex_stack_limit directives

---

reference/json/functions/json-decode.xml

JSON DECODE: Change `PHP variable` into `PHP value`

---

appendices/extensions.xml
reference/simdjson/book.xml
reference/simdjson/constants.xml
reference/simdjson/functions/simdjson-decode.xml
reference/simdjson/functions/simdjson-is-valid.xml
reference/simdjson/functions/simdjson-key-count.xml
reference/simdjson/functions/simdjson-key-exists.xml
reference/simdjson/functions/simdjson-key-value.xml
reference/simdjson/reference.xml
reference/simdjson/setup.xml
reference/simdjson/simdjsonexception.xml
reference/simdjson/simdjsonvalueerror.xml
reference/simdjson/versions.xml

API documentation and other example snippets are available at https://github.com/crazyxman/simdjson_php
Depends on https://github.com/php/doc-base/pull/71 to build

Document the simdjson PECL

---

language/predefined/internaliterator.xml
reference/intl/idn/idn-to-utf8.xml
reference/pcntl/functions/pcntl-rfork.xml
reference/random/random.brokenrandomengineerror.xml
reference/random/random.cryptosafeengine.xml
reference/random/random.engine.mt19937.xml
reference/random/random.engine.pcgoneseq128xslrr64.xml
reference/random/random.engine.secure.xml
reference/random/random.engine.xml
reference/random/random.engine.xoshiro256starstar.xml
reference/random/random.randomerror.xml
reference/random/random.randomexception.xml
reference/random/random.randomizer.xml
reference/random/random/engine/generate.xml
reference/random/random/engine/mt19937/construct.xml
reference/random/random/engine/pcgoneseq128xslrr64/construct.xml
reference/random/random/engine/xoshiro256starstar/construct.xml
reference/reflection/reflectionenum.xml
reference/reflection/reflectionenumbackedcase.xml
reference/zip/ziparchive/getexternalattributesindex.xml

Sync a few manual pages with the stubs

---

language/predefined/variables/server.xml

Drop personalisation
Drop mention of specific HTTP headers and use a general statement instead
Various markup nits
Resolves: #1901

Rewrite $_SERVER docs

---

reference/spl/arrayiterator.xml
reference/spl/arrayobject.xml
reference/spl/cachingiterator.xml
reference/spl/filesystemiterator.xml
reference/spl/multipleiterator.xml
reference/spl/recursivearrayiterator.xml
reference/spl/recursiveiteratoriterator.xml
reference/spl/recursivetreeiterator.xml
reference/spl/regexiterator.xml
reference/spl/spldoublylinkedlist.xml
reference/spl/splfileobject.xml

These are usually simple sync changes: visibility modifier is added, value is removed. Only ~2 new constants are added.

Sync ext/spl class constants with stubs - part 1

---

reference/xmlreader/xmlreader.xml

This PR contains only whitespaces change besides the added visibility modifiers + removed values

Sync XMLReader class constants with stubs

---

reference/network/functions/net-get-interfaces.xml

As far as I see, there's no reason for the procedural role.

Remove unnecessary procedural role

---

reference/exec/functions/exec.xml
reference/exec/functions/passthru.xml
reference/funchand/functions/register-shutdown-function.xml
reference/gmp/functions/gmp-random-seed.xml

Not sure what the wording usually is for the changelog and the error sections, so please advise.

Improve and fix docs which had incorrect stub info

---

reference/datetime/datetimeimmutable/settime.xml

Corrects code sample

---

language-snippets.ent
language/predefined/attributes/sensitive-parameter.xml

based on RFC: https://wiki.php.net/rfc/redact_parameters_in_back_traces

added SensitiveParameter usage example.

---

language/functions.xml

The formatting in this example didn't match the other examples on the page.

Fix inconsistent formatting for anonymous function

---

reference/dir/functions/scandir.xml

Improved readability. Furthermore, value of SCANDIR_SORT_DESCENDING can possibly change in the future :)

scandir - use constant name instead of its value

---

install/unix/openbsd.xml

This is only a draft. First of all, I'm not sure about the ports section. Do the two subdirectories core and extensions still exist? I could not find them in the ports tree.

Adapt to current OpenBSD version

---

reference/zip/ziparchive/open.xml

- https://github.com/JetBrains/phpstorm-stubs/pull/1499
- https://github.com/php/php-src/blob/ca8247654c1e324d412bb6f40ef14fb506487983/ext/zip/php_zip.c#L1454-L1471

ZipArchive::open(): bool|int

---

reference/uodbc/functions/odbc-connection-string-is-quoted.xml
reference/uodbc/functions/odbc-connection-string-quote.xml
reference/uodbc/functions/odbc-connection-string-should-quote.xml
reference/uodbc/versions.xml

Unsure if the language here is clear enough. Also having difficulty with the output scripts, so unsure if these even are in the right place.

Attempt to add ODBC connection string functions

---

reference/pdo_sqlsrv/configure.xml

Related PR https://github.com/php/doc-base/pull/49

Improve installation instructions for PDO sqlsrv on Linux

---

reference/reflection/reflectionfunction/invokeargs.xml
reference/reflection/reflectionmethod/invokeargs.xml

Similar to #1714 , but for the `invokeArgs` methods.

Add invokeArgs Changelog

---

reference/curl/curlfile.xml
reference/curl/curlfile/construct.xml
reference/curl/curlfile/getfilename.xml
reference/curl/curlfile/getmimetype.xml
reference/curl/curlfile/getpostfilename.xml
reference/curl/curlfile/setmimetype.xml
reference/curl/curlfile/setpostfilename.xml
reference/curl/curlstringfile.xml
reference/curl/curlstringfile/construct.xml

Based on https://github.com/php/php-src/pull/9901

Update ext/curl role attributes

---

reference/com/com.xml
reference/com/com/construct.xml
reference/com/compersisthelper.xml
reference/com/compersisthelper/construct.xml
reference/com/compersisthelper/getcurfilename.xml
reference/com/compersisthelper/getmaxstreamsize.xml
reference/com/compersisthelper/initnew.xml
reference/com/compersisthelper/loadfromfile.xml
reference/com/compersisthelper/loadfromstream.xml
reference/com/compersisthelper/savetofile.xml
reference/com/compersisthelper/savetostream.xml
reference/com/dotnet.xml
reference/com/dotnet/construct.xml
reference/com/variant.xml
reference/com/variant/construct.xml

Update ext/com role attributes

---

reference/xsl/xsltprocessor.xml
reference/xsl/xsltprocessor/construct.xml
reference/xsl/xsltprocessor/getparameter.xml
reference/xsl/xsltprocessor/getsecurityprefs.xml
reference/xsl/xsltprocessor/hasexsltsupport.xml
reference/xsl/xsltprocessor/importstylesheet.xml
reference/xsl/xsltprocessor/registerphpfunctions.xml
reference/xsl/xsltprocessor/removeparameter.xml
reference/xsl/xsltprocessor/setparameter.xml
reference/xsl/xsltprocessor/setprofiling.xml
reference/xsl/xsltprocessor/setsecurityprefs.xml
reference/xsl/xsltprocessor/transformtodoc.xml
reference/xsl/xsltprocessor/transformtouri.xml
reference/xsl/xsltprocessor/transformtoxml.xml

Based on https://github.com/php/php-src/pull/9901

Update ext/xsl role attributes

---

reference/array/functions/array-unshift.xml

Added an example that shows how two associative arrays are combined using `array_unshift()`
https://www.php.net/manual/en/function.array-unshift.php

array_unshift page, add an example with two associative arrays

---

reference/ldap/examples.xml

[Issues/2093] fix typo

---

reference/stream/php-user-filter.xml
reference/stream/php_user_filter/construct.xml
reference/stream/versions.xml
reference/xml/versions.xml
reference/xml/xmlparser.xml
reference/xml/xmlparser/construct.xml
reference/xmlreader/versions.xml
reference/xmlreader/xmlreader.xml
reference/xmlreader/xmlreader/construct.xml
reference/xmlwriter/versions.xml
reference/xmlwriter/xmlwriter.xml
reference/xmlwriter/xmlwriter/construct.xml
reference/xsl/xsltprocessor.xml
reference/xsl/xsltprocessor/construct.xml
reference/zip/versions.xml
reference/zip/ziparchive.xml
reference/zip/ziparchive/construct.xml
reference/zlib/deflatecontext.xml
reference/zlib/deflatecontext/construct.xml
reference/zlib/inflatecontext.xml
reference/zlib/inflatecontext/construct.xml
reference/zlib/versions.xml

First followup for https://github.com/php/php-src/pull/10098/

Add documentation for default constructors - part 1

---

reference/errorfunc/functions/set-error-handler.xml

While hilarious as is, this should probably be reworded.

Reword excessively hardcore requirement

---

.github/workflows/check-whitespace.yml
.github/workflows/integrate.yaml

see php/php-src@1d45ca58c86ac103ea624c3af3c81c20863950ad

Add explicit `permissions` to GHA workflows

---

reference/snmp/snmp.xml
reference/spl/splpriorityqueue.xml

Only 7 false positive class synopsis page diffs remain with the stubs after this PR!

Add missing class constants with empty description - part 4

---

reference/random/random/randomizer/pickarraykeys.xml
reference/random/random/randomizer/shufflearray.xml

- Add more elements to be able to select reasonable subsets.
- Don't use two differently-colored apples.
- Showcase two different selections.

Improve random fruit examples

---

reference/xml/functions/xml-get-current-column-number.xml

Same reason as https://github.com/php/doc-en/pull/2210

Drop xml_get_current_column_number() return false description

---

reference/xml/functions/xml-get-current-line-number.xml

Same reason as https://github.com/php/doc-en/pull/2210

Drop xml_get_current_line_number() return false description

---

reference/xml/functions/xml-get-error-code.xml

Same reason as https://github.com/php/doc-en/pull/2210

Drop xml_get_error_code() return false description

---

reference/datetime/formats.xml

Hi,
just a little fix of a typo !
Thanks for your work :)

Fix typo in reference/datetime/formats

---

reference/filesystem/functions/tmpfile.xml

ref https://github.com/php/php-src/blob/master/main/php_open_temporary_file.c#L103

tmpfile() uses binary mode.

---

reference/random/random/randomizer/pickarraykeys.xml

random: Showcase turning picked array keys into values

---

reference/network/functions/long2ip.xml

Fix typo in long2ip 

---

reference/gmp/functions/gmp-clrbit.xml
reference/gmp/functions/gmp-setbit.xml

fixes https://github.com/php/doc-en/issues/2288

Fix gmp_clrbit and gmp_setbit num parameter description

---

reference/dom/domcharacterdata/deletedata.xml

Add missing DOMCharacterData::deleteData return false description

---

reference/pdo/pdo/setattribute.xml

PDO::MYSQL_ATTR_USE_BUFFERED_QUERY is true by default

---

security/database.xml

The page was full of bloat and unclear text. The most important thing: prepared statements wasn't even given a good example. This PR attempts to improve this page by rewrite large chunks of it, moving some information around, and emphasising important points. 
@colshrapnel You might be interested in reviewing this PR too.

Rewrite Sql injection page

---

language/predefined/exception/clone.xml

cloning Exception hasn't been fatal since PHP 5.6

---

reference/dom/domnode/insertbefore.xml

This method returns false on error.

Add DOMNode::insertBefore() return false description

---

reference/dom/domnode/removechild.xml

This method returns false on error.

Add DOMNode::removeChild() return false description

---

reference/dom/domimplementation/createdocumenttype.xml

This method returns false on error.

Add DOMImplementation::createDocumentType() return false description

---

reference/mysqli/mysqli/query.xml
reference/mysqli/mysqli_stmt/execute.xml

Add execute_query() to the See also section

---

reference/math/functions/log.xml

A little bit of help to those who might be looking for a way to log error messages.

Add error_log() to See Also for log()

---

language-snippets.ent
reference/array/functions/array-diff-uassoc.xml
reference/array/functions/array-diff-ukey.xml
reference/array/functions/array-intersect-uassoc.xml
reference/array/functions/array-intersect-ukey.xml
reference/array/functions/array-udiff-assoc.xml
reference/array/functions/array-udiff-uassoc.xml
reference/array/functions/array-udiff.xml
reference/array/functions/array-uintersect-assoc.xml
reference/array/functions/array-uintersect-uassoc.xml
reference/array/functions/array-uintersect.xml
reference/array/functions/uasort.xml
reference/array/functions/uksort.xml
reference/array/functions/usort.xml
reference/ds/ds/deque/sort.xml
reference/ds/ds/deque/sorted.xml
reference/ds/ds/map/ksort.xml
reference/ds/ds/map/ksorted.xml
reference/ds/ds/map/sort.xml
reference/ds/ds/map/sorted.xml
reference/ds/ds/sequence/sort.xml
reference/ds/ds/sequence/sorted.xml
reference/ds/ds/set/sort.xml
reference/ds/ds/set/sorted.xml
reference/ds/ds/vector/sort.xml
reference/ds/ds/vector/sorted.xml
reference/spl/arrayiterator/uasort.xml
reference/spl/arrayiterator/uksort.xml
reference/spl/arrayobject/uasort.xml
reference/spl/arrayobject/uksort.xml

Add sort.callback.description entity

---

reference/datetime/functions/date-parse.xml

As far as I can tell, it never did.

date_parse does not return false

---

language/oop5/traits.xml

Remove readonly in example Conflict Resolution

---

language/types/type-juggling.xml

Rephrasing the sentence while keeping its meaning.

Rephrase sentence to improve grammar

---

language/types/literal.xml

Replace a word to improve sentence meaning.

Correct word in sentence

---

reference/phar/PharData/addFromString.xml

eems like this was copied from addFile and not changed accordingly.

fix incorrect refpurpose

---

language-snippets.ent
reference/strings/functions/fprintf.xml
reference/strings/functions/printf.xml
reference/strings/functions/sprintf.xml
reference/strings/functions/vfprintf.xml
reference/strings/functions/vprintf.xml
reference/strings/functions/vsprintf.xml

docs: update exceptions for sprintf and vsprintf

---

reference/classobj/functions/is-a.xml

Use supertype instead of parent in is_a function

---

reference/mysqlinfo/concepts.xml
reference/pdo_mysql/constants.xml

See https://bugs.php.net/bug.php?id=71491

Improve PDO_MySQL unbuffered documentation

---

language/constants.xml
language/oop5/basic.xml

Attempting to fix PR #728 which in turn fixes issue https://github.com/php/doc-en/issues/707

Remove replaceable class from magic constant

---

reference/parallel/parallel/sync/get.xml

typo fixed

---

reference/spl/splfileobject/tostring.xml

Doc update for https://github.com/php/php-src/pull/9912

Update SplFileObject::_toString() after bugfix

---

reference/filesystem/functions/pathinfo.xml

These are the only two changes worth keeping from the comments section, most of which I have now purged.

Fold in comments for pathinfo()

---

reference/dom/domdocument/getelementsbytagnamens.xml
reference/dom/domelement/getelementsbytagnamens.xml

And while we're here, make the documentation consistent.
Never contributed to the docs before, so not sure about wording etc :P

Clarifications about getElementsByTagNameNS

---

language/enumerations.xml

Hoping the CI works to test it's formatted okay....

Adding example of why enum inheritance is not allowed.

---

language/wrappers/php.xml

Sorry. I made a mistake in my previously merged PR #2508

Fix wording

---

reference/network/functions/headers-sent.xml

https://github.com/php/doc-en/issues/2523

Add note to headers_sent() about empty filename

---

language/oop5/traits.xml

Hi, 
this should fix this issue #2142 
If it’s OK for you, I can do the same for the others languages.
Regards,
Sylvain

Fix: #2142 Traits conflict resolution example error

---

reference/openssl/constants.xml

Ref: https://github.com/php/php-src/pull/10696

docs(openssl): add PKCS7_NOOLDMIMETYPE and OPENSSL_CMS_OLDMIMETYPE

---

reference/dom/domattr.xml

DOMAttr: setting value triggers XML entity parsing

---

language/functions.xml

Correct singular and plural usage in a sentence.

Correct word

---

language/predefined/arrayaccess.xml
language/predefined/backedenum.xml
language/predefined/iterator.xml
language/predefined/iteratoraggregate.xml
language/predefined/serializable.xml
language/predefined/stringable.xml
language/predefined/throwable.xml
language/predefined/traversable.xml
language/predefined/unitenum.xml
reference/datetime/datetimeinterface.xml
reference/dom/domchildnode.xml
reference/dom/domparentnode.xml
reference/random/random.cryptosafeengine.xml
reference/random/random.engine.xml
reference/reflection/reflector.xml
reference/session/sessionhandlerinterface.xml
reference/session/sessionidinterface.xml
reference/session/sessionupdatetimestamphandlerinterface.xml
reference/spl/countable.xml
reference/spl/outeriterator.xml
reference/spl/recursiveiterator.xml
reference/spl/seekableiterator.xml
reference/spl/splobserver.xml
reference/spl/splsubject.xml

According to https://github.com/php/phd/pull/75

Render interfaces according to the new format

---

appendices/migration82/new-functions.xml
reference/imap/functions/imap-is-open.xml
reference/imap/versions.xml

Added imap_is_open docs, based on https://github.com/php/php-src/commit/52a891aeaa1333b3cb02f0dfd796c0fae8ab175c.

[PHP 8.2] added imap_is_open documentation

---

reference/mysqlinfo/set.xml

Fixes https://bugs.php.net/bug.php?id=75518

Add prepared statement example to mysqlinfo.api.choosing

---

reference/dom/domelement/setattributenode.xml
reference/dom/domelement/setattributenodens.xml

Fixes #1400
I am not sure if I referenced `strictErrorChecking` correctly though.

Corrections and clarifications to setAttributeNode(NS)

---

reference/dom/domnode/lookupnamespaceuri.xml

Ref:
- https://github.com/php/php-src/blob/c40dcf93d0b95d9a1026476b202f5aa965fb3fdd/ext/dom/node.c#L1622-L1650
- https://github.com/php/php-src/blob/b3553159a7b15d1ddd485aba9f83485f08e2e800/ext/dom/node.c#L1515-L1543
- https://www.w3.org/TR/DOM-Level-3-Core/core.html#Node3-lookupNamespaceURI

Update docs for `DOMNode::lookupNamespaceURI`

---

language/predefined/arrayaccess.xml

ArrayAccess::offsetSet($offset, $value):void
ArrayAccess::offsetExists($offset):bool
ArrayAccess::offsetUnset($offset):void
ArrayAccess::offsetGet($offset):mixed

ArrayAccess:: method need a return type

---

reference/pcre/pattern.syntax.xml

Fix https://github.com/php/doc-en/issues/2565

Add missing word in pcre/pattern page

---

reference/classobj/functions/class-alias.xml

Fix https://github.com/php/doc-en/issues/2383

Add a note about lowercase declared class alias

---

reference/pdo/pdostatement/bindvalue.xml

Fix https://github.com/php/doc-en/issues/2155
It is actually already documented, but I tried a bit of rewording to be clearer

Reword parameters value binding

---

language/types/enumerations.xml

Fix https://github.com/php/doc-en/issues/2079

Display version required by enumerations

---

reference/info/functions/phpversion.xml

Fix https://github.com/php/doc-en/issues/2381

Add a note about PHP core extension versions in `phpversion()`

---

reference/password/setup.xml

Fix https://github.com/php/doc-en/issues/2102

Remove configure option argument requirement as of PHP 8.1.0

---

reference/reflection/reflectionclass/construct.xml

Fix https://github.com/php/doc-en/issues/2421

Improve `ReflectionClass` example

---

reference/spl/iteratoriterator/construct.xml

Fix https://github.com/php/doc-en/issues/1144

[IteratorIterator] Add second constructor argument doc

---

reference/pcntl/functions/pcntl-rfork.xml

Fix https://github.com/php/doc-en/issues/2428

Add note about `pcntl_rfork` function availability

---

reference/libxml/setup.xml

Update libxml installation text

---

reference/xml/functions/xml-parser-get-option.xml
reference/xml/functions/xml-parser-set-option.xml

Fix https://github.com/php/doc-en/issues/2233

Improve `xml_parser_get/set_option` parameters section

---

reference/array/functions/array-diff-assoc.xml
reference/array/functions/array-diff-uassoc.xml

Fix https://github.com/php/doc-en/issues/2631

Fix examples for array diff functions

---

reference/datetime/functions/gmmktime.xml
reference/datetime/functions/mktime.xml

Fix https://github.com/php/doc-en/issues/2649

Add missing `mktime()` and `gmmktime()` return values

---

language-snippets.ent
reference/strings/functions/stripos.xml
reference/strings/functions/stristr.xml
reference/strings/functions/strpos.xml
reference/strings/functions/strrchr.xml
reference/strings/functions/strripos.xml
reference/strings/functions/strrpos.xml
reference/strings/functions/strstr.xml

Fix https://github.com/php/doc-en/issues/2639

Fix GH-2639: Mention empty needle in string functions

---

reference/spl/arrayobject.xml

Fix https://github.com/php/doc-en/issues/2484

Add a note about accessing dynamic properties in `ArrayObject`

---

language/predefined/traversable.xml

Fix https://github.com/php/doc-en/issues/2357

Fix GH-2357: improve `Traversable` page

---

reference/mysqli/mysqli_result/field-seek.xml

Moved from #1413.
Reference;
[`mysqli_close`](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_api.c#L282)
[`mysqli_stmt_close`](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_api.c#L1480)
[`mysqli_field_seek`](https://github.com/php/php-src/blob/master/ext/mysqli/mysqli_api.c#L810)

mysqli functions that always return true

---

reference/dom/book.xml

There's loadHTML(File) and saveHTML(File) to to load and save HTML documents. People use it for both XML and HTML.

Update DOM intro

---

language/predefined/throwable.xml

Fix `Throwable` labeled as class

---

reference/mysqli/constants.xml
reference/zip/constants.xml

Adding missing constant type information. And that's the last sync PR for now. :)

Synchronize predefined constants with stubs - part 4

---

reference/yar/yar_client/setopt.xml

add the description of yar-client new feature to the manual.
the details see :  https://github.com/laruence/yar/pull/167

feature:add yar http-proxy example

---

appendices/migration83/other-changes.xml

PHP 8.3.0 migration guide addition

---

language-snippets.ent

The former will be required for MT_RAND_PHP.

language-snippets: Add warn.deprecated.feature-8-3-0 and warn.deprecated.feature-8-3-0

---

reference/random/constants.xml
reference/random/functions/mt-srand.xml
reference/random/random/engine/mt19937/construct.xml

MT_RAND_PHP: Indicate deprecation

---

reference/random/random/randomizer/getfloat.xml

getFloat() is still in progress, but I wanted to send the stuff I already have and that is unlikely to change before continuing.

Randomizer::getFloat(): Expand documentation

---

reference/strings/functions/crypt.xml

see https://chat.stackoverflow.com/transcript/message/56738441#56738441

crypt: Improve comment in example

---

appendices/migration83/deprecated.xml

refs: [PEP387#soft-deprecation](https://peps.python.org/pep-0387/#soft-deprecation)

Clarified the meaning of soft deprecation

---

reference/hash/functions/hash-copy.xml

see 20dcfbb0dd7150cbe5dfd7903a3001229295c549

hash_copy: Unify with hash_*

---

reference/dom/domdocument/savexml.xml

Documentation for https://github.com/php/php-src/pull/11794

Document LIBXML_NOXMLDECL support

---

reference/strings/functions/strrchr.xml

edit example for strrchr (#2867)

---

appendices/migration56.xml
appendices/migration70.xml
appendices/migration71.xml
appendices/migration72.xml
appendices/migration73.xml
appendices/migration74.xml
appendices/migration80.xml
appendices/migration81.xml
appendices/migration82.xml
appendices/migration83.xml
contributors.xml
language/errors.xml
language/exceptions.xml
reference/datetime/formats.xml

Requires: https://github.com/php/phd/pull/82

Use new markup for indicating section should not be chunked

---

features/gc.xml

Fixes https://github.com/php/doc-en/issues/2882

Fixed deprecation warning for dynamic property creation

---

appendices/migration83/new-classes.xml

refs: https://github.com/php/doc-en/commit/71692b6f4cace8dca72a18ccd80d4cd7305e5d4e

Added Date/Time related new Error/Exception classes to migration83 guide

---

language/types/string.xml

Improve sentence grammar

---

appendices/migration83/new-features.xml

refs: https://github.com/php/php-src/pull/11351

Added fallback/default ini variable syntax change to migration83.

---

reference/intl/intlcalendar/setdate.xml
reference/intl/intlcalendar/setdatetime.xml

Ref: https://github.com/php/php-src/commit/f236eb83b4

[PHP 8.3] IntlCalendar setDate / setDateTime

---

reference/dom/domelement/toggleattribute.xml

The type of force is ?bool not bool.

Fix signature of DOMElement::toggleAttribute

---

reference/mongodb/bson/packedarray.xml
reference/mongodb/configure.xml
reference/mongodb/mongodb/driver/manager/addsubscriber.xml
reference/mongodb/mongodb/driver/monitoring/logsubscriber.xml
reference/mongodb/mongodb/driver/monitoring/logsubscriber/log.xml
reference/mongodb/monitoring.xml
reference/mongodb/versions.xml

https://jira.mongodb.org/browse/PHPC-2219
https://jira.mongodb.org/browse/PHPC-2180
https://jira.mongodb.org/browse/PHPC-2289
https://jira.mongodb.org/browse/PHPC-1017
https://jira.mongodb.org/browse/PHPC-2311
https://jira.mongodb.org/browse/PHPC-2280

Documentation updates for ext-mongodb 1.17

---

appendices/migration82/other-changes.xml

remove duplicate line

---

language-snippets.ent

This fix affects the folowing functions.
- posix_fpathconf
- posix_isatty
- posix_ttyname
refs: https://github.com/php/php-src/blob/PHP-8.3/ext/posix/posix.stub.php

fixed posix related fd signature

---

reference/math/functions/acos.xml
reference/math/functions/asin.xml
reference/math/functions/atan.xml

In accordance with @Girgias suggestions.
Closes #2976

Correction to variable name - for issue #2976

---

reference/pcre/functions/preg-match-all.xml

Currently these 2 phrases do no read that well. Adding these extra words will improve the readability of the docs.

Improve phrasing in preg-match-all.xml

---

reference/funchand/functions/unregister-tick-function.xml
reference/gmp/functions/gmp-divexact.xml

Correction to parameter name in gmp-divexact.xml

---

reference/ldap/functions/ldap-connect-wallet.xml
reference/ldap/functions/ldap-exop-sync.xml
reference/ldap/versions.xml

Undocumented, based on stubs:
- https://github.com/php/php-src/blob/PHP-8.3/ext/ldap/ldap.stub.php#L784
- https://github.com/php/php-src/blob/PHP-8.3/ext/ldap/ldap.stub.php#L615

[PHP 8.3] New LDAP functions

---

reference/zip/ziparchive/open.xml

I just noticed this while reading

Fix typo in article

---

reference/mysqli/mysqli_result/fetch-field-direct.xml

mysqli_result::fetch_field_direct correction to parameter name

---

reference/curl/functions/curl-setopt.xml
reference/memcached/ini.xml

When translating into another language, the question arises what does mean in English: "The timeout for Expect: 100-continue responses…"?!
A-a-ah! The timeout for «Expect: 100-continue» responses!

Curl setopt.xml

---

reference/mysql_xdevapi/examples.xml
reference/mysql_xdevapi/mysql_xdevapi/collection/modify.xml
reference/mysql_xdevapi/mysql_xdevapi/collection/remove.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionfind/execute.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionfind/fields.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionfind/groupby.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionfind/lockexclusive.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionfind/lockshared.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/arrayinsert.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/construct.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/patch.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/skip.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/sort.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionmodify/unset.xml
reference/mysql_xdevapi/mysql_xdevapi/collectionremove/construct.xml
reference/mysql_xdevapi/mysql_xdevapi/columnresult/construct.xml
reference/mysql_xdevapi/mysql_xdevapi/columnresult/isnumbersigned.xml
reference/mysql_xdevapi/mysql_xdevapi/schema/construct.xml
reference/mysql_xdevapi/mysql_xdevapi/schema/createcollection.xml
reference/mysql_xdevapi/mysql_xdevapi/schema/dropcollection.xml
reference/mysql_xdevapi/mysql_xdevapi/schema/existsindatabase.xml
reference/mysql_xdevapi/mysql_xdevapi/schema/getcollection.xml
reference/mysql_xdevapi/mysql_xdevapi/schema/getcollectionastable.xml
reference/mysql_xdevapi/mysql_xdevapi/session/sql.xml
reference/mysql_xdevapi/mysql_xdevapi/table/isview.xml

This fixes some typos, adds some tags, and tries to improve wording.

mysqli_xdevapi: fix typos/change wording

---

reference/dom/domnode/getlineno.xml

Very minor change, but I found the current wording unclear.

Clarify DOMNode::getLineNo()

---

reference/pgsql/constants.xml

The funcion pg_set_error_context_set_visibility() doesn't exists, probably typo

Amended of the pg_set_error_context_set_visibility() function name in pgsql/constants.xml

---

reference/fpm/status.xml

Update FPM status documentation

---

reference/pdo_ibm/ini.xml
reference/pdo_ibm/reference.xml

These are basically equivalent to the ibm_db2 versions.

Add PDO_IBM INI options

---

reference/libxml/libxmlerror.xml

Related to https://github.com/php/doc-en/issues/2162#issuecomment-1874577989

Fix LibXMLError class name

---

reference/sqlite3/book.xml
reference/sqlite3/sqlite3exception.xml
reference/sqlite3/versions.xml

Add documentation for SQLite3Exception (#2162).

Add SQLite3Exception documentation

---

reference/misc/functions/connection-status.xml

Fix GH-3103 connection_status(): Add link to constants

---

appendices/ini.list.xml
reference/outcontrol/ini.xml

Updated the default value and clarified when a hidden field is added to forms.

Update output control configuration page

---

appendices/ini.list.xml

Minor cleanup of ini.list as suggested [here](https://github.com/php/doc-en/pull/3098#discussion_r1449284764).

Cleanup of ini.list

---

reference/image/functions/imagecropauto.xml

imagecropauto: Fixing typo

---

language/namespaces.xml

The same as https://github.com/php/doc-en/pull/3117
Too noisy

Make namespaces to pure lsit

---

reference/classobj/functions/is-a.xml

How about adding parameter tag instead 'this'?

Update is-a.xml: paramter tag instead 'this'

---

reference/pdo/pdorow.xml

Adds more details to `PDORow`'s description as suggested [here](https://github.com/php/doc-en/pull/3059#pullrequestreview-1802030301).
@kamil-tekiela could you also take a look to make sure this covers everything?

Add details on PDORow

---

reference/mysqli/setup.xml
reference/pdo_mysql/reference.xml

See https://bugs.php.net/bug.php?id=79275
Fixes #3141

Clarify support for caching_sha2_password

---

reference/event/book.xml
reference/event/event/construct.xml
reference/event/eventbase/construct.xml
reference/event/eventbuffer/construct.xml
reference/event/eventbufferevent/construct.xml
reference/event/eventconfig/construct.xml
reference/event/eventdnsbase.xml
reference/event/eventdnsbase/construct.xml
reference/event/eventexception.xml
reference/event/eventhttp/construct.xml
reference/event/eventhttpconnection/construct.xml
reference/event/eventhttprequest/construct.xml
reference/event/eventlistener/construct.xml
reference/event/eventsslcontext/construct.xml
reference/event/eventutil/construct.xml

- Added EventException class.
- Updated description of the initialize parameter of the EventDnsBase::__construct

Updated Event docs

---

language-snippets.ent
reference/array/functions/array-udiff-assoc.xml
reference/array/functions/array-udiff-uassoc.xml
reference/array/functions/array-udiff.xml
reference/array/functions/array-uintersect-assoc.xml
reference/array/functions/array-uintersect-uassoc.xml
reference/array/functions/array-uintersect.xml

Fix GH-3003 (array_udiff(): Add precision to the comparison function)

---

reference/classobj/functions/property-exists.xml

Fix return value of property_exists

---

reference/inotify/functions/inotify-add-watch.xml
reference/inotify/functions/inotify-init.xml

Fix return type of inotify_add_watch(), inotify_init()

---

reference/misc/functions/defined.xml

Improve description of defined

---

reference/mysqli/mysqli_result/fetch-object.xml

Fixes #3153 
Change the comment of procedural style example from `associative` to `object`

Fix comment of mysqli_fetch_object

---

reference/filesystem/functions/fnmatch.xml

I added a table with details about `fnmatch` wildcards.

Improve documentation about fnmatch wildcards

---

reference/ps/constants.xml

Add constant IDs and tags to PS's constants.

Add PS constant IDs and tags

---

reference/svm/svm.xml
svm_constant_id.sh

There was a typo in the ID.
Bash script can be used to apply update to all translations.

Update SVM constant ID

---

language/predefined/weakmap.xml

`WeakMap` implements `IteratorAggregate` instead.

`WeakMap` does *not* implement `Iterator`

---

reference/array/functions/array-rand.xml

array_rand() may throw ValueError since 8.0

---

reference/strings/functions/strstr.xml

Upgrade note on strstr functions

---

language/control-structures/goto.xml

The label text is merges with the text of the documentation

goto.xml: add caption-tag to caption-text and combed examples

---

reference/pdo/pdo/construct.xml

Correction to comments in the examples.

Corrections to comments in PDO construct examples

---

reference/dom/domimplementation/hasfeature.xml

Fix broken code sample in DOMImplementation::hasfeature().

Fix DOMImplementation::hasfeature() example

---

reference/xlswriter/xlsx-format/align.xml
reference/xlswriter/xlsx-format/bold.xml
reference/xlswriter/xlsx-format/italic.xml
reference/xlswriter/xlsx-format/underline.xml
reference/xlswriter/xlsx-kernel/set-column.xml
reference/xlswriter/xlsx-kernel/set-row.xml

ref https://github.com/php/doc-es/issues/78

Fix xlswriter examples

---

appendices/migration83/incompatible.xml

https://github.com/php/php-src/issues/13866

Document number_format() $decimals change

---

reference/classobj/functions/class-alias.xml

As descibe PHP 8.3 [Upgrade notes](https://github.com/nielsdos/php-src/blob/436f00bce979a3200de6bb74e9e65683192f9acb/UPGRADING)

class-alias.xml: added note and change log for an internal classes

---

reference/stream/functions/stream-context-create.xml

Update code example to use php5.4 array syntax, change newline to standard unix vs windows line ending, add some spaces

Update example syntax in stream-context-create.xml

---

language/oop5/serialization.xml

serialization.xml: the abbreviation of a title must be abbreviation

---

reference/ffi/ffi.cdata.xml

Replacing char U+2013 by regular dash char U+002d.

Fix dash char in ffi.cdata

---

reference/outcontrol/functions/ob-start.xml

Fix GH-3399

---

reference/mongodb/mongodb/driver/manager/executebulkwrite.xml
reference/mongodb/mongodb/driver/manager/executecommand.xml
reference/mongodb/mongodb/driver/manager/executequery.xml
reference/mongodb/mongodb/driver/manager/executereadcommand.xml
reference/mongodb/mongodb/driver/manager/executereadwritecommand.xml
reference/mongodb/mongodb/driver/manager/executewritecommand.xml
reference/mongodb/mongodb/driver/server/executebulkwrite.xml
reference/mongodb/mongodb/driver/server/executecommand.xml
reference/mongodb/mongodb/driver/server/executequery.xml
reference/mongodb/mongodb/driver/server/executereadcommand.xml
reference/mongodb/mongodb/driver/server/executereadwritecommand.xml
reference/mongodb/mongodb/driver/server/executewritecommand.xml

https://jira.mongodb.org/browse/PHPC-2303

Clarify option inheritance for ext-mongodb execute methods

---

reference/ps/constants.xml

Words correction

---

language/control-structures/match.xml

Validation of operation of the example using Comparison Operators
https://onlinephp.io/c/a6825
Related to Spanish translation:
https://github.com/php/doc-es/pull/86

Add new example to match using comparison operators

---

reference/math/functions/fdiv.xml

I used name of operators from the doc: https://www.php.net/manual/en/language.operators.comparison.php

fdiv: improve note about comparisons

---

reference/strings/constants.xml

Add descriptions of the locale constants on the string constants page.

Add locale constant descriptions

---

reference/strings/constants.xml

This is a follow up to #3299 .

Add individual ABDAY, DAY, ABMON and MON constants

---

reference/xml/functions/xml-error-string.xml

see
php -r 'const XML_NS_ERR_UNDEFINED_NAMESPACE = 201; var_dump(xml_error_string(XML_NS_ERR_UNDEFINED_NAMESPACE));' string(7) "Unknown"

may also return "Unknown" if no description was found

---

appendices/migration82/other-changes.xml

Fixes GH-3223
I don't actually have the docs set up, so I'm not sure how well this will render. I will leave this up to the more experienced docs contributors. :slightly_smiling_face:

Clarify return value of strcmp() and friends

---

reference/pgsql/constants.xml

PostgreSQL reference found [here](https://postgrespro.com/docs/postgrespro/14/libpq-control#LIBPQ-PQSETERRORVERBOSITY).

Add PGSQL_ERRORS_SQLSTATE constant

---

reference/filesystem/constants.xml

Add descriptions to all PATHINFO constants.
Add constant_list role to variablelist.

Add PATHINFO_ALL constant

---

reference/filesystem/functions/fopen.xml

Or: add notice like: `…'1' (for the coercive typing mode only) or &true;…`

fopen.xml: remove the string '1' for the boolean parameter

---

reference/sockets/functions/socket-addrinfo-lookup.xml

socket-addrinfo-lookup.xml: to clarify the family of functions

---

reference/openssl/constants.xml

Partially related to https://github.com/php/doc-en/issues/3333.

Add OpenSSL constants

---

reference/datetime/constants.xml

Part of https://github.com/php/doc-en/issues/2747.

Add global DATE format constants to constants list

---

language/predefined/interfaces.xml
language/predefined/php-incomplete-class.xml
reference/igbinary/functions/igbinary-unserialize.xml
reference/var/functions/unserialize.xml

Add a page on `__PHP_Incomplete_Class`.

Add __PHP_Incomplete_Class

---

reference/strings/functions/trim.xml

```<?php
$string = "foo123bar";
var_dump(
trim($string, "a..z"), // 123
trim($string, "a..Z"), // Warning: trim(): Invalid '..'-range, '..'-range needs to be incrementing
);```

trim.xml: additionally describe the characters `parameter`

---

reference/math/functions/pow.xml

I don't think `pow()` can return an `object`?

Fix pow() return value section

---

install/windows/index.xml

See https://github.com/php/php-src/blob/f21947a7ae7ad7ec5f18c8e8c7a4a488b9150b66/UPGRADING#L630-L631.

Windows 7 is no longer supported as of PHP 8.3.0

---

appendices/history.xml

Could be fleshed out more, but I think this hits the high points.

Add history for PHP 6, 7, and 8 (#3358)

---

reference/varnish/setup.xml

…or `>=` to the `≥` mb-symbol, if more relevant

varnish/setup.xml: change the `>` character to the gt-mnemonic character

---

reference/hash/book.xml

Based on this comment by @cmb69:
https://github.com/php/doc-en/issues/3616#issuecomment-2254714040
Related to issue #3616.

Add more description for hash extension

---

reference/hash/book.xml

Moved early algorithm description to warning block

---

reference/mysqlinfo/concepts.xml
reference/mysqlinfo/set.xml

Adding database server examples that use the MySQL protocol (MariaDB, MySQL, Percona, TiDB) as per discussion https://github.com/php/doc-en/issues/3628

adding database server examples

---

appendices/extensions.xml
reference/gnupg/book.xml
reference/svn/book.xml

Includes fixing invalid states for gnupg and svn

Update extensions lists by status (fixes #3643)

---

reference/mongodb/bson.xml
reference/mongodb/mongodb.xml

Set extension-membership for MongoDB extensions

---

reference/ds/ds/sequence/apply.xml

change docs example from creating an object of Ds\Sequence which is an interface to Ds\Vector
[Docs Example link ](https://www.php.net/manual/en/ds-sequence.apply.php#refsect1-ds-sequence.apply-examples)

bugfix docs example

---

reference/datetime/functions/date.xml

The same as: https://github.com/php/doc-en/pull/3693

date.xml replace the `DateTime::format` method by interface method

---

language/types/integer.xml

I think this way it's more obvious what you're trying to show.

Update integer overflow example

---

language/types/integer.xml

There are two infinities: positive and negative. I think we should mention both, not just the positive one ;-)

integer.xml: wrap NaN, Inf and -Inf with the `literal` tag

---

reference/win32service/functions/win32-add-right-access-service.xml
reference/win32service/functions/win32-read-all-rights-access-service.xml
reference/win32service/functions/win32-read-right-access-service.xml
reference/win32service/rightinfo/get-rights.xml

Fix `contants` => `constants` in `win32service`

---

install/unix/apache2.xml

1. Added a comma after "Of course" for proper punctuation.
2. Added "for" to clarify the relationship between configuration options and the softwares (Apache and PHP).

Corrected a grammatical error

---

reference/win32service/rightinfo/construct.xml
reference/win32service/rightinfo/get-domain.xml
reference/win32service/rightinfo/get-full-username.xml
reference/win32service/rightinfo/get-rights.xml
reference/win32service/rightinfo/get-username.xml
reference/win32service/rightinfo/is-grant-access.xml
reference/win32service/win32servicerightinfo.xml

* Add `getFullUsername` documentation
* Fix return type for `getUsername` and `getDomain`

Fix Win32Service documentation

---

reference/mongodb/mongodb/driver/monitoring/commandfailedevent/gethost.xml
reference/mongodb/mongodb/driver/monitoring/commandfailedevent/getport.xml
reference/mongodb/mongodb/driver/monitoring/commandfailedevent/getserver.xml
reference/mongodb/mongodb/driver/monitoring/commandstartedevent/gethost.xml
reference/mongodb/mongodb/driver/monitoring/commandstartedevent/getport.xml
reference/mongodb/mongodb/driver/monitoring/commandstartedevent/getserver.xml
reference/mongodb/mongodb/driver/monitoring/commandsucceededevent/gethost.xml
reference/mongodb/mongodb/driver/monitoring/commandsucceededevent/getport.xml
reference/mongodb/mongodb/driver/monitoring/commandsucceededevent/getserver.xml
reference/mongodb/versions.xml

https://jira.mongodb.org/browse/PHPC-2442

Deprecate getServer and add getHost and getPort to command event classes

---

install/unix/apache2.xml

I did not change the text, I only changed:
* Amend an XML markup (for the most part, the indentation were corrected)
* Removed the extra space characters (double spaces)
* Added tags: `command`, `literal`, `filename`

apache2.xml: amend the XML markup

---

chapters/intro.xml

I think the sentence `writing simple scripts in a few hours` is misleading and detrimental to our message that starting with PHP is easy. 
I can copy and paste the example on the page and I already have a PHP script.
I'd like to propose we change it to something a little more motivational for a new comer.
> With PHP, you can get up and running and be writing simple scripts in no time at all.

Change onboarding duration

---

reference/datetime/datetimeinterface/diff.xml

Added info about `absolute` parameter and returned property `invert` of `DateInterval` object.

Added info about invert property

---

language/control-structures/include-once.xml

`include_once` is an expression since it returns a value. See #369

`include_once` is not a statement but an expression

---

install/unix/source.xml

A chapter with three tiny sections is annoying.

Change reference from installation.problems to faq.installation

---

reference/strings/functions/wordwrap.xml

https://stackoverflow.com/questions/1273693/why-is-u-used-to-designate-a-unicode-code-point

wordwrap.xml Add errors/changelog sections, specify U+0020 instead U+20

---

reference/mongodb/mongodb/driver/session/committransaction.xml

Correction of typo in value string.

MongoDB committransaction: Typo correction

---

language/variables.xml

I have removed false information and clarified the concepts described on the page. I have added some new information too.

Refactor Language variables section basics

---

reference/yaml/functions/yaml-parse-url.xml

Parameter name is `url` for this method.

yaml-parse-url.xml: Fix parameter name

---

appendices/reserved.constants.core.xml

Added via https://github.com/php/php-src/pull/13363

Add PHP_SBINDIR (PHP-8.4)

---

reference/mysqli/mysqli/change-user.xml

I opened a bug report https://github.com/php/php-src/issues/10382 but then I realized that I was actually confused by the documentation. I tried to explain it better and also provide clearer code examples. The function works how it was designed, but the documentation was unclear.

Improve documentation for mysqli_change_user

---

language/generators.xml

Follow up from #1285. 
I welcome any input. I know this can be worded better, but I also agree with @nikic that the current wording isn't ambiguous. 
I hope it also appeases @colshrapnel who wrote this article https://phpdelusions.net/articles/generators

Better wording for generators

---

reference/ftp/configure.xml
reference/mysqlnd/install.xml

Added to php-src 8.4 via https://github.com/php/php-src/pull/14028

Document --with-ftp-ssl and --with-mysqlnd-ssl configure options

---

install/cloud/azure.xml

This file may need also be fully re-indented.

Remove example linked link in favor of literal

---

appendices/migration84/new-features.xml

Just the stock standard example, really.

Add migration example of property hooks.

---

reference/dom/domxpath.xml

Is this useful to document? No idea.

Document clone behaviour of DOMXPath

---

appendices/migration84/new-features.xml

Expand upon DOM section in PHP 8.4 new features

---

language-snippets.ent

Maybe we can explain what these numbers mean and get rid of the excessive number of parentheses? :)

language-snippets.ent Explain the meaning of nums and add tags

---

reference/curl/functions/curl-multi-select.xml

...and clarify number of which descriptors are returned

curl-multi-select.xml Replace `curl_multi` to `cURL multi handle`

---

reference/spl/arrayobject/getiterator.xml

Can we specify which iterator is created using this method? This will also link the method and the specific iterator

getiterator.xml Specify the exact classname for the new iterator

---

reference/strings/functions/htmlentities.xml

see https://github.com/php/doc-en/issues/2405

fix example as it's not valid as of php 8.1

---

appendices/resources.xml

Based on comment: https://www.php.net/manual/en/resource.php#128764

Document 'process' resource type

---

reference/stream/constants.xml

This organizes the constants into dedicated lists relevant to their usage.
There are some to-dos about things I noticed while I reworked this page.

Rework stream constants page

---

language/oop5/basic.xml

New feature in core mentioned in #3872
https://wiki.php.net/rfc/new_without_parentheses

Add documentation for new MyClass()->method() without parentheses

---

reference/array/functions/array.xml

see https://github.com/php/doc-en/issues/3841

explain short syntax in arrays

---

reference/array/functions/list.xml

see https://github.com/php/doc-en/issues/1753

explain shorthand syntax

---

language/types.xml
language/types/type-system.xml
reference/var/functions/is-scalar.xml

Initial take for issue #3939.
It made me go through all of the types documented on the type-system page, and this may be more than what the issue originally asks for. In which case, I can do a simpler attempt. Parts of this may be confusing or simply wrong too, if so, please correct me or let me know. This was a sort of a recap of theory and a categorization exercise which I may have failed : )

Document what's considered as a scalar type

---

reference/filesystem/constants.xml

And add title to indicate with what functions they are used.
Also stop using tables, as I don't think it brings much value in these cases.

Group related filesystems constants together

---

reference/mysqli/versions.xml

Add MySQLi deprecations to `versions.xml`

---

reference/snmp/snmp/construct.xml

Maybe we should add some known information to the description of the method?

SNMP construct.xml Slightly complete the description

---

reference/var/functions/is-scalar.xml

The function 'is_scalar` can check the scalarity of not only variables, as the manual claims, but also other expressions
```
<?php
var_dump(
is_scalar(1),
is_scalar([]),
is_scalar(new stdClass()),
is_scalar(list(0 => $name) = ['Bob']),
is_scalar(1 > 2),
// etc.
);
```

is-scalar.xml Give a more precise formulation

---

language/oop5/final.xml

Sorry for the small change.
Would you mind fixing the inconsistent tag nesting and indentation levels?

fix(language/oop5/final): indent level

---

README.md

This changeset fixes broken links found in the README.

Broken link fixes

---

reference/yaf/yaf_response_abstract/appendbody.xml

https://github.com/php/doc-zh/issues/935

fix typo in Yaf_Response_Abstract::appendBody

---

reference/reflection/reflectionclassconstant/gettype.xml
reference/reflection/reflectionclassconstant/hastype.xml
reference/reflection/reflectionparameter/ispromoted.xml
reference/reflection/versions.xml

Reflection document missing methods

---

reference/curl/constants_curl_setopt.xml
reference/mysqli/constants.xml

Found via a new documentation tool I am working on.

MySQLi: Fix incorrect XML IDs for constant linking

---

reference/sockets/functions/socket-create-listen.xml

This was changed in db22a7cfcbc3af221f67e228336ac3e2d62aaf2c already

Add changelog for sockets PHP 8.4 change

---

language/operators/arithmetic.xml

Add tags for arithmetic operator page

---

language/oop5/visibility.xml

Clarify spacing in aviz (or lack thereof).

---

reference/filter/ini.xml

Remove personalization, add warning about deprecation

Filter: Rewrite INI page

---

reference/password/constants.xml

Also remove personalization while at it

Fix PASSWORD_DEFAULT constant type

---

reference/sockets/constants.xml

[PHP 8.4] Fix sockets constants update

---

reference/spl/arrayobject/append.xml
reference/spl/arrayobject/construct.xml
reference/spl/arrayobject/exchangearray.xml
reference/spl/arrayobject/getarraycopy.xml
reference/spl/arrayobject/natcasesort.xml
reference/spl/arrayobject/natsort.xml
reference/spl/arrayobject/offsetset.xml
reference/spl/arrayobject/offsetunset.xml
reference/spl/arrayobject/setflags.xml
reference/spl/arrayobject/setiteratorclass.xml
reference/spl/arrayobject/uasort.xml

This changed in PHP 5.3 so I think it's time to update it.

Change output of ArrayObject

---

reference/reflection/reflectionattribute.xml
reference/reflection/reflectionclass.xml
reference/reflection/reflectionclassconstant.xml
reference/reflection/reflectionfunction.xml
reference/reflection/reflectionmethod.xml
reference/reflection/reflectionproperty.xml

[PHP 8.4] Add class constant types for `Reflection`

---

features/commandline.xml

[PHP 8.4] Mention `PHP_HISTFILE` env var

---

language/predefined/weakreference.xml

[PHP 8.4] Update `WeakReference::__debugInfo()` changelog

---

language/predefined/closure.xml

[PHP 8.4] Update `Closure::__debugInfo()` changelog

---

reference/mbstring/functions/mb-split.xml
reference/mbstring/functions/mb-str-split.xml
reference/pcre/functions/preg-split.xml

Cross-ref explode in some functions

---

reference/filesystem/functions/fseek.xml

Add warning about fseek()'s return values

---

language/oop5/traits.xml

Make a new trait example

---

appendices/migration84/new-features.xml

@Girgias  What do I need to do to make the documenation compile again locally. I keep getting this:
```
ERROR (file:///D:/projects/en/reference/pdo_pgsql/pdo-pgsql.xml:193:42)
&reference.pdo-pgsql.pdo.entities.pgsql;
------------------------------------------^
Entity 'reference.pdo-pgsql.pdo.entities.pgsql' not defined
```

Improve new Pdo 8.4 changes

---

reference/var/functions/is-callable.xml

Improve example: is_callable() and constructors

---

language/oop5/traits.xml

This overrides the PR #4188
cc @alexandre-daubois

Improve information on Traits page

---

language/oop5/property-hooks.xml

Fix missing space

---

reference/fpm/status.xml

Documente new (8.4) status field for memory peak.

Document FPM memory peak status field

---

reference/image/functions/imagefilledpolygon.xml
reference/image/functions/imageopenpolygon.xml
reference/image/functions/imagepolygon.xml

Example of update image functions

---

reference/gmp/gmp/construct.xml

This, and https://github.com/php/doc-it/issues/55 fixes `doc-it` into a building state.

[skip-revcheck] Remove xi:fallback, partial fix for doc-it

---

language/enumerations.xml

As called out by a comment, that I have since deleted as this PR will resolve it.

Minor corection to enum traits.

---

reference/outcontrol/functions/output-add-rewrite-var.xml

Document the bugfix of php/php-src/pull/13294. This is a part of https://github.com/php/doc-en/issues/3872.

Document output_add_rewrite_var() url_rewriter.hosts bugfix

---

reference/outcontrol/functions/ob-start.xml

Document the change made in php/php-src/pull/13087. This is a part of https://github.com/php/doc-en/issues/3872.

Document ob_start() change

---

language-snippets.ent
reference/pdo_odbc/reference.xml
reference/uodbc/functions/odbc-connect.xml
reference/uodbc/functions/odbc-pconnect.xml

Related changes https://github.com/php/php-src/commit/bbe122295672320abe121998fc80fc76d383284b

Updated pdo_odbc, odbc_connect and odbc_pconnect

---

language/basic-syntax.xml
language/constants.xml
language/enumerations.xml
language/exceptions.xml
language/expressions.xml
language/functions.xml
language/namespaces.xml
language/references.xml
language/variables.xml

Fix double space in languague folder

fix double space

---

language/variables.xml

Formatting &example.outputs; in language.variables.variable.php,  Example #1 Variable property example

Formatting &example.outputs; in language.variables.variable.php,

---

appendices/ini.core.xml

No meaning changed; I just worded it a little better.

English grammar corrections

---

language/oop5/changelog.xml

Add Property Hooks changelog

---

.github/ISSUE_TEMPLATE/bug-issue.md
.github/ISSUE_TEMPLATE/documentation-issue.md

If you have any ideas for question templates or things to change to make things clearer or more manageable for labels or the like, let me know :)

add issue templates bug + documentation

---

reference/password/functions/password-hash.xml

Fix cost calculation in password hash output

---

reference/mongodb/configure.xml

* Add note about pkgconf and openssl being required
* Mention shivammathur/extensions tap containing the latest version

Update installation instructions for MacOS

---

.github/ISSUE_TEMPLATE/bug-issue.md
.github/ISSUE_TEMPLATE/documentation-issue.md

This pull request includes minor changes to the issue templates to simplify the titles for bug reports and documentation improvements.
[PR#4457](https://github.com/php/doc-en/pull/4457)
Thanks for your review @TimWolla

fix review issue template github

---

reference/ldap/functions/ldap-set-option.xml

See https://github.com/php/php-src/issues/12081

ldap: add notice about TLS options

---

reference/reflection/versions.xml

Fix missing propertyhooktype version info

---

reference/gmagick/gmagick/setcompressionquality.xml
reference/imagick/imagick/colormatriximage.xml
reference/lua/lua/construct.xml
reference/mongodb/mongodb/driver/cursor/getid.xml
reference/simdjson/functions/simdjson-is-valid.xml
reference/stream/streamwrapper/stream-seek.xml

Remove <initializer> from required params

---

appendices/reserved.xml

- Fix style of `foreach`
- Add `__PROPERTY__`
- Better link for magic constants
- Respect `cols="5"`

Update reserved words

---

reference/intl/idn/idn-to-ascii.xml

Page: https://www.php.net/manual/en/function.idn-to-ascii.php
This would close https://bugs.php.net/bug.php?id=80922

Update idn-to-ascii.xml: Adding info about conversion to lowercase

---

reference/random/functions/mt-rand.xml

`mt_rand()` may throw ValueError since PHP 8.0

---

reference/errorfunc/functions/get-error-handler.xml
reference/errorfunc/functions/get-exception-handler.xml

Followup of #4567 to address post-merge comments

Followup "Document get_error_handler(), get_exception_handler()"

---

reference/imagick/imagick/profileimage.xml
reference/swoole/swoole/table/column.xml
reference/swoole/swoole/table/create.xml
reference/swoole/swoole/table/decr.xml
reference/swoole/swoole/table/del.xml
reference/swoole/swoole/table/destroy.xml
reference/swoole/swoole/table/get.xml
reference/swoole/swoole/table/incr.xml
reference/swoole/swoole/table/key.xml
reference/swoole/swoole/table/next.xml
reference/swoole/swoole/table/set.xml

Update Swoole\Table method

---

appendices/migration84/new-functions.xml

Remove duplicate new function for 84

---

appendices/migration84/new-functions.xml

https://github.com/php/php-src/blob/3cb7d1bd8ac352d7c97237e509da3b4c1db1aed8/ext/intl/timezone/timezone.stub.php#L119

Fix class for getIanaID method

---

language/types/string.xml

Rephrased advice in Heredoc string example 6

---

reference/errorfunc/constants.xml

Fix E_ALL constant value

---

reference/json/functions/json-last-error-msg.xml

Update json-last-error-msg.xml - json_validate()

---

appendices/examples.xml
reference/dio/functions/dio-tcsetattr.xml
reference/enchant/functions/enchant-broker-request-dict.xml
reference/enchant/functions/enchant-dict-add.xml
reference/enchant/functions/enchant-dict-describe.xml
reference/enchant/functions/enchant-dict-suggest.xml
reference/filter/constants.xml
reference/intl/intlcalendar/fromdatetime.xml
reference/intl/numberformatter/format.xml
reference/intl/numberformatter/get-error-code.xml

Note that issue 30 was fixed by https://github.com/php/doc-base/commit/b255d4570f3d60a02a70e4c9f2ed0257aeeca542
And issues 68-81 were fixed by deleting the respective user notes.
The new appendix will require a change in doc-base to be included in the rendered documentation, but I want to get wording checked.

Audit review

---

reference/sodium/functions/sodium-crypto-aead-xchacha20poly1305-ietf-decrypt.xml

Fix reference to encryption function

---

reference/reflection/reflectionclass/innamespace.xml
reference/reflection/reflectionclass/isabstract.xml
reference/reflection/reflectionclass/isanonymous.xml
reference/reflection/reflectionclass/isfinal.xml
reference/reflection/reflectionclass/isinstance.xml
reference/reflection/reflectionclass/isinstantiable.xml
reference/reflection/reflectionclass/isinterface.xml
reference/reflection/reflectionclass/isinternal.xml
reference/reflection/reflectionclass/isiterable.xml
reference/reflection/reflectionclass/issubclassof.xml

Fix issue [https://github.com/php/doc-en/issues/4601](url)
Resolves #4601 
[--Ed]

Update doc for reflection class is methods

---

language/operators.xml
language/operators/functional.xml

Most of the text and examples here are pulled straight from the RFC.

Document the pipe operator.
