php/doc-en

reference/exec/functions/escapeshellcmd.xml

It is a known issue that spaces are not escaped in shell commands, which can be especially problematic on Windows.
This adds a warning about this behaviour to the function, including a way to solve this in userland code.
Ref: https://bugs.php.net/bug.php?id=43261 (last two comments)
Also see: https://github.com/squizlabs/PHP_CodeSniffer/pull/3214

escapeshellcmd: add warning about spaces in paths on Windows

---

language/oop5/traits.xml

As of PHP 8.0, `abstract private` methods are allowed in `trait`s. `abstract public` method were previously already supported.
Also see: https://3v4l.org/eQY8v and https://3v4l.org/HKLcI

Language Ref/Traits: fix incorrect information about abstract methods

---

language-snippets.ent
reference/mysqli/mysqli_result/fetch-all.xml

This page was missing an example. I have created a simple example with a single fetch mode. 
While I was at it I read the note about mysqlnd. I have spent more time than I care to admit trying to understand what it said. As a result, I decided to remove it. It might be technically correct; processing the data row by row will use less memory as long as you discard the previous row every iteration. This is a no-brainer. But people looking at fetch_all are interested in fetching all of the data into an array, in which case fetch_all is a perfect choice. I removed the note because it was comparing apples to oranges and I couldn't find any sensible way to rewrite it and still make sense. If we compare apples to apples, then fetch_all consumes the same amount of memory and is faster. 
The …

Updating mysqli: fetch_all

---

reference/mysqli/mysqli_stmt/bind-param.xml

This PR aims to improve examples for parameter binding. The existing examples were simplified to show only the important bits, and a new example was added to show how to bind values from arrays. 
I moved variable assignment before prepare() but I am having second thoughts now. Some people are unaware of how binding by reference works, so creating them after bind_param() in the example makes sense. 
I am not sure about the second-last commit cebb442e040d063cbb8af572a36ca23e91c17159. If the PR is better without it, then we can drop it.

Updating mysqli: bind_param

---

language/references.xml

This had a stray ")", and was left with a misleading half-sentence
about "new" returning a reference, which it doesn't.

Fix half-deleted sentence about "new" and reference assignment

---

language/operators.xml

- explain why associativity is not applicable to unary operators
- distinguish between unary and binary `+`/`-`
- add some missing reference links
- update the precedence of string concatenation for PHP 8
- fix "(n/a)" ("not applicable") to "non-associative" for ternary
References:
- https://github.com/php/php-src/blob/master/Zend/zend_ast.c
(search "Operator Precedence")
- https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y
(search "precedence")
(NOTE: in opposite order)

Fix/update operators.precedence

---

reference/filesystem/functions/file.xml
reference/xml/functions/xml-parse-into-struct.xml
reference/zlib/functions/gzencode.xml

This is a weirdly inefficient way of getting a file's content into
a string, and I'm not sure why anyone would think it was a good
idea.

Remove or rewrite examples using implode("", file(...))

---

language/attributes.xml

The method `targetDirectoryExists` in the attributes overview example emits **E_WARNING** if `$targetDirectory` already exists. This PR fixes this issue by wrapping the `mkdir` call in an `is_dir` check. 
https://github.com/php/doc-en/blob/68a416eeb74a6df5b7e31b77cfa5e91a4c368844/language/attributes.xml#L69-L72

Fix attributes overview example emitting E_WARNING

---

reference/mbstring/functions/mb-detect-encoding.xml
reference/mbstring/ini.xml

- People expect this function to work miracles. Add some examples of why that's not possible. Hat tip to this FAQ for the cipher  comparison: https://chardet.readthedocs.io/en/latest/faq.html
- The strict parameter wasn't really explained at all. I *think* this is what it actually does.
- General expansion and grammar fixes (I suspect the original author didn't speak English as a first language, which makes sense since the mbstring extension originated in Japan).

Expand documentation for mb_detect_encoding

---

appendices/migration80/deprecated.xml
reference/libxml/functions/libxml-disable-entity-loader.xml

The current text in the migration guide about the deprecation of `libxml_disable_entity_loader()` is misleading and can easily lead to the introduction of XXE vulnerable code.
In select circumstances, when `LIBXML_NOENT` is used, code can still be vulnerable to XXE attacks, even on PHP 8.0.
So I'm proposing to add an appropriate warning and mention the upgrade path in the migration guide.
Includes fixing a typo on the `libxml_disable_entity_loader()` page.

PHP 8.0 migration/deprecated: expand on libxml_disable_entity_loader()

---

reference/filter/filters.xml

We found the description for the filter `FILTER_SANITIZE_STRING` misleading. It says in https://www.php.net/manual/en/filter.filters.sanitize.php:
> Strip tags, optionally strip or encode special characters.
But apart from removing tags, this filter also encodes quotes.
Example: 
``` php
<?php
echo filter_var("'\"", FILTER_SANITIZE_STRING);
// >> &#39;&#34;
```
This seems to be the result of the following line in the sourcecode: 
https://github.com/php/php-src/blob/0236bbc777e8ef1c72a5bb6b88bfc5f843627eab/ext/filter/sanitizing_filters.c#L194
As this behavior is undocumented and led to some confusion, we propose to modify the documentation to better reflect this behavior.

Undocumented behavior in FILTER_SANITIZE_STRING

---

reference/strings/functions/echo.xml
reference/strings/functions/print.xml

Replaced two instances of
> .. not a function but a language language construct.
To
> .. not a function but a language construct.

Fix double "language"

---

language/types/array.xml
language/types/string.xml

The documentation still states that array/string curly brace access is possible but this was deprecated as of PHP 7.4 as per this RFC: https://wiki.php.net/rfc/deprecate_curly_braces_array_access
As of PHP 8.0.0 this syntax is no longer supported. This PR specifies the changes in support for this syntax. I did think about removing these notes altogether but thought they'd still have value for people working with, or migrating, older code.
By the way, this is my first time contributing to any official PHP project so please let me know if there's a different process I should be following or if any actions need to be taken before contributing.

Updated string & array curly brace access with support notice

---

language/predefined/exception/getprevious.xml

Screenshots: [Exception](https://user-images.githubusercontent.com/7404452/116270481-6a3d0080-a77f-11eb-84ab-9526a25b8f35.png) vs [Error](https://user-images.githubusercontent.com/7404452/116270556-7e80fd80-a77f-11eb-91ce-caed714e7128.png)

Fix missing space between `public` and `getPrevious` in Exception class synopsis

---

language-snippets.ent
reference/array/functions/count.xml

This PR adds the **TypeError** `count()` now throws to the changelog, and also updates the example showing that PHP 8.0 throws a **TypeError** instead of emitting and **E_WARNING**.
First time adding to a changelog, so not 100% sure if the versions are displayed in descending order or ascending. 🤔&nbsp; Will change if requested.

[80999] Fix count TypeError not documented

---

reference/fileinfo/configure.xml
reference/fileinfo/setup.xml
reference/sphinx/setup.xml

Basic fixes that I saw when updating the FR translation.
There are still many pages which still have references to PHP 5 although said file has been touched.
I might do another pass on the whole documentation when I'm caught up with the updating the French version.

Cleanup after PHP 5 mention removal

---

reference/strings/functions/explode.xml

This PR updates the `<note>` about return values if the start or end of `$string` contains a **separator** value. Also updated the changelog since `explode` now throws a `TypeError` when `$separator` is an empty string.
Personally don't think adding an example regarding the return value would be necessary here. `explode` already has *3* examples, *2* with outputs - and a `<note>` about it being binary-safe, so it would be a bit much IMHO. Therefore I opted to update the return values `<note>` instead.
Also, should the **changelog** be added before **notes** or after? I know it's usually after **examples** and before **seealso**, but not sure where the position should be in regards to **notes**.

[80975] Fix: Doc incomplete - explode

---

reference/array/functions/count.xml

After the discussion in #558 about the **changelog** location, I noticed the **changelog** for `count` function was in the wrong section, currently located *below* the **examples**. This PR moves the **changelog** to the correct place above the **examples**.

Fix `count` changelog being in wrong section.

---

reference/spl/versions.xml

- Generated verions.xml based on the following stubs.
* https://github.com/php/php-src/blob/PHP-8.0/Zend/zend_interfaces.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/Zend/zend_exceptions.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/spl/spl_observer.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/spl/spl_directory.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/spl/spl_array.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/spl/php_spl.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/spl/spl_heap.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/spl/spl_dllist.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/spl/spl_iterators.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/spl/spl_fixedarray.stub. …

Added PHP 8 into versions.xml for spl based on stubs.

---

reference/zlib/functions/zlib-get-coding-type.xml

The given issue this pull request fixes were found by the following script: [section-order.php](https://gist.github.com/Girgias/885fa1622511fc72afec3dd026748e5b).

Add missing parameters section to zlib-get-coding-type.xml

---

reference/zip/ziparchive/registercancelcallback.xml
reference/zip/ziparchive/registerprogresscallback.xml
reference/zip/ziparchive/setencryptionindex.xml

This PR fixes `notes` being in the wrong order for reference/zip, with them being before `examples` and or `changelog` sections.

Fix notes section being in wrong order for reference/zip

---

reference/xsl/xsltprocessor/hasexsltsupport.xml

This PR adds missing `parameters` section to `XSLTProcessor::hasExsltSupport`.

Add missing parameters section to XSLTProcessor::hasExsltSupport

---

reference/xml/functions/xml-get-current-byte-index.xml
reference/xml/functions/xml-set-default-handler.xml

This PR fixes `xml_set_default_handler` and `xml_get_current_byte_index` having sections out-of-order.

Fix two `xml` functions having section out-of-order.

---

reference/xmlrpc/functions/xmlrpc-set-type.xml

This PR moves `xmlrpc_set_type` errors section to it's correct place.

Fix xmlrpc_set_type errors section being out-of-order

---

reference/xmlreader/xmlreader/close.xml
reference/xmlreader/xmlreader/isvalid.xml
reference/xmlreader/xmlreader/movetoelement.xml
reference/xmlreader/xmlreader/movetofirstattribute.xml
reference/xmlreader/xmlreader/movetonextattribute.xml
reference/xmlreader/xmlreader/read.xml

This PR solves the issues of some `XMLReader` methods not having any parameter sections. While they don't accept any arguments, this fact should still be documented correctly, similar to other methods and functions.

Add missing parameter sections to XMLReader methods

---

reference/uopz/functions/uopz-set-mock.xml
reference/uopz/functions/uopz-unset-mock.xml

Fix `uopz_unset_mock`, `uopz_set_mock` No returnvalues sections, both was missing void return values sections.

Fix two uopz functions having no returnvalues sections

---

reference/mbstring/functions/mb-convert-encoding.xml

`mb_convert_encoding` now throws `ValueError` if either `$to_encoding` or `$from_encoding` are passed an invalid encoding. Looking at other changelogs, I'm guessing this is the correct way to add multiple changes to one version?
Added an `errors` section to indicate the old and new behavior - since previous to PHP 8.0, this function did emit a warning when supplied invalid encoding types, as demonstrated in this [3v4l demo](https://3v4l.org/5cErI).

[80671] Update `mb_convert_encoding`.

---

reference/ui/functions/ui.draw.text.font.fontfamilies.xml

This PR is frankly a little unnecessary since `description` section already says what's returned, but technically should be in the missing `returnvalues` section. 🤷‍♂️

Fix `fontFamilies` No returnvalues sections

---

reference/var/functions/get-defined-vars.xml
reference/var/functions/gettype.xml
reference/var/functions/is-object.xml
reference/var/functions/print-r.xml

This PR fixes some issues found in `reference/var`. Mainly sections out-of-order, and `get_defined_var` not having a parameters section.

Clean up various variable handling functions.

---

reference/yac/yac/construct.xml

This PR adds back the missing `returnvalues` section and adds a new `errors` section indicating what causes the constructor to throw an exception. @laruence could possibly confirm if this PR and the #569 PR are correct in terms of return values and expectations.
Note: Not sure if `<constant>` is a valid way to target constants in a package, see line 48 in PR.

Fix Yac::__construct documentation.

---

language/oop5/variance.xml
language/types/iterable.xml

Makes more sense to group it together but we lose the example.

Move iterable variance section to OOP section

---

reference/zookeeper/functions/zookeeper_dispatch.xml
reference/zookeeper/zookeeper/close.xml
reference/zookeeper/zookeeper/connect.xml
reference/zookeeper/zookeeper/construct.xml
reference/zookeeper/zookeeper/getclientid.xml
reference/zookeeper/zookeeper/getconfig.xml
reference/zookeeper/zookeeper/getrecvtimeout.xml
reference/zookeeper/zookeeper/getstate.xml
reference/zookeeper/zookeeper/isrecoverable.xml
reference/zookeeper/zookeeperconfig/add.xml
reference/zookeeper/zookeeperconfig/remove.xml
reference/zookeeper/zookeeperconfig/set.xml

This PR adds missing `parameters` and `returnvalues` sections to [zookeeper](https://github.com/php/doc-en/tree/HEAD/reference/zookeeper) documentation. Default **no parameter** and **void return** sections have been added.

Add missing sections to zookeeper documentation

---

reference/pdo/versions.xml

- Generated verions.xml based on the following stubs.
* https://github.com/php/php-src/blob/PHP-8.0/ext/pdo/pdo.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/pdo/pdo_stmt.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/pdo/pdo_dbh.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/pdo_pgsql/pgsql_driver.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/pdo_sqlite/sqlite_driver.stub.php
- Note
* I did not change PECL specific function and methods.
- `pdo::cubrid_schema`
- `pdo_user*`
- `pdo_* dsn`
- `pdostatement::fetchsingle`
* Not unsure the following is implemented in PHP 8.
- `pdo::__sleep`
- `pdo::__wakeup`
- `pdostatement::__sleep`
- `pdostatement::__wakeup`

Added PHP 8 into versions.xml for pdo based on stubs.

---

reference/intl/versions.xml

- Generated verions.xml based on the following stubs.
* https://github.com/php/php-src/blob/PHP-8.0/ext/intl/formatter/formatter.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/intl/normalizer/normalizer.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/intl/php_intl.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/intl/spoofchecker/spoofchecker.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/intl/breakiterator/breakiterator.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/intl/timezone/timezone.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/intl/transliterator/transliterator.stub.php
* https://github.com/php/php-src/blob/PHP-8.0/ext/intl/msgformat/msgformat.stub.php
* …

Added PHP 8 into versions.xml for intl based on stubs.

---

reference/openssl/functions/openssl-pkcs7-read.xml

The input shall be a string data.
Basic example along with the error cases.
Fix: related to, https://github.com/php/php-src/commit/bb0107b63dec8de5b0f3c3f535d3c52c2decda28

Improve openssl-pkcs7-read - fix arguments

---

appendices/migration80/deprecated.xml

Just removing an extra full stop before a constant name.
Follow-up to f3b5475 / #528.

Remove extra full stop

---

reference/reflection/reflectionfunctionabstract/getparameters.xml
reference/reflection/reflectionnamedtype/isbuiltin.xml
reference/reflection/reflectionparameter/getclass.xml
reference/reflection/reflectionparameter/gettype.xml
reference/reflection/reflectionparameter/isarray.xml
reference/reflection/reflectionparameter/iscallable.xml

Considerable chunks of the ReflectionParameter class are marked as deprecated with no indication of what to do instead.  After some experimentation (while trying to remove the deprecated stuff from TYPO3), I offer the following "do this instead" options.  And some other commentary and improvement along the way.
I'm not 100% sure my XML structuring is right.  Let me know what I should do instead and I'll adjust accordingly.

Reflection deprecation

---

appendices/migration73/other-changes.xml
reference/errorfunc/ini.xml
reference/network/functions/syslog.xml

https://github.com/php/php-src/pull/4265 restored the previous handling of multi-line log messages by adding `syslog.filter=raw`.
Relates to https://bugs.php.net/bug.php?id=77913

Documenting the changes to syslog.filter

---

reference/sqlite3/sqlite3/setauthorizer.xml

5th and 6th parameter description is wrong, because they are copy-and-pasted from the following C interface manual page[*1].
In PHP world, we use only 5 parameters as an Authorizer callback[*2].
[*1] https://www.sqlite.org/c3ref/c_alter_table.html
[*2] https://github.com/php/php-src/blob/php-8.0.0/ext/sqlite3/sqlite3.c#L2077-L2126

fixed SQLite3::setAuthorizer parameter order description.

---

language/oop5/interfaces.xml

I deleted nearly all of the comments on this page and replaced them with this PR.  Most changes are based on comments that I felt were worth mentioning in some way, but not as a comment.  There's also one or two that may have been true in PHP 5.1 but are no longer true now, like the constructor mention, or coding style conventions.

Fold comments into interfaces page

---

reference/dom/versions.xml

Generated verions.xml based on the following stubs.
- https://github.com/php/php-src/blob/PHP-8.0/ext/dom/php_dom.stub.php
- Note
* the following methods not implemented in PHP-8.0.
- domdocument
* `domdocument::renamenode`
- domimplementation
* `domimplementation::source_get_domimplementations`
* `domimplementation::source_get_domimplementation`
* `domimplementation::listitem`
- domnamednodemap
* `domnamednodemap::removenameditem`
* `domnamednodemap::removenameditemns`
* `domnamednodemap::setnameditem`
* `domnamednodemap::setnameditemns`
- domnode
* `domnode::getfeature`
*  `domnode::comparedocumentposition`
*  `domnode::getuserdata`
* `domnode::isequalnode`
*  `domnode::setuserdata`
* `domtext::replacewholetext`
* not exist in stub file, but [exists in …

Added PHP 8 into versions.xml for dom based on stubs.

---

reference/filesystem/functions/fputcsv.xml

As pointed out in https://github.com/php/doc-en/pull/606#issuecomment-843098871 by @cmb69 
fputcsv is now seperator not delimiter: https://3v4l.org/BBCBF

Fix fputcsv for php 8 to separator

---

reference/solr/solrobject/construct.xml
reference/solr/solrobject/offsetunset.xml
reference/tokyo_tyrant/tokyotyrant/setmaster.xml
reference/tokyo_tyrant/tokyotyrant/stat.xml
reference/tokyo_tyrant/tokyotyrantquery/addcond.xml

Removed unnecessary `<methodname>Classname::Method</methodname>` refs

Clean up Classname::Method refs

---

reference/mysqli/ini.xml

This PR fixes the default value of `mysqli.rollback-on-cached-plink`. It's is `"0"` as set here. 
https://github.com/php/php-src/blob/php-8.0.6/ext/mysqli/mysqli.c#L490

Fix the default value of `mysqli.rollback-on-cached-plink`

---

language/operators.xml

The current warning https://www.php.net/manual/en/language.operators.comparison.php is correct: 
> Prior to PHP 8.0.0, if a string is compared to a number or a numeric string then the string was converted to a number before performing the comparison. This can lead to surprising results as can be seen with the following example:
However, without showing outputs for the current example, it's hard to see the subtle differences between PHP 8.0 and PHP < 8.0. That's why I am adding these outputs. 
The output is captured from here https://3v4l.org/SHpi4
Relevant links:
- https://wiki.php.net/rfc/string_to_number_comparison
- https://www.php.net/manual/en/migration80.incompatible.php

Add outputs to show differences between PHP 8 and previous versions

---

reference/filesystem/functions/mkdir.xml

Thankfully PHP 8 provides us with [named arguments][1].
Unfortunately the current [documentation for the `mkdir` function][2] does not specify the correct parameter names.
As per the current documentation, the first parameter is named `pathname` and the second parameter `mode`.
This is not correct and can be verified with
```
$ php -v
PHP 8.0.3 (cli) (built: Apr  1 2021 15:33:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
$ php -a
Interactive shell
php > mkdir(pathname: '/tmp/test', recursive: true);
Warning: Uncaught Error: Unknown named parameter $pathname in php shell code:1
Stack trace:
#0 {main}
thrown in php shell code on line 1
php > $r = new \ReflectionFunction('mkdir');
php > var_dump($r->getParameters());
array(4) {
[0]=> …
```

Fix parameter names for the `mkdir` function

---

reference/filesystem/functions/rmdir.xml

Basically the same as #614.
I looked around a bit more and noticed, that the parameter names in the [documentation of the `rmdir` function][1]
also differ from the implementation.
```
$ php -v
PHP 8.0.3 (cli) (built: Apr  1 2021 15:33:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
$ php -a
Interactive shell
php > print_r((new \ReflectionFunction('rmdir'))->getParameters());
Array
(
[0] => ReflectionParameter Object
(
[name] => directory
)
[1] => ReflectionParameter Object
(
[name] => context
)
)
```
If I find some more bugs of this kind in the future, should I continue to create a PR per function or collect all changes in a single PR?
[1]: https://archive.is/2l650

Fix parameter names for the `rmdir` function

---

reference/pcre/pattern.syntax.xml

Inspired by https://bugs.php.net/bug.php?id=81060

Clarify that \Q and \E don't affect delimiters

---

reference/mysqli/mysqli/connect-errno.xml
reference/mysqli/mysqli/connect-error.xml
reference/mysqli/mysqli/errno.xml
reference/mysqli/mysqli_stmt/errno.xml

- Removed unhelpful notes
- Replaced `die()` with `error_log()` - if default error reporting is disabled then the errors should probably be logged to a file
- Removed mention of `mysqli_connect`. The connection error can come from all connection attempts except `change_user`
- Added explanatory comments in the code examples

Updating mysqli: connect_error & connect_errno

---

reference/mysqli/mysqli/character-set-name.xml

The example had incorrect return value. It does not return current collation, but the charset. Fixed the example, which now set the charset before reading to show the behaviour more clearly.

Fix the examples for character_set_name

---

reference/pdo/pdostatement/execute.xml

Similar to what was proposed in the bug report but used the word "positional" for question mark placeholder values. Fixed the third title too.

Doc Bug #81073 Fixed example titles in PDOStatement::execute

---

reference/yaf/yaf_controller_abstract/forward.xml
reference/yaf/yaf_response_abstract/appendbody.xml
reference/yaf/yaf_route_map/assemble.xml
reference/yaf/yaf_route_regex/assemble.xml
reference/yaf/yaf_route_rewrite/assemble.xml
reference/yaf/yaf_route_simple/assemble.xml
reference/yaf/yaf_route_static/assemble.xml
reference/yaf/yaf_route_supervar/assemble.xml
reference/yaf/yaf_view_simple/construct.xml

This PR fixes some small issues on **reference/yaf** documentation, some `return values` sections were out-of-order or had completely blank `<para>`s. Fixed to the best of my knowledge after reading up and peeking at the `yaf` source. Also combined a duplicate `seealso` into a single.
Is there a warnings section or something that can be added warning about documentation possibly being out-of-date? Looking at the [repository](https://github.com/laruence/yaf) for `yaf` the current version is `3.3.2`, docs target everything from `1.0.0` to `2.2.0`.

Clean up reference/yaf documentation.

---

reference/zmq/zmqcontext/construct.xml
reference/zmq/zmqcontext/getsocket.xml
reference/zmq/zmqdevice/getidletimeout.xml
reference/zmq/zmqdevice/gettimertimeout.xml
reference/zmq/zmqpoll/poll.xml
reference/zmq/zmqsocket/connect.xml
reference/zmq/zmqsocket/construct.xml
reference/zmq/zmqsocket/recv.xml

This PR cleans up [reference/zmq](https://github.com/php/doc-en/tree/master/reference/zmq) by re-ordering the `returnvalues` section into the proper place and also adding default `parameters` sections to documents that don't have it. 

Cleanup reference/zmq documentation.

---

reference/wincache/functions/wincache-fcache-meminfo.xml
reference/wincache/functions/wincache-ocache-meminfo.xml
reference/wincache/functions/wincache-rplist-fileinfo.xml
reference/wincache/functions/wincache-rplist-meminfo.xml
reference/wincache/functions/wincache-scache-meminfo.xml
reference/wincache/functions/wincache-ucache-clear.xml
reference/wincache/functions/wincache-ucache-meminfo.xml

This PR fixes multiple `wincache_*` functions not having parameter sections, most missing non-argument ones. 
`wincache_rplist_fileinfo` was missing its `$summaryonly` parameter section and description. Copied `wincache_fcache_fileinfo` parameter section and description for the latter since its name is the same. I will update the description once I know what the argument does. 🤷‍♂️

Fix multiple `wincache_*` functions having missing parameter sections

---

reference/spl/functions/spl-autoload-register.xml

This PR might not be necessary but noticed `spl_autoload_register` didn't have a signature for its callback parameter, so I decided to add it.
Choose to base it on the signature of `spl_autoload` which is the default method called if the callback is *null*. Hence the `string $class_name` parameter and `void` return type.
Feel this will be quicker for end-users to see the signature here instead of scrolling down to the examples section to see the implementation.

Update `spl_autoload_register` parameter section.

---

reference/classobj/functions/get-object-vars.xml

These were the only comments I thought worth folding in.  The rest were for PHP 4 and didn't even make sense then...
Another 37-ish comments exterminated.

Fold in comments for get_object_vars()

---

reference/image/functions/imageresolution.xml

Seems that `not` is missed.
The previous description was:
```
If only <parameter>res_x</parameter> is given, the horizontal and vertical resolution  are set to this value.
```

Fix function description

---

reference/stream/functions/stream-bucket-make-writeable.xml

The current documentation states `stream_bucket_make_writeable` returns `object`. 
This is incorrect, it returns `object|null`: 
* https://github.com/php/php-src/blob/dd83ced6bd600e0dd5b09cf26fe4302344521e97/ext/standard/user_filters.c#L382
* https://github.com/php/php-src/blob/dd83ced6bd600e0dd5b09cf26fe4302344521e97/ext/standard/basic_functions.stub.php#L1456

Update stream_bucket_make_writeable return types

---

reference/strings/functions/strtok.xml

There are some nuances, explained on the strtok man page, https://man7.org/linux/man-pages/man3/strtok.3.html namely starting, ending and duplicated tokens are ignored.

Add a note to strtok

---

appendices/ini.core.xml

Currently the upload_max_filesize entry makes no reference to post_max_size, which creates a gotcha when increasing its value. (There is a similar note under post_max_size, but users who don't know about this aren't likely to be looking there)

Ini settings: upload_max_filesize: Add note regarding post_max_size

---

reference/filter/constants.xml
reference/filter/filters.xml

Hey there :vulcan_salute: 
this pull request will add documentation about the `FILTER_VALIDATE_BOOL` alias for `FILTER_VALIDATE_BOOLEAN` to the docs, see #674
Kind regards
Florian

Add FILTER_VALIDATE_BOOL alias to docs

---

reference/filter/filters.xml

Hey there :vulcan_salute: 
I found the following comment in the docs to be true https://www.php.net/manual/en/filter.filters.flags.php#125956
The `FILTER_NULL_ON_FAILURE` flag can not only be used with `FILTER_VALIDATE_BOOL`/`FILTER_VALIDATE_BOOLEAN` but also with other validating filters.
This PR updates the docs accordingly, see https://3v4l.org/raIiu
Kind regards

Update FILTER_NULL_ON_FAILURE usage

---

reference/var/functions/is-callable.xml

I'm not sure this is structured properly.  I can restructure to some other format if someone tells me what the format should be. :-)

Fold in comments from is_callable() page

---

reference/mysqli/functions/mysqli-get-client-stats.xml
reference/mysqli/mysqli/get-connection-stats.xml
reference/mysqli/mysqli/poll.xml
reference/mysqli/mysqli/reap-async-query.xml
reference/mysqli/mysqli_result/fetch-all.xml
reference/mysqli/mysqli_stmt/get-result.xml
reference/mysqli/mysqli_stmt/more-results.xml
reference/mysqli/mysqli_stmt/next-result.xml

I'm not sure about the `note` tag.
Some functions have this note as plain text (e.g. [`mysqli_get_client_stats`](https://www.php.net/function.mysqli-get-client-stats)).
If it should be a note, I'll wrap this in other functions, 
if not — replace it as plain text in these functions.

Fix issues in mysqli directory

---

language/constants.xml

Change link from predefined constants to magic constants on [Constants page](https://www.php.net/manual/en/language.constants.php).

fix link from predefined to magic constants

---

reference/network/functions/header.xml

This may be the first thing users see when searching how to set the
response code - most will not be familiar with differences between
http/1.0 and 1.1
- HTTP/1.0 does not support connection keepalive
- http_response_code(404) is a shorter way to set a status code with the default
status message
https://www.php.net/manual/en/function.header.php#92305 also mentions
that the wrong protocol can cause issues with (older?) web servers
https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#History http 1.1 was officially released in 1997

Use a better example for using header() to set status code

---

reference/stream/functions/stream-set-blocking.xml

`set_socket_blocking` was removed in PHP 7.0. `socket_set_blocking` is still an alias and is not deprecated, but since we don't document aliases in notes, I removed the whole note.

Remove unneeded note

---

reference/strings/functions/ucwords.xml

Revised the wording in the second paragraph of `ucwords`. I'm not entirely sure about the use of double quotes around "word", but I think the changes overall provide clearer meaning of intent.
Resolves https://github.com/php/doc-en/issues/720

Revise wording for ucwords

---

appendices/aliases.xml
appendices/ini.core.xml
language-snippets.ent
reference/filesystem/functions/fwrite.xml
reference/info/functions/get-magic-quotes-runtime.xml
reference/info/ini.xml
reference/oci8/functions/oci-bind-by-name.xml
reference/strings/functions/parse-str.xml
reference/zlib/functions/gzwrite.xml

This PR removes information related to magicquotes which has been removed in PHP 7.0. 
I did _**not**_ change:
https://www.php.net/manual/en/function.parse-ini-file
https://www.php.net/manual/en/function.get-magic-quotes-gpc
https://www.php.net/manual/en/function.get-magic-quotes-runtime.php
https://www.php.net/manual/en/function.mysql-escape-string
https://www.php.net/manual/en/function.mysql-real-escape-string.php
https://www.php.net/security.variables

Remove Magic quotes runtime

---

reference/intl/dateformatter/get-timezone-id.xml
reference/intl/versions.xml

I am not sure what exactly CN was and I can't find out what the purpose of this example was, but I replaced it with a valid timezone name.

Fix example of datefmt_get_timezone_id

---

language-snippets.ent
reference/ldap/functions/ldap-count-entries.xml
reference/ldap/functions/ldap-count-references.xml
reference/ldap/functions/ldap-first-entry.xml
reference/ldap/functions/ldap-free-result.xml
reference/ldap/functions/ldap-get-entries.xml
reference/ldap/functions/ldap-parse-result.xml

Fixed `result` parameter description, based on stubs for:
- [ldap_free_result](https://github.com/php/php-src/blob/master/ext/ldap/ldap.stub.php#L52)
- [ldap_count_entries](https://github.com/php/php-src/blob/master/ext/ldap/ldap.stub.php#L54)
- [ldap_first_entry](https://github.com/php/php-src/blob/master/ext/ldap/ldap.stub.php#L56)
- [ldap_get_entries](https://github.com/php/php-src/blob/master/ext/ldap/ldap.stub.php#L60)
- [ldap_count_references](https://github.com/php/php-src/blob/master/ext/ldap/ldap.stub.php#L125)
- [ldap_parse_result](https://github.com/php/php-src/blob/master/ext/ldap/ldap.stub.php#L144)
Added `ldap_count_references` function, ref #674

Fix ldap functions description

---

reference/sodium/book.xml
reference/sodium/setup.xml

Many great improvement of ext/sodium documentation was added in #592.
I added some more basic information about it.
- filled ext/sodium Introduction page contents
* copied from https://doc.libsodium.org/
- filled Resouce type page, too.
* ext/sodium uses sodium_init() internally and seems to use no resource.

Improved ext/sodium [Introduction|Resource Types] documentation.

---

install/windows/apache2.xml

The internet will always take your example code and repost it out of context. Googling shows plenty of installation guides that use `AddHandler application/x-httpd-php .php`, which potentially leads to parsing unsafe files like `evil.php.jpg`
I propose to totally remove the unsafe example and only show the correct version with `<FilesMatch \.php$>`, similar to https://www.php.net/manual/en/install.unix.apache2.php

Remove unsafe AddHandler example

---

reference/reflection/reflectionproperty/getdefaultvalue.xml
reference/reflection/reflectionproperty/hasdefaultvalue.xml
reference/reflection/reflectionproperty/isdefault.xml

These methods only exist on the `ReflectionProperty` class, not on `ReflectionClass`.

ReflectionProperty: fix a few references to wrong class name(s)

---

reference/rar/setup.xml

This fixes a couple of typos on https://www.php.net/manual/en/rar.resources.php

Fix typos in setup.xml

---

reference/classobj/functions/class-exists.xml

`__autoload` has been removed now, so the example using it should be changed too.

New example for class_exists

---

reference/phar/book.xml

Added a couple of missing punctuation marks on https://www.php.net/manual/en/intro.phar.php

Add period and comma on Phar intro page

---

reference/mysqli/versions.xml

Generated verions.xml based on the following stubs.
- https://github.com/php/php-src/blob/PHP-8.0/ext/mysqli/mysqli.stub.php
- Notable changes
* deleted functions as of PHP 8
- `mysqli_embedded_server_start`
- `mysqli_embedded_server_end`
- `mysqli_driver::embedded_server_end`
- `mysqli_driver::embedded_server_start`
* not exist in manual nor PHP 5, PHP 7, PHP 8 source.
- `mysqli_result_*` function, for example, `mysqli_result_current_field`
- `mysqli_host_info`
* exists in PHP5, PHP 7 source, but not exist in manual.
- `mysqli_row_seek`
- `mysqli_read_query_result`

Added PHP 8 into versions.xml for mysqli based on stubs.

---

reference/mysqli/versions.xml

As salathe said, there don't need to be duplicate entries for methods in `mysqli_result`. However, for properties, I left it with a comment for compliance with the rest of the file. Otherwise, I would have to deduplicate the whole file. (it's something we might have to do in PHP 9). 
I also removed the two entries for functions that never existed in PHP.

Fixed remaining issues in mysqli versions.xml

---

reference/classobj/functions/class-exists.xml
reference/classobj/versions.xml
reference/spl/functions/class-implements.xml
reference/spl/functions/class-parents.xml
reference/spl/functions/class-uses.xml

PHAR still uses `__autoload` in their documentation but I don't care that much about changing it right now.

Fix remaining usages of __autoload

---

reference/session/sessionhandlerinterface/gc.xml

The type is `int|false` but documented as `int|bool`.
https://github.com/php/php-src/blob/PHP-8.0.8/ext/session/session.stub.php#L83

Update return type for SessionHandlerInterface::gc()

---

appendices/reserved.constants.core.xml

Page https://www.php.net/manual/en/reserved.constants.php contains incorrect link to magic constants (https://www.php.net/manual/en/language.constants.predefined.php) while the correct one is https://www.php.net/manual/en/language.constants.magic.php

Fixed the link to magic constants

---

reference/network/functions/syslog.xml

Nor any other printf specifier
Drop version name for Windows note as a drive by fix.

Syslog does not support the %m format specificer

---

reference/spl/recursivecallbackfilteriterator/construct.xml

From manual page: https://php.net/class.recursivecallbackfilteriterator
---
The callback can be any callable, e.g. anonymous functions are supported

Fix typehint

---

language/types/declarations.xml

There is a weird space after `float` which seems to be caused by the multi-line list of types. Made the list of types a single line to avoid it.
Also, the list was in a random order which made it awkward to read. There are probably many opinions on the correct order, but picked something that grouped types together better.
Original:
`array|bool|callable|int|float |object|resource|string|null`
New:
`object|resource|callable|array|string|int|float|bool|null`

Fix space and sort types that define mixed union type

---

reference/spl/cachingiterator/hasnext.xml

The return type for `CachingIterator::hasNext` is currently documented as `void` when it should be `bool`.

Fix documented return type for CachingIterator::hasNext()

---

reference/event/eventconfig/requirefeatures.xml
reference/event/eventconfig/setflags.xml
reference/event/versions.xml

1. add `eventConfig::setFlags`. Source code reference: https://bitbucket.org/osmanov/pecl-event/src/1fa696a0dc145d5d5f40a144f7a27be31eaf14a5/php8/classes/event_config.c#lines-135
2. add `eventConfig::requireFeatures` missing return value description
3. add `EventConfig::setMaxDispatchInterval` required pecl event version

add eventConfig missing method

---

reference/exec/functions/shell-exec.xml

Related to https://github.com/php/php-src/pull/7306#issuecomment-886489235
`shell_exec` can return `false`.

Update shell_exec doc

---

reference/exec/functions/shell-exec.xml

#821 newly added return `&false;` in case of pipe establish error, so we need to add it to signatures.

additional return value fix of shell_exec func.

---

reference/array/sorting.xml

https://www.php.net/manual/en/array.sorting.php
Updated sorting functions description, followed appendices/migration80/new-features.xml [*1].
[*1] https://github.com/php/doc-en/blob/fdd6debfb8fe88340e6c654a05c1ab7a51673aa0/appendices/migration80/new-features.xml#L502-L506

Sorting functions is stable, as of PHP 8.0.0.

---

reference/array/functions/array-filter.xml

This was the only meaningful change from the comments I just deleted; a few of them mentioned array_intersect, which kinda makes sense as it is also a make-array-smaller function.

Add additional reference to array_filter.

---

language/predefined/arrayaccess.xml
language/predefined/iterator.xml
language/predefined/serializable.xml
language/predefined/stringable.xml
language/predefined/throwable.xml
language/predefined/traversable.xml
reference/datetime/datetimeinterface.xml
reference/json/jsonserializable.xml
reference/reflection/reflector.xml
reference/session/sessionhandlerinterface.xml
reference/session/sessionidinterface.xml
reference/spl/countable.xml
reference/spl/outeriterator.xml
reference/spl/recursiveiterator.xml
reference/spl/seekableiterator.xml

A few more to come when the class synopsis pages are generated from stubs.
Needs https://github.com/php/phd/pull/50/ first!

Mark a few interfaces as oointerface rather than ooclass

---

language/predefined/arrayaccess/offsetexists.xml
language/predefined/arrayaccess/offsetget.xml
language/predefined/arrayaccess/offsetset.xml
language/predefined/arrayaccess/offsetunset.xml

https://www.php.net/manual/en/class.arrayaccess.php
Now that ArrayAccess is shown as an interface, the `abstract` modifier doesn't make sense. This suggests that interfaces can/should use the abstract modifier when it isn't allowed.
```
abstract public offsetExists(mixed $offset): bool
abstract public offsetGet(mixed $offset): mixed
abstract public offsetSet(mixed $offset, mixed $value): void
abstract public offsetUnset(mixed $offset): void
```

Remove abstract modifier from ArrayAccess methods

---

reference/array/functions/list.xml

Let's not have XSS in the manual. 
The example was only applicable to PHP 5, but then the context got lost and the example was left in the manual. It was showing the right-to-left assignment of `list()`

Remove XSS and broken example from list() page

---

reference/curl/constants.xml
reference/curl/functions/curl-setopt.xml

In cURL 7.46.0 the default for `CURLOPT_TIMECONDITION` was changed from `CURL_TIMECOND_IFMODSINCE` to `CURL_TIMECOND_NONE`.
References:
- https://curl.se/libcurl/c/CURLOPT_TIMECONDITION.html
- https://curl.se/changes.html#7_46_0
- https://github.com/curl/curl/commit/cd2b73b3e

Reflect new default for `CURLOPT_TIMECONDITION` since cURL 7.46.0

---

reference/mysqli/mysqli/multi-query.xml

The page was in dire need of explaining how the processing works. Judging by the number of notes, users have been confused about the asynchronous nature, and the way that the results need to be retrieved every time. I tried to make this abundantly clear. I have taken inspiration (and few sentences) from https://dev.mysql.com/doc/c-api/8.0/en/c-api-multiple-queries.html

Provide better documentation for mysqli_multi_query

---

language/types/string.xml

Newly documented Flexible heredoc/nowdoc, based on RFC [*1], 
Closes #741
[*1] https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

Document Flexible heredoc/nowdoc.

---

language/attributes.xml

Looks like the example function name and the function call do not match, if it's an oversight this commit fixes it.

Fix typo in example function call

---

language/functions.xml

This pull request updates the return value documentation for functions to reflect newer syntax provided by PHP as reported in https://bugs.php.net/bug.php?id=80538

[80538] Shorthand syntax for array destruction

---

reference/opcache/preload.xml

Nikita said in a [bug report](https://bugs.php.net/bug.php?id=79956) that constants aren't covered and won't be, which is suboptimal but this at least captures the facts on the ground more accurately.

Clarify preloading and constant behavior.

---

reference/pcre/functions/preg-match-all.xml
reference/pcre/functions/preg-match.xml

Re f33541d1561d9cf39eda962d02693f2fd90c3eae: align the return values of these 3 functions to say the same thing.

Align return values for pcre_*  functions

---

language/basic-syntax.xml

Fixes typo in the note about not using short tags

Update basic-syntax.xml to fix typo

---

appendices/migration80/other-changes.xml

Strict typing directive is not `strict_type`, but `strict_types`.
Also, we may be able to replace it with a link to strict typing page [*1]
[*1] https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict

fixed strict typing directive spelling.

---

language/types/boolean.xml

Updated examples of casting to boolean adding one case that is pretty often appearing in code: string `"0"`.

Updated examples of casting to boolean

---

appendices/resources.xml

This probably resulted in extra added table cells that breaks the 5 column table layout.

partly resolve #77017 resources table layout problem

---

reference/intl/numberformatter/parse.xml

First contribution, so go easy on me!
Seems like we're missing the documentation for the `$value` parameter from this function, which has confused at least my colleague @anotherjames that pointed this out to me.

Add missing documentation for value parameter of numfmt_parse

---

reference/opcache/ini.xml

@nikic, is that a correct interpretation of https://bugs.php.net/bug.php?id=81365#1629279195?

Fix #81365: Flipping opcache.file_cache_only is broken

---

appendices/ini.list.xml
reference/errorfunc/ini.xml

Quoted from [appendices/migration80/incompatible.xml](https://github.com/php/doc-en/blob/master/appendices/migration80/incompatible.xml#L175-L180).
```
display_startup_errors is now enabled by default.
```

Followed change of default value of display_startup_errors, as of PHP 8.0.0

---

reference/info/functions/phpcredits.xml
reference/info/functions/phpinfo.xml
reference/info/functions/phpversion.xml
reference/info/functions/zend-version.xml

This PR removes 4 references to the now-removed `php_logo_guid` function.

Remove `php_logo_guid` references

---

reference/filesystem/functions/glob.xml

The use of the `GLOB_BRACE` flag causes the function to crash if the application runs in an alpine-based docker container. The note only mentions Solaris as an example where the flag doesn't work but Alpine seems like an important exception to mention as well as it is widely used to create docker images.

Add note about GLOB_BRACE flag in Alpine

---

language/predefined/iterator/current.xml
language/predefined/iterator/key.xml
language/predefined/iterator/next.xml
language/predefined/iterator/rewind.xml
language/predefined/iterator/valid.xml
language/predefined/iteratoraggregate/getiterator.xml
language/predefined/serializable/serialize.xml
language/predefined/serializable/unserialize.xml
language/predefined/throwable/getcode.xml
language/predefined/throwable/getfile.xml
language/predefined/throwable/getline.xml
language/predefined/throwable/getmessage.xml
language/predefined/throwable/getprevious.xml
language/predefined/throwable/gettrace.xml
language/predefined/throwable/gettraceasstring.xml
language/predefined/weakmap/getiterator.xml
reference/json/jsonserializable/jsonserialize.xml
reference/session/sessionhandlerinterface/close.xml
reference/session/sessionhandlerinterface/destroy.xml
reference/session/sessionhandlerinterface/gc.xml
reference/session/sessionhandlerinterface/open.xml
reference/session/sessionhandlerinterface/write.xml
reference/session/sessionidinterface/create-sid.xml
reference/session/sessionupdatetimestamphandlerinterface/updatetimestamp.xml
reference/session/sessionupdatetimestamphandlerinterface/validateid.xml

These are unnecessary since the `interface` keyword is displayed on the class synopsis pages.

Remove some unnecessary abstract modifiers from methodsynopses

---

language/predefined/variables/superglobals.xml

In the site it looked like "Superglobals — Superglobals are built-in variables that are always available in all scopes" 
https://www.php.net/manual/en/language.variables.superglobals.php

Remove duplicate "Superglobals"

---

reference/curl/curlfile/construct.xml

It used to be erroneously removed.

Fix methodsynopsis role of curl_file_create()

---

appendices/extensions.xml
reference/var_representation/book.xml
reference/var_representation/constants.xml
reference/var_representation/functions/var-representation.xml
reference/var_representation/reference.xml
reference/var_representation/setup.xml
reference/var_representation/versions.xml

Information about the extension can be found at https://github.com/TysonAndre/var_representation https://pecl.php.net/var_representation - it was proposed at https://marc.info/?l=pecl-dev&m=162400655627665&w=2 in June.

Add documentation for var_representation PECL

---

language/attributes.xml

As pointed out in #951, the titles in the [attribute classes](https://www.php.net/language.attributes.classes) example seems to be mixed up, this PR fixes that.

Fix attribute example titles

---

reference/password/functions/password-needs-rehash.xml

Noticed that the current method signature for `password_needs_rehash` in the [documentation](https://www.php.net/manual/en/function.password-needs-rehash.php) was wrong.
`$algo` should be of `string|int|null` like `password_hash` and not `mixed`. It was also missing the default initializer for `$options`.
This PR makes sure the signature matches up with the internal method signature found in [standard/basic_functions.stub.php](https://github.com/php/php-src/blob/c19e4b9997cd429c86c20e9210ff3d9b2e94171d/ext/standard/basic_functions.stub.php#L1511).

Fix `password_needs_rehash` method signature

---

language-snippets.ent
reference/mbstring/functions/mb-stripos.xml
reference/mbstring/functions/mb-stristr.xml
reference/mbstring/functions/mb-strpos.xml
reference/mbstring/functions/mb-strrchr.xml
reference/mbstring/functions/mb-strrichr.xml
reference/mbstring/functions/mb-strripos.xml
reference/mbstring/functions/mb-strrpos.xml
reference/mbstring/functions/mb-strstr.xml

This PR aims to fix the currently missing "_`needle` argument can now be empty_" changelogs in some `mb_*` functions.
If the wording in the changelog is acceptable, it will be added to the rest of the function, namely `mb_strpos`, `mb_strrpos`, `mb_strstr`, `mb_stristr`, `mb_strchr` and `mb_strichr`. Those are the function listed in the [migration](https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.mbstring).
Potentially by creating a new entity `&mbstring.changelog.needle-empty;` to avoid duplication.

[80738] Update MB string functions

---

reference/datetime/functions/localtime.xml

`localtime` function of PHP returns assosiative array which has  identical elements of the structure returned by the C [*1].
Also, it is inconsistent with [function description](https://github.com/php/doc-en/blob/d91e36266dddbe570789dbe218e5672fc0b85089/reference/datetime/functions/localtime.xml#L18).
[*1] https://linux.die.net/man/3/localtime

fixed localtime returnvalues description.

---

reference/exec/functions/passthru.xml
reference/exec/functions/shell-exec.xml
reference/funchand/functions/register-shutdown-function.xml
reference/math/functions/pow.xml
reference/math/functions/round.xml
reference/math/functions/srand.xml

These are mostly simpler cases (e.g. when only parameter names changed).

Generate some standard methodsynopses based on stubs

---

reference/dom/domdocument.xml

Property `documentElement` is `NULL` when there is no document element since PHP 5.4.0. https://3v4l.org/vOYYo
```php
var_dump( (new DOMDocument())->documentElement );
NULL
```
Other NULL properties on `DOMDocument` and `DOMNode` has been set before, see https://github.com/php/doc-en/pull/52

DOMDocument::documentElement property can be NULL

---

reference/misc/functions/get-browser.xml
reference/misc/functions/highlight-file.xml
reference/misc/functions/highlight-string.xml

Noticed that the return types for some functions in the Misc Functions were wrong.
This PR makes sure the return types matches up with the internal return types found in [standard/basic_functions.stub.php.](https://github.com/php/php-src/blob/master/ext/standard/basic_functions.stub.php)

Fix `mixed` return type declarations and parameters of Misc. Functions

---

appendices/migration81.xml
appendices/migration81/constants.xml
appendices/migration81/deprecated.xml
appendices/migration81/incompatible.xml
appendices/migration81/new-classes.xml
appendices/migration81/new-features.xml
appendices/migration81/new-functions.xml
appendices/migration81/other-changes.xml

Currently missing sections:
From the [UPGRADING](https://github.com/php/php-src/blob/PHP-8.1/UPGRADING) document in the PHP-8.1 branch.

Migration guide from PHP 8.0 to PHP 8.1

---

install/unix/debian.xml

Updated Debian GNU/Linux installation notes, based on Debian 11 (bullseye).
* we should replace php5 related package name.
* update ini file location.
* use not `apt-get`, but `apt` for interactive usage.
- https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_literal_apt_literal_vs_literal_apt_get_literal_literal_apt_cache_literal_vs_literal_aptitude_literal
Closes #964

Update Debian GNU/Linux installation notes

---

language/types/declarations.xml

Support to PhD to generate the link should also be added.
I don't know if it makes sense to clarify at the same type that ``mixed`` is the top type.
@muglug @ondrejmirtes could you have a look as the RFC authors?

Add documentation about the never type

---

language/functions.xml
reference/strings/functions/get-html-translation-table.xml
reference/strings/functions/html-entity-decode.xml
reference/strings/functions/htmlentities.xml
reference/strings/functions/htmlspecialchars-decode.xml
reference/strings/functions/htmlspecialchars.xml

I'm not familiar with the PHP development process, but it looks like [PR 6583](https://github.com/php/php-src/pull/6583) has been accepted in [50eca61](https://github.com/php/php-src/commit/50eca61f68815005f3b0f808578cc1ce3b4297f0), and will be in PHP 8.1.
These should update the documentation to reflect this change.

Use 'ENT_QUOTES|ENT_SUBSTITUTE' for HTML encoding and decoding functions

---

reference/reflection/reflectionfunctionabstract.xml

Abstract keyword was missing in synopsis of class `ReflectionFunctionAbstract`.

ReflectionFunctionAbstract is abstract

---

reference/imagick/imagick/montageimage.xml

`Imagick::montageImage` returns a new Imagick, not bool.
Also `thumbnail_geometry` example looks like a typo.
`>` is indeed a valid geometry flag, but it makes sense only for dimensions, not offsets.
Therefore, `120x120+4+3>` would be silently parsed as `120x120>+4+3`
Too misleading for an example value.

Fix return value of Imagick::montageImage

---

reference/strings/functions/strcspn.xml
reference/strings/functions/strspn.xml

Commit e095023e408c8cb6378ae16bb6870343a3946919 renamed the `$subject`, `$mask`, and `$start` parameters of the `strspn()` and `strcspn()` functions to `$string`, `$characters`, and `$offset`, respectively.
For both of them, three instances in the code example were missed. This PR fixes them.

strspn() and strcspn(): Use proper parameter names in docs reference

---

reference/image/functions/imageavif.xml
reference/image/functions/imagecreatefromavif.xml
reference/image/versions.xml

Based on stubs:
- [imageavif](https://github.com/php/php-src/blob/PHP-8.1/ext/gd/gd.stub.php#L142) ([parameters](https://github.com/php/php-src/blob/master/ext/gd/libgd/gd_avif.c#L444))
- [imagecreatefromavif](https://github.com/php/php-src/blob/PHP-8.1/ext/gd/gd.stub.php#L88)

[PHP 8.1] Add `imageavif` and `imagecreatefromavif` functions

---

reference/url/functions/http-build-query.xml

This PR adds the missing parameter initializers for the `http_build_query` function And updates the signature to match the one in [/basic_functions.stub.php](https://github.com/php/php-src/blob/f983373e44dd45c7e09036fc67476fc946306b3c/ext/standard/basic_functions.stub.php#L1298). As discussed in #916

Add missing parameter defaults for `http_build_query`

---

appendices/resources.xml
language-snippets.ent
reference/image/book.xml
reference/image/functions/imagechar.xml
reference/image/functions/imagecharup.xml
reference/image/functions/imagefontheight.xml
reference/image/functions/imagefontwidth.xml
reference/image/functions/imageloadfont.xml
reference/image/functions/imagestring.xml
reference/image/functions/imagestringup.xml
reference/image/gdfont.xml
reference/image/setup.xml
reference/image/versions.xml

As of PHP [8.1.0](https://github.com/php/php-src/blob/PHP-8.1/ext/gd/gd.stub.php), a GdFont class was added.
Not sure about `gd font` resource.. because PHP 8.0 already [has](https://github.com/php/php-src/blob/PHP-8.0/ext/gd/gd.stub.php) int values instead of resources 🤔

[PHP 8.1] Use GdFont

---

reference/filesystem/functions/fdatasync.xml
reference/filesystem/functions/fsync.xml
reference/filesystem/versions.xml

Added [`fdatasync`](https://github.com/php/php-src/blob/PHP-8.1/ext/standard/basic_functions.stub.php#L1109) and [`fsync`](https://github.com/php/php-src/blob/PHP-8.1/ext/standard/basic_functions.stub.php#L1106) description.

[PHP 8.1] Add `fdatasync` and `fsync` description

---

reference/datetime/datetime/createfromformat.xml

Current doc is referencing the Epoch time as the target of reseted value. But it can be misleading, because `Epoch time` is time point independently of Timezone. The `createFromFormat()` but doesn't target resetted values to Epoch time, but only to the zero-like values.
Epoch time is NOT time representation (e.g.: `1970-01-01 00:00:00`), it's explicitly defined point in Timeline regardless to TimeZone. When you represent Epoch time in non-GTM Time zone, you MUST precising time to neutralize time zone shifting. 
That's mean `1970-01-01 00:00:00-08:00` is NOT Epoch time! Right is this: `1970-01-01 08:00:00-08:00`.
PHP doc is referencing resetting fields to Epoch time. It's misleading because when user define non-GTM Time zone, the PHP method `createFromFormat()` is reset fields to values …

DateTime::createFromFormat - fix misleading epoch info

---

reference/opcache/functions/opcache-get-status.xml
reference/opcache/functions/opcache-invalidate.xml
reference/opcache/functions/opcache-is-script-cached.xml
reference/opcache/functions/opcache-reset.xml

The functions `opcache_get_status`, `opcache_invalidate`, `opcache_is_script_cached` and `opcache_reset` only apply to in-memory cache, not file cache. Also [fixes bug #75070](https://bugs.php.net/bug.php?id=75070).

Opcache functions only apply to in-memory cache

---

reference/datetime/datetimeinterface/format.xml

Use _ISO 8601_, instead of _ISO-8601_, for consistency and alignment with https://www.iso.org/iso-8601-date-and-time-format.html

Update ISO 8601 text

---

reference/curl/constants.xml

Description:
- [`CURLOPT_DOH_URL`](https://curl.se/libcurl/c/CURLOPT_DOH_URL.html)
- [`CURLOPT_ISSUERCERT_BLOB`](https://curl.se/libcurl/c/CURLOPT_ISSUERCERT_BLOB.html)
- [`CURLOPT_PROXY_ISSUERCERT`](https://curl.se/libcurl/c/CURLOPT_PROXY_ISSUERCERT.html)
- [`CURLOPT_PROXY_ISSUERCERT_BLOB`](https://curl.se/libcurl/c/CURLOPT_PROXY_ISSUERCERT_BLOB.html)
- [`CURLOPT_PROXY_SSLCERT_BLOB`](https://curl.se/libcurl/c/CURLOPT_PROXY_SSLCERT_BLOB.html)
- [`CURLOPT_PROXY_SSLKEY_BLOB`](https://curl.se/libcurl/c/CURLOPT_PROXY_SSLKEY_BLOB.html)
- [`CURLOPT_SSLCERT_BLOB`](https://curl.se/libcurl/c/CURLOPT_SSLCERT_BLOB.html)
- [`CURLOPT_SSLKEY_BLOB`](https://curl.se/libcurl/c/CURLOPT_SSLKEY_BLOB.html)

[PHP 8.1] Add cURL constants

---

language-snippets.ent
reference/pcre/functions/preg-filter.xml
reference/pcre/functions/preg-grep.xml
reference/pcre/functions/preg-match-all.xml
reference/pcre/functions/preg-match.xml
reference/pcre/functions/preg-replace-callback-array.xml
reference/pcre/functions/preg-replace-callback.xml
reference/pcre/functions/preg-replace.xml
reference/pcre/functions/preg-split.xml

All PCRE pattern matching functions will throw a warning when an invalid regex is passed to the `$pattern` parameter.
See: https://3v4l.org/WkVIW
This was thus far undocumented behaviour.
This PR adds:
* The "Errors/Exceptions" section to each of the PCRE pattern matching function documentation pages (if it didn't exist yet).
* Adds a macro for the text snippet about the warning to display in the section and uses that in the "Errors/Exceptions" section for each function.

PCRE: add missing "Errors/Exceptions" section

---

reference/spl/arrayobject/unserialize.xml

The [ArrayObject::unserialize](https://www.php.net/manual/en/arrayobject.unserialize.php) has `void` return type so it looks a bit incorrect describing it as returning an "unserialized ArrayObject"

Remove incorrect return comment for ArrayObject::unserialize

---

reference/array/functions/key.xml

`key()` is often used to get the first key of the array. But it brings various issues related to the array internal pointer, hence the introduction of `array_key_first()` (and its sibling `array_key_last()`) in PHP 7.3. Thus, a "see also" link to this function seems really appropriate, especially as people may not be aware of this newer function.

On page for key(), add link to array_key_first()

---

language/types/declarations.xml

Based on [8.1.0 migration guide](https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.void-by-ref), added deprecation note about `returning by reference from a void function`.

Document returning by reference from a void function deprecation.

---

language/types/declarations.xml

The behavior in the `Example #7 Old way to make arguments nullable` is still possible in PHP today.
For reference, I thought initially this was a bug in the PHP Core, and tried to add the respective test case in the PR:
https://github.com/php/php-src/pull/7627

Correct note to state behavior is possible

---

reference/mbstring/overloading.xml

warning: untested, i don't know if `warn.deprecated.function-7-2-0.removed-8-0-0` is a real... thing. but i guess it's a real thing, after studying the code for similar error messages..

mb_ overloading was removed in 8.0.0

---

language/types/array.xml

https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.autovivification-false
Based on php 8.1 migration guide, added autovivification note.

Document autovivification from false deprecation.

---

appendices/migration81/new-features.xml
language/oop5/inheritance.xml
language/oop5/properties.xml
reference/reflection/reflectionproperty/isprivate.xml
reference/reflection/reflectionproperty/isprotected.xml
reference/reflection/reflectionproperty/isreadonly.xml
reference/reflection/reflectionproperty/isstatic.xml
reference/reflection/versions.xml

Based on [RFC](https://wiki.php.net/rfc/readonly_properties_v2), added documentation of readonly properties.
- TODO
* RFC states readonly keyword is reserved, however, [we can use it as function name](https://github.com/php/php-src/commit/76348f3378dbc0c92568380d23a8d75a777ae49c).

[PHP 8.1] Document readonly properties.

---

language/predefined/serializable.xml

Apologies if this is poorly formed - wasn't able to get the documentation to build properly on my machine but this looks like a fairly straightforward change.
Ref #980 "Implementing Serializable without __serialize() and __unserialize()"
RFC reference https://wiki.php.net/rfc/phase_out_serializable

[PHP 8.1] Add note about implementing Serializable without __serialize

---

reference/curl/book.xml
reference/curl/curlstringfile.xml
reference/curl/curlstringfile/construct.xml
reference/curl/versions.xml

Added CURLStringFile document based on https://github.com/php/php-src/pull/6456 and [its stubs](
https://github.com/php/php-src/blob/PHP-8.1.0/ext/curl/curl_file.stub.php#L30-L37).

[PHP 8.1] Document CURLStringFile

---

language/predefined/variables/globals.xml

https://wiki.php.net/rfc/restrict_globals_usage

[PHP 8.1] Document restriction of $GLOBALS usage.

---

appendices/migration81/new-features.xml
language/oop5/basic.xml
language/oop5/changelog.xml
language/oop5/constants.xml
language/oop5/final.xml
language/oop5/interfaces.xml
reference/reflection/reflectionclassconstant/isfinal.xml
reference/reflection/reflectionclassconstant/isprivate.xml
reference/reflection/reflectionclassconstant/isprotected.xml
reference/reflection/versions.xml

Based on [RFC](https://wiki.php.net/rfc/final_class_const), added documentation of final class constants. It's ready for review.
* TODO

[PHP 8.1] Document final class constants.

---

appendices/migration81/incompatible.xml

That's not what "respectively" means.
http://www.lexico.com/definition/respectively
"The PSpell functions now accept and return, respectively, PSpell\Config objects instead of pspell config resources."
means (a) there are precisely _two_ PSpell functions, where the first one (and you know which one that is) now accepts an object instead of a resource, and the second returns one.

Drop use of noise word "respectively"

---

reference/reflection/reflectionextension/clone.xml
reference/reflection/reflectionfunctionabstract/clone.xml
reference/reflection/reflectionparameter/clone.xml
reference/reflection/reflectionproperty/clone.xml
reference/reflection/reflectionzendextension/clone.xml

- `ReflectionExtension::__clone()` — https://3v4l.org/SEPiF
- `ReflectionFunctionAbstract::__clone()` — https://3v4l.org/d2pT7
- `ReflectionParameter::__clone()` — https://3v4l.org/MBOVF
- `ReflectionProperty::__clone()` — https://3v4l.org/XcB7t
- `ReflectionZendExtension::__clone()` — https://3v4l.org/ksU1U

[PHP 8.1] Remove final modifier from `__clone()`

---

language/attributes.xml

I wasn't able to find these anywhere in the Attributes documentation, and needed to use reflection to find the valid values.
I think the constant names are self-explanatory enough to not require additional information.

Add list of attribute target constants

---

appendices/migration81/new-features.xml
language/fibers.xml
language/predefined/fiber.xml

Moved Fibers overview contents to be linked from the top page of manual, because it is core functionality like Generators.
We must merge https://github.com/php/doc-base/pull/53, or build will fail.

Moved [overview|example] of Fibers to language/fibers.xml page.

---

appendices/migration81/deprecated.xml
language-snippets.ent
reference/ctype/functions/ctype-alnum.xml
reference/ctype/functions/ctype-alpha.xml
reference/ctype/functions/ctype-cntrl.xml
reference/ctype/functions/ctype-digit.xml
reference/ctype/functions/ctype-graph.xml
reference/ctype/functions/ctype-lower.xml
reference/ctype/functions/ctype-print.xml
reference/ctype/functions/ctype-punct.xml
reference/ctype/functions/ctype-space.xml
reference/ctype/functions/ctype-upper.xml
reference/ctype/functions/ctype-xdigit.xml

https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.ctype

[PHP 8.1] Document deprecated ctype non-string argument.

---

features/file-upload.xml

Add documentation for `full_path` entry, [introduced in PHP 8.1](https://www.php.net/manual/en/migration81.new-features.php#migration81.new-features.core.upload-full-path-key).

[PHP 8.1] Documentation for `full_path` entry of `$_FILES`

---

reference/dom/domdocument.xml

A better description for documentElement that can be `NULL`.
See #955

Reword description on DOMDocument::domElement

---

reference/runkit7/functions/runkit7-object-id.xml
reference/spl/functions/spl-object-hash.xml

Encourage the use of spl_object_id instead.
Using an integer is faster and more memory-efficient than creating a 32-byte
string hash.
spl_object_hash historically obfuscated the object id with xor for security reasons, but it was sufficient for security to not expose raw pointers.
`runkit7_object_id` is one way to polyfill PHP 7.2+ `spl_object_id`
in older PHP 7 versions and continues to exist in the PECL.

Link to spl_object_id from similar functions.

---

language/oop5/basic.xml
language/operators.xml
reference/misc/functions/define.xml

This PR is an attempt to solve the remaining core items in: https://github.com/php/doc-en/issues/674
Specifically this will cover the following:

[8.0] Document remaining core changes

---

reference/pdo/pdo/prepare.xml
reference/pdo/pdostatement/bindparam.xml
reference/pdo/pdostatement/bindvalue.xml
reference/pdo/pdostatement/execute.xml

passing values for named parameters in an array allow array keys being
either the names of the named parameters or (alternatively) the names
prefixed with colons (\<colon> : \<U003A> COLON) mimicking the placeholders
in the SQL query.
therefore the example should show first verbatim names as the array keys
and then highlight the alternative way to have the array keys with a
dedicated comment within the examples code.

PDOStatement colons for names in array example

---

reference/pdo/pdostatement/fetchall.xml

It either returns all or remaining rows. These aren't exactly the same operation which can be confusing.

Update fetchAll() return description to match summary wording

---

reference/filesystem/ini.xml

auto_detect_line_endings deprecated as of PHP 8.1.0
Spotted in tests and you can see it here:
https://3v4l.org/2pjOA

auto_detect_line_endings deprecated

---

reference/mysqli/mysqli/get-client-info.xml

https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.mysqli

[PHP 8.1] mysqli::get_client_info is deprecated

---

reference/mysqli/mysqli/init.xml

https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.mysqli

[PHP 8.1] mysqli::init() is deprecated

---

reference/datetime/dateinterval/construct.xml
reference/datetime/dateperiod/getdateinterval.xml
reference/datetime/dateperiod/getenddate.xml
reference/datetime/dateperiod/getrecurrences.xml
reference/datetime/dateperiod/getstartdate.xml
reference/datetime/datetime/construct.xml
reference/datetime/datetime/createfromimmutable.xml
reference/datetime/datetime/createfrominterface.xml
reference/datetime/datetime/set-state.xml
reference/datetime/datetimezone/construct.xml

These roles are not necessary, since the respective class pages don't depend on them. Followup to #1011

Remove unnecessary DateInterval, DatePeriod, DateTime and DateTimeZone method synopsis roles

---

reference/datetime/datetimeimmutable/add.xml
reference/datetime/datetimeimmutable/construct.xml
reference/datetime/datetimeimmutable/createfrominterface.xml
reference/datetime/datetimeimmutable/createfrommutable.xml
reference/datetime/datetimeimmutable/modify.xml
reference/datetime/datetimeimmutable/set-state.xml
reference/datetime/datetimeimmutable/setdate.xml
reference/datetime/datetimeimmutable/setisodate.xml
reference/datetime/datetimeimmutable/settime.xml
reference/datetime/datetimeimmutable/settimestamp.xml
reference/datetime/datetimeimmutable/settimezone.xml
reference/datetime/datetimeimmutable/sub.xml

The DateTimeImmutable class page doesn't depend on these roles. Followup to https://github.com/php/doc-en/pull/1011

Remove unnecessary DateTimeImmutable method synopsis roles

---

reference/mysqli/mysqli_driver.xml

https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.mysqli
https://github.com/php/php-src/pull/6407

mysqli_driver::$driver_version is deprecated and $embedded is removed

---

appendices/migration81/new-features.xml
language/functions.xml
language/predefined/closure/fromcallable.xml
language/types/callable.xml

Added the first class callable syntax docs, based on https://wiki.php.net/rfc/first_class_callable_syntax.

[PHP 8.1] Document the first class callable syntax.

---

chapters/tutorial.xml

We should not encourage use of Notepad for editing PHP files, and those
who use it, should at least know how it works (after all, it's not that
complex).

Drop Windows Notepad usage instructions

---

reference/mysqli/mysqli.xml
reference/mysqli/mysqli/construct.xml
reference/mysqli/mysqli/init.xml
reference/mysqli/mysqli/real-connect.xml
reference/mysqli/mysqli_driver.xml
reference/mysqli/mysqli_result.xml
reference/mysqli/mysqli_result/construct.xml
reference/mysqli/mysqli_stmt.xml
reference/mysqli/mysqli_stmt/bind-param.xml
reference/mysqli/mysqli_stmt/bind-result.xml
reference/mysqli/mysqli_warning.xml
reference/mysqli/mysqli_warning/construct.xml
reference/mysqli/versions.xml

Follow-up to https://github.com/php/doc-en/pull/301

Regenerate ext/mysqli class and method synopses from stubs

---

reference/dom/domattr.xml
reference/dom/domcharacterdata.xml
reference/dom/domdocument.xml
reference/dom/domdocumentfragment.xml
reference/dom/domdocumenttype.xml
reference/dom/domelement.xml
reference/dom/domentity.xml
reference/dom/domxpath.xml

These are only syntactical changes + a few include fallbacks and `oointerfaces` were added.

Generate ext/dom class synopses from stubs - part 2

---

reference/ffi/ctype/getalignment.xml
reference/ffi/ctype/getarrayelementtype.xml
reference/ffi/ctype/getarraylength.xml
reference/ffi/ctype/getattributes.xml
reference/ffi/ctype/getenumkind.xml
reference/ffi/ctype/getfuncabi.xml
reference/ffi/ctype/getfuncparametercount.xml
reference/ffi/ctype/getfuncparametertype.xml
reference/ffi/ctype/getfuncreturntype.xml
reference/ffi/ctype/getkind.xml
reference/ffi/ctype/getname.xml
reference/ffi/ctype/getpointertype.xml
reference/ffi/ctype/getsize.xml
reference/ffi/ctype/getstructfieldnames.xml
reference/ffi/ctype/getstructfieldoffset.xml
reference/ffi/ctype/getstructfieldtype.xml
reference/ffi/ffi.ctype.xml
reference/ffi/versions.xml

Currently, the FFI\CType class page warns due to the missing documentation of its methods.
Pages are generated by docgen.php

Add undocumented FFI\CType methods

---

appendices/migration80/new-features.xml
appendices/migration81/new-features.xml
language/oop5/variance.xml
language/types/declarations.xml

Not sure weather to prefer ``composite`` or ``compound`` types, so letting Twitter decide.
The diff is a bit crap because of the re-indenting of the union type sections within the composite type sections.
Moved redundant types out of the union types section as it applies more generally to composite types.

Restructure type declaration page & document Intersection types

---

language/types/declarations.xml

#982 is a great work, but the word `class-types` is misleading, especially for translators.
I considered it is only included classes, not interfaces.
refs: https://wiki.php.net/rfc/pure-intersection-types

Clarify class-types meaning in composite type description.

---

reference/errorfunc/ini.xml

I'm not sure if it's valuable to keep the note about the purpose of enabling E_NOTICE, as most of the information currently in this note is incorrect.
Also not sure how to enclose the old value, as ``<constant>`` is not a child of ``<code>`` or ``<literal>`` apparently...

Default value for error_reporting is E_ALL as of PHP 8.0.0

---

reference/sqlite3/sqlite3/exec.xml

SQLite3 does not have the 'STRING' data type. Please check https://www.sqlite.org/datatype3.html.

Updates a data type to a valid one in the example

---

reference/dom/book.xml
reference/dom/domchildnode.xml
reference/dom/domchildnode/after.xml
reference/dom/domchildnode/before.xml
reference/dom/domchildnode/remove.xml
reference/dom/domchildnode/replaceWith.xml
reference/dom/domnode/appendchild.xml
reference/dom/domnode/removechild.xml
reference/dom/domnode/replacechild.xml
reference/dom/domparentnode.xml
reference/dom/domparentnode/append.xml
reference/dom/domparentnode/prepend.xml
reference/dom/versions.xml

Add new `DOMChildNode` and `DOMParentNode` interfaces.

[PHP 8.0] Add new DOM interfaces

---

reference/opcache/ini.xml

I tried to tell JIT to compile every loop and function
by setting both opcache.jit_hot_loop and opcache.jit_hot_func
to 0, but failed to get the expected result.
After having read the source code and done simple experiments, I 
found that setting these two options to 0 will actually disable JIT to
compile any iterations and calls.
So I would like to add clarifications for this behavior in PHP manual.
Signed-off-by: Su, Tao <tao.su@intel.com>

Clarification for setting 0 to jit_hot_loop/func

---

language/enumerations.xml

Deprecated Features [Changelog](https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.static-trait)

[PHP 8.1] Calling a static element on a trait is deprecated

---

reference/openssl/functions/openssl-cms-decrypt.xml
reference/openssl/functions/openssl-cms-encrypt.xml
reference/openssl/functions/openssl-cms-sign.xml
reference/openssl/functions/openssl-cms-verify.xml

Fix wrong encoding constants being used in openssl-cms-x docs.

Fix openssl cms encoding constants

---

language/enumerations.xml

I think it's obvious that `->name` might be handy sometimes :-)

Deleting usage "limitation" to debugging

---

reference/opcache/ini.xml

As a new bird to PHP interpreter, I tried to set jit_bisect_limit
with jit=tracing in order to debug/probe PHP JIT feature, but
failed to hit my breakpoint and hence got confused.
I found that jit_bisect_limit only works under special JIT trigger
mode like 0: on script load, or 1: on first execution, after heavily
reading source code and trial-and-error experiments.
So, I would like to clarify the usage in PHP manual.
Hopefully, this can save time cost and reduce confusion of new PHP
interpreter developers.
The patch is verified on my local machine with phd build and the
web content and link looks good.
Signed-off-by: Su, Tao <tao.su@intel.com>

Clarification of jit_bisect_limit usage

---

reference/opcache/ini.xml

I once tuned jit_hot_func=300 in my php-fpm and did not catch 
the warning message, which is the main motivation for this patch 
after code reading.
This patch clarifies the usage of the four JIT tunable options -
jit_hot_{loop,func,return,side_exit} - in PHP manual which end users
should be aware of before they start to tune these options.
1. Valid value range
2. Default value will be used in case beyond valid range
3. Special case of zero value
The patch was verified on my machine with phd local website.
Signed-off-by: Su, Tao <tao.su@intel.com>

Clarification for usage of JIT tunable options

---

reference/pdo/pdostatement/bindparam.xml

https://www.php.net/manual/en/pdostatement.bindparam.php
___
It has no effect on input parameters, but is even passed in the examples.

PDOStatement::bindParam maxLength is confusing

---

reference/uopz/setup.xml

Directive `uopz.overloads` was misspelled as `uopz.exit` in the explanation section.

Fix ini directive name for uopz extension

---

reference/image/functions/gd-info.xml

Available since PHP 8.1.
Other related documentation: #983

Add return value "AVIF Support" to gd_info()

---

language/oop5/paamayim-nekudotayim.xml

The word "parents" in "When an extending class overrides the parents definition of a method,
PHP will not call the parent's method." needs to be changed to "parent's".

Grammer fix for paamayim-nekudotayim.xml docs

---

reference/strings/functions/substr.xml

Length parameter to substr() behaves differently for PHP8+. It recognizes null as if no value was provided at all. Updated the documentation to reflect this.

Update documentation for PHP8

---

reference/sodium/functions/sodium-crypto-kx-keypair.xml

Examples should use best practice, in this case it should show using the constant time sodium implementation of bin2hex and not the standard PHP version. This helps prevent timing attacks in code.

Should use constant time sodium_bin2hex in examples

---

reference/password/functions/password-hash.xml
reference/password/functions/password-verify.xml
reference/strings/functions/crypt.xml

> `password_verify` is compatible with `crypt`. Therefore, password hashes created by `crypt` can be used with `password_verify`.
Was added to `password_verify` and `crypt` and removed from `password_hash`. I believe it was added to `password_hash` instead of `password_verify`. Also fixed an error in `crypt` documentation confusing bytes and characters.

`password_verify` is capable of verifying `crypt` hashes

---

reference/array/functions/array-keys.xml

The definition of `search_value` in "Parameters" is a bit ambiguous. "these values" _could_ be interpreted to mean that if an array is passed as the `$search_value`, keys of elements of `$search_value` that match _any_ of those `$array` elements will be returned.
Note, the "Description" section does not have this ambiguity as it states "that value" instead of "those values".

Disambiguate semantics of `search_value`

---

appendices/migration80/incompatible.xml
appendices/reserved.xml

mixed is now reserved word as of PHP 8.0.0, so updated migration guide and reserved word list.
* trait
- https://3v4l.org/kZ0Mc
* class
- https://3v4l.org/5NCWs
* interface
- https://3v4l.org/FsR5g

mixed is a reserved word as of PHP 8.0.0.

---

appendices/migration81/incompatible.xml
appendices/reserved.xml

Similar to PR #938 for the PHP 8.0 `mixed` reserved word, this commit adds the new reserved word `never` to the list of "Other reserved words" and adds a mention of this to the Backward Incompatible Changes page in the migration guide.

PHP 8.1 | Other reserved words: add `never`

---

.github/workflows/integrate.yaml

A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
* https://github.com/actions/upload-artifact/releases

GH Actions: version update for various predefined actions

---

reference/curl/curlfile/construct.xml

This PR cleans up the examples for sending multiple files using curl. Currently, the examples are poorly formatted and hard to read with a `curl_setopt` function call being split up into two lines and beginning another `curl_setopt` call directly after it on the same line.
<details><summary>
<h4>Unformatted example</h>
</summary>
</details><details><summary>
<h4>Formatted example</h>
</summary>
</details>

Fix CURLFile multiple files examples

---

appendices/migration81/deprecated.xml

> GD:
> The `$num_points` parameter of `image(open|filled)polygon` has been deprecated.
Refs:
* https://github.com/php/php-src/blob/f67986a9218f4889d9352a87c29337a5b6eaa4bd/UPGRADING#L397-L398
* https://github.com/php/php-src/pull/6789
* https://github.com/php/php-src/commit/e1285c4aa5eba7d1cc2865400c0c165201f9e5f8

PHP 8.1 | MigrationGuide/Deprecated: add missing function

---

appendices/migration81/constants.xml

> * Added CURLOPT_DOH_URL option
> * Added certificate blob options when for libcurl >= 7.71.0:
>
>         CURLOPT_ISSUERCERT_BLOB
>         CURLOPT_PROXY_ISSUERCERT
>         CURLOPT_PROXY_ISSUERCERT_BLOB
>         CURLOPT_PROXY_SSLCERT_BLOB
>         CURLOPT_PROXY_SSLKEY_BLOB
>         CURLOPT_SSLCERT_BLOB
>         CURLOPT_SSLKEY_BLOB
Refs:
* https://github.com/php/php-src/blob/f67986a9218f4889d9352a87c29337a5b6eaa4bd/UPGRADING#L220-L229
* https://github.com/php/php-src/pull/6612
* https://github.com/php/php-src/commit/3dad63b5b25fc27604a38964b3bea885cbfbf1d3
* https://github.com/php/php-src/pull/7194
* https://github.com/php/php-src/commit/b11785c5e48437a0fd0e6935c52c372239838382
> GD:
> * Avif support is now available through the `imagecreatefromavif()` and
>     `imageavif()` …

PHP 8.1 | MigrationGuide/New constants: add missing constants

---

appendices/migration81/new-functions.xml

(mentioned in new features, but not in the new functions list)
> GD:
> * Avif support is now available through the `imagecreatefromavif()` and
>    `imageavif()` functions, if libgd has been built with avif support.
Refs:
* https://github.com/php/php-src/blob/f67986a9218f4889d9352a87c29337a5b6eaa4bd/UPGRADING#L245-L247
* https://github.com/php/php-src/pull/7026
* https://github.com/php/php-src/commit/81f6d36c90b8626660a6571cdc128265fa00697f
(mentioned in new features, but not in the new functions list)
> `mysqli_result::fetch_column()` has been added to allow fetching a single scalar value from the result set.
While only the method is mentioned in the RFC and the Migration guide, a procedural version of the same was also implemented.
Refs:
* …

PHP 8.1 | MigrationGuide/New functions: add missing functions

---

appendices/migration81/new-classes.xml

> Added `CURLStringFile`, which can be used to post a file from a string rather than a file
Refs:
* https://github.com/php/php-src/blob/f67986a9218f4889d9352a87c29337a5b6eaa4bd/UPGRADING#L231-L235
* https://github.com/php/php-src/pull/6456
* https://github.com/php/php-src/commit/e727919b97c4baeca93cb7700d4adf2e35a3530f
As part of the Fibers RFC/PR, the Reflection extension also received a new class.
* https://wiki.php.net/rfc/fibers
* https://github.com/php/php-src/pull/6875
* https://github.com/php/php-src/commit/c276c16b6627222c40bd43907475d664734b9abe
Note: I've not listed the `Fiber` and `FiberError` classes as those could be considered covered via the mention of Fibers on the "New Features" page, though happy to update the commit if so desired.

PHP 8.1 | MigrationGuide/New classes: add missing classes

---

reference/hash/functions/hash-algos.xml

> **MurmurHash3**
>
> Added support for MurmurHash3 with streaming support. The following variants are implemented:
> * murmur3a, 32-bit hash
> * murmur3c, 128-bit hash for x86
> * murmur3f, 128-bit hash for x64
>
> **xxHash**
>
> Added support for xxHash. The following variants are implemented:
> * xxh32, 32-bit hash
> * xxh64, 64-bit hash
> * xxh3, 64-bit hash
> * xxh128, 128-bit hash
Refs:
* https://www.php.net/manual/en/migration81.new-features.php#migration81.new-features.hash.murmurhash3
* https://github.com/php/php-src/pull/6059
* https://github.com/php/php-src/commit/72e91e9fc82b85d0c5a6ff043cd1b2daee6c26d0
* https://www.php.net/manual/en/migration81.new-features.php#migration81.new-features.hash.xxhash
* https://github.com/php/php-src/pull/6524
* …

PHP 8.1 | Update hash_algos() documentation

---

reference/mysqli/mysqli/connect-errno.xml
reference/mysqli/mysqli/connect-error.xml

This is an attempt to provide a code example that works both on PHP 8.0 and 8.1. Due to how broken this functionality is, I can't think of a reasonable example that would make sense. 
I removed the output as outputting this information is a really bad idea. 
I thought about putting an example such as 
```
<?php
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$mysqli = new mysqli();
try {
/* @ is used to suppress warnings */
@$mysqli->real_connect('localhost', 'fake_user', 'my_password', 'does_not_exist');
} catch (mysqli_sql_exception $e) {
/* Use your preferred error logging method here */
error_log('Connection error: ' . $mysqli->connect_error);
}
```
but in the end, I decided that the older one is more relevant. 
I also wanted to add a note about warnings and why we use …

Modernize examples on connect_error & connect_errno

---

reference/phar/versions.xml

- PharData::__construct and PharData::__destruct exists in PHP8.
- PharFileInfo::compress and PharFileInfo::decompress also.

Issue #1403 : PharData and PharFileInfo methods missing PHP8 compatibility 

---

reference/pdo/pdostatement/fetch.xml

The comment in the source code [goes](https://github.com/php/php-src/blob/04a4864b655b6ace1150e512179f23ec0d47566f/ext/pdo/pdo_stmt.c#L1152) as "if there are no more rows" and doesn't mention any failure.

Fix the return value description

---

reference/ev/evcheck.xml
reference/ev/evcheck/construct.xml
reference/ev/evchild.xml
reference/ev/evchild/construct.xml
reference/ev/evembed.xml
reference/ev/evembed/construct.xml
reference/ev/evfork.xml
reference/ev/evfork/construct.xml
reference/ev/evidle.xml
reference/ev/evidle/construct.xml
reference/ev/evio.xml
reference/ev/evio/construct.xml
reference/ev/evloop.xml
reference/ev/evloop/construct.xml
reference/ev/evperiodic.xml
reference/ev/evperiodic/construct.xml
reference/ev/evprepare.xml
reference/ev/evprepare/construct.xml
reference/ev/evsignal.xml
reference/ev/evsignal/construct.xml
reference/ev/evstat.xml
reference/ev/evstat/construct.xml
reference/ev/evtimer.xml
reference/ev/evtimer/construct.xml
reference/ev/evwatcher.xml
reference/ev/evwatcher/construct.xml

Drop the return value section at the same time.

Fix constructorsynopsis usage in EV extension

---

reference/var/functions/empty.xml

Previously it was written from the negative perspective, which was confusing to understand.

Improve description of `empty` return value

---

reference/intl/book.xml
reference/intl/intldatepatterngenerator.xml
reference/intl/intldatepatterngenerator/create.xml
reference/intl/intldatepatterngenerator/getbestpattern.xml
reference/intl/versions.xml

Add `IntlDatePatternGenerator` description ([RFC](https://wiki.php.net/rfc/intldatetimepatterngenerator)).
Implementation php/php-src#6771

[PHP 8.1] Add IntlDatePatternGenerator description

---

reference/array/functions/array-combine.xml

close https://github.com/php/doc-en/issues/849

Fix array_combine throws ValueError since PHP 8

---

reference/strings/functions/substr.xml

When strict types are enabled, passing false currently throws the following error:
> Fatal error: Uncaught TypeError: substr(): Argument #3 ($length) must be of type ?int, bool given
See https://github.com/php/php-src/pull/7533.

False isn't allowed for substr()'s $length

---

appendices/migration80/incompatible.xml

`DOMNamedNodeMap::removeNamedItem` is listed twice and I suspect the one after `DOMNamedNodeMap::setNamedItemNS` was meant to be `DOMNamedNodeMap::removeNamedItemNS` instead.

Fix listing of unimplemented DOM methods

---

reference/pdo/pdo/setattribute.xml
reference/pdo/pdostatement/getattribute.xml
reference/pdo/pdostatement/setattribute.xml

This, with #1457, fixes the remain (current) issues raised by the section order QA script #658.
After merging both of them we should add the check to CI so that a PR can't introduce section ordering issues.

Add missing param/return value sections

---

reference/ffi/book.xml

Foreign Function Interface (FFI) has been introduced in 2019 (PHP 7.4) and the API didn't change since then, it should probably be considered safe to use it.

Remove "experimental" warning from Foreign Function Interface (#1495)

---

language-snippets.ent
reference/iconv/functions/iconv.xml
reference/info/functions/get-extension-funcs.xml
reference/intl/uconverter/transcode.xml
reference/mbstring/functions/mb-convert-encoding.xml
reference/recode/functions/recode-string.xml
reference/strings/functions/utf8-decode.xml
reference/strings/functions/utf8-encode.xml
reference/strings/versions.xml
reference/wddx/examples.xml
reference/xml/versions.xml

- Move utf8_encode and utf8_decode into the strings chapter, since
they were moved out of the XML extension in 7.2
- Recommend mb_convert_encoding, iconv, and UConverter::transcode
when mentioning encoding in passing
- Document UConverter::transcode, based on examination of source
and upstream ICU docs
- Make the language used more consistent, e.g. "convert" rather
than "encode"/"decode", "encoding" rather than "charset"

Improve documentation of string encoding conversion functions

---

appendices/migration81/new-features.xml

The example seems not relevant to me since it already works and produces the same output in the previous PHP versions.

Fix unpacking with string key example

---

reference/pdo_mysql/constants.xml

The first change mentioned in the manual for `PDO::MYSQL_ATTR_LOCAL_INFILE_DIRECTORY` was 03f0ebc60c1e2c397ca81997646197d3d0cb4fed.
Then 607ec1f63c524e6951e7d3480377973788d495c5 stated about the version to which the constant was added.
However, it incorrectly appends to `MYSQL_ATTR_LOCAL_INFILE` instead of `MYSQL_ATTR_LOCAL_INFILE_DIRECTORY`.

PDO::MYSQL_ATTR_LOCAL_INFILE_DIRECTORY was added in PHP 8.1

---

reference/spl/appenditerator/construct.xml
reference/spl/arrayiterator/construct.xml
reference/spl/arrayobject/construct.xml
reference/spl/callbackfilteriterator/construct.xml
reference/spl/directoryiterator/construct.xml
reference/spl/filesystemiterator/construct.xml
reference/spl/filteriterator/construct.xml
reference/spl/globiterator/construct.xml
reference/spl/infiniteiterator/construct.xml
reference/spl/iteratoriterator/construct.xml
reference/spl/limititerator/construct.xml
reference/spl/multipleiterator/construct.xml
reference/spl/norewinditerator/construct.xml
reference/spl/parentiterator/construct.xml
reference/spl/recursivecachingiterator/construct.xml
reference/spl/recursivecallbackfilteriterator/construct.xml
reference/spl/recursivedirectoryiterator/construct.xml
reference/spl/recursivefilteriterator/construct.xml
reference/spl/recursiveiteratoriterator/construct.xml
reference/spl/recursivetreeiterator/construct.xml
reference/spl/splfileobject/construct.xml
reference/spl/splfixedarray/construct.xml
reference/spl/splheap/construct.xml
reference/spl/splpriorityqueue/construct.xml
reference/spl/splqueue/construct.xml
reference/spl/splstack/construct.xml
reference/spl/spltempfileobject/construct.xml

QA: remove return value section
Update some error sections
I dropped the error section when the exception was a ZPP like exception.

Update SPL class construtor pages

---

reference/intl/intltimezone/countequivalentids.xml
reference/intl/intltimezone/createdefault.xml
reference/intl/intltimezone/createenumeration.xml
reference/intl/intltimezone/createtimezone.xml
reference/intl/intltimezone/createtimezoneidenumeration.xml
reference/intl/intltimezone/fromdatetimezone.xml
reference/intl/intltimezone/getcanonicalid.xml
reference/intl/intltimezone/getdisplayname.xml
reference/intl/intltimezone/getdstsavings.xml
reference/intl/intltimezone/getequivalentid.xml
reference/intl/intltimezone/geterrorcode.xml
reference/intl/intltimezone/geterrormessage.xml
reference/intl/intltimezone/getgmt.xml
reference/intl/intltimezone/getid.xml
reference/intl/intltimezone/getidforwindowsid.xml
reference/intl/intltimezone/getoffset.xml
reference/intl/intltimezone/getrawoffset.xml
reference/intl/intltimezone/getregion.xml
reference/intl/intltimezone/gettzdataversion.xml
reference/intl/intltimezone/getunknown.xml
reference/intl/intltimezone/getwindowsid.xml
reference/intl/intltimezone/hassamerules.xml
reference/intl/intltimezone/todatetimezone.xml
reference/intl/intltimezone/usedaylighttime.xml

This one is pretty straightforard, since mostly only parameter names have changed, and return types are not documented.

Generate ext/intl methodsynopses based on stubs (IntlTimeZone)

---

reference/sodium/functions/sodium-crypto-stream-xchacha20-keygen.xml
reference/sodium/functions/sodium-crypto-stream-xchacha20-xor.xml
reference/sodium/functions/sodium-crypto-stream-xchacha20.xml
reference/sodium/versions.xml

Added `sodium_crypto_stream_xchacha20`, `sodium_crypto_stream_xchacha20_keygen`, and `sodium_crypto_stream_xchacha20_xor` functions.
Based on [stubs](https://github.com/php/php-src/blob/master/ext/sodium/libsodium.stub.php#L203-L207).

[PHP 8.1] Add new sodium functions

---

reference/dom/domdocument.xml

This is the **last class synopsis page which can be normally synced** (and doesn't already have a pending PR). There are some remaining smaller sync issues though (on a total of 15 pages). Some classes don't declare properties (`DateInterval`), or they include methods in a custom way (`DateTimeImmutable`), or explicitly document overridden methods (`SplQueue::__construct()`) etc. The rest of the diff between the docs and the output of gen_stubs comes from missing constant generation support (~ 40-50 pages).
I include a before-after print screen about the properties of DOMDocument because the diff is not easy to overview:
.

Reorder DOMDocument properties

---

reference/strings/functions/htmlentities.xml

This line now reads better when you're in a hurry (imo), and doesn't give the impression that ALL characters will be converted to entities.

Improve readability of htmlentities.xml

---

reference/reflection/reflectionattribute.xml

The constant `ReflectionAttribute::IS_INSTANCEOF` is missing from the [documentation](https://www.php.net/manual/en/class.reflectionattribute.php) entirely.
This PR adds the definition. I was unsure of the exact way to do it, but I made an educated guess based on the language and layout of other constant flags and reflection class constants (Most notably `array_filter` and `ReflectionMethod`).
I hope to create other PRs in the near future adding documentation to the `getAttributes()` methods on the various reflection classes, which will need to reference this constant.

Add missing constant definition ReflectionAttribute::IS_INSTANCEOF

---

reference/pdo/pdostatement/getcolumnmeta.xml

Since php/php-src@caa710037e663fd78f67533b29611183090068b2, all bundled drivers (Firebird and ODBC being the omissions before) implement this function. The third-party drivers, even the ones in massive states of disrepair, support it too. It's still optional, so a new PDO driver could take us by surprise, but the list is misleading, so just include the warning.

All drivers implement getColumnMeta

---

language/oop5/static.xml
language/variables.xml

Relates [Migration Guide](https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.core.static-variable-inheritance)

[PHP 8.1] Usage of static Variables in Inherited Methods

---

reference/reflection/reflectionfunctionabstract/getclosureusedvariables.xml
reference/reflection/versions.xml

Add `ReflectionFunctionAbstract::getClosureUsedVariables` description.
Based on [stubs](https://github.com/php/php-src/blob/PHP-8.1/ext/reflection/php_reflection.stub.php#L57).

[PHP 8.1] Add ReflectionFunctionAbstract::getClosureUsedVariables

---

language/functions.xml

Relates [Migration Guide](https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.null-not-nullable-internal)

[PHP 8.1] Passing null to non-nullable parameters of built-in functions

---

reference/zip/ziparchive/replacefile.xml

In all of the `ZipArchive` methods, the `index` is always described as `int` (see https://www.php.net/manual/en/class.ziparchive.php). Only for the `replaceFile` it is documented as `string`. However, actually passing a `string` will trigger (in PHP 8.1.5)
> Fatal error: Uncaught TypeError: ZipArchive::replaceFile(): Argument #2 ($index) must be of type int, string given
> TypeError: ZipArchive::replaceFile(): Argument #2 ($index) must be of type int, string given
The error also appears in other languages of the documentation. But _replacefile.xml_ is only present in this repo. So I assume the other language docs will be automatically fixed after merging this?

Fix type for index in ZipArchive::replaceFile

---

reference/reflection/reflectionclass/getattributes.xml

This PR updates the documentation  for the `ReflectionClass::getAttributes` method, including;
- Descriptions of parameters
- Example with no arguments
- Example with only `name` provided
- Example with `name` provided, and `flags` provided using `ReflectionAttribute::IS_INSTANCEOF`
The interface for the third example is called `Colour` (I'm from the UK), and I'm unsure of which spelling to go with. Am happy to change to `Color` if required.
If we can identify the ideal wording for any of this, once the PR is merged, if it is, I will go through and duplicate, with relevant examples, to all the following;
- `ReflectionClassConstant::getAttributes`
- `ReflectionFunctionAbstract::getAttributes`
- `ReflectionParameter::getAttributes`
- `ReflectionProperty::getAttributes`
<details>
<summary>If …

Add missing documentation for the ReflectionClass::getAttributes method

---

reference/errorfunc/functions/set-exception-handler.xml

This removes outdated PHP 5 information.

Reword parameter description of set_exception_handler

---

reference/ds/ds.collection.xml

Discovered in https://github.com/phpstan/phpstan/issues/7258.
`Ds\Collection` extends `IteratorAggregate` in both [the `php-ds/php-ds` polyfill](https://github.com/php-ds/polyfill/blob/master/src/Collection.php) and [the `ext-ds` extension](https://github.com/php-ds/ext-ds/blob/master/src/php/classes/php_collection_ce.c), so the documentation should be updated to reflect this.
Note that `Traversable` is removed from the `extends` because `IteratorAggregate` already extends `Traversable`.

Fix: `Ds\Collection` extends `IteratorAggregate`.

---

reference/openssl/functions/openssl-decrypt.xml
reference/openssl/functions/openssl-encrypt.xml

The `$aad` parameter in `openssl_encrypt` and `openssl_decrypt` is used to pass additional plaintext data that is `authenticated` (i.e. has integrity guaranteed, but no confidentiality). The current documentation uses the word `authentication` for this data, which is misleading and probably a typo of the intended `authenticated`.
The OpenSSL wiki uses `authenticated` consistently for the `$aad` parameter, and never `authentication`: https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption

Clarify `aad` parameter in openssl-encrypt

---

reference/mbstring/functions/mb-internal-encoding.xml

mb-internal-encoding() Thrown ValueError Thrown on invalid encoding since PHP8
Close #1611

mb-internal-encoding : ValueError Thrown on invalid encoding in PHP8

---

reference/zip/ziparchive/close.xml

ping @cmb69 
Simple copy/paste from libzip documentation
https://github.com/nih-at/libzip/blob/48695e84d566d87f36fb1328bb1880a4e9d8c1df/man/zip_close.mdoc#L50
To document (probably confusing) behavior.

ZipArchive::close deletes file if empty

---

language-snippets.ent
reference/ldap/functions/ldap-list.xml
reference/ldap/functions/ldap-read.xml
reference/ldap/functions/ldap-search.xml

Noticed that the array return type value was specified in the function signature but not in the documentation. I assume that it is an array of Ldap\Result :)
Additionally, the text about parallel searches seems to be out of date, as it is referencing the previous function signature. I also deleted a sentence that was confusing.

Update documentation for ldap_search()

---

reference/info/functions/get-defined-constants.xml
reference/misc/functions/constant.xml

These functions are somewhat similar in use and are useful to be linked. Also, I couldn't reach it from the sidebar because the function categories are different.

Add reference to get_defined_constants() and constant() each other

---

language/control-structures/return.xml

I think the expression about return statement on page "[return](https://www.php.net/manual/en/function.return.php)" is not as clear as that on page "[Migrating from PHP 7.0.x to PHP 7.1.x](https://www.php.net/manual/en/migration71.incompatible.php#migration71.incompatible.typed-returns-compile-time)".

Make the expression more clear

---

.editorconfig

@cmb69 Following our discussing https://github.com/php/doc-en/pull/1650. I'm not sure what editors this is configuration affects, but won't hurt.

Disable trim_trailing_whitespace in .editorconfig

---

reference/misc/functions/constant.xml

https://www.php.net/manual/en/function.constant.php
This updates the text from:
> An Error exception is thrown, if the constant is not defined.
to:
> If the constant is not defined, an Error exception is thrown.
The existing text is more difficult to read as it puts the condition behind the result. If the existing text is preferred, I'd remove the comma.

functions/constant Minor tweak to "errors" section

---

.github/workflows/check-whitespace.yml

Original work is in [git] github mirror.
With ~~local~~ upstream fixes of the comment on top ~~, stale since Jul 2021 changes
upstream~~.
[git]: https://github.com/git/git/blob/master/.github/workflows/check-whitespace.yml

Add white space checker script to CI

---

reference/sockets/constants.xml

> https://man7.org/linux/man-pages/man7/unix.7.html
> EBADF  This error can occur for [sendmsg(2)](https://man7.org/linux/man-pages/man2/sendmsg.2.html) when sending a file
>               descriptor as ancillary data over a UNIX domain socket
>               (see the description of SCM_RIGHTS, above), and indicates
>               that the file descriptor number that is being sent is not
>              valid (e.g., it is not an open file descriptor).
I think it is more appropriate to replace  `Bad file number` with `Bad file descriptor`.

fixed SOCKET_EBADF describe

---

reference/xml/examples.xml

The example uses the `$parser` as array index, but that implicit
conversion to integer already raises a notice as of PHP 7.0.0, and
outright fails as of PHP 8.0.0, since the `$parser` is an object now.
Since there doesn't appear a good reason for `$depth` to be an array
which supports different parsers, we change it to an integer, what also
simplifies the example.
This basically integrates user note 127199.

Fix XMLParser example for more recent PHP versions

---

language/control-structures/switch.xml

I cleaned out most of the comments on the `switch` page.  These are the bits worth including.

Expand switch description and examples to deprecate comments.

---

reference/pcre/functions/preg-replace.xml

refs: https://github.com/php/doc-en/pull/1671/commits/c69fbf081307b1bbdbc3ccffd09a3dc518d4d39a
In preg_replace function, `<parameter>replacement</parameter>` key is not preserved in return value.
We should replace it with `<parameter>subject</parameter>`, I think.
```php
<?php
/*
array(2) {
["subjectkey1"]=>
string(4) "bbbb"
["subjectkey2"]=>
string(4) "ccbb"
}
*/
var_dump(
preg_replace(
['pkey' => '/aa/'],
['rkey' => 'bb'],
['subjectkey1' => 'aaaa', 'subjectkey2' => 'ccaa']
)
);
```

fixed preserve key in return value of preg_replace.

---

reference/session/ini.xml

For consistency with all other constants, where the default value is also mentioned in the description so you don't have to go back to the table to look it up.

Added gc_maxlifetime default value to description

---

reference/filter/filters.xml

`FILTER_SANITIZE_STRING` and `FILTER_SANITIZE_STRIPPED` has been deprecated but were not added to the changelog in https://github.com/php/doc-en/pull/1193, only a note was added.

PHP 8.1: Update sanitize filters changelog with deprecations

---

reference/datetime/functions/strtotime.xml

I deleted another bunch of comments.  These are the changes worth keeping.
In particular, the current discussion of separator parsing is incorrect, as the new code sample shows.  It's quite bonkers.

strtotime() fixes from comments

---

language/enumerations.xml

This is a simple addition aimed to address #1564.
Looking at the documentation, I thought this would be the natural place for someone check such a difference as per the original poster of #1564.
This doesn't add the blog post link, nor go into technical detail, like discussed as options in the thread since I thought that goes too far into implementation detail, which is not stated for any other (arguably more significant) differences detailed for enums.

Added enum "Differences from objects" item regarding hoisting

---

reference/filter/filters.xml

It is not clear from the documentation that this filter accepts more than the listed values.
Eg. when using `FILTER_NULL_ON_FAILURE`, `null` is accepted (returns `false`, not `null`), which can be surprising.
Similarly, `'     1      '` (leading/trailing whitespace), `1.0` (float), and `new class { function __toString() { return '1'; } }` are also accepted.
It might also make sense to specifically add these values to the example values - cc #1475 for that.

FILTER_VALIDATE_BOOL: clarify non-string values

---

reference/opcache/ini.xml

Add more explanation for root trace and side trace in PHP manual.
Includes the influence when reach the maximum value of
opcache.jit_max_root_traces or opcache.jit_max_side_traces.
Signed-off-by:Wang, Xue <xue1.wang@intel.com>

Update document for jit_max_root_traces

---

reference/array/functions/array-udiff-assoc.xml

https://onlinephp.io?s=jVLBboMwDL0j8Q8WyqGRYCJsPWwU-ilRyIIaCQIKodU07d_nDCqycth8ip_93nPinM7jZYwj2YlpAmnhM44AY7T6KpwC4g-8V32jbLmU2tlIpweD3QdyFR1d4JXog7iLnrI6oEIFvnVV-Iqj5TA54bQMFId-5D7jXlukQJq9um4Baw_yFRo0vzAKVrnZGsjLjbtCO369Y5-BvWVsG_hnZiLwIsJa8XFI8ieWQFWDUTf_Eq80BcSOIcYKBPMAKJ4RYFv-gmkR1DN2pClFU9KERsVfRsWj0X990Mmqae7c3Y7P77ptOX6GQa4bSO-DSJugdbijhHoRfDbjOC5skaLlNw%2C%2C&v=8.1.8%2C8.0.21%2C7.4.30

fix: add php8 array_udiff_assoc compatibility

---

reference/array/functions/array-udiff-uassoc.xml

https://onlinephp.io?s=jZLdboMwDIXvkXgHC3HRSDARtl5sDPooUciCGpU_haRTNe3d5wyqZkUTjbiIj-PzWdjvh_E4hoFo-TSB0PAVBoBn1OrMjYTYXVgnu1rqYk41thdGDT2-3sVn3pJZXgrdic1RTWnllUIJ7uni8B0G82Uy3CjhOQ7dyFzEnDdPIK7X7qoBzN3Zlwio_2gEtDRW95AVt9pFWtVXq-oD0LeUPt7wSV42Ol6a3Ojrt5UVHT9nAFxrftlF2RONoKygl59uCq8kAdT2vkZzFDNPyJ9RoLf4BcPcy6d0TxKCyLj2QfkWKL8HPcpBkpaTbc0Vx-yHahpmcRMHsfzM5NqJ0BGy_QWJyL9JHEZEHAMn2huGuzSTSPED&v=8.1.8%2C8.0.21%2C7.4.30

fix: add php8 array_udiff_uassoc compatibility

---

reference/mysqli/mysqli_result/data-seek.xml

From manual page: https://php.net/mysqli-result.data-seek
---
In the parameters section the part explaining the offset has the following line. 
> The field offset. Must be between zero and the total number of rows minus one (0..[mysqli_num_rows()](https://www.php.net/manual/en/mysqli-result.num-rows.php) - 1).
Shouldn't the **field offset** be **row offset** ?

Parameter offset explanation refers to field when it should be row.

---

reference/snmp/functions/snmp3-get.xml
reference/snmp/functions/snmp3-getnext.xml
reference/snmp/functions/snmp3-real-walk.xml
reference/snmp/functions/snmp3-walk.xml

See https://github.com/php/php-src/blob/PHP-8.1.0/UPGRADING#L590
https://github.com/php/php-src/commit/718e91343fddb8817a004f96f111c424843bf746

snmp: add SHA256 and SHA512 for security protocol in 8.1

---

reference/dom/domdocument/registernodeclass.xml

`DOMDocument::registerNodeClass` with `DOMDocument` is possible and can be useful.
Fixes GH-1733
/cc @cmb69

Fix GH-1733: registerNodeClass can be used with DOMDocument

---

language/oop5/magic.xml

In the current manual, the following is seen: "...if a very large objects...", where it should use the singular form. This PR fixes that so it becomes "...if a very large object...".

Fix minor typo (the word "object" should be singular)

---

reference/var/functions/is-numeric.xml

`filter_var` is a cool way to solve some of the [limitations](https://github.com/php/php-src/issues/9311) of `is_numeric` and therefore I suggest adding it in the see also section.

Add filter_var() to is_numeric() see also section

---

reference/datetime/datetime.xml

Using "the DateTimeInterface" instead of a DateTime object makes no sense, using a DateTimeImmutable instead of a DateTime does.

DateTime: change suggestion to DateTimeImmutable

---

language/types/array.xml

Supercedes #145 and #451
I know that this duplicates the information from https://www.php.net/manual/en/function.list.php but I believe this information belongs on the array page. Unless we can somehow have a dedicated page for "array destructuring" that wouldn't be `list`-centric then I think having this information in both places is beneficial. Fewer people are using `list()` and nudging people to use the short syntax should be our goal. 
We could have a separate "book" for arrays, but it's also not really necessary. The page is long but not that long.

Array destructuring

---

language/oop5/inheritance.xml
language/predefined/arrayaccess/offsetexists.xml
language/predefined/iterator.xml

These backslashes were previously added in 214335df7e8b11b517779aa3420d794f343a7309, 081cf71ecb97b239c1e07beaadb71af0b0c42764, and cfaa7659dab118ecf6b420c550a6b8183f4190ad
Based on previous discussion in https://github.com/php/doc-en/pull/1560, I think these can be removed. I'll note that these were the only examples in the manual that included a leading backslash for ReturnTypeWillChange.
The code examples do not use a namespace and refer to other global classes without a FQCN (e.g. Iterator); however, it's possible the ReturnTypeWillChange backslash was intentional. IIRC, attributes don't require a class to be defined so users blindly copying these examples into a namespaced file might encounter an unexpected error (unlike a missing Iterator interface, which would be very clear). In …

Remove backslash prefix for some ReturnTypeWillChange attributes

---

reference/soap/soapclient/construct.xml

`SoapClient::getLastRequest` does not exist. 
The correct name is `SoapClient::__getLastRequest`
Same issue with `getLastRequestHeaders`, `getLastResponse`, and `getLastResponseHeaders`

SoapClient::__construct - Fix method names referenced in trace option

---

reference/var/functions/is-numeric.xml

Considering this output : 
https://onlinephp.io?s=nY4xC8IwEIX3QP7Dozi0ULWWLqLiJDiI7eAmUmq52qAmJYkiSP-7EUu3Lt70uPv47i3XTd1wNrJkrMEKR87gxkMSe2GXkxh9xjyKZl6I6RRSyfFZU3EV8gLTFCV1zBfBMHNacMZZpdy6rOF3rwuDEd3oTtIGeP9MooIvTC4fd9Ki9Pt7D3yHylrhWeicXo3StqdCWP2gABNXWhh0Elcr22b5Jt0tfooWdDP0h3CfHoalnLUf&v=8.1.9%2C8.0.22%2C7.4.30%2C7.0.33
Output for `is_numeric` are not the displayed ones on documentation.

Fix `is_numeric` example snippet

---

language/enumerations.xml

Per #1780, if we're telling people to use CamelCase for enum cases, the docs should do so consistently.

Standardize casing for Enum examples.

---

reference/win32service/constants.xml

Hi,
I'm the Win32Service PHP extension maintainer.
In Win32Service documentation, the constant values of `WIN32_SC_ACTION_REBOOT` and `WIN32_SC_ACTION_RESTART` is inverted.
Thank you a lot.

Fix Win32Service constant value error

---

reference/info/functions/get-loaded-extensions.xml

copied from https://3v4l.org/gcKp8
to stress the names are not in LC and `Core` is present

Update get_loaded_extensions() output example

---

reference/pdo/pdo/prepare.xml

This PR replaces `array()` with square brackets `[]` in [PDO::prepare](https://www.php.net/manual/en/pdo.prepare.php) method examples. Right now they are inconsistent.

Fix PDO::prepare code style

---

reference/dba/constants.xml

Ref:
php/php-src#8892
https://github.com/php/php-src/blob/PHP-8.2/ext/dba/dba.stub.php

[PHP 8.2] Add DBA flag constants

---

reference/sodium/functions/sodium-crypto-stream-xchacha20-xor-ic.xml
reference/sodium/versions.xml

Refs:
https://github.com/php/php-src/pull/8276
https://doc.libsodium.org/advanced/stream_ciphers/xchacha20#usage
/cc @paragonie-security

[PHP 8.2] Add `sodium_crypto_stream_xchacha20_xor_ic` description

---

reference/pdo/error-handling.xml

Using try catch is irrelevant to examples and echoing errors out unconditionally is a bad practice.

Removing try-catch from examples

---

reference/pdo/pdostatement/rowcount.xml

This puts emphasis on the important part. Some have claimed that rowCount will return inconsistent, untrue or broken results. That's not true.

Improve rowCount explanation

---

reference/image/functions/getimagesize.xml

Ref:
https://github.com/php/php-src/blob/PHP-8.2/UPGRADING#L303

[PHP 8.2] Update `getimagesize` description

---

appendices/ini.list.xml
appendices/migration82.xml
appendices/migration82/constants.xml
appendices/migration82/deprecated.xml
appendices/migration82/incompatible.xml
appendices/migration82/new-features.xml
appendices/migration82/new-functions.xml
appendices/migration82/other-changes.xml
appendices/migration82/windows-support.xml
reference/errorfunc/ini.xml
reference/mysqli/ini.xml
reference/sqlite3/ini.xml

Will need a doc-base change to be added to the live version.
This covers the UPGRADING file.
I think it is best to merge this ASAP and handle adding examples and links in other PRs as needed.

Add initial version of the PHP 8.2 migration guide

---

language-snippets.ent
reference/csprng/functions/random-bytes.xml
reference/csprng/functions/random-int.xml

Hey there :vulcan_salute:
this will add docs about the changes in PHP 8.2 to the `random_bytes` and `random_int` functions as per https://github.com/php/php-src/pull/9220
Kind regards
Florian
Refs: #1803

add docs for `random_int`/`random_bytes` changes in PHP 8.2

---

reference/info/functions/memory-get-peak-usage.xml
reference/info/functions/memory-reset-peak-usage.xml
reference/info/versions.xml

Hi there,
this will add documentation for `memory_reset_peak_usage()` as found in #1803
Kind regards
Florian

Add docs for `memory_reset_peak_usage()`

---

reference/filter/filters.xml

Hey there :vulcan_salute: 
this will add documentation for `FILTER_FLAG_GLOBAL_RANGE` as found in #1803 and added to PHP 8.2 with https://github.com/php/php-src/commit/d8fc05c05eb6fe189a663c599421a8457bc6c767
I was thinking to write down all global IP ranges (as you can see in the docs for `FILTER_FLAG_NO_PRIV_RANGE`), but it turns out that these are quite a few. So I thought it might be sufficient to link to the RFC where those global ranges are defined.
WDYT?
Kind regards
Florian

add `FILTER_FLAG_GLOBAL_RANGE` documentation

---

reference/mbstring/functions/mb-check-encoding.xml

Passing null or omitting the arguments is deprecated as of this RFC https://wiki.php.net/rfc/deprecations_php_8_1

[PHP 8.1]  Calling mb_check_encoding() without argument is deprecated

---

reference/memcached/memcached/construct.xml

prototype is `?string $persistent_id=null`   - UNTESTED, i don't know if `<type>?string</type>` is actually valid or not.. someone should double-check that before merging

the default argument is nullable

---

reference/filesystem/functions/tempnam.xml

Updates a comment in the example as "do something here" is a more complete sentence than "do here something".

Fix grammar in code example comment

---

appendices/ini.list.xml
appendices/migration82/other-changes.xml
language/oop5/autoload.xml
reference/var/functions/unserialize.xml
reference/var/ini.xml

Resolves #1822 
I initially set out to resolve just #1822 but noticed `max_depth` also wasn't documented as an option, so I took a swing at that, as well.

Document unserialize max_depth option

---

reference/array/functions/array-change-key-case.xml

Function throws `Fatal error: Uncaught TypeError: array_change_key_case(): Argument #1 ($array) must be of type array` which is default value of generic incorrect type passed to the function. It's not anymore internal behavior of the function.

Outdated information about warning of array_change_key_case

---

reference/mysqli/mysqli/execute-query.xml
reference/mysqli/mysqli/prepare.xml
reference/mysqli/mysqli/query.xml
reference/mysqli/mysqli_stmt/prepare.xml
reference/mysqli/versions.xml

I hope I haven't made any mistakes. :)

[PHP 8.2] Document mysqli_execute_query

---

language-snippets.ent
reference/mongodb/mongodb/driver/clientencryption/addkeyaltname.xml
reference/mongodb/mongodb/driver/clientencryption/createdatakey.xml
reference/mongodb/mongodb/driver/clientencryption/deletekey.xml
reference/mongodb/mongodb/driver/clientencryption/getkey.xml
reference/mongodb/mongodb/driver/clientencryption/getkeybyaltname.xml
reference/mongodb/mongodb/driver/clientencryption/getkeys.xml
reference/mongodb/mongodb/driver/clientencryption/removekeyaltname.xml
reference/mongodb/mongodb/driver/clientencryption/rewrapmanydatakey.xml
reference/mongodb/versions.xml

Moves the masterKey docs to a common snippet, since it's duplicated for createDataKey and rewrapManyDataKey.
Also adds missing docs for the KMIP provider's masterKey document, which was introduced in version 1.12.
https://jira.mongodb.org/browse/PHPC-2093
https://jira.mongodb.org/browse/PHPC-1912

Document Key management API for ext-mongodb 1.15

---

reference/mysqlnd/install.xml

We don't have to use MySQL Client Library(libmysqlclient) for installing MySQL database extension, because we already have mysqlnd.

Removed obsolete mysqlnd install description.

---

reference/strings/functions/levenshtein.xml

The character limit on the 2 string arguments for the levenshtein function was removed in PHP 8. The documentation should be updated to reflection this difference. 
https://github.com/php/php-src/commit/6a8c094e2d86a8d9294e4d7fddabd9486bc92ed8

Update return value for levenshtein

---

reference/intl/messageformatter/format-message.xml
reference/intl/messageformatter/parse-message.xml
reference/intl/numberformatter/format-currency.xml
reference/intl/numberformatter/format.xml

Document a way how to get currency formatted with narrow currency symbol as discussed in #1897.

Fix #1897: Document limits of NumberFormatter and possible workaround

---

reference/dom/domnode.xml

The fieldsynopsis above documents it as non-nullable, so don't say it can be null. Checking the source of dom_node_prefix_read(), it has always returned a string since the initial commit, it can't return null.

DOMNode::$prefix is not nullable

---

reference/hash/functions/hash-equals.xml
reference/hash/functions/hash-hkdf.xml
reference/hash/functions/hash-hmac-file.xml
reference/hash/functions/hash-hmac.xml
reference/hash/functions/hash-init.xml
reference/hash/functions/hash-pbkdf2.xml

Update the manual for the changes to the hash functions by Mark Randall in August 2019 and subsequent tweaks by Máté Kocsis in March 2020.
Build tested.

Updates for hash functions that now throw errors

---

reference/dba/functions/dba-fetch.xml

The overloaded signature is still supported but discouraged.

dba_fetch() signature has changed to follow userland semantics

---

reference/session/functions/session-unset.xml

This was meant to be used when  was still around.
Fixes #1906

Rewrite outdated note for session_unset()

---

.gitattributes

This should fix the repository's language statistics, so that it doesn't show as HTML, due to one HTML file.
see https://github.com/github/linguist/blob/master/docs/overrides.md#detectable

Mark `*.xml` as `linguist-detectable`

---

.gitattributes

see php/doc-en@91bdc784307128c56aeb90e91772b0cca254d36f

Configure linguist highlighting for `*.ent` files

---

reference/ssh2/functions/ssh2-shell.xml

This is reflected as `termtype` - https://github.com/php/pecl-networking-ssh2/blob/master/ssh2.c#L1427.
Found while updating psalm function maps.

Fix ssh2_shell termtype parameter name

---

language/oop5/properties.xml

Because obviously this is not documented *sigh*

Document dynamic properties

---

reference/apcu/ini.xml

The current documentation implies that the apc.ttl setting would mark all cache
entries as liable to be evicted if they have not been accessed in this many
seconds. However, apc_cache_entry_expired() and apc_cache_entry_soft_expired()
reveal that apc.ttl is only taken into account for entries that do not have an
explicit TTL set. Accordingly, clarify that the effect of apc.ttl is limited
only to entries that do not have an explicit TTL set.

[apcu] Clarify the effect of apc.ttl

---

language-snippets.ent
reference/array/constants.xml
reference/strings/functions/lcfirst.xml
reference/strings/functions/setlocale.xml
reference/strings/functions/str-ireplace.xml
reference/strings/functions/stripos.xml
reference/strings/functions/stristr.xml
reference/strings/functions/strripos.xml
reference/strings/functions/strtolower.xml
reference/strings/functions/strtoupper.xml
reference/strings/functions/ucfirst.xml
reference/strings/functions/ucwords.xml

* Add a detailed description of what is meant by ASCII case conversion to strtolower() and strtoupper().
* Replace locale-related text on ucfirst(), lcfirst() and ucwords() with text about ASCII case conversion.
* Remove entity note.locale-single-byte since it was only used on ucwords().
* Add changelog entries to all the functions mentioned in the RFC.

Updates for RFC: Locale-independent case conversion

---

language-snippets.ent

There are two reasons for this:
- It's standard functionality that a TypeError will be thrown for improper parameter types. This is nothing special for the CSPRNG functionality.
- The snippet is now also used for `Secure::generate()` which does not take any parameters.

random: Remove TypeError listitem from `&csprng.errors;`

---

language/exceptions.xml

So this conflict a tiny bit with my PR #320.
But this will fix the fact that the examples start their number at 3.
The reason for that is the numbering starts within the previous ``<sect1>`` but this is not rendered on the page, but in a follow-up page.
However, we cannot put this sections after the ``<simplesect>`` as that doesn't respect the DTD: https://tdg.docbook.org/tdg/5.0/chapter.html
Thus, we convert them to ``<sect1>``, this however makes them render into different pages (which might actually be better as it stops having so much on the same page).
@TimWolla this should be a helpful explanation :)

Change simplesect to sect1 in exception chapter

---

language/oop5/basic.xml

RFC: https://wiki.php.net/rfc/readonly_classes

Document readonly classes

---

reference/reflection/reflectionclass/isreadonly.xml
reference/reflection/versions.xml

We added readonly class documentation in #1996, but ReflectionClass::isReadOnly is missing.

added ReflectionClass::isReadOnly documentation.

---

reference/array/functions/array-rand.xml
reference/array/functions/shuffle.xml
reference/misc/functions/uniqid.xml
reference/openssl/functions/openssl-random-pseudo-bytes.xml
reference/random/functions/random-bytes.xml
reference/random/functions/random-int.xml
reference/strings/functions/str-shuffle.xml

Basically:
- Point to Randomizer where useful.
- Do not point from Randomizer to elsewhere (except random_int, random_bytes), developers should use the new API.

random: Clean up cross-references for randomness related functions

---

reference/random/functions/random-bytes.xml
reference/random/functions/random-int.xml
reference/random/random/engine/mt19937/generate.xml
reference/random/random/engine/pcgoneseq128xslrr64/generate.xml
reference/random/random/engine/pcgoneseq128xslrr64/jump.xml
reference/random/random/engine/secure/generate.xml
reference/random/random/engine/xoshiro256starstar/generate.xml
reference/random/random/engine/xoshiro256starstar/jump.xml
reference/random/random/engine/xoshiro256starstar/jumplong.xml
reference/random/random/randomizer/getint.xml

I intentionally didn't touch the function [we plan to deprecate with 8.3](https://wiki.php.net/rfc/deprecations_php_8_3#global_mersenne_twister) to not add unnecessary churn for the translators.

random: Improve short descriptions for methods

---

language-snippets.ent
reference/memcached/memcached/delete.xml
reference/memcached/memcached/deletebykey.xml
reference/memcached/memcached/deletemulti.xml
reference/memcached/memcached/deletemultibykey.xml

* Note that it's always an error to specify a non-zero time parameter, and delete the long-winded explanations of what it is meant to do.
* Expand the description of the return value from deleteMulti().
* Replace the incorrect description of the return value of deleteMultiByKey(). Use the one from deleteMulti() instead.
* Explain what getResultCode() will return after deleteMulti().

Improve documentation of the Memcached delete methods

---

reference/datetime/datetimeimmutable/construct.xml

The first parameter for `DateTimeImmutable::__construct` is expected to be string. But in the **_Example `#2` Intricacies of DateTimeImmutable::__construct()_** for the example, 'Current date/time in the specified time zone' `null` is used instead of `now`.
**Current**
```php
// Current date/time in the specified time zone.
$date = new DateTimeImmutable(null, new DateTimeZone('Pacific/Nauru'));
echo $date->format('Y-m-d H:i:sP') . "\n";
```
**Expected**
```php
// Current date/time in the specified time zone.
$date = new DateTimeImmutable('now', new DateTimeZone('Pacific/Nauru'));
echo $date->format('Y-m-d H:i:sP') . "\n";
```

Update now instead of null in the example for DateTimeImmutable::__construct

---

reference/random/random/engine/pcgoneseq128xslrr64/jump.xml

Contrary to xoshiro256**’s `jump()` methods (https://www.php.net/manual/en/random-engine-xoshiro256starstar.jump.php) I was not able to think of a “prime use case”. While “splitting the engine” also works with PCG, it works less great due to the smaller overall state and the fact that jump distance is limited by `PHP_INT_MAX`, which is in the realm of collision for 32 Bit PHP at least.
So a simple description of the functionality it is, unless @zeriyoshi has some ideas of what could be added?

random: Add description to PcgOneseq128XslRr64::jump()

---

language/oop5/traits.xml

The docs for traits probably need a good overhaul.
@sj-i could you have a look as you wrote the RFC.

Update trait docs for PHP-8.2

---

appendices/migration81/new-features.xml
language/oop5/properties.xml
language/oop5/variance.xml
language/types.xml
language/types/boolean.xml
language/types/declarations.xml
language/types/integer.xml
language/types/iterable.xml
language/types/literal.xml
language/types/mixed.xml
language/types/never.xml
language/types/null.xml
language/types/relative-class-types.xml
language/types/string.xml
language/types/type-juggling.xml
language/types/type-system.xml
language/types/void.xml

To incorporate typing features added in PHP 8.2.0 and also (hopefully) future proof for additional additions.
This is still a bit WIP as I haven't added DNF types but I already wanted to get some eyes on it to gather some opinions.
I've taken a bit of inspiration from the Rust manual: https://doc.rust-lang.org/reference/types.html

Rewrite type section

---

.github/workflows/integrate.yaml

Currently phpdoc github actions workflow fails in some locale, because we specify "runs-on: ubuntu-latest". `ubuntu-latest` is currently transitioning to ubuntu-22.04, so we take workarounds with `runs-on: ubuntu-20.04`.
----
ubuntu-latest is currently transitioning to ubuntu-22.04. During this time, you may experience some jobs running on either an ubuntu-20.04 or ubuntu-22.04 runner. You can specify `runs-on: ubuntu-20.04` in your workflow if you need the previous version.
https://github.com/actions/runner-images
https://github.com/actions/runner-images/issues/6399

Ubuntu-latest workflows will use Ubuntu-22.04, temporary workaround

---

reference/info/functions/ini-parse-quantity.xml
reference/info/versions.xml

Hello there :vulcan_salute:
this will add the documentation for the `ini_parse_quantity` function as found in #1803 
Kind regards
Florian

add docs for `ini_parse_quantity` function

---

language/oop5/properties.xml

"Existant" is a common misspelling of "Existent". Also, 'non' should act as a prefix to the word, either being hyphenated or treated as a compound word ("nonexistent").  I'm leaving it alone for now.

Fix spelling

---

reference/tokenizer/phptoken.xml
reference/tokenizer/phptoken/construct.xml
reference/tokenizer/phptoken/getTokenName.xml
reference/tokenizer/phptoken/is.xml
reference/tokenizer/phptoken/isIgnorable.xml
reference/tokenizer/phptoken/toString.xml
reference/tokenizer/phptoken/tokenize.xml

Based on https://github.com/php/php-src/pull/9901

Update ext/tokenizer role attributes

---

appendices/migration82/incompatible.xml
reference/spl/filesystemiterator/construct.xml
reference/spl/filesystemiterator/current.xml
reference/spl/filesystemiterator/key.xml
reference/spl/filesystemiterator/setflags.xml

Hello, I'm updating documentation for [FilesystemIterator::__construct](https://www.php.net/manual/en/filesystemiterator.construct.php).
Before PHP 8.2 the `FilesystemIterator::SKIP_DOTS` was always set and couldn't be removed, this changed in PHP 8.2.
If you are using the default value for `flags` parameter then everything work as expected, but if you are using any other value you have to add `FilesystemIterator::SKIP_DOTS` to maintain old behavior. 
You can see an example in <https://3v4l.org/HrmZ2>.
This already provoked a bug (see https://github.com/phingofficial/phing/pull/1685), that's why I also updated documentation in "breaking changes" section.
This change was added in https://github.com/php/php-src/commit/088e5478029f7b3482a9c5ae2b06b77772b92480 and as far as I know it's not …

Update FilesystemIterator::__construct doc for php 8.2

---

reference/ldap/functions/ldap-first-attribute.xml
reference/ldap/functions/ldap-next-attribute.xml

The docs for ldap_first_attribute and ldap_next_attribute note that PHP accepts a third, deprecated argument, `$ber_identifier` without raising an error.
In fact, passing 3 parameters to these functions has been an ArgumentCountError since PHP 8.0.0 (see php/php-src@eeec37d31d6aa4452d83e2640aee7c8c25349617).
For both functions, this change removes the argument from the list, removes the note indicating that a third argument can be passed, and adds the change at version 8.0.0 to the changelog.

ldap: Document removal of ber_identifier param

---

language/types/type-juggling.xml

The big one is the need to clarify the behaviour around the coercive typing mode, as the conversion of objects to strings is relatively straight forward but in theory internal objects that overload the cast handler can convert to other types too.

Nits to the type juggling page

---

appendices/migration70/incompatible/other.xml

The title refers to "break and switch" when it means "break and continue".

Fix typo in PHP 7.0 migration guide

---

reference/misc/functions/usleep.xml

It is unnatural that the only example exceeds that number even though <q>may not be supported by the operating system</q> is mentioned. Also, it makes sense to show that you can sleep with sub-second accuracy.
> Note: Values larger than 1000000 (i.e. sleeping for more than a second) may not be supported by the operating system. Use [sleep()](https://www.php.net/manual/en/function.sleep.php) instead.
Linux timers seem to work with this precision: https://3v4l.org/1GI6a

Better example for usleep()

---

language/oop5/traits.xml

The example code contained three errors:
* Reference to non-existent `ConstantTrait` trait (x2).
* Instantiation of non-existent `ConstantExample` class.
* Reference to an undefined constant.
Fixed now.

OOP5/Traits/Constants: fix example code

---

reference/datetime/functions/date.xml

Duplicate the note because users who tried to use `date()` get confused about the format for microseconds.
refs https://github.com/php/doc-en/pull/2113

Duplicate note on microsecond precision from datetime.formats

---

reference/datetime/functions/date.xml

The documentation hints that `timestamp` can be non-numeric, but that will cause a `TypeError` since PHP 8.0.

Update return value description for date()

---

reference/reflection/reflectionclass/gettraitaliases.xml

This was dropped with the RETURN_THROWS conversions.

Remove outdated ReflectionClass::getTraitAliases() null return description

---

reference/reflection/reflectionclass/gettraitnames.xml

This was dropped with the RETURN_THROWS conversions.

Remove outdated ReflectionClass::getTraitNames() null return description

---

language/predefined/interfaces.xml
language/predefined/sensitiveparametervalue.xml
language/predefined/sensitiveparametervalue/construct.xml
language/predefined/sensitiveparametervalue/debuginfo.xml
language/predefined/sensitiveparametervalue/getvalue.xml
language/predefined/versions.xml

Some parts (long description for `getValue()` and general refining) are still missing, but having something is better than having nothing and these parts should allows folks to build onto it.

Add SensitiveParameterValue documentation

---

reference/pdo/pdostatement/fetchall.xml

This was missed in review. The overloaded signature is not identical to `setFetchMode`. 
Additionally, specified that these parameters do not work with named parameters.

Redesign parameter list for PDO_Statement::fetchAll

---

reference/reflection/reflectionfunction/getclosure.xml

Remove ReflectionFunction::getClosure() null return description

---

reference/xml/functions/xml-get-current-byte-index.xml

This was dropped during conversion to object in https://github.com/php/php-src/commit/e35a3cb28cd663489b27630e4dca2a5e61898f2e so no new exceptions were added that require a changelog.

Drop xml_get_current_byte_index() return false description

---

reference/random/functions/random-int.xml
reference/random/random/randomizer/getint.xml

It’s impossible to pass an integer that does not fall into the documented range, making this useless information. Integers outside these ranges will be converted into floats, making those a TypeError.

random: Drop the range constraints from getInt()/random_int()

---

language/oop5/decon.xml
reference/reflection/reflectionproperty/getdefaultvalue.xml

Noticed this in https://3v4l.org/vZrFf - surprising behavior but clearly documented in https://wiki.php.net/rfc/constructor_promotion#desugaring.  Writing a similar example and adding a note to `ReflectionProperty::getDefaultValue()`.

Add note that ReflectionProperty::getDefaultValue() does not copy from promoted property

---

reference/spl/functions/spl-autoload-functions.xml

I've updated the return description and added a changelog for `spl_autoload_functions` to reflect the changes made in php/php-src@5b59d49.
This closes php/doc-en#2185 and ollieread/php-doc-en#14.

Added changelog to reflect changed return type of spl_autoload_functions

---

reference/spl/splfileobject/fgets.xml

This was converted to an exception, but looks like that's already in the errors section.

Drop SplFileObject::fgets() return false description

---

reference/random/random/engine/mt19937/generate.xml
reference/random/random/engine/pcgoneseq128xslrr64/generate.xml
reference/random/random/engine/secure/generate.xml
reference/random/random/engine/xoshiro256starstar/generate.xml

This method is not meant to be used directly and showcasing some random bytes of fixed length does not provide a value-add for the reader.

random: Drop example section from the `generate()` method of the Engines

---

reference/random/book.xml

This patch reorders the engines in the overview to list the “Secure” engine first, as that is the preferred engine for the majority of use cases. As a side effect the CryptoSafeEngine interface is documented right after the Engine interface.
The other engines remain sorted alphabetically.

random: Reorder engines documentation

---

reference/password/functions/password-hash.xml
reference/password/functions/password-verify.xml

Successful validation should usually be followed by re-hashing the
password, if necessary.  The `password_needs_rehash()` docs already
have a good example, but the `password_verify()` page does not mention
that at all.  Instead of duplicating the example, we refer to it.
We also remove the link to the password compatibility library, since it
is no longer relevant for the manual.

Make password_needs_rehash() more prominent

---

language/generators.xml

`iterator_to_array()` second parameter's name is `preserve_keys` and not `use_keys` as it is currently stated.
This is useful when using named parameters.

Fixes iterator_to_array parameter name

---

reference/array/functions/array.xml

(Refering to the code differential)
2 indexes are indices.
Regarding "overwrites," below there's an assumed meaning/reference in this clause.   "the last (index/one) overwrites the first (index/one)."  And this is perfectly fine to write it with these assumed words, but since that assumed thing is **singular**, the verb needs to have an 's' at the end (not because the verb is plural, it's just the way English refers to verbs regarding singular things).

Plurality Grammar Correction

---

reference/strings/functions/substr.xml

The php8 example contains an additional `]` at the end. Probably a mistake.

Fix typo in php8 example

---

reference/dba/functions/dba-open.xml

According to reflection, this change was in PHP 8.2 as well from https://github.com/php/php-src/commit/7db32add9be75421347af30b0ae9b908ea8944cf

Fix dba_open changelog php version

---

language/predefined/unitenum/cases.xml

as per the RFC, and example in the doc:
https://wiki.php.net/rfc/enumerations#value_listing
> cases() returns a packed array of all defined Cases in the order of declaration.

fix: UnitEnum::cases() returns enums ordered by declaration

---

reference/array/functions/array-unique.xml

The array_unique function doesn't sort, but compares. It uses the same constants but terms are mixed up. The text uses "sorting" while each constant uses "compare".
This is now streamlined in order to reduce friction while reading.

Don't mention sorting but comparison

---

reference/random/functions/mt-srand.xml
reference/random/functions/srand.xml

These examples teach the readers bad practices, because they indicate that seeding from the current time is reasonable (it is not). Users should ideally use the `random_int()` function. If that is not possible, the `Random\Randomizer` is the next best choice. If that's not an option either, then relying on the random seed of the global Mt19937 is better than any manual seeding that relies on the current time.

random: Remove examples for mt_srand() and srand()

---

reference/zlib/functions/inflate-get-status.xml

inflate_get_status() does not return false on error. Previously, it returned false on invalid resource parameters. Not sure if that needs a changelog since that's not normally done for parameter parsing errors.

Remove incorrect inflate_get_status() return false description

---

language/oop5/basic.xml
language/oop5/inheritance.xml

This doesn't seem to be explicitly mentioned anywhere as far as I can tell, but the visibility of constructors can be restricted.

Constructor visibility can be restricted

---

reference/session/functions/session-destroy.xml
reference/session/functions/session-unset.xml

I believe this was written back when PHP 5.4 was released. The old note isn't very clear now unless someone remembers the old days. However, the note still makes sense on the `session_unset` page with a clear explanation of why using it may be problematic. 
P.S. Help wanted for a good example code for this page.

Modernize note about session_unset

---

reference/openssl/functions/openssl-pkey-get-details.xml

Changed wording to use `on` instead of `in` to be consistent with other functions.

Fix wording of openssl-pkey-get-details to be consistent with other functions

---

reference/phar/Phar/webPhar.xml

This was not made nullable in PHP 8.0 and still expects an array.

Remove incorrect Phar::webPhar() changelog for nullable parameter

---

reference/phar/Phar/mungServer.xml

This should just be an array of strings. The string indices wording is confusing.

Fix wording in Phar::mungServer() variables description

---

reference/random/functions/mt-rand.xml
reference/random/functions/rand.xml
reference/random/random/engine/pcgoneseq128xslrr64/construct.xml
reference/random/random/engine/pcgoneseq128xslrr64/jump.xml
reference/random/random/engine/xoshiro256starstar/construct.xml
reference/random/random/engine/xoshiro256starstar/jump.xml
reference/random/random/engine/xoshiro256starstar/jumplong.xml
reference/random/random/randomizer/getbytes.xml
reference/random/random/randomizer/pickarraykeys.xml
reference/random/random/randomizer/shufflearray.xml
reference/random/random/randomizer/shufflebytes.xml

I apologize to the translators in advance :see_no_evil: The changes should be able to be trivially copied over, though.
-------------------
The spaces within a function call have been introduced in ad458c5f01db4bed979d1623267738ccc7a31962 and I have been trying to emulate them, but failed due to muscle memory, resulting in very inconsistently formatted examples.
Adjust the code examples purely stylistically, without changing their output:
- Remove the extra spaces within the function calls to match the commonly accepted code style (e.g. PSR-12).
- Use `implode()` instead of the `join()` alias.
- Use comma instead of string concatenation when echo-ing.
- Consistently use "\n" to emit newlines, not `PHP_EOL`.
- Unify to double quotes.

random: Unify code style in examples

---

reference/dom/domelement/removeattributens.xml

This function does not return a value. The code always returns NULL which should be valid for return type `void`.

Fix DOMElement::returnAttributeNS() return void description

---

reference/spl/functions/spl-autoload-register.xml

Due to this guarantee there is no need to perform this unnecessary check within the autoloader.

Explicitly mention that spl_autoload_register will drop any leading backslash

---

reference/strings/functions/str-split.xml

It looks like `str_split` behaviour's did change in PHP8.2.0: https://3v4l.org/mHMvb
This document the change. I am unsure about the wording, also an example may be clearer.

`str-split`: precise behavior change for PHP 8.2.0

---

reference/phar/Phar/count.xml

I have updated the documentation for the Phar::count method to include information on its $mode parameter. This should fix issue #2362.

added: Phar::count parameter documentation

---

language/exceptions.xml

This pull request
See https://www.php.net/manual/en/language.exceptions.php#example-336:

Fix: Remove class declaration

---

reference/gmp/functions/gmp-random.xml
reference/gmp/functions/gmp_random_bits.xml
reference/gmp/functions/gmp_random_range.xml

Add warning that GMP's random functions are not cryptographically secure

---

reference/funchand/functions/call-user-func-array.xml

Since PHP 8.0, the keys can be used as argument names.

call_user_func_array $args need not be indexed

---

reference/oci8/ocilob/read.xml

This updates the doc verbiage based on @cjbj 's comments on https://bugs.php.net/bug.php?id=70700.

update length verbiage to differentiate behavior between BLOB bytes and CLOB characters

---

language/variables.xml

Using ${expr} (variable variables) in strings is deprecated in PHP 8.2

Fix example code throwing deprecation warning

---

reference/strings/functions/strlen.xml

This also fixes #2332. We don't document undefined behaviour for every function. As this function is documented to accept only strings, passing any other type is an undefined behaviour. The return value cannot be relied upon and in fact changed many times over the years https://3v4l.org/ukOhg. The note mentioning arrays is out of place, because why would we mention arrays on this page?

Fix strlen page

---

reference/spl/functions/spl-autoload-register.xml

I've added note about ignored parameter
https://github.com/php/php-src/commit/2302b14aab3bf01a9a87d2ee87951a13bc7752a0

spl_autoload_register ignores throw parameter

---

reference/classobj/functions/class-alias.xml
reference/classobj/functions/class-exists.xml
reference/classobj/functions/enum-exists.xml
reference/classobj/functions/interface-exists.xml
reference/classobj/functions/trait-exists.xml
reference/spl/functions/class-implements.xml
reference/spl/functions/class-parents.xml
reference/spl/functions/class-uses.xml

I've replaced some links to removed [__autoload](https://www.php.net/manual/en/function.autoload.php) with [autoloading classes](https://www.php.net/manual/en/language.oop5.autoload.php). There are also a few in SPL, but I've not updated these.
Fixes #1456

Replace links to __autoload

---

appendices/reserved.xml

Fixes #2397 and brings documentation in sync with the RFC on [namespaces as a single token](https://wiki.php.net/rfc/namespaced_names_as_token) which was [implemented in 8.0](https://github.com/php/php-src/milestone/1?closed=1).

Issue #2397: Bring reserved.xml in sync with RFC 

---

appendices/migration81/deprecated.xml
language-snippets.ent

As further described in the issue, it was not clear - to me and I believe others - that the suggestion to "use ArrayIterator" was actually a suggestion to "use ArrayIterator's method instead of these functions". I thought that, similar to the Countable interface which allows classes to work with `count()`, the ArrayIterator class could somehow work with these array functions.
In testing the ArrayIterator class and contrasting it with other classes, it was a surprise to learn that while non-SPL classes would still work with these array functions in PHP 7.4 and PHP 8.0, SPL classes stopped working with these array functions in PHP 7.4, with no mention on the function pages.
I have done my best to create this initial draft and mirrored as much as possible the format used in other places in …

array pointer functions: Clarify deprecated use on objects

---

language/attributes.xml

Line 32: "Lets assume an [...]" -> "Let's assume an [...]"
Hi there! This is my first contribution to the PHP documentation. I did read the contribution guidelines, specifically http://doc.php.net/tutorial/editing.php, but please let me know if there are any inadequacies with the current PR.
Thank you.

Corrected typo in language/attributes.xml

---

reference/stream/functions/stream-get-contents.xml

Clarify in a note that even if a stream's contents are much smaller a buffer of the maximum length will be allocated if a maximum length is provided. This may be surprising if you otherwise expect the function to dynamically grow a buffer depending on the actual stream contents, as it does with the default null value.

stream_get_contents: Note buffer of max length size will always be allocated

---

reference/ftp/functions/ftp-nb-get.xml

Missed false on return in case of failure
https://github.com/php/php-src/blob/4177257178d6a1a44f0aa6d6b23d02b91e0a58d3/ext/ftp/php_ftp.c#L797

Fix function signature

---

reference/errorfunc/ini.xml

See https://www.php.net/manual/en/migration81.other-changes.php#migration81.other-changes.ini

document removal of log_errors_max_len in PHP 8.1

---

reference/var/functions/floatval.xml
reference/var/functions/intval.xml

In 8.0.0 it was changed to warning.
Not sure of the correct wording/format tho.

Change error level for intval and floatval

---

language-snippets.ent

The result is absolutely not pretty, but it should hopefully be accurate for all PHP versions supported by the manual (i.e. >= 7.0):
It's a little messy, because new sources have often been added in patch versions. At least the NetBSD getrandom(2) support will only appear starting in 8.3.

random: Update list of CSPRNG sources

---

language/enumerations.xml
reference/misc/functions/constant.xml
reference/misc/functions/defined.xml

The `constant()` & `defined()` methods can be used with dynamic enum cases names, which doesn't seem to be documented anywhere at the moment.

Document that constant & defined work with enums

---

language-snippets.ent
reference/strings/functions/printf.xml

When '*' is used to indicate width or precision in a formatting specifier, an additional integer argument is to be supplied which will provide the width/precision to be used.
#2423

Mention the use of '*' in printf-formatting specifiers

---

reference/url/functions/http-build-query.xml

Change affects this page: https://www.php.net/manual/en/function.http-build-query.php
The line I am changing: https://github.com/php/doc-en/blob/master/reference/url/functions/http-build-query.xml#L198
This change updates the phrasing of that label to use what `&example.outputs;` generates.
I opted to not use `&example.outputs;` because I figure that the text should remain static, rather than doing something like
```xml
&example.outputs;
<para>(word wrapped for readability)</para>
```
but I'm not sure about this... because it could be the preference to use the dynamically generated text regardless of whether there's an addendum.

Update phrasing for consistency with dynamically generated text

---

language/wrappers/php.xml

I need to read `php://input` under any circumstances to implement a reverse proxy. After reading the current document, I thought that it would not be possible and it took me a long time to find the solution.

Link to `enable_post_data_reading` from the `php://input` documentation

---

reference/dom/domcharacterdata/appenddata.xml

The return type is bool not void and always returns true.

Add missing DOMCharacterData::appendData() return true description

---

reference/reflection/reflectionclass/getparentclass.xml
reference/reflection/reflectionclass/getstartline.xml
reference/reflection/reflectionclass/getstaticproperties.xml
reference/reflection/reflectionclass/gettraitaliases.xml
reference/reflection/reflectionclass/gettraitnames.xml
reference/reflection/reflectionclass/gettraits.xml
reference/reflection/reflectionclass/istrait.xml
reference/reflection/reflectionextension/construct.xml
reference/reflection/reflectionextension/ispersistent.xml
reference/reflection/reflectionextension/istemporary.xml
reference/reflection/reflectionfunction/getclosure.xml
reference/reflection/reflectionfunction/tostring.xml
reference/reflection/reflectionfunctionabstract/getclosurescopeclass.xml
reference/reflection/reflectionfunctionabstract/getclosurethis.xml
reference/reflection/reflectionfunctionabstract/tostring.xml
reference/reflection/reflectionmethod/getclosure.xml
reference/reflection/reflectionparameter/getdeclaringfunction.xml
reference/reflection/reflectionparameter/tostring.xml
reference/reflection/reflectionproperty/tostring.xml
reference/reflection/reflectionzendextension/construct.xml

* If a method has a refpurpose, description, parameters and return
values, it's documented, there's no need for the warning box.
* Add description where there was none. It is usually very similar
to the refpurpose.
* Document ReflectionZendExtension::__construct(), and update
ReflectionExtension::__construct() for consistency.
* In ReflectionFunction::__toString()
* Remove some references to deprecated export() methods.
* Add example for ReflectionParameter::__toString().

Reflection: fix some "undocumented" methods, and some other edits for consistency

---

reference/array/functions/array-combine.xml

Last time I searched how to zip up an array, and all I came up with was `array_combine`. Hence, I guess a link from `array_combine` to `array_map` would be helpful.
WDYT?

docs: add a reference to array_map from array_combine

---

reference/session/security.xml

@iluuu1994 there is unrelated markup change as I just did a drive by cleanup while fixing the docs for https://github.com/php/php-src/pull/11471

Fix session security docs markup and wording

---

reference/filesystem/functions/file.xml

it seems this flag is available but missing from the docs

Added missing `FILE_NO_DEFAULT_CONTEXT` for file()

---

reference/strings/functions/number-format.xml

Function number_format uses only rounding half up rule. Others are not supported.
Line responsible for the rounding method used: https://github.com/php/php-src/blob/master/ext/standard/math.c#L1034

Add used rounding rule into the description of function number_format 

---

reference/filter/filters.xml
reference/filter/functions/filter-var.xml

It's not made clear that inputting an array as `value` causes each entry to be filtered rather than the array itself.

Clarify return value when array is inputted

---

reference/ds/ds/set/capacity.xml

There is no `push` method, `add` seems equivalent here.

Fix broken method reference, `push` doesn't exist

---

reference/opcache/functions/opcache-reset.xml

The `opcache_reset()` function also returns `false` when the restart is pending or in progress.

Update when opcache_reset returns false

---

reference/imagick/imagick/profileimage.xml

Actually this parameter accepts `null` to remove the value.
The original stub is below:
https://github.com/Imagick/imagick/blob/28f27044e435a2b203e32675e942eb8de620ee58/Imagick.stub.php#L1050

Fix Imagick::profileImage() parameter type

---

language-snippets.ent
reference/info/functions/get-magic-quotes-gpc.xml
reference/info/functions/get-magic-quotes-runtime.xml
reference/info/ini.xml
reference/mysql/functions/mysql-escape-string.xml
reference/mysql/functions/mysql-real-escape-string.xml

Remove outdated information about magic quotes
Warn that assert.quiet-eval was removed and to use zend.assertions

Improve Info INI page

---

reference/curl/functions/curl-share-errno.xml

As stated in the changelog, this method no longer returns `false` on error.

Remove false return hint on `curl_share_errno`

---

reference/random/random/randomizer/nextint.xml

> However, if ~~`Randomizer::getInt()` with no arguments~~ `Randomizer::nextInt()` is executed in a 32-bit environment using an Engine that generates values above 32-bit, a RuntimeException will be thrown to avoid incompatibility.
> https://wiki.php.net/rfc/rng_extension#final_class_random_randomizer
Also added return value description

Randomizer::nextInt return value and 32-bit note

---

reference/dom/domdocument/loadxml.xml

Calling this statically has been made impossible since PHP 8.0.
Diff looks funky, but expand it in the webview to see it is right :P

Remove non-working, outdated example

---

reference/curl/functions/curl-multi-init.xml

ref.: https://github.com/php/php-src/blob/master/ext/curl/multi.c#L60 (stub: `function curl_multi_init(): CurlMultiHandle {}`)
⇒ "Stubs are the authoriative source of truth. The descriptions in the manual are sometimes buggy due to them not being syncronized with the stubs via automatic tooling (unlike signatures)." - Máté Kocsis (https://twitter.com/kocsismate90/status/1681912594024525824)

curl_multi_init: fix return description

---

reference/pcre/pattern.modifiers.xml

Almost copied and pasted from [PHP 8.2 migration guide](https://www.php.net/manual/en/migration82.new-features.php#migration82.new-features.pcre).

[PHP 8.2] Added PCRE n (NO_AUTO_CAPTURE) modifier description.

---

reference/opcache/ini.xml

The changes aim to clarify that disabling `opcache.validate_timestamps` doesn't mean timestamps will never be checked.
In scenarios where `opcache.file_update_protection` is non-zero (it is `2` by default) or `opcache.max_file_size` is set to a non-default value, OPcache may still validate file timestamps. This behavior was not clearly indicated in the original documentation and could lead to potential confusion for users (e.g., https://github.com/amnuts/opcache-gui/issues/92#issuecomment-1261958279)
I have confirmed this is the behavior here: https://github.com/php/php-src/blob/master/ext/opcache/ZendAccelerator.c#L1772C2-L1772C2

OPcache: clarify validate_timestamps considering other options

---

chapters/tutorial.xml

Update the example to a browser that people can actually download and install from official websites on macOS, Linux, and Windows today.
MSIE is EOL and was Windows-only (apart from [IE 5.5 for Mac](https://www.versionmuseum.com/history-of/internet-explorer), back in the day). Note that even IE11 no longer identified as MSIE, it identified as Trident instead.

tutorial: Promote lowercase boolean to beginners

---

reference/spl/functions/spl-object-hash.xml

Fix https://github.com/php/doc-en/issues/2406

Add a notice to `spl_object_hash()` return values comparison

---

reference/json/functions/json-decode.xml

Fix https://github.com/php/doc-en/issues/2513

Reworded json_decode return value paragraph to be more explicit about `true`, `false` and `null`

---

language/types/declarations.xml

Fix https://github.com/php/doc-en/issues/2373

Add example for class properties type declaration

---

reference/opcache/ini.xml

This is to clarify that `file_update_protection` and `max_file_size` settings affect validation of timestamps at compile-time only.
Context: https://github.com/php/doc-en/pull/2609#issuecomment-1655109927

OPcache: clarify timestamps can be checked at compile-time

---

reference/opcache/ini.xml

Related: https://github.com/php/doc-en/pull/2609

OPcache: explain why setting file_update_protection to 0 may improve performance

---

reference/image/setup.xml

Fix https://github.com/php/doc-en/issues/1383
Got the [version info here](https://github.com/php/php-src/blob/655f116be57b46efe32221d7adfec6d6b81eeece/ext/zlib/config0.m4#L4), hope hat was the good place to get it :slightly_smiling_face:

Add `zlib` requirement to GD

---

extensions.ent
features/dtrace.xml
install/pecl.xml
language-snippets.ent
language/wrappers/audio.xml
language/wrappers/expect.xml
language/wrappers/rar.xml
language/wrappers/ssh2.xml
reference/ibm_db2/configure.xml
reference/oci8/setup.xml
reference/pdo_cubrid/configure.xml
reference/pdo_ibm/configure.xml
reference/pdo_informix/configure.xml
reference/pdo_sqlsrv/configure.xml

This PR replaces the tag `<link xlink:href="&url.pecl;">PECL</link>` and its more extended versions, like `<link xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="&url.pecl;">PECL</link>`, with the entity `&link.pecl;`.

Replace PECL <link> with entity &link.pecl;

---

reference/spl/splfixedarray.xml
reference/spl/splfixedarray/getiterator.xml
reference/spl/splfixedarray/jsonserialize.xml
reference/spl/splfixedarray/serialize.xml
reference/spl/splfixedarray/unserialize.xml
reference/spl/versions.xml

Fix https://github.com/php/doc-en/issues/1702

Update `SplFixedArray` methods + add PHP 8.2.0 changelog entry

---

reference/intl/dateformatter/create.xml

Fix https://github.com/php/doc-en/issues/2425

[IntlDateFormatter] Add changelog entry about making `dateType` and `timeType` optional

---

language/oop5/magic.xml

https://3v4l.org/m1pdW#v8.1rc3
Based on 8.1.0 [migration guide](https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.core.magic-sleep), added warning note about __sleep magic method.

[PHP 8.0] Document returning a non-array from __sleep() warning.

---

reference/ds/ds.collection.xml
reference/ds/ds.hashable.xml
reference/ds/ds.sequence.xml

per title, this fixes the current build issues.
this is accomplished by updating the Data Structures docs to match the examples from here: https://github.com/php/doc-en/pull/2563
once merged these interfaces will use the proper new syntax and fixes both the builds and the current render issues on php.net

Updates the DS interfaces to use new syntax

---

reference/ds/ds.collection.xml
reference/ds/ds.sequence.xml

Per title, this fixes one thing I noticed after my quick PR to fix the broken builds.
So now DS Collection shows the method from IteratorAggregate.
And sequence shows all the ones it inherits from Collection too.

Add missing inherited methods to DS extension docs

---

reference/sodium/functions/sodium-crypto-secretbox-open.xml
reference/sodium/functions/sodium-crypto-secretbox.xml

This corrects 2 instances of the word _nonce_ misspelled as _nouce_ in the documentation for `sodium_crypto_secretbox()` and `sodium_crypto_secretbox_open()`

Fix minor spelling errors in the sodium_crypto_secretbox docs

---

language/control-structures/alternative-syntax.xml

Fix https://github.com/php/doc-en/issues/2635

Fix switch alternative syntax

---

reference/mbstring/functions/mb-convert-kana.xml

Throws ValueError since PHP 8.2.
I add ChangeLog section it.
```php
mb_convert_kana("abc", "sS", "UTF-8");
Fatal error: Uncaught ValueError: mb_convert_kana(): Argument #2 ($mode) must not combine 'S' and 's' flags in /in/gvk4D:3
Stack trace:
#0 /in/gvk4D(3): mb_convert_kana('abc', 'sS', 'UTF-8')
#1 {main}
thrown in /in/gvk4D on line 3
```
3v4l <https://3v4l.org/gvk4D>

mb_convert_kana throws ValueError when impossible combination since PHP 8.2

---

appendices/migration80/incompatible.xml
language/predefined/argumentcounterror.xml

Fix https://github.com/php/doc-en/issues/2450

Fix GH-2450: mention when ArgumentCountError being thrown by built-in functions

---

reference/curl/constants.xml
reference/curl/functions/curl-getinfo.xml
reference/curl/functions/curl-multi-setopt.xml
reference/curl/functions/curl-setopt.xml

Hi, thought I can help with #1803 regarding the curl constants. This PR starts with the curlinfo constants added in one commit. Made a list below, but I could use some pointers as to what goes where, which other pages need to be updated, if I'm missing any I had planned below.
CURLINFO_PROXY_ERROR (libcurl >= 7.73.0) https://curl.se/libcurl/c/CURLINFO_PROXY_ERROR.html
CURLINFO_REFERER     (libcurl >= 7.76.0) https://curl.se/libcurl/c/CURLINFO_REFERER.html
CURLINFO_RETRY_AFTER (libcurl >= 7.66.0) https://curl.se/libcurl/c/CURLINFO_RETRY_AFTER.html
CURL_VERSION_GSASL (libcurl >= 7.76.0)
CURL_VERSION_HSTS (libcurl >= 7.74.0)
CURL_VERSION_HTTP3 (libcurl >= 7.66.0)
CURL_VERSION_UNICODE (libcurl >= 7.72.0)
CURL_VERSION_ZSTD (libcurl >= 7.72.0)
CURLAUTH_AWS_SIGV4 (libcurl >= 7.75.0) …

Document new 8.2 curl constants

---

reference/array/functions/array-diff-assoc.xml
reference/array/functions/array-diff-uassoc.xml

Fix https://github.com/php/doc-en/issues/2631
My last try to clarify this wasn't the good fix. I try here to clarify what happens with `array_diff_(u)assoc` and why `red` is present in the output.

Clarify `array_diff_(u)assoc` examples

---

reference/calendar/functions/easter-date.xml

Updated the easter_date doc to reflect the changes introduced in PR https://github.com/php/php-src/pull/11862

Update easter_date docs to reflect PHP 8.3 changes

---

.docker/Dockerfile
.gitignore
README
docker-compose.yml

Use case: a casual contributor who wants to preview their changes before opening a PR.
- There is currently no way to provide custom args to phd/render.php, because then we'd be back to complicated instructions.
- I tried not to make any assumptions about the host system, so I don't use make.
- This image is tied to an older commit of phd, since a (very) recent commit causes a crash on `assert($this->cchunk["classsynopsis"]["legacy"] === true);`. I'll just assume that it's a regression, since it fails on 2 machines and 2 PHP versions. I don't want to go down that rabbit hole today.
Fixes #2637

Create a docker container for a single-line setup and rendering

---

reference/pdo/connections.xml

The current phrasing appears to be incorrect. The Zend engine doesn't necessarily display the error and back trace. And catching exception is not required in order to hide the sensitive information.

Better phrasing and code example for PDO connection management

---

reference/stream/functions/stream-set-chunk-size.xml

Fix https://github.com/php/doc-en/issues/2209

Fix GH-2209: update return value and changelog of stream_set_chunk_size()

---

features/file-upload.xml
features/xforms.xml
language/oop5/constants.xml
language/types/declarations.xml
reference/math/functions/pow.xml
reference/mysqli/mysqli/real-escape-string.xml

This commit changes tag usage without changing text contents. I'm in doubt to submit it with or without `[skip-revcheck]`.

Improve tag semantic usage

---

reference/mysqli/mysqli/construct.xml

Docs need updating according to this:
https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.mysqli

Update Mysqli::construct() docs for return value as of PHP 8.1

---

language/variables.xml

Accessing undefined variables generate an E_WARNING since PHP 8 (and will result in error exceptions being thrown in PHP 9).

Clarify the output of example code

---

reference/strings/functions/str-getcsv.xml

It's surprising that `str_getcsv("")` returns `[null]`. This adds an example to warn users of this behavior.

Add an example for str_getcsv with empty input

---

language/control-structures/alternative-syntax.xml

As per the discussion in php/doc-en#2648, the part that might actually be unexpected is that leading indentation also causes problems.  The addition of the empty line distracts from that. Now that the CSS for PHP.net is fixed, this can be reverted.
This reverts commit 1d73d6e34f2963c42456dbb8384bc15f5fa5642a.
see php/web-php#801

Revert "Fix GH-2635: Fix switch alternative syntax (#2648)"

---

language/control-structures/alternative-syntax.xml

This was part of an unrelated commit and is now re-added in a dedicated single-purpose commit.
see #2648
see #2693

Re-add the semicolon after `endswitch` in alternative-syntax.xml

---

reference/spl/functions/class-implements.xml
reference/spl/functions/class-parents.xml

Fix https://github.com/php/doc-en/issues/1606

Add mention of `is_a()` and `instanceof` in `class_implements()` and `class_parents()` pages

---

language/types/string.xml

An example used the deprecated `${varname}` syntax; fix it.

Update string.xml to remove old string interpolation

---

reference/var/functions/intval.xml

In `intval` function, the `base` parameter allows to set the desired base to convert a string to int.
The base "0" works as "automatic base", the base will be detected:
```php
echo intval('101', 0);   // 101
echo intval('0x101', 0); // 257
echo intval('0X101', 0); // 257
echo intval('0b101', 0); // 5
echo intval('0B101', 0); // 5
echo intval('0101', 0);  // 65
```
I updated the documentation to include binary `0b` and `0B` prefixes.
I would have liked to do the same for octal numeral notation, but `0o` and `0O` seems to not be implemented yet, only `0` works.

update intval doc with explicit binary numeral notation

---

chapters/tutorial.xml

There is inconsistent indentation within the "Getting started" section of the docs including the same example across different pages.
I feel that using 4 spaces is pretty established indentation in the PHP community and should be our standard within the docs.
[This example](https://www.php.net/manual/en/intro-whatis.php
):
is then repeated on [different pages](https://www.php.net/manual/en/tutorial.firstpage.php) in the same section with different indentation.

Standardise Getting Started example indentation

---

chapters/tutorial.xml

The first example on the PHP documentation that isn't a "hello world" is searching the `User-Agent` for the string `"Firefox"`.
This example currently uses [`strpos`](https://www.php.net/manual/en/function.strpos.php). I believe we should be using [`str_contains`](https://www.php.net/manual/en/function.str-contains).
I believe this for a few reasons, but to start with I'll let the function descriptions do the talking:
> Find the position of the first occurrence of a substring in a string
vs.
> Determine if a string contains a given substring
`str_contains` matches the semantics of what we are doing and eases the overhead of understanding what is happening.
When using `strpos` we are also introducing the reader to:
1. "Truthiness"
2. Boolean literals
3. PHP's "return `false` as a flag to …

Use `str_contains` over `strpos` for tutorial example

---

chapters/tutorial.xml

This PR improves the form example by:
1. Using `label` tags, rather than generic inaccessible `<p>` tags.
2. Removes the redundant `type` attribute from input tags.
> If this attribute is not specified, the default type adopted is text [source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types)
3. Adds an `id` tag to the `input` so that `label` tags can reference them with their `for` attibute.
3. Use a submit `button` and provide custom text. Adding custom text between an HTML tag feels much more familiar than doing it within an attribute. This also matches how the `label` works.
4. Added some spacing to ease the flow to reading the `label` / `input` pairs.
5. Removed the "closing" slash on the inputs. We've already shown the doctype in the opening example of …

Use semantic HTML tags for tutorial `form` example

---

reference/strings/functions/str-pad.xml

IIMHO, we need to specify that `length` is the desired length of the final padded chain. In my case, it was unclear.

Improve str_pad documentation

---

reference/strings/functions/strrchr.xml

Documents the new `$before_needle` argument of `strrchr()` add in https://github.com/php/php-src/pull/11430.

Document new `$before_needle` argument of `strrchr()`

---

reference/strings/functions/strrchr.xml

New parameter `$before_needle` outputs result based on the **last** occurances of needle.
```
$ sapi/cli/php --version | head -n 1
PHP 8.4.0-dev (cli) (built: Aug 30 2023 22:08:33) (NTS)
$ sapi/cli/php -r '$text = "Line 1:Line 2:Line 3"; var_dump(strrchr($text, ":", false));'
string(7) ":Line 3"
$ sapi/cli/php -r '$text = "Line 1:Line 2:Line 3"; var_dump(strrchr($text, ":", true));'
string(13) "Line 1:Line 2"
```

Fixed $before_needle argument of strrchr() description

---

chapters/tutorial.xml

https://www.php.net/manual/en/tutorial.useful.php
The output of the first example includes an initial new line.
The script to generate this output will not generate a newline. Here is the output of the given script:
Wrapping in CDATA, which seems to be the pattern used for `screen` tags, fixes this.

Wrap example output in CDATA

---

chapters/tutorial.xml

Proposing that for **full HTML document** examples, we include a doctype.
The section's initial example includes a doctype, but then we don't include it on the subsequent examples.
Has doctype: https://www.php.net/manual/en/intro-whatis.php
Missing doctype: https://www.php.net/manual/en/tutorial.firstpage.php

Add doctype to full HTML document

---

reference/memcached/ini.xml

The default was changed in 3.2.0 - Fixes https://github.com/php/doc-en/issues/2727

Update the default value for memcached.store_retry_count

---

chapters/intro.xml

With the demise of Flash, I think we should remove the reference to it from the "what can PHP do" section.
Sure, it continues to be able to do this (I assume), but I think we would be better off highlighting some other features.
I've opted to highlight encryption and sending emails. These feel like very practical things for modern web development.

Remove reference to generating "Flash" movies

---

language/namespaces.xml

I was reading the documentation on the namespace and got confused when I saw the word currentdirectory, I thought it was a typo error but noticed that it is referencing a part of an initially highlighted part of the text <literal>currentdirectory/foo.txt</literal>.
Since this is used as an example, it has to be highlighted as well, I added the highlight

Added syntax highlighting for currentdirectory in 'Using Namespace' page

---

reference/array/constants.xml
reference/calendar/constants.xml
reference/curl/constants.xml
reference/datetime/constants.xml
reference/exif/constants.xml
reference/fileinfo/constants.xml
reference/filesystem/constants.xml
reference/filter/constants.xml
reference/ftp/constants.xml
reference/gmp/constants.xml
reference/hash/constants.xml
reference/image/constants.xml
reference/imap/constants.xml
reference/intl/constants.xml
reference/libxml/constants.xml
reference/mbstring/constants.xml
reference/openssl/constants.xml
reference/outcontrol/constants.xml
reference/pdo/constants.xml
reference/pgsql/constants.xml
reference/posix/constants.xml
reference/pspell/constants.xml
reference/readline/constants.xml
reference/sockets/constants.xml
reference/strings/constants.xml
reference/uodbc/constants.xml
reference/xml/constants.xml
reference/zlib/constants.xml

This is the beginning PR for syncronizing predefined constants with stubs. For now, the changes only affect formatting, and mostly are whitespace changes.

Syncronize predefined constants with stubs - part 1

---

reference/json/constants.xml
reference/random/constants.xml
reference/strings/constants.xml

Fix wrong formatting of constant types

Synchronize predefined constants with stubs - part 2

---

language/oop5/serialization.xml
reference/session/book.xml

re: #2730 
Removes references to the `session_register` function removed in PHP 5.4

Remove `session_register` references

---

reference/gnupg/functions/gnupg-decrypt.xml
reference/gnupg/functions/gnupg-decryptverify.xml
reference/gnupg/functions/gnupg-encrypt.xml
reference/gnupg/functions/gnupg-encryptsign.xml
reference/gnupg/functions/gnupg-export.xml
reference/gnupg/functions/gnupg-geterror.xml
reference/gnupg/functions/gnupg-gettrustlist.xml
reference/gnupg/functions/gnupg-import.xml
reference/gnupg/functions/gnupg-keyinfo.xml
reference/gnupg/functions/gnupg-listsignatures.xml
reference/gnupg/functions/gnupg-sign.xml
reference/gnupg/functions/gnupg-verify.xml

This PR fixes return type hints for gnupg extension functions.

[gnupg] Fix return type hints

---

language/oop5/decon.xml

I was recently made aware that any modifier can be used to apply constructor property promotion, instead of just visibility modifiers:
https://github.com/php/php-src/issues/12122
This PR aims to clarify this in the docs.

Clarify constructor property promotion modifiers

---

reference/intl/book.xml

Replace a comma by a point in the Introduction of intl

typo(intl): comma instead of point

---

reference/simplexml/simplexmlelement/current.xml

1) There's a typo in the variable name
2) The call returned NULL in PHP < 8.1. It throws an exception starting
in 8.1. To keep the example simple and not introduce different
variants based on the version, just remove the faulty call and
expand upon the comment.

Fix SimpleXMLElement::current() example

---

reference/stream/functions/stream-notification-callback.xml

At least for HTTP streams, the `$message` parameter of `stream_notification_callback()` is nullable, let's document it.
See https://onlinephp.io/c/f0a2fc for a simple script to get the types.

$message in stream_notification_callback() is nullable

---

reference/strings/functions/strrpos.xml

Fixes #2220 
The negative value for `strrpos` offset is inclusive of those bytes as a starting point, but was previously described as skipping those bytes.

Corrected description of negative offsets.

---

reference/array/functions/compact.xml

Since PHP 8.0: "[A number of notices have been converted into warnings](https://www.php.net/manual/en/migration80.incompatible.php)"
Usually, in the PHP manual, even if the error level is raised from E_NOTICE to E_WARNING, a changelog isn't kept within individual function pages.
However, on the compact() page, there's already an entry in the changelog regarding the previous change to 'now issues an E_NOTICE'. Therefore, I believe that adding a note explicitly indicating the recent change in the issued error might prevent confusion.

`compact()` now issues an E_WARNING error.(PHP8.0)

---

reference/xml/functions/xml-parser-get-option.xml
reference/xml/functions/xml-parser-set-option.xml

Reference: https://github.com/php/php-src/commit/81e59c64979c458b658695aac85fb8dbaad4a7ef
Came across this by coincidence and noticed the manpage is not yet up-to-date for 8.3 and there was no PR, so here we go.

Corrections to xml_parser_[gs]et_option

---

reference/password/functions/password-hash.xml

50 ms is way to short to generate actually secure hashes. Update the recommendation to 350 ms with a starting cost of 10 (the current default) and example output of 12.
see https://wiki.php.net/rfc/bcrypt_cost_2023
/cc @roycewilliams

password_hash: Update script to generate cost recommendations

---

reference/password/functions/password-needs-rehash.xml

The old example was broken, because the `cost` option is only valid for bcrypt, but not for argon2. Thus in case the default algorithm actually changes, the example would be broken.
Also update the example costs with 12 as per #2784.

password_needs_rehash: Fix example

---

reference/strings/functions/crypt.xml

The existing examples showcased constant salts and the use of DES-based hashing. Showcase a simple example of validating an existing SHA-512 crypt hash with `1000000` rounds for compatibility with non-PHP software that relies on libc's crypt (commonly mail servers or the OS's /etc/shadow).

crypt: Remove examples showcasing bad practices

---

reference/strings/functions/crypt.xml

`md5()` should not be referenced anywhere, especially not anywhere near a function that is suitable for hashing passwords.

crypt: Do not reference `md5()`

---

language/predefined/errorexception.xml

IMO the old example should have been 
```
set_error_handler(__NAMESPACE__ . "\\exception_error_handler");
```
so it would work in any namespace, because the old example just worked in the global namespace, and crashed-at-runtime if used in any other namespace,  but as of PHP8.1.0 we have an even better way to do it: set_error_handler(exception_error_handler(...));

modernize ErrorException example code

---

language/types/string.xml

Clarify which part of each sequence is the regular expression by repeating it in the description, and give examples of each. Before this change, the curly braces are confusing due to having two different meanings in these sequences.

Update descriptions of octal, hex and unicode escape sequences

---

appendices/migration83.xml
appendices/migration83/constants.xml
appendices/migration83/deprecated.xml
appendices/migration83/incompatible.xml
appendices/migration83/new-classes.xml
appendices/migration83/new-features.xml
appendices/migration83/new-functions.xml
appendices/migration83/other-changes.xml
appendices/migration83/windows-support.xml

Based on [PHP 8.3 UPGRADE NOTES](https://github.com/php/php-src/blob/PHP-8.3/UPGRADING) and past migration guides.
- TODO
- https://github.com/php/doc-base/pull/101
closes: #2774

PHP 8.3 migration guide.

---

reference/ctype/configure.xml
reference/filter/configure.xml
reference/posix/configure.xml
reference/session/configure.xml
reference/tokenizer/configure.xml

Replaces the text about disabling extensions enabled by default with the entity `installation.enabled.disable`.

Use entity installation.enabled.disable on installation section

---

reference/xsl/xsltprocessor/registerphpfunctions.xml

You can't call these DOMDocument functions statically anymore.

Fix example of XSLTProcessor::registerPHPFunctions()

---

language-snippets.ent
reference/dom/domdocument/loadhtml.xml
reference/dom/domdocument/loadhtmlfile.xml
reference/dom/domdocument/xinclude.xml
reference/simplexml/functions/simplexml-load-file.xml
reference/simplexml/functions/simplexml-load-string.xml

PHP 7.0 requires at least libxml2 2.6.11. So any note about an older version is simply irrelevant.
Use an entity to use consistent, more useful wording.
This patch also gets rid of some personification.

Cleanup options parameter description

---

reference/xsl/xsltprocessor/transformtodoc.xml

Mainly, this is to fix https://bugs.php.net/bug.php?id=53693, which is about the undocumented returnClass argument.
However, I found that the description on this page was in general suboptimal, so this patch fixes that.

Update transformToDoc description

---

reference/random/random/randomizer/getbytesfromstring.xml
reference/random/random/randomizer/getfloat.xml
reference/random/random/randomizer/nextfloat.xml

Generate using https://github.com/php/php-src/pull/12330 and running the following command (for my folder hierarchy):
```shell
../php-src/build/gen_stub.php --generate-methodsynopses ../PHP-8.3/ext/random/ ./../docs-php/en/reference/random/
```

random: Add stubs generated from php-src stubs

---

appendices/migration83/other-changes.xml

It seems that `mb_strtotitle` function does not exist in the latest php-src, and the past implementation.

deleted non-existent mb_strtotitle description

---

reference/hash/functions/hash-equals.xml

The current version was pretty much incomprehensible unless you already know what `hash_equals()` does for you. The example was also terrible.

hash_equals: Rewrite the page

---

reference/hash/functions/hash-file.xml
reference/hash/functions/hash-final.xml
reference/hash/functions/hash-hmac.xml
reference/hash/functions/hash-init.xml
reference/hash/functions/hash-update-stream.xml
reference/hash/functions/hash.xml

- Consistently use `sha256` in the examples, as sha256 is the right choice if all things are equal.
- Improve the `hash_init()` example by showcasing that incremental hashing is equivalent to hashing the contents in full.

hash_*: Rewrite examples

---

reference/random/functions/mt-rand.xml

Nowadays it's the same function and in older version it's the worse alternative.

mt_rand: Remove rand() from the see also section

---

reference/random/functions/lcg-value.xml

This is only appearing twice in the entire documentation, copying is probably preferable to creating an entity.
---------------
see php/doc-en#2825

lcg_value: Include the caution from Randomizer::nextFloat()

---

reference/random/functions/mt-getrandmax.xml

This affine transformation results in a bias and `Randomizer::getFloat()` must be used.

mt_getrandmax: Remove example
